Repository openshift/openshift-ansible, pull requests merged in 2018-04, with the labels that each got.

#7253 OpenShift Reference Component Docs
  docs/openshift_components.md
  docs/repo_structure.md
Labels: lgtm, retest-not-required-docs-only, size/L

#7543 Don't remove pvs when uninstalling openshift_management
  roles/openshift_management/tasks/uninstall.yml
Labels: lgtm, size/XS

#6816 Adds node hooks: pre, mid and post update hook.
  playbooks/common/openshift-cluster/upgrades/upgrade_nodes.yml
Labels: lgtm, size/M

#7414 Aligning version defaults for logging components
  roles/openshift_logging_elasticsearch/vars/default_images.yml
  roles/openshift_logging_eventrouter/vars/default_images.yml
  roles/openshift_logging_fluentd/vars/default_images.yml
  roles/openshift_logging_kibana/vars/default_images.yml
  roles/openshift_logging_mux/vars/default_images.yml
Labels: affects_3.9, lgtm, size/S

#7298 Fix typo in hawkular-cassandra RC
  roles/openshift_metrics/templates/hawkular_cassandra_rc.j2
Labels: lgtm, size/XS

#7463 dockergc: use oc rather than openshift for ex subcommand
  roles/openshift_docker_gc/templates/dockergc-ds.yaml.j2
Labels: kind/bug, lgtm, size/XS

#7743 Documents new node upgrade hooks.
  HOOKS.md
Labels: lgtm, needs-ok-to-test, retest-not-required-docs-only, size/S

#7693 Add a role to install the Cluster Monitoring Operator
  playbooks/common/private/components.yml
  playbooks/openshift-monitoring/README.md
  playbooks/openshift-monitoring/config.yml
  playbooks/openshift-monitoring/install-gcp.yml
  playbooks/openshift-monitoring/private/config.yml
  playbooks/openshift-monitoring/private/roles
  roles/openshift_cluster_monitoring_operator/README.md
  roles/openshift_cluster_monitoring_operator/defaults/main.yml
  roles/openshift_cluster_monitoring_operator/files/cluster-monitoring-operator.yaml
  roles/openshift_cluster_monitoring_operator/meta/main.yaml
  roles/openshift_cluster_monitoring_operator/tasks/install.yaml
  roles/openshift_cluster_monitoring_operator/tasks/main.yaml
  roles/openshift_cluster_monitoring_operator/tasks/remove.yaml
Labels: lgtm, size/L

#7711 [1529575] Ensure etcd.conf variables are updated during upgrade
  roles/etcd/tasks/upgrade/upgrade_image.yml
  roles/etcd/tasks/upgrade/upgrade_rpm.yml
  roles/etcd/tasks/upgrade/validate_etcd_conf.yml
  roles/lib_utils/library/openshift_cert_expiry.py
Labels: kind/bug, lgtm, size/M

#7742 Skip oc_adm_csr when no bootstrapping is required on GCP
  roles/openshift_gcp/tasks/configure_master_bootstrap.yml
Labels: lgtm, size/XS

#7713 [1561247] Add kubeconfig to openshift_bootstrap_autoapprover
  roles/openshift_bootstrap_autoapprover/tasks/main.yml
Labels: kind/bug, lgtm, size/XS

#7750 Remove complex containerized version logic and fix f27 build
  .papr.sh
  roles/openshift_version/tasks/first_master_containerized_version.yml
Labels: lgtm, size/M

#7749 catalog: turn on async bindings by default
  roles/openshift_service_catalog/defaults/main.yml
Labels: lgtm, size/XS

#7736 Fix node upgrade hooks
  playbooks/common/openshift-cluster/upgrades/upgrade_nodes.yml
Labels: lgtm, size/S

#7741 Skip oc_adm_csr when no bootstrapping is required on GCP
  roles/openshift_gcp/tasks/configure_master_bootstrap.yml
Labels: size/XS

#7737 use new filter name for AWS availability zones
  roles/openshift_aws/tasks/vpc_and_subnet_id.yml
Labels: lgtm, size/XS

#7760 [1558689] Add iproute to origin-ansible image
  images/installer/Dockerfile
Labels: kind/bug, lgtm, size/XS

#7686 Fix s3 image as rhgs3/rhgs-s3-server-rhel7
  roles/openshift_storage_glusterfs/README.md
Labels: lgtm, retest-not-required-docs-only, size/XS

#7733 Removing non-null default for cpu_limit for es
  roles/openshift_logging_elasticsearch/defaults/main.yml
Labels: lgtm, size/XS

#7762 When bootstrapping automatically sync node config
  playbooks/openshift-master/private/config.yml
  playbooks/openshift-node/private/bootstrap.yml
  roles/openshift_node_group/defaults/main.yml
  roles/openshift_node_group/tasks/bootstrap_config.yml
Labels: lgtm, size/M

#7694 Refactor session authentication secrets
  playbooks/openshift-master/private/config.yml
  roles/lib_utils/action_plugins/sanity_checks.py
  roles/openshift_control_plane/defaults/main.yml
  roles/openshift_control_plane/tasks/check_existing_config.yml
  roles/openshift_control_plane/tasks/generate_session_secrets.yml
  roles/openshift_control_plane/tasks/main.yml
  roles/openshift_control_plane/templates/master.yaml.v1.j2
  roles/openshift_control_plane/templates/sessionSecretsFile.yaml.v1.j2
  roles/openshift_facts/library/openshift_facts.py
  roles/openshift_master_facts/tasks/main.yml
Labels: lgtm, size/L

#7768 fix cherry for binary name
  roles/openshift_storage_glusterfs/tasks/glusterfs_common.yml
  roles/openshift_storage_glusterfs/tasks/heketi_deploy_part2.yml
Labels: lgtm, size/XS

#7720 CRIO openshift-sdn toggle
  roles/container_runtime/defaults/main.yml
  roles/container_runtime/tasks/package_crio.yml
  roles/container_runtime/tasks/systemcontainer_crio.yml
Labels: lgtm, size/XS

#7772 is_atomic fix
  roles/openshift_storage_glusterfs/tasks/glusterfs_common.yml
Labels: lgtm, size/XS

#7773 Fix undefined variable in session secrets
  roles/openshift_control_plane/defaults/main.yml
Labels: lgtm, size/XS

#7688 Cert check playbooks: remove become
  playbooks/openshift-checks/certificate_expiry/easy-mode.yaml
  playbooks/openshift-checks/certificate_expiry/html_and_json_default_paths.yaml
  playbooks/openshift-checks/certificate_expiry/html_and_json_timestamp.yaml
  playbooks/openshift-checks/certificate_expiry/longer-warning-period-json-results.yaml
  playbooks/openshift-checks/certificate_expiry/longer_warning_period.yaml
Labels: lgtm, size/XS

#7778 GlusterFS: Fix missing parameter for registry PVC
  roles/openshift_persistent_volumes/tasks/main.yml
Labels: size/XS

#7405 GlusterFS: Use custom StorageClass for S3
  roles/openshift_storage_glusterfs/files/gluster-s3-pvcs-template.yml
  roles/openshift_storage_glusterfs/tasks/gluster_s3_deploy.yml
  roles/openshift_storage_glusterfs/templates/gluster-s3-storageclass.yml.j2
Labels: lgtm, size/M

#7758 [release-3.9] [1561247] Add kubeconfig to openshift_bootstrap_autoapprover
  roles/openshift_bootstrap_autoapprover/tasks/main.yml
Labels: kind/bug, lgtm, size/XS

#7699 Refactor openshift_version setting
  playbooks/common/openshift-cluster/upgrades/pre/verify_upgrade_targets.yml
  playbooks/common/openshift-cluster/upgrades/pre/version_override.yml
  playbooks/container-runtime/config.yml
  playbooks/container-runtime/setup_storage.yml
  playbooks/init/main.yml
  playbooks/init/version.yml
  playbooks/openshift-etcd/certificates.yml
  playbooks/openshift-etcd/config.yml
  playbooks/openshift-etcd/redeploy-ca.yml
  playbooks/openshift-etcd/redeploy-certificates.yml
  playbooks/openshift-etcd/restart.yml
  playbooks/openshift-etcd/scaleup.yml
  playbooks/openshift-etcd/upgrade.yml
  playbooks/openshift-node/private/image_prep.yml
  playbooks/prerequisites.yml
  roles/container_runtime/defaults/main.yml
  roles/lib_utils/action_plugins/sanity_checks.py
  roles/openshift_repos/tasks/centos_repos.yml
  roles/openshift_repos/tasks/rhel_repos.yml
  roles/openshift_version/defaults/main.yml
  roles/openshift_version/tasks/check_available_rpms.yml
  roles/openshift_version/tasks/first_master.yml
  roles/openshift_version/tasks/first_master_containerized_version.yml
  roles/openshift_version/tasks/first_master_rpm_version.yml
  roles/openshift_version/tasks/masters_and_nodes.yml
Labels: lgtm, size/L

#7786 Fix session secrets file and remove old facts
  inventory/hosts.example
  playbooks/openshift-master/private/certificates-backup.yml
  playbooks/openshift-master/private/config.yml
  playbooks/openshift-master/private/scaleup.yml
  roles/openshift_control_plane/tasks/generate_session_secrets.yml
  roles/openshift_control_plane/tasks/main.yml
  roles/openshift_control_plane/templates/master.yaml.v1.j2
  roles/openshift_facts/library/openshift_facts.py
  roles/openshift_master_facts/tasks/main.yml
Labels: kind/bug, lgtm, priority/P1, size/M

#7785 master: set DEBUG_LOGLEVEL based on openshift_master_debug_level
  roles/openshift_control_plane/files/apiserver.yaml
  roles/openshift_control_plane/files/controller.yaml
  roles/openshift_control_plane/templates/master.env.j2
Labels: lgtm, size/XS

#7784 Ensure legacy inventories continue to work for infra nodes
  roles/openshift_manage_node/tasks/set_default_node_role.yml
Labels: lgtm, size/S

#7763 Use consistent config location in web console debugging
  roles/openshift_web_console/tasks/start.yml
Labels: lgtm, size/XS

#7761 Updating default image tags to be only vX.Y for origin installs
  roles/openshift_logging_curator/vars/default_images.yml
  roles/openshift_logging_elasticsearch/vars/default_images.yml
  roles/openshift_logging_eventrouter/vars/default_images.yml
  roles/openshift_logging_fluentd/vars/default_images.yml
  roles/openshift_logging_kibana/vars/default_images.yml
  roles/openshift_logging_mux/vars/default_images.yml
Labels: affects_3.9, lgtm, size/M

#7738 Implement descheduler cluster lifecycle role and playbook.
  playbooks/openshift-descheduler/config.yml
  playbooks/openshift-descheduler/private/config.yml
  playbooks/openshift-descheduler/private/roles
  playbooks/openshift-descheduler/private/uninstall.yml
  playbooks/openshift-descheduler/private/upgrade.yml
  playbooks/openshift-descheduler/uninstall.yml
  playbooks/openshift-descheduler/upgrade.yml
  roles/openshift_descheduler/README.md
  roles/openshift_descheduler/defaults/main.yaml
  roles/openshift_descheduler/files/clusterrole.yaml
  roles/openshift_descheduler/meta/main.yaml
  roles/openshift_descheduler/tasks/install_descheduler.yaml
  roles/openshift_descheduler/tasks/main.yaml
  roles/openshift_descheduler/tasks/uninstall_descheduler.yaml
  roles/openshift_descheduler/tasks/upgrade.yaml
  roles/openshift_descheduler/templates/descheduler-cronjob.yaml.j2
  roles/openshift_descheduler/templates/policy.yaml.j2
Labels: lgtm, size/L

#7709 Add logic for new default CRD backend for ASB
  roles/ansible_service_broker/files/bundles.automationbroker.io.yaml
  roles/ansible_service_broker/files/jobstates.automationbroker.io.yaml
  roles/ansible_service_broker/files/servicebindings.automationbroker.io.yaml
  roles/ansible_service_broker/files/serviceinstances.automationbroker.io.yaml
  roles/ansible_service_broker/tasks/facts.yml
  roles/ansible_service_broker/tasks/install.yml
  roles/ansible_service_broker/tasks/migrate.yml
  roles/ansible_service_broker/tasks/remove.yml
  roles/ansible_service_broker/tasks/upgrade.yml
  roles/ansible_service_broker/templates/asb_dc.yaml.j2
  roles/ansible_service_broker/templates/configmap.yaml.j2
Labels: lgtm, size/XL

#7712 PAPR - Don't install ASB, do install TSB
  .papr.inventory
Labels: lgtm, size/XS

#7795 openshift_facts: convert node labels to string before joining
  roles/openshift_facts/library/openshift_facts.py
Labels: size/XS

#7687 openshift_facts: convert node labels to string before joining
  roles/openshift_facts/library/openshift_facts.py
Labels: size/XS

#7770 Don't install etcd on bootstrapped hosts
  roles/etcd/tasks/certificates/fetch_server_certificates_from_ca.yml
  roles/etcd/tasks/static.yml
Labels: lgtm, size/S

#7684 Remove openshift_etcd_facts role
  playbooks/openshift-etcd/private/ca.yml
  playbooks/openshift-etcd/private/master_etcd_certificates.yml
  playbooks/openshift-etcd/private/scaleup.yml
  playbooks/openshift-etcd/private/server_certificates.yml
  playbooks/openshift-etcd/private/upgrade_backup.yml
  playbooks/openshift-node/private/etcd_client_config.yml
  roles/etcd/defaults/main.yaml
  roles/etcd/tasks/add_new_member.yml
  roles/etcd/tasks/rpm.yml
  roles/etcd/tasks/set_facts.yml
  roles/etcd/tasks/static.yml
  roles/nuage_master/tasks/etcd_certificates.yml
  roles/openshift_etcd/meta/main.yml
  roles/openshift_etcd_client_certificates/meta/main.yml
  roles/openshift_etcd_facts/defaults/main.yml
  roles/openshift_etcd_facts/meta/main.yml
  roles/openshift_etcd_facts/tasks/main.yml
  roles/openshift_etcd_facts/tasks/set_etcd_ca_host.yml
  roles/openshift_etcd_facts/vars/main.yml
Labels: lgtm, size/L

#7788 Allow no sdn's to be specified in sanity checks
  roles/lib_utils/action_plugins/sanity_checks.py
Labels: lgtm, size/XS

#7776 [release-3.9] RPM upgrade: support jinja 2.7
  roles/openshift_master/tasks/upgrade/rpm_upgrade.yml
Labels: lgtm, size/XS

#7764 Fixing crlnumber file missing during 'openshift_logging' install
  roles/openshift_logging/tasks/generate_certs.yaml
Labels: lgtm, size/S

#7757 Updating for es5.x image naming and removing origin restriction
  roles/openshift_logging/tasks/install_logging.yaml
  roles/openshift_logging/tasks/main.yaml
  roles/openshift_logging_curator/tasks/main.yaml
  roles/openshift_logging_curator/templates/2.x/curator.j2
  roles/openshift_logging_curator/templates/5.x/curator-cj.j2
  roles/openshift_logging_elasticsearch/tasks/main.yaml
  roles/openshift_logging_elasticsearch/templates/2.x/es.j2
  roles/openshift_logging_elasticsearch/templates/5.x/es.j2
  roles/openshift_logging_fluentd/templates/2.x/fluentd.j2
  roles/openshift_logging_fluentd/templates/5.x/fluentd.j2
  roles/openshift_logging_kibana/tasks/main.yaml
  roles/openshift_logging_kibana/templates/2.x/kibana.j2
  roles/openshift_logging_kibana/templates/5.x/kibana.j2
Labels: lgtm, size/M

#7781 [release-3.6] [1529575] Ensure etcd.conf variables are updated during upgrade
  roles/etcd/tasks/upgrade/validate_etcd_conf.yml
  roles/etcd_upgrade/tasks/upgrade_image.yml
  roles/etcd_upgrade/tasks/upgrade_rpm.yml
  roles/openshift_certificate_expiry/library/openshift_cert_expiry.py
Labels: kind/bug, lgtm, size/M

#7780 [release-3.7] [1529575] Ensure etcd.conf variables are updated during upgrade
  roles/etcd/tasks/upgrade/upgrade_image.yml
  roles/etcd/tasks/upgrade/upgrade_rpm.yml
  roles/etcd/tasks/upgrade/validate_etcd_conf.yml
  roles/openshift_certificate_expiry/library/openshift_cert_expiry.py
Labels: kind/bug, lgtm, size/M

#7683 [BZ 1560695] Add support for standalone hawkular-metrics schema installer
  roles/openshift_metrics/tasks/install_hawkular_schema_job.yaml
  roles/openshift_metrics/tasks/install_metrics.yaml
  roles/openshift_metrics/templates/hawkular_metrics_schema_job.j2
Labels: lgtm, size/M

#7506 Use long form of "scc" resource type in logging facts
  roles/openshift_logging/library/openshift_logging_facts.py
Labels: lgtm, size/XS

#7695 Remove etcd_migrate and embedded2external
  playbooks/openshift-etcd/embedded2external.yml
  playbooks/openshift-etcd/migrate.yml
  playbooks/openshift-etcd/private/embedded2external.yml
  playbooks/openshift-etcd/private/migrate.yml
  roles/etcd/defaults/main.yaml
  roles/etcd/tasks/auxiliary/clean_data.yml
  roles/etcd/tasks/auxiliary/disable_etcd.yml
  roles/etcd/tasks/auxiliary/force_new_cluster.yml
  roles/etcd/tasks/backup.archive.yml
  roles/etcd/tasks/backup.copy.yml
  roles/etcd/tasks/backup.fetch.yml
  roles/etcd/tasks/backup.force_new_cluster.yml
  roles/etcd/tasks/backup.unarchive.yml
  roles/etcd/tasks/backup/backup.yml
  roles/etcd/tasks/backup_master_etcd_certificates.yml
  roles/etcd/tasks/certificates/backup_master_etcd_certificates.yml
  roles/etcd/tasks/check_cluster_health.yml
  roles/etcd/tasks/clean_data.yml
  roles/etcd/tasks/disable_etcd.yml
  roles/etcd/tasks/migrate.add_ttls.yml
  roles/etcd/tasks/migrate.configure_master.yml
  roles/etcd/tasks/migrate.pre_check.yml
  roles/etcd/tasks/migrate.yml
  roles/etcd/tasks/migration/add_ttls.yml
  roles/etcd/tasks/migration/check.yml
  roles/etcd/tasks/migration/check_cluster_health.yml
  roles/etcd/tasks/migration/check_cluster_status.yml
  roles/etcd/tasks/migration/configure_master.yml
  roles/etcd/tasks/migration/migrate.yml
  roles/lib_utils/library/openshift_cert_expiry.py
  roles/nuage_master/tasks/etcd_certificates.yml
  roles/openshift_master/defaults/main.yml
  roles/openshift_master/tasks/configure_external_etcd.yml
Labels: lgtm, size/XL

#7820 Add CL role and playbook for Node Problem Detector
  playbooks/openshift-node-problem-detector/config.yml
  playbooks/openshift-node-problem-detector/private/config.yml
  playbooks/openshift-node-problem-detector/private/roles
  playbooks/openshift-node-problem-detector/private/uninstall.yml
  playbooks/openshift-node-problem-detector/private/upgrade.yml
  playbooks/openshift-node-problem-detector/uninstall.yml
  playbooks/openshift-node-problem-detector/upgrade.yml
  roles/openshift_node_problem_detector/README.md
  roles/openshift_node_problem_detector/defaults/main.yaml
  roles/openshift_node_problem_detector/files/node-problem-detector-configmap.yaml
  roles/openshift_node_problem_detector/meta/main.yaml
  roles/openshift_node_problem_detector/tasks/install.yaml
  roles/openshift_node_problem_detector/tasks/main.yaml
  roles/openshift_node_problem_detector/tasks/uninstall.yaml
  roles/openshift_node_problem_detector/tasks/upgrade.yaml
  roles/openshift_node_problem_detector/templates/node-problem-detector-daemonset.yaml.j2
Labels: lgtm, size/L

#7268 Upgrade Prometheus AlertManager to v0.14.0
  roles/openshift_prometheus/vars/default_images.yml
Labels: lgtm, size/XS

#7609 [release-3.7] Add max-time option to curl to avoid long running ansible
  playbooks/common/openshift-master/scaleup.yml
  playbooks/common/openshift-master/tasks/wire_aggregator.yml
  roles/openshift_logging/handlers/main.yml
  roles/openshift_manage_node/tasks/main.yml
  roles/openshift_master/handlers/main.yml
  roles/openshift_master/tasks/check_master_api_is_ready.yml
  roles/openshift_metrics/handlers/main.yml
  roles/openshift_node/tasks/config.yml
Labels: size/S

#5387 disable adc reconciler sync for aws
  roles/openshift_facts/library/openshift_facts.py
Labels: lgtm, size/XS

#7509 backport calico self-hosted install to v3.9
  playbooks/byo/calico/legacy_upgrade.yml
  playbooks/byo/calico/roles
  playbooks/byo/calico/upgrade_versions.yml
  roles/calico/README.md
  roles/calico/defaults/main.yaml
  roles/calico/handlers/main.yml
  roles/calico/meta/main.yml
  roles/calico/tasks/main.yml
  roles/calico/templates/10-calico.conf.j2
  roles/calico/templates/calico.service.j2
  roles/calico/templates/calicoctl.cfg.j2
  roles/calico_master/README.md
  roles/calico_master/defaults/main.yaml
  roles/calico_master/meta/main.yml
  roles/calico_master/tasks/certs.yml
  roles/calico_master/tasks/main.yml
  roles/calico_master/templates/calico-policy-controller.yml.j2
  roles/calico_master/templates/calico.yml.j2
Labels: do-not-merge/hold, size/XXL

#7789 Remove some pointless usages of openshift_facts
  playbooks/common/openshift-cluster/upgrades/v3_9/upgrade_control_plane.yml
  playbooks/openshift-master/private/upgrade.yml
  playbooks/openshift-master/private/validate_restart.yml
  roles/etcd/tasks/upgrade/upgrade_image.yml
  roles/openshift_cli/tasks/main.yml
Labels: lgtm, size/M

#7810 bug 1535300. Default logging namespace to openshift-logging
  roles/openshift_hosted/defaults/main.yml
  roles/openshift_logging/defaults/main.yml
  roles/openshift_logging/tasks/install_logging.yaml
  roles/openshift_logging/tasks/main.yaml
  roles/openshift_logging/vars/main.yaml
  roles/openshift_sanitize_inventory/vars/main.yml
Labels: affects_3.9, lgtm, size/M

#7828 Calico fixes
  roles/calico_master/tasks/certs.yml
  roles/calico_master/tasks/main.yml
Labels: lgtm, size/XS

#7823 Change set imagepullpolicy to allow for offline install
  roles/openshift_storage_glusterfs/files/deploy-heketi-template.yml
Labels: lgtm, size/XS

#7821 Update console liveness probe
  roles/openshift_web_console/files/console-template.yaml
Labels: lgtm, size/XS

#7817 Remove unused task-file import
  roles/openshift_node/tasks/upgrade_pre.yml
Labels: lgtm, size/XS

#7816 Remove dead code from openshift_facts
  roles/openshift_facts/library/openshift_facts.py
Labels: lgtm, size/L

#7813 PAPR: install ASB after CRD backend is used
  .papr.inventory
Labels: lgtm, size/XS

#7799 PARP: Store ansible log file separately
  .papr.sh
  .papr.yml
Labels: lgtm, size/XS

#7798 PAPR: remove bootstrap vars to be as close to default as possible
  .papr.inventory
Labels: lgtm, size/XS

#7807 Bug 1564499 - ASB usability improvements
  roles/ansible_service_broker/defaults/main.yml
  roles/ansible_service_broker/templates/configmap.yaml.j2
Labels: lgtm, size/XS

#7774 Revert "Add metrics-server to openshift-metrics playbook"
  roles/openshift_metrics/README.md
  roles/openshift_metrics/defaults/main.yaml
  roles/openshift_metrics/tasks/generate_certificates.yaml
  roles/openshift_metrics/tasks/generate_metrics_server_certificates.yaml
  roles/openshift_metrics/tasks/generate_rolebindings.yaml
  roles/openshift_metrics/tasks/generate_serviceaccounts.yaml
  roles/openshift_metrics/tasks/generate_services.yaml
  roles/openshift_metrics/tasks/install_metrics.yaml
  roles/openshift_metrics/tasks/install_support.yaml
  roles/openshift_metrics/tasks/pre_install.yaml
  roles/openshift_metrics/tasks/uninstall_metrics.yaml
  roles/openshift_metrics/templates/metrics-server-apiservice.j2
  roles/openshift_metrics/templates/metrics-server-auth-delegator.j2
  roles/openshift_metrics/templates/metrics-server-auth-reader.j2
  roles/openshift_metrics/templates/metrics-server-deployment.j2
  roles/openshift_metrics/templates/metrics-server-resource-reader.j2
  roles/openshift_metrics/templates/metrics-server-role.js2
  roles/openshift_metrics/templates/metrics-server-sa.j2
  roles/openshift_metrics/templates/metrics-server-service.j2
Labels: lgtm, size/L

#7676 Re-Org OpenStack provision playbooks
  playbooks/openstack/openshift-cluster/provision.yml
  playbooks/openstack/openshift-cluster/provision_install.yml
Labels: lgtm, size/XS

#7830 Fix type of l_osm_session_secrets_stat
  roles/openshift_control_plane/tasks/generate_session_secrets.yml
Labels: kind/bug, lgtm, size/S

#7822 Cleanup node role tasks
  roles/openshift_node/tasks/config.yml
  roles/openshift_node/tasks/container_images.yml
  roles/openshift_node/tasks/dnsmasq_install.yml
  roles/openshift_node/tasks/main.yml
  roles/openshift_node/tasks/storage_plugins/ceph.yml
  roles/openshift_node/tasks/storage_plugins/glusterfs.yml
  roles/openshift_node/tasks/storage_plugins/nfs.yml
Labels: lgtm, size/M

#7818 Change include_ to import_ where possible
  playbooks/common/openshift-cluster/upgrades/docker/docker_upgrade.yml
  playbooks/common/openshift-cluster/upgrades/docker/tasks/upgrade.yml
  playbooks/common/openshift-cluster/upgrades/pre/config.yml
  playbooks/openshift-master/private/config.yml
  playbooks/openshift-master/private/enable_bootstrap.yml
  playbooks/openshift-master/private/upgrade.yml
  roles/openshift_control_plane/tasks/main.yml
  roles/openshift_control_plane/tasks/update-vsphere.yml
  roles/openshift_control_plane/tasks/upgrade.yml
  roles/openshift_control_plane/tasks/upgrade/upgrade_scheduler.yml
Labels: kind/bug, lgtm, size/M

#7649 Make API aggregation part of openshift_ca
  playbooks/openshift-master/private/tasks/wire_aggregator.yml
  roles/openshift_control_plane/templates/master.yaml.v1.j2
Labels: lgtm, queue/blocks-others, size/L

#5563 Remove quick installer
  .github/ISSUE_TEMPLATE.md
  images/installer/Dockerfile.rhel7
  images/installer/root/exports/manifest.json
  openshift-ansible.spec
  setup.cfg
  setup.py
  tox.ini
  utils/.gitignore
  utils/README.md
  utils/docs/config.md
  utils/docs/man/man1/atomic-openshift-installer.1
  utils/docs/man/man1/atomic-openshift-installer.1.asciidoc.in
  utils/etc/ansible-quiet.cfg
  utils/etc/ansible.cfg
  utils/setup.cfg
  utils/setup.py
  utils/site_assets/oo-install-bootstrap.sh
  utils/site_assets/oo_install_launcher.README.txt
  utils/src/DESCRIPTION.rst
  utils/src/MANIFEST.in
  utils/src/ooinstall/__init__.py
  utils/src/ooinstall/ansible_plugins/facts_callback.py
  utils/src/ooinstall/cli_installer.py
  utils/src/ooinstall/oo_config.py
  utils/src/ooinstall/openshift_ansible.py
  utils/src/ooinstall/utils.py
  utils/src/ooinstall/variants.py
  utils/test/__init__.py
  utils/test/cli_installer_tests.py
  utils/test/fixture.py
  utils/test/oo_config_tests.py
  utils/test/openshift_ansible_tests.py
  utils/test/test_utils.py
Labels: lgtm, size/XXL

#7681 service catalog: create service and ssl certs for controller manager
  roles/openshift_prometheus/templates/prometheus.yml.j2
  roles/openshift_service_catalog/tasks/generate_certs.yml
  roles/openshift_service_catalog/tasks/install.yml
  roles/openshift_service_catalog/templates/api_server.j2
  roles/openshift_service_catalog/templates/controller_manager.j2
Labels: lgtm, size/M

#7847 Fix wrong reference to user policy.
  roles/openshift_grafana/tasks/install_grafana.yaml
Labels: lgtm, size/XS

#7209 Add the OpenStack load balancer deployment options
  playbooks/openstack/configuration.md
  playbooks/openstack/inventory.py
  playbooks/openstack/openshift-cluster/cluster-info.yml
  playbooks/openstack/openshift-cluster/install.yml
  playbooks/openstack/openshift-cluster/provision.yml
  playbooks/openstack/post-install.md
  playbooks/openstack/sample-inventory/group_vars/all.yml
  roles/openshift_openstack/defaults/main.yml
  roles/openshift_openstack/tasks/check-prerequisites.yml
  roles/openshift_openstack/tasks/generate-dns.yml
  roles/openshift_openstack/templates/heat_stack.yaml.j2
  roles/openshift_openstack/templates/heat_stack_server.yaml.j2
Labels: lgtm, size/L

#7856 Prefix the node-problem-detector with the system:
  roles/openshift_node_problem_detector/tasks/install.yaml
  roles/openshift_node_problem_detector/tasks/uninstall.yaml
Labels: lgtm, size/XS

#7836 Switch Node Problem Detector to only pull IfNotPresent, make it configurable
  roles/openshift_node_problem_detector/defaults/main.yaml
  roles/openshift_node_problem_detector/tasks/install.yaml
  roles/openshift_node_problem_detector/templates/node-problem-detector-daemonset.yaml.j2
Labels: lgtm, size/XS

#7835 [3.9] PAPR: verify minor update on all-in-one cluster
  .papr.all-in-one.inventory
  .papr.sh
  .papr.yml
  setup.py
Labels: lgtm, size/M

#7831 GlusterFS: enable modprobe in pods that manage bricks
  roles/openshift_storage_glusterfs/files/glusterfs-template.yml
Labels: lgtm, size/XS

#6713 Support creating OpenStack Cinder registry volume
  playbooks/openstack/configuration.md
  playbooks/openstack/sample-inventory/group_vars/OSEv3.yml
  playbooks/openstack/sample-inventory/group_vars/all.yml
  roles/lib_utils/action_plugins/generate_pv_pvcs_list.py
  roles/openshift_openstack/tasks/create-registry-volume.yml
  roles/openshift_openstack/tasks/provision.yml
Labels: lgtm, size/L

#7868 Add missing 'is' in when condiditon for slurp
  roles/openshift_control_plane/tasks/generate_session_secrets.yml
Labels: lgtm, size/XS

#7869 Removing clear_facts from 3.10 upgrade
  playbooks/common/openshift-cluster/upgrades/v3_10/upgrade_control_plane.yml
Labels: lgtm, size/XS

#7878 Update dbus before installing dnsmasq
  roles/openshift_node/tasks/dnsmasq_install.yml
Labels: size/S

#7888 [3.9] Update dbus before installing dnsmasq
  roles/openshift_node/tasks/dnsmasq_install.yml
Labels: size/S

#7849 Fix OpenStack playbooks on clouds without Cinder
  playbooks/openstack/inventory.py
Labels: lgtm, size/S

#7855 wait_for_pod: wait for deployment to be Complete
  roles/openshift_hosted/tasks/wait_for_pod.yml
Labels: lgtm, size/XS

#7887 Add oo_etcd_to_config to service_catalog init
  playbooks/openshift-service-catalog/config.yml
Labels: size/XS

#7530 Label master nodes with openshift-infra=apiserver for service catalog
  roles/openshift_service_catalog/defaults/main.yml
Labels: lgtm, size/XS

#7870 Add openshift-descheduler project.
  roles/openshift_descheduler/defaults/main.yaml
  roles/openshift_descheduler/tasks/install_descheduler.yaml
  roles/openshift_descheduler/tasks/uninstall_descheduler.yaml
  roles/openshift_descheduler/tasks/upgrade.yaml
  roles/openshift_descheduler/templates/descheduler-cronjob.yaml.j2
Labels: lgtm, size/M

#7912 Only install docker-rhel-push-plugin on enterprise
  roles/container_runtime/tasks/package_docker.yml
Labels: lgtm, size/XS

#7927 Revert docker-rhel-push-plugin
  roles/container_runtime/tasks/package_docker.yml
Labels: size/XS

#7854 Openshift facts: ensure 'disable-attach-detach-reconcile-sync' contains a list value
  roles/openshift_facts/library/openshift_facts.py
Labels: lgtm, size/XS

#7908 Don't block on node start when bootstrapping
  roles/openshift_node/tasks/distribute_bootstrap.yml
Labels: lgtm, size/XS

#7930 fixed typo, caused unknown char error
  roles/openshift_hosted/tasks/secure.yml
Labels: size/XS

#7918 [3.7] etcd migrate: skip openshift version check during migration
  playbooks/common/openshift-etcd/migrate.yml
  roles/openshift_version/tasks/main.yml
Labels: lgtm, size/XS

#7767 Release 3.6 gluster fs cherry e2e
  playbooks/byo/openshift-glusterfs/uninstall.yml
  playbooks/common/openshift-glusterfs/config.yml
  playbooks/common/openshift-glusterfs/uninstall.yml
  roles/openshift_facts/library/openshift_facts.py
  roles/openshift_hosted/README.md
  roles/openshift_hosted/tasks/registry/registry.yml
  roles/openshift_hosted/tasks/registry/storage/glusterfs.yml
  roles/openshift_hosted/tasks/storage/glusterfs_endpoints.yml
  roles/openshift_hosted/templates/v3.6/glusterfs-registry-endpoints.yml.j2
  roles/openshift_hosted/templates/v3.6/glusterfs-registry-service.yml.j2
  roles/openshift_node/tasks/storage_plugins/iscsi.yml
  roles/openshift_sanitize_inventory/tasks/unsupported.yml
  roles/openshift_storage_glusterfs/README.md
  roles/openshift_storage_glusterfs/defaults/main.yml
  roles/openshift_storage_glusterfs/files/v1.5/glusterfs-template.yml
  roles/openshift_storage_glusterfs/files/v3.6/deploy-heketi-template.yml
  roles/openshift_storage_glusterfs/files/v3.6/gluster-s3-template.yml
  roles/openshift_storage_glusterfs/files/v3.6/glusterfs-template.yml
  roles/openshift_storage_glusterfs/files/v3.6/heketi-template.yml
  roles/openshift_storage_glusterfs/tasks/glusterfs_common.yml
  roles/openshift_storage_glusterfs/tasks/glusterfs_config.yml
  roles/openshift_storage_glusterfs/tasks/glusterfs_config_facts.yml
  roles/openshift_storage_glusterfs/tasks/glusterfs_deploy.yml
  roles/openshift_storage_glusterfs/tasks/glusterfs_registry.yml
  roles/openshift_storage_glusterfs/tasks/glusterfs_registry_facts.yml
  roles/openshift_storage_glusterfs/tasks/glusterfs_uninstall.yml
  roles/openshift_storage_glusterfs/tasks/heketi_deploy_part2.yml
  roles/openshift_storage_glusterfs/tasks/host_services.yml
  roles/openshift_storage_glusterfs/tasks/kernel_modules.yml
  roles/openshift_storage_glusterfs/tasks/main.yml
  roles/openshift_storage_glusterfs/tasks/uninstall.yml
  roles/openshift_storage_glusterfs/templates/glusterfs.conf
  roles/openshift_storage_glusterfs/templates/glusterfs.conf.j2
  roles/openshift_storage_glusterfs/templates/v1.5/glusterfs-storageclass.yml.j2
  roles/openshift_storage_glusterfs/templates/v1.5/topology.json.j2
  roles/openshift_storage_glusterfs/templates/v3.6/glusterfs-storageclass.yml.j2
  roles/openshift_storage_glusterfs/templates/v3.6/topology.json.j2
Labels: lgtm, size/XL

#7710 upgrade prometheus 2.1.0 -> 2.2.1
  roles/openshift_prometheus/vars/default_images.yml
Labels: lgtm, size/XS

#7929 Fix missing close parenthesis
  roles/openshift_control_plane/vars/main.yml
Labels: lgtm, size/XS

#7904 Cert verification: add more certs to verify
  roles/lib_utils/library/openshift_cert_expiry.py
Labels: lgtm, size/XS

#7858 Remove obsolete openshift_docker_disable_push_dockerhub
  inventory/hosts.example
  roles/container_runtime/defaults/main.yml
  roles/container_runtime/tasks/package_docker.yml
Labels: lgtm, size/XS

#7891 [3.7] Ensure etcd_urls are created for service_catalog
  playbooks/byo/openshift-cluster/service-catalog.yml
Labels: size/S

#7928 Fix registry x509 SAN omit placeholder
  roles/lib_openshift/library/oc_adm_ca_server_cert.py
  roles/lib_openshift/src/class/oc_adm_ca_server_cert.py
  roles/openshift_hosted/tasks/secure.yml
Labels: lgtm, size/S

#7932 [release-3.7] Set efs provisioner image version to latest
  roles/openshift_provisioners/defaults/main.yaml
Labels: lgtm, size/XS

#7862 Allow node-exporter port through GCP firewall
  roles/openshift_gcp/templates/provision.j2.sh
Labels: lgtm, size/XS

#7812 [3.9] PAPR: check 3 masters install
  .papr-master-ha.inventory
  .papr.yml
Labels: lgtm, size/M

#7919 [3.9] health checks: use etcd_image as it would work on Origin correctly
  roles/openshift_health_checker/openshift_checks/docker_image_availability.py
  roles/openshift_health_checker/test/docker_image_availability_test.py
Labels: lgtm, size/XS

#7901 fix certificate auth on containerized etcd
  roles/etcd/tasks/upgrade/validate_etcd_conf.yml
  roles/etcd/templates/etcd.conf.j2
Labels: lgtm, size/M

#7931 always add es and es-ops hostname to the es server cert
  roles/openshift_logging/files/generate-jks.sh
  roles/openshift_logging/tasks/generate_jks.yaml
Labels: lgtm, size/XS

#7394 Default logging namespace to openshift-logging
  roles/openshift_hosted/defaults/main.yml
  roles/openshift_logging/defaults/main.yml
  roles/openshift_logging/tasks/install_logging.yaml
  roles/openshift_logging/tasks/main.yaml
  roles/openshift_logging/vars/main.yaml
  roles/openshift_sanitize_inventory/vars/main.yml
Labels: affects_3.9, lgtm, size/M

#7925 catalog: use service serving cert for ctrl mgr & use default prometheus scrape
  roles/openshift_prometheus/templates/prometheus.yml.j2
  roles/openshift_service_catalog/tasks/generate_certs.yml
  roles/openshift_service_catalog/tasks/install.yml
Labels: lgtm, size/M

#7935 [BZ 1564857] fix image name
  roles/openshift_metrics/templates/hawkular_metrics_schema_job.j2
Labels: lgtm, size/XS

#7865 Ensure user provides sane values for openshift_release
  roles/openshift_version/defaults/main.yml
  roles/openshift_version/tasks/first_master.yml
Labels: lgtm, size/S

#7953 Revert "bug 1535300. Default logging namespace to openshift-logging"
  roles/openshift_hosted/defaults/main.yml
  roles/openshift_logging/defaults/main.yml
  roles/openshift_logging/tasks/install_logging.yaml
  roles/openshift_logging/tasks/main.yaml
  roles/openshift_logging/vars/main.yaml
  roles/openshift_sanitize_inventory/vars/main.yml
Labels: lgtm, size/M

#7793 Set the pid_max value only when lower than certain threshold.
  roles/tuned/templates/openshift/tuned.conf
Labels: lgtm, size/XS

#7899 [3.9] crio: don't configure openshift-sdn when disabled
  roles/container_runtime/defaults/main.yml
  roles/container_runtime/tasks/package_crio.yml
  roles/container_runtime/tasks/systemcontainer_crio.yml
Labels: size/XS

#7378 Specify the namespace to "oc process" for better idempotent
  roles/template_service_broker/tasks/deploy.yml
Labels: lgtm, size/XS

#7954 Don't always update dbus but do restart dbus if dnsmasq changed
  roles/openshift_node/tasks/dnsmasq_install.yml
Labels: lgtm, size/S

#7900 Mount device manager socket dir path
  roles/openshift_node/templates/openshift.docker.node.service
Labels: lgtm, size/XS

#7745 Improve support for azure cloud provider
  playbooks/openshift-hosted/private/openshift_default_storage_class.yml
  roles/openshift_cloud_provider/tasks/azure.yml
  roles/openshift_cloud_provider/templates/azure.conf.j2
  roles/openshift_default_storage_class/defaults/main.yml
  roles/openshift_facts/library/openshift_facts.py
  roles/openshift_management/README.md
  roles/openshift_management/defaults/main.yml
  roles/openshift_management/tasks/storage/storage.yml
  roles/openshift_management/tasks/validate.yml
  roles/openshift_sanitize_inventory/tasks/main.yml
Labels: lgtm, size/M

#7519 Removing heat template outputs for stack scalability.
  playbooks/openstack/configuration.md
  playbooks/openstack/sample-inventory/group_vars/all.yml
  roles/openshift_openstack/templates/heat_stack.yaml.j2
Labels: lgtm, size/S

#7863 Wipe filesystem metadata from CNS block devices.
  roles/openshift_storage_glusterfs/tasks/glusterfs_uninstall.yml
Labels: lgtm, size/XS

#7769 cluster_monitoring: Bump operator version and adjust related config
  roles/openshift_cluster_monitoring_operator/defaults/main.yml
  roles/openshift_cluster_monitoring_operator/files/cluster-monitoring-operator.yaml
Labels: lgtm, size/S

#7906 cluster_monitoring_operator: Don't use cluster-admin role
  roles/openshift_cluster_monitoring_operator/files/cluster-monitoring-operator.yaml
  roles/openshift_cluster_monitoring_operator/tasks/install.yaml
Labels: lgtm, size/L

#7945 Label all-in-one cluster as compute=true
  roles/openshift_manage_node/tasks/set_default_node_role.yml
Labels: lgtm, size/S

#7937 upgrade prometheus 2.1.0 -> 2.2.1
  roles/openshift_prometheus/vars/default_images.yml
Labels: lgtm

#7844 [release-3.7] Install latest node package during upgrade
  roles/openshift_node_upgrade/tasks/rpm_upgrade.yml
Labels: lgtm, size/XS

#7802 PAPR: check 3 masters install and minor update
  .papr-master-ha.inventory
  .papr.all-in-one.inventory
  .papr.sh
  .papr.yml
  playbooks/common/openshift-cluster/upgrades/pre/verify_cluster.yml
  playbooks/openshift-master/private/upgrade.yml
  playbooks/openshift-node/private/restart.yml
  roles/etcd/defaults/main.yaml
  roles/etcd/tasks/backup/backup.yml
  roles/etcd/tasks/upgrade/upgrade_static.yml
  roles/etcd/tasks/version_detect.yml
  roles/openshift_control_plane/tasks/static_shim.yml
  roles/openshift_node/tasks/upgrade.yml
  setup.py
Labels: lgtm, size/L

#7145 Add support for kuryr-controller health checks
  roles/kuryr/defaults/main.yaml
  roles/kuryr/templates/cni-daemonset.yaml.j2
  roles/kuryr/templates/configmap.yaml.j2
  roles/kuryr/templates/controller-deployment.yaml.j2
Labels: lgtm, size/M

#7974 [3.9] etcd: rework r_etcd_common_etcdctl_command
  roles/etcd/defaults/main.yaml
Labels: lgtm, size/XS

#7982 Fix wrong handler name masters
  roles/openshift_control_plane/tasks/bootstrap_settings.yml
  roles/openshift_control_plane/tasks/update-vsphere.yml
Labels: lgtm, size/XS

#7890 Remove iam_cert23 and use upstream iam_cert.
  roles/lib_utils/library/iam_cert23.py
  roles/openshift_aws/tasks/iam_cert.yml
  roles/openshift_aws/tasks/uninstall_iam_cert.yml
Labels: lgtm, size/L

#7976 Remove all references to prometheus storage via NFS
  inventory/hosts.example
  roles/lib_utils/action_plugins/generate_pv_pvcs_list.py
  roles/openshift_facts/defaults/main.yml
  roles/openshift_prometheus/README.md
  roles/openshift_storage_nfs/tasks/main.yml
  roles/openshift_storage_nfs/templates/exports.j2
Labels: lgtm, size/L

#7968 Add bootstrap and join to node scaleup
  playbooks/openshift-node/scaleup.yml
Labels: lgtm, size/XS

#7965 Remove deprecated networkPluginName from node config template
  roles/openshift_node/templates/node.yaml.v1.j2
Labels: lgtm, size/XS

#7960 Update the docker-registry CA symlink on nodes during upgrade
  roles/openshift_gcp/tasks/setup_scale_group_facts.yml
  roles/openshift_node/tasks/bootstrap.yml
  roles/openshift_node/tasks/upgrade/bootstrap_changes.yml
  roles/openshift_node/tasks/upgrade/config_changes.yml
  roles/openshift_node_group/tasks/upgrade.yml
Labels: approved, lgtm, size/M

#7552 catalog: use configmap for leader election lock
  roles/openshift_service_catalog/files/kubeservicecatalog_roles_bindings.yml
  roles/openshift_service_catalog/templates/controller_manager.j2
Labels: lgtm, size/S

#7998 [BZ 1567251] make cassandra snapshots configurable
  roles/openshift_metrics/defaults/main.yaml
  roles/openshift_metrics/templates/hawkular_cassandra_rc.j2
Labels: lgtm, size/XS

#7955 Don't attempt to set context on non existant paths
  roles/container_runtime/tasks/package_crio.yml
Labels: size/XS

#7997 Revert "crio: Fixup docker SELinux permissions"
  roles/container_runtime/tasks/package_crio.yml
Labels: size/XS

#7864 Adding anti affinity configurations for ES and kibana pods
  roles/openshift_logging_elasticsearch/templates/2.x/es.j2
  roles/openshift_logging_elasticsearch/templates/5.x/es.j2
  roles/openshift_logging_kibana/templates/2.x/kibana.j2
  roles/openshift_logging_kibana/templates/5.x/kibana.j2
Labels: affects_3.9, lgtm, size/M

#7992 Remove etcd_version
  inventory/hosts.example
  roles/etcd/tasks/auxiliary/drop_etcdctl.yml
  roles/etcd/tasks/certificates/fetch_server_certificates_from_ca.yml
  roles/etcd/tasks/rpm.yml
Labels: lgtm, size/XS

#7996 Bug 1567767 - openshift_logging : Run JKS generation script failed
  roles/openshift_logging/files/generate-jks.sh
  roles/openshift_logging/tasks/generate_jks.yaml
Labels: lgtm, size/M

#7987 [release-3.9] fix certificate auth on containerized etcd
  roles/etcd/tasks/upgrade/validate_etcd_conf.yml
  roles/etcd/templates/etcd.conf.j2
Labels: lgtm, size/M

#7977 cluster_monitoring_operator: Bump to the latest build
  roles/openshift_cluster_monitoring_operator/defaults/main.yml
  roles/openshift_cluster_monitoring_operator/files/cluster-monitoring-operator.yaml
Labels: lgtm, size/XS

#7970 Fix undefined var in openstack dns record setting
  roles/openshift_openstack/tasks/generate-dns.yml
Labels: lgtm, size/XS

#7853 fixing Master Scaleup process
  playbooks/common/openshift-master/tasks/wire_aggregator.yml
Labels: lgtm, size/XS

#5646 Add OWNERS files
  OWNERS
  docs/openshift_components.md
  playbooks/aws/OWNERS
  playbooks/cluster-operator/OWNERS
  playbooks/gcp/OWNERS
  playbooks/openshift-checks/OWNERS
  playbooks/openshift-descheduler/OWNERS
  playbooks/openshift-glusterfs/OWNERS
  playbooks/openshift-logging/OWNERS
  playbooks/openshift-metrics/OWNERS
  playbooks/openshift-monitoring/OWNERS
  playbooks/openshift-node-problem-detector/OWNERS
  playbooks/openshift-prometheus/OWNERS
  playbooks/openshift-service-catalog/OWNERS
  playbooks/openshift-web-console/OWNERS
  playbooks/openstack/OWNERS
  roles/ansible_service_broker/OWNERS
  roles/kuryr/OWNERS
  roles/openshift_aws/OWNERS
  roles/openshift_builddefaults/OWNERS
  roles/openshift_buildoverrides/OWNERS
  roles/openshift_ca/OWNERS
  roles/openshift_certificate_expiry/OWNERS
  roles/openshift_cfme/OWNERS
  roles/openshift_cluster_monitoring_operator/OWNERS
  roles/openshift_daemonset_config/OWNERS
  roles/openshift_descheduler/OWNERS
  roles/openshift_docker_gc/OWNERS
  roles/openshift_gcp/OWNERS
  roles/openshift_health_checker/OWNERS
  roles/openshift_logging/OWNERS
  roles/openshift_logging_curator/OWNERS
  roles/openshift_logging_elasticsearch/OWNERS
  roles/openshift_logging_eventrouter/OWNERS
  roles/openshift_logging_fluentd/OWNERS
  roles/openshift_logging_kibana/OWNERS
  roles/openshift_logging_mux/OWNERS
  roles/openshift_metrics/OWNERS
  roles/openshift_named_certificates/OWNERS
  roles/openshift_node_certificates/OWNERS
  roles/openshift_node_problem_detector/OWNERS
  roles/openshift_openstack/OWNERS
  roles/openshift_prometheus/OWNERS
  roles/openshift_service_catalog/OWNERS
  roles/openshift_storage_glusterfs/OWNERS
  roles/openshift_web_console/OWNERS
  roles/tuned/OWNERS
Labels: retest-not-required-docs-only, size/XL

#7961 Provide backup_ext functionality keeping backwards compatibility.
  roles/lib_openshift/library/oc_adm_ca_server_cert.py
  roles/lib_openshift/library/oc_adm_csr.py
  roles/lib_openshift/library/oc_adm_manage_node.py
  roles/lib_openshift/library/oc_adm_policy_group.py
  roles/lib_openshift/library/oc_adm_policy_user.py
  roles/lib_openshift/library/oc_adm_registry.py
  roles/lib_openshift/library/oc_adm_router.py
  roles/lib_openshift/library/oc_clusterrole.py
  roles/lib_openshift/library/oc_configmap.py
  roles/lib_openshift/library/oc_edit.py
  roles/lib_openshift/library/oc_env.py
  roles/lib_openshift/library/oc_group.py
  roles/lib_openshift/library/oc_image.py
  roles/lib_openshift/library/oc_label.py
  roles/lib_openshift/library/oc_obj.py
  roles/lib_openshift/library/oc_objectvalidator.py
  roles/lib_openshift/library/oc_process.py
  roles/lib_openshift/library/oc_project.py
  roles/lib_openshift/library/oc_pvc.py
  roles/lib_openshift/library/oc_route.py
  roles/lib_openshift/library/oc_scale.py
  roles/lib_openshift/library/oc_secret.py
  roles/lib_openshift/library/oc_service.py
  roles/lib_openshift/library/oc_serviceaccount.py
  roles/lib_openshift/library/oc_serviceaccount_secret.py
  roles/lib_openshift/library/oc_storageclass.py
  roles/lib_openshift/library/oc_user.py
  roles/lib_openshift/library/oc_version.py
  roles/lib_openshift/library/oc_volume.py
  roles/lib_utils/library/yedit.py
  roles/lib_utils/src/ansible/yedit.py
  roles/lib_utils/src/class/yedit.py
  roles/lib_utils/src/doc/yedit
  roles/lib_utils/src/test/integration/yedit.yml
  roles/lib_utils/src/test/unit/test_yedit.py
Labels: lgtm, size/XL
