Repository openshift/openshift-ansible, pull requests merged in 2018-10, with the labels that each got.

#10128 Update Web Console customizations variables
  inventory/hosts.example
Labels: lgtm, size/XS

#10081 Cns secgrp
  roles/openshift_openstack/templates/heat_stack.yaml.j2
Labels: approved, lgtm, size/XS

#9881 node_boot_time metric not available anymore
  roles/openshift_grafana/files/dashboards/node-exporter-full-dashboard.json
Labels: lgtm, size/XS

#10268 Add pyOpenSSL and iproute to RPM dependencies
  openshift-ansible.spec
Labels: approved, lgtm, size/XS

#10275 Replace 'command chmod' with 'file mode=...'
  playbooks/openshift-etcd/private/redeploy-ca.yml
  playbooks/openshift-master/private/create_service_signer_cert.yml
  playbooks/openshift-master/private/redeploy-openshift-ca.yml
  roles/openshift_examples/tasks/main.yml
  roles/openshift_master_certificates/tasks/main.yml
Labels: approved, lgtm, size/S

#10227 Replace undefined {{ item }} by filename
  roles/openshift_storage_glusterfs/tasks/gluster_s3_deploy.yml
Labels: approved, lgtm, size/XS

#10278 Add CI scripts in hack/
  hack/ci-build-rpm.sh
  hack/ci-build-unittests.sh
  hack/ci-run-unittests.sh
Labels: approved, lgtm, size/S

#10183 Fixes #8267
  roles/lib_utils/library/openshift_cert_expiry.py
  roles/openshift_certificate_expiry/tasks/main.yml
  test-requirements.txt
Labels: approved, lgtm, size/XS

#9805 [3.10] Remove exclude-bootstrapped logic
  playbooks/openshift-node/private/bootstrap.yml
  playbooks/openshift-node/private/clean_image.yml
  playbooks/openshift-node/private/configure_bootstrap.yml
  playbooks/openshift-node/private/configure_nodes.yml
  playbooks/openshift-node/private/disable_excluders.yml
  playbooks/openshift-node/private/enable_excluders.yml
  playbooks/openshift-node/private/image_prep.yml
Labels: approved, lgtm, size/M

#10259 Remove unlicensed code from internet in sanity checks
  roles/lib_utils/action_plugins/sanity_checks.py
  roles/lib_utils/test/test_sanity_checks.py
Labels: approved, lgtm, size/S

#10195 Pass admin kubeconfig
  roles/openshift_cloud_provider/tasks/vsphere-svc.yml
  roles/openshift_control_plane/tasks/check_master_api_is_ready.yml
  roles/openshift_control_plane/tasks/main.yml
Labels: approved, lgtm, size/S

#10295 Update the role to use the correct oc path
  roles/openshift_cloud_provider/tasks/vsphere-svc.yml
Labels: lgtm, size/XS

#10307 roles/cluster_monitoring: minor wording improvement
  roles/openshift_cluster_monitoring_operator/tasks/install.yaml
Labels: approved, lgtm, size/XS

#10147 Use clusterid attribute to filter servers in dynamic inventory
  playbooks/openstack/configuration.md
  playbooks/openstack/resources.py
Labels: approved, lgtm, size/M

#10313 glusterfs: add probe script for liveness and readiness checks
  roles/openshift_storage_glusterfs/files/glusterfs-template.yml
Labels: approved, lgtm, size/S

#10317 glusterfs: add probe script for liveness and readiness checks
  roles/openshift_storage_glusterfs/files/glusterfs-template.yml
Labels: approved, lgtm, size/S

#10255 [release-3.10] Fix etcd scaleup on standalone hosts
  playbooks/openshift-etcd/private/scaleup.yml
  playbooks/openshift-etcd/private/upgrade_backup.yml
  roles/etcd/defaults/main.yaml
  roles/etcd/tasks/add_new_member.yml
  roles/etcd/tasks/set_etcdctlv2.yml
  roles/installer_checkpoint/callback_plugins/installer_checkpoint.py
Labels: approved, lgtm, size/S

#10316 Remove unused registry migration task
  roles/openshift_hosted/tasks/migrate_default_registry_var.yml
Labels: approved, lgtm, size/S

#10323 prelim/partial update to jenkins imagestream to enable tests (while w…
  roles/openshift_examples/files/examples/latest/image-streams/image-streams-centos7.json
  roles/openshift_examples/files/examples/latest/image-streams/image-streams-rhel7.json
Labels: approved, lgtm, size/XS

#10326 [release-3.7] Override ovsdb-server systemd unit timeout when upgrading.
  roles/openshift_node_upgrade/tasks/openvswitch.yml
  roles/openshift_node_upgrade/tasks/restart.yml
Labels: size/M

#10324 [release-3.9] Override ovsdb-server systemd unit timeout when upgrading.
  roles/openshift_node/tasks/upgrade/openvswitch.yml
  roles/openshift_node/tasks/upgrade/restart.yml
Labels: lgtm, size/M

#8454 [release-3.6] Add a block to set openshift_push_via_dns when running upgrade_control
  playbooks/common/openshift-cluster/upgrades/upgrade_control_plane.yml
Labels: lgtm, size/S

#8897 [3.9] hosts.example: document openshift_hosted_infra_selector and TSB selector
  inventory/hosts.example
Labels: size/XS

#10337 unmount just before removing
  roles/container_runtime/tasks/common/setup_docker_symlink.yml
Labels: approved, lgtm, size/S

#10334 Fail on openshift_hostname defined; add openshift_kubelet_name_override
  images/installer/root/usr/local/bin/generate
  inventory/hosts.example
  inventory/hosts.openstack
  playbooks/init/cluster_facts.yml
  playbooks/init/validate_hostnames.yml
  playbooks/openstack/resources.py
  roles/lib_utils/action_plugins/sanity_checks.py
  roles/openshift_openstack/tasks/node-configuration.yml
  roles/openshift_openstack/templates/heat_stack_server.yaml.j2
Labels: approved, lgtm, size/M

#10353 Increase number of retries in sync DS
  roles/openshift_manage_node/tasks/config.yml
  roles/openshift_node_group/tasks/sync.yml
Labels: approved, lgtm, size/XS

#10362 Add missing option in Openstack documentation and sample file.
  playbooks/openstack/configuration.md
  playbooks/openstack/sample-inventory/group_vars/OSEv3.yml
Labels: approved, lgtm, size/XS

#10257 Fix etcd scaleup on standalone hosts
  playbooks/openshift-etcd/private/scaleup.yml
  roles/etcd/tasks/add_new_member.yml
  roles/etcd/tasks/set_facts.yml
Labels: approved, lgtm, size/S

#10329 test/ci: update instances to latest packages / ostree commit
  test/ci/launch.yml
Labels: approved, lgtm, size/S

#10341 Replace openshift.node.nodename with l_kubelet_node_name
  playbooks/byo/calico/legacy_upgrade.yml
  playbooks/common/openshift-cluster/upgrades/docker/docker_upgrade.yml
  playbooks/common/openshift-cluster/upgrades/upgrade_nodes.yml
  playbooks/common/openshift-cluster/upgrades/upgrade_scale_group.yml
  playbooks/init/cluster_facts.yml
  playbooks/openshift-glusterfs/private/add_hosts.yml
  playbooks/openshift-node/private/join.yml
  playbooks/openshift-node/private/registry_auth.yml
  playbooks/openshift-node/private/restart.yml
  roles/openshift_control_plane/tasks/main.yml
  roles/openshift_facts/defaults/main.yml
  roles/openshift_hosted/tasks/storage/glusterfs.yml
  roles/openshift_manage_node/tasks/config.yml
  roles/openshift_manage_node/tasks/main.yml
  roles/openshift_node/tasks/upgrade.yml
  roles/openshift_storage_glusterfs/README.md
  roles/openshift_storage_glusterfs/tasks/glusterfs_uninstall.yml
  roles/openshift_storage_glusterfs/tasks/label_nodes.yml
  roles/openshift_storage_glusterfs/templates/topology.json.j2
Labels: approved, lgtm, size/M

#10300 GlusterFS uninstall: Only unlabel configured nodes
  roles/openshift_storage_glusterfs/tasks/glusterfs_uninstall.yml
Labels: approved, lgtm, size/XS

#10263 Openshift autoheal fails to pull images even if oreg_url is specified
  playbooks/openshift-autoheal/private/config.yml
  roles/openshift_autoheal/defaults/main.yml
Labels: approved, lgtm, size/S

#10370 README: ansible 2.7 is not supported
  README.md
Labels: approved, lgtm, size/XS

#10343 Sync pod mod
  roles/openshift_node_group/files/sync.yaml
Labels: approved, lgtm, size/S

#10209 Configure Ansible service broker secrets
  roles/ansible_service_broker/defaults/main.yml
  roles/ansible_service_broker/templates/configmap.yaml.j2
Labels: approved, lgtm, size/XS

#10328 bug 1636248. Delete logging cluster service if clusterIP != None
  roles/openshift_logging_elasticsearch/tasks/main.yaml
Labels: approved, lgtm, size/S

#10379 [3.11] Dockerfile: install ansible 2.6
  README.md
  images/installer/Dockerfile
  openshift-ansible.spec
  requirements.txt
  roles/lib_utils/callback_plugins/aa_version_requirement.py
Labels: approved, lgtm, size/S

#10356 [3.11] Hostname fixes backport
  images/installer/root/usr/local/bin/generate
  inventory/hosts.example
  inventory/hosts.openstack
  playbooks/byo/calico/legacy_upgrade.yml
  playbooks/common/openshift-cluster/upgrades/docker/docker_upgrade.yml
  playbooks/common/openshift-cluster/upgrades/upgrade_nodes.yml
  playbooks/common/openshift-cluster/upgrades/upgrade_scale_group.yml
  playbooks/init/cluster_facts.yml
  playbooks/init/validate_hostnames.yml
  playbooks/openshift-glusterfs/private/add_hosts.yml
  playbooks/openshift-node/private/join.yml
  playbooks/openshift-node/private/registry_auth.yml
  playbooks/openshift-node/private/restart.yml
  playbooks/openstack/resources.py
  roles/lib_utils/action_plugins/sanity_checks.py
  roles/openshift_control_plane/tasks/main.yml
  roles/openshift_facts/defaults/main.yml
  roles/openshift_hosted/tasks/storage/glusterfs.yml
  roles/openshift_manage_node/tasks/config.yml
  roles/openshift_manage_node/tasks/main.yml
  roles/openshift_node/tasks/upgrade.yml
  roles/openshift_node_group/files/sync.yaml
  roles/openshift_openstack/tasks/node-configuration.yml
  roles/openshift_openstack/templates/heat_stack_server.yaml.j2
  roles/openshift_storage_glusterfs/README.md
  roles/openshift_storage_glusterfs/tasks/glusterfs_uninstall.yml
  roles/openshift_storage_glusterfs/tasks/label_nodes.yml
  roles/openshift_storage_glusterfs/templates/topology.json.j2
Labels: approved, lgtm, size/M

#10348 [3.11] Atomic upgrade: ensure /etc/origin/kubelet-plugins exists
  roles/openshift_control_plane/tasks/static.yml
Labels: approved, lgtm, size/XS

#10335 [3.11] Node problem detector always pull images from registry.redhat.io for openshift-enterprise
  roles/openshift_node_problem_detector/defaults/main.yaml
  roles/openshift_node_problem_detector/templates/node-problem-detector-daemonset.yaml.j2
Labels: approved, lgtm, size/S

#10382 [3.10] Dockerfile: install ansible 2.6.5
  images/installer/Dockerfile
Labels: approved, lgtm, size/XS

#10340 Add support for only installing and running the schema installer job
  playbooks/openshift-metrics/private/schema.yml
  playbooks/openshift-metrics/schema.yml
  roles/openshift_metrics/tasks/cleanup.yaml
  roles/openshift_metrics/tasks/create_temp_dirs.yaml
  roles/openshift_metrics/tasks/main.yaml
  roles/openshift_metrics/tasks/run_schema_job.yaml
Labels: approved, lgtm, size/L

#10392 [3.10] Hostname fixes backport
  images/installer/root/usr/local/bin/generate
  inventory/hosts.example
  inventory/hosts.openstack
  playbooks/byo/calico/legacy_upgrade.yml
  playbooks/common/openshift-cluster/upgrades/docker/docker_upgrade.yml
  playbooks/common/openshift-cluster/upgrades/upgrade_nodes.yml
  playbooks/common/openshift-cluster/upgrades/upgrade_scale_group.yml
  playbooks/init/cluster_facts.yml
  playbooks/init/validate_hostnames.yml
  playbooks/openshift-glusterfs/private/add_hosts.yml
  playbooks/openshift-node/private/join.yml
  playbooks/openshift-node/private/restart.yml
  playbooks/openstack/inventory.py
  roles/calico/tasks/main.yml
  roles/lib_utils/action_plugins/sanity_checks.py
  roles/openshift_control_plane/tasks/main.yml
  roles/openshift_facts/defaults/main.yml
  roles/openshift_hosted/tasks/storage/glusterfs.yml
  roles/openshift_manage_node/tasks/config.yml
  roles/openshift_manage_node/tasks/main.yml
  roles/openshift_node/tasks/upgrade.yml
  roles/openshift_node/tasks/upgrade/restart.yml
  roles/openshift_node/templates/node.yaml.v1.j2
  roles/openshift_node_group/files/sync.yaml
  roles/openshift_openstack/tasks/node-configuration.yml
  roles/openshift_openstack/templates/heat_stack_server.yaml.j2
  roles/openshift_storage_glusterfs/README.md
  roles/openshift_storage_glusterfs/tasks/glusterfs_uninstall.yml
  roles/openshift_storage_glusterfs/tasks/label_nodes.yml
  roles/openshift_storage_glusterfs/templates/topology.json.j2
Labels: approved, lgtm, priority/P0, priority/critical-urgent, size/L

#10377 Dockerfile: install ansible 2.6
  README.md
  images/installer/Dockerfile
  openshift-ansible.spec
  requirements.txt
  roles/lib_utils/callback_plugins/aa_version_requirement.py
Labels: approved, lgtm, priority/P0, size/S

#10258 [release-3.11] Fix etcd scaleup playbook
  playbooks/openshift-etcd/private/remove-etcdv2-data.yml
  playbooks/openshift-etcd/private/scaleup.yml
  playbooks/openshift-etcd/private/server_certificates.yml
  playbooks/openshift-etcd/private/upgrade_rpm_members.yml
  playbooks/openshift-etcd/private/upgrade_static.yml
  roles/etcd/defaults/main.yaml
  roles/etcd/etcdctl.sh
  roles/etcd/tasks/add_new_member.yml
  roles/etcd/tasks/remove-etcd-v2-data.yml
  roles/etcd/tasks/set_facts.yml
  roles/etcd/tasks/static.yml
  roles/etcd/tasks/upgrade_rpm.yml
  roles/etcd/tasks/upgrade_static.yml
  roles/etcd/tasks/verify_cluster_health.yml
  roles/etcd/templates/etcdctl.sh.j2
  roles/installer_checkpoint/callback_plugins/installer_checkpoint.py
Labels: approved, lgtm, size/L

#10292 Update Fuse templates with 7.1 release (3.9)
  roles/openshift_examples/files/examples/v3.9/xpaas-streams/fis-image-streams.json
  roles/openshift_examples/files/examples/v3.9/xpaas-templates/eap-camel-amq-template.json
  roles/openshift_examples/files/examples/v3.9/xpaas-templates/eap-camel-cdi-template.json
  roles/openshift_examples/files/examples/v3.9/xpaas-templates/eap-camel-cxf-jaxrs-template.json
  roles/openshift_examples/files/examples/v3.9/xpaas-templates/eap-camel-cxf-jaxws-template.json
  roles/openshift_examples/files/examples/v3.9/xpaas-templates/eap-camel-jpa-template.json
  roles/openshift_examples/files/examples/v3.9/xpaas-templates/karaf-camel-amq-template.json
  roles/openshift_examples/files/examples/v3.9/xpaas-templates/karaf-camel-log-template.json
  roles/openshift_examples/files/examples/v3.9/xpaas-templates/karaf-camel-rest-sql-template.json
  roles/openshift_examples/files/examples/v3.9/xpaas-templates/karaf-cxf-rest-template.json
  roles/openshift_examples/files/examples/v3.9/xpaas-templates/spring-boot-camel-amq-template.json
  roles/openshift_examples/files/examples/v3.9/xpaas-templates/spring-boot-camel-config-template.json
  roles/openshift_examples/files/examples/v3.9/xpaas-templates/spring-boot-camel-drools-template.json
  roles/openshift_examples/files/examples/v3.9/xpaas-templates/spring-boot-camel-infinispan-template.json
  roles/openshift_examples/files/examples/v3.9/xpaas-templates/spring-boot-camel-rest-sql-template.json
  roles/openshift_examples/files/examples/v3.9/xpaas-templates/spring-boot-camel-teiid-template.json
  roles/openshift_examples/files/examples/v3.9/xpaas-templates/spring-boot-camel-template.json
  roles/openshift_examples/files/examples/v3.9/xpaas-templates/spring-boot-camel-xa-template.json
  roles/openshift_examples/files/examples/v3.9/xpaas-templates/spring-boot-camel-xml-template.json
  roles/openshift_examples/files/examples/v3.9/xpaas-templates/spring-boot-cxf-jaxrs-template.json
  roles/openshift_examples/files/examples/v3.9/xpaas-templates/spring-boot-cxf-jaxws-template.json
Labels: size/XXL

#10406 Add CentOS ansible 2.6-versioned repo to the Dockerfile
  images/installer/origin-extra-root/etc/yum.repos.d/centos-ansible26.repo
Labels: approved, lgtm, size/XS

#10409 [release-3.10] Fail on openshift_kubelet_name_override for new hosts.
  playbooks/init/cluster_facts.yml
  playbooks/prerequisites.yml
  roles/openshift_facts/defaults/main.yml
Labels: size/S

#10266 [release-3.9] Re-apply tuned profile during upgrade
  playbooks/common/openshift-cluster/upgrades/upgrade_nodes.yml
  playbooks/openshift-master/private/upgrade.yml
Labels: approved, lgtm, size/XS

#10407 [3.10] Add ansible 2.4 repo
  images/installer/Dockerfile
  images/installer/origin-extra-root/etc/yum.repos.d/centos-ansible24.repo
Labels: approved, lgtm, size/XS

#10418 [3.10] Ensure raw_hostname used as openshift.node.nodename
  roles/openshift_facts/library/openshift_facts.py
Labels: approved, lgtm, size/XS

#10339 Add support for only installing and running the schema installer job
  playbooks/openshift-metrics/private/schema.yml
  playbooks/openshift-metrics/schema.yml
  roles/openshift_metrics/tasks/cleanup.yaml
  roles/openshift_metrics/tasks/create_temp_dirs.yaml
  roles/openshift_metrics/tasks/main.yaml
  roles/openshift_metrics/tasks/run_schema_job.yaml
Labels: approved, lgtm, size/L

#10413 [release-3.9] Fix version issue in openshift_facts when using custom image.
  playbooks/init/cluster_facts.yml
  roles/openshift_facts/library/openshift_facts.py
Labels: lgtm, size/S

#10325 [release-3.7] Set credentials and proper hostname when updating loopback kubeconfig
  roles/openshift_facts/library/openshift_facts.py
  roles/openshift_master/tasks/set_loopback_context.yml
Labels: size/S

#10393 [release-3.10] Increase number of retries in sync DS
  roles/openshift_manage_node/tasks/config.yml
  roles/openshift_node_group/tasks/sync.yml
Labels: approved, lgtm, size/XS

#10429 Use first_master_client_binary from hostvars[groups.oo_first_master.0]
  roles/openshift_storage_glusterfs/tasks/check_cluster_health.yml
Labels: approved, lgtm, size/XS

#10408 Ensure skopeo is installed prior to upgrade to 3.11
  playbooks/openshift-node/private/registry_auth.yml
Labels: approved, lgtm, size/S

#10425 [3.10] Fix hostname warning
  playbooks/init/cluster_facts.yml
Labels: approved, lgtm, size/XS

#10430 [3.10] Fix scaleup failure for hostname override
  playbooks/prerequisites.yml
Labels: approved, lgtm, size/XS

#10290 Update Fuse templates with 7.1 release (3.11)
  roles/openshift_examples/files/examples/latest/xpaas-streams/fis-image-streams.json
  roles/openshift_examples/files/examples/latest/xpaas-templates/eap-camel-amq-template.json
  roles/openshift_examples/files/examples/latest/xpaas-templates/eap-camel-cdi-template.json
  roles/openshift_examples/files/examples/latest/xpaas-templates/eap-camel-cxf-jaxrs-template.json
  roles/openshift_examples/files/examples/latest/xpaas-templates/eap-camel-cxf-jaxws-template.json
  roles/openshift_examples/files/examples/latest/xpaas-templates/eap-camel-jpa-template.json
  roles/openshift_examples/files/examples/latest/xpaas-templates/fis-console-cluster-template.json
  roles/openshift_examples/files/examples/latest/xpaas-templates/fis-console-namespace-template.json
  roles/openshift_examples/files/examples/latest/xpaas-templates/karaf-camel-amq-template.json
  roles/openshift_examples/files/examples/latest/xpaas-templates/karaf-camel-log-template.json
  roles/openshift_examples/files/examples/latest/xpaas-templates/karaf-camel-rest-sql-template.json
  roles/openshift_examples/files/examples/latest/xpaas-templates/karaf-cxf-rest-template.json
  roles/openshift_examples/files/examples/latest/xpaas-templates/spring-boot-camel-amq-template.json
  roles/openshift_examples/files/examples/latest/xpaas-templates/spring-boot-camel-config-template.json
  roles/openshift_examples/files/examples/latest/xpaas-templates/spring-boot-camel-drools-template.json
  roles/openshift_examples/files/examples/latest/xpaas-templates/spring-boot-camel-infinispan-template.json
  roles/openshift_examples/files/examples/latest/xpaas-templates/spring-boot-camel-rest-sql-template.json
  roles/openshift_examples/files/examples/latest/xpaas-templates/spring-boot-camel-teiid-template.json
  roles/openshift_examples/files/examples/latest/xpaas-templates/spring-boot-camel-template.json
  roles/openshift_examples/files/examples/latest/xpaas-templates/spring-boot-camel-xa-template.json
  roles/openshift_examples/files/examples/latest/xpaas-templates/spring-boot-camel-xml-template.json
  roles/openshift_examples/files/examples/latest/xpaas-templates/spring-boot-cxf-jaxrs-template.json
  roles/openshift_examples/files/examples/latest/xpaas-templates/spring-boot-cxf-jaxws-template.json
Labels: approved, lgtm, size/XXL

#10385 pin azure cli to version 2.0.47
  images/installer/Dockerfile
  images/installer/Dockerfile.ci
  playbooks/azure/openshift-cluster/tasks/create_blob_from_vm.yml
Labels: approved, lgtm, size/XS

#10395 Fail on openshift_kubelet_name_override for new hosts.
  playbooks/init/cluster_facts.yml
  playbooks/prerequisites.yml
  roles/openshift_facts/defaults/main.yml
Labels: approved, priority/P0, size/S

#10411 [release-3.6] Remove v3.7 check for shared-resource-viewer in control plane upgrade
  playbooks/common/openshift-cluster/upgrades/upgrade_control_plane.yml
Labels: lgtm, size/XS

#10444 [3.10] Pass admin kubeconfig
  roles/openshift_cloud_provider/tasks/vsphere-svc.yml
  roles/openshift_control_plane/tasks/check_master_api_is_ready.yml
  roles/openshift_control_plane/tasks/main.yml
Labels: approved, lgtm, size/XS

#10423 Remove value rather than replacing it with an empty string
  roles/openshift_control_plane/tasks/upgrade.yml
Labels: approved, lgtm, size/XS

#10320 Allow Ansible 2.5.7
  openshift-ansible.spec
  roles/lib_utils/callback_plugins/aa_version_requirement.py
Labels: needs-rebase, size/XS

#10303 Pass admin kubeconfig
  playbooks/common/openshift-cluster/upgrades/v3_7/validator.yml
  playbooks/openshift-master/private/tasks/wire_aggregator.yml
  roles/nuage_master/tasks/main.yaml
  roles/nuage_master/tasks/serviceaccount.yml
  roles/openshift_cloud_provider/tasks/vsphere-svc.yml
  roles/openshift_docker_gc/tasks/main.yml
  roles/openshift_grafana/tasks/install_grafana.yaml
  roles/openshift_hosted/tasks/storage/glusterfs_endpoints.yml
  roles/openshift_logging_elasticsearch/tasks/get_es_version.yml
  roles/openshift_logging_elasticsearch/tasks/main.yaml
  roles/openshift_master/tasks/bootstrap.yml
  roles/openshift_prometheus/tasks/install_prometheus.yaml
Labels: lgtm, size/M

#10462 3.10 - pin azure cli to version 2.0.47
  images/installer/Dockerfile
  images/installer/Dockerfile.ci
  playbooks/azure/openshift-cluster/tasks/create_blob_from_vm.yml
Labels: approved, lgtm, size/XS

#10471 Mount /etc/pki into apiserver pod
  roles/openshift_control_plane/files/apiserver.yaml
Labels: approved, lgtm, size/XS

#10485 [release-3.11] Mount /etc/pki into apiserver pod
  roles/openshift_control_plane/files/apiserver.yaml
Labels: approved, size/XS

#10486 [release-3.10] Mount /etc/pki into apiserver pod
  roles/openshift_control_plane/files/apiserver.yaml
Labels: approved, size/XS

#10387 fixes #10386 - cluster-monitoring: Adds storageclass name variable
  roles/openshift_cluster_monitoring_operator/defaults/main.yml
  roles/openshift_cluster_monitoring_operator/templates/cluster-monitoring-operator-config.j2
Labels: approved, lgtm, size/XS

#10404 Add openshift_hosted_registry_storage_swift_insecureskipverify parameter
  playbooks/openstack/configuration.md
  roles/openshift_hosted/templates/registry_config.j2
Labels: approved, lgtm, size/XS

#10400 Updated logging namespace name
  roles/openshift_logging/README.md
Labels: approved, lgtm, size/XS

#10075 Fix oc group get
  roles/lib_openshift/library/oc_group.py
  roles/lib_openshift/src/class/oc_group.py
  roles/lib_openshift/src/test/unit/test_oc_group.py
Labels: approved, lgtm, size/S

#10442 quick fix for formatting of error messages, bz# 1640823
  roles/lib_utils/action_plugins/sanity_checks.py
Labels: approved, lgtm, size/XS

#10468 [release-3.10] Remove hostname override from OpenStack inventory
  playbooks/openstack/inventory.py
Labels: approved, lgtm

#10467 [release-3.11] Remove hostname override from OpenStack inventory
  playbooks/openstack/resources.py
Labels: approved, lgtm, size/XS

#10466 Remove hostname override from OpenStack inventory
  playbooks/openstack/resources.py
Labels: approved, lgtm, size/XS

#10432 3.10: migrate LDAP/RequestHeader/OpenID CA during upgrade
  roles/lib_utils/filter_plugins/oo_filters.py
  roles/openshift_control_plane/tasks/create_ca_files.yml
  roles/openshift_control_plane/tasks/main.yml
  roles/openshift_control_plane/tasks/migrate_idproviders.yml
  roles/openshift_control_plane/tasks/upgrade.yml
Labels: approved, lgtm, size/L

#10460 Run the init playbooks to properly set vars
  playbooks/openstack/openshift-cluster/build_image.yml
  playbooks/openstack/openshift-cluster/install.yml
Labels: approved, lgtm, size/XS

#10498 Fix incorrect until condition in servicecatalog api check
  roles/openshift_control_plane/tasks/check_master_api_is_ready.yml
Labels: approved, lgtm, size/XS

#10443 Add permissions for the Calico CNI plugin to access namespaces
  roles/calico/templates/calicov3.yml.j2
Labels: approved, lgtm, size/XS

#10499 [release-3.10] Add permissions for the Calico CNI plugin to access namespaces
  roles/calico_master/templates/calicov3.yml.j2
Labels: approved, lgtm, size/XS

#10497 [release-3.10] Wait for aggregated API availability
  roles/openshift_control_plane/tasks/check_master_api_is_ready.yml
Labels: approved, size/M

#10496 [release-3.10] Remove value rather than replacing it with an empty string
  roles/openshift_control_plane/tasks/upgrade.yml
Labels: approved, lgtm, size/XS

#10357 bug 1627689. Peg logging-es-ops to appropriate configmap
  roles/openshift_logging_elasticsearch/tasks/main.yaml
  roles/openshift_logging_elasticsearch/templates/es.j2
Labels: approved, lgtm, size/XS

#10476 Fix version number in upgrade readme to 4.0.
  playbooks/byo/openshift-cluster/upgrades/README.md
Labels: approved, lgtm, size/XS

#10512 Fix fluent prom scheme
  roles/openshift_logging_fluentd/templates/fluentd.j2
Labels: approved, lgtm, size/XS

#10501 Don't install cockpit unless required
  roles/openshift_health_checker/openshift_checks/package_availability.py
  roles/openshift_node/defaults/main.yml
Labels: approved, lgtm, size/XS

#10511 Only enable console TSB support when both SC and TSB are installed
  playbooks/common/openshift-master/tasks/wire_aggregator.yml
Labels: lgtm, size/XS

#10484 Fix ansible version checking
  .pylintrc
  roles/lib_utils/callback_plugins/aa_version_requirement.py
Labels: approved, lgtm, size/S

#10513 Added validation to avoid upload template always
  playbooks/ovirt/openshift-cluster/ovirt-vm-infra.yml
  playbooks/ovirt/provisioning-vars.yaml.example
Labels: approved, lgtm, size/XS

#10464 Prepull node image using openshift_container_cli
  roles/openshift_node/tasks/prepull.yml
Labels: approved, lgtm, size/XS

#10514 openshift_console: remove OAuthClient when uninstalling
  roles/openshift_console/tasks/remove.yml
Labels: approved, lgtm, size/XS

#9884 Update existing template for registry-console and make sure created objects are updated
  roles/cockpit-ui/tasks/install.yml
Labels: approved, lgtm, size/XS

#10173 Disable a number open ports in various secgroups that are depricated
  playbooks/openstack/configuration.md
  roles/openshift_openstack/defaults/main.yml
Labels: approved, lgtm, size/L

#10532 Improve cleanup of networks and disks in GCP
  roles/openshift_gcp/templates/remove.j2.sh
Labels: approved, lgtm, size/M

#10446 Increase Octavia OpenShift API loadbalancer timeouts
  playbooks/openstack/configuration.md
  roles/openshift_openstack/defaults/main.yml
  roles/openshift_openstack/library/os_lbaas_listener_timeout.py
  roles/openshift_openstack/tasks/provision.yml
Labels: approved, lgtm, size/L

#10548 OSA 3.11 repos enable
  playbooks/azure/openshift-cluster/build_node_image.yml
  playbooks/azure/openshift-cluster/group_vars/all/yum_repos.yml
  playbooks/azure/openshift-cluster/tasks/yum_certs.yml
Labels: approved, lgtm, size/S

#10519 Updating clean up task to match become of creation task
  roles/openshift_logging/tasks/main.yaml
Labels: affects_3.10, affects_3.9, approved, lgtm, size/XS

#10555 [3.11] Ensure proper task ordering atomic upgrades.
  roles/openshift_node/tasks/config.yml
  roles/openshift_node/tasks/systemd_units.yml
  roles/openshift_node/tasks/upgrade/restart.yml
Labels: approved, size/S

#10531 Make timeout a param and increase default to 20 for docker_creds.py
  roles/lib_utils/library/docker_creds.py
Labels: approved, lgtm, size/S

#10541 This PR will allow OSP provisioning of separate 'etcd' instances from the master instances
  playbooks/openstack/configuration.md
  playbooks/openstack/resources.py
  playbooks/openstack/sample-inventory/group_vars/all.yml
  roles/openshift_openstack/defaults/main.yml
Labels: approved, lgtm, size/M

#10560 osa- downgrade azure cli
  images/installer/Dockerfile
  playbooks/azure/openshift-cluster/tasks/create_blob_from_vm.yml
Labels: approved, lgtm, size/XS

#10568 [release-3.10] osa - downgrade azure cli
  images/installer/Dockerfile
  images/installer/Dockerfile.ci
  playbooks/azure/openshift-cluster/tasks/create_blob_from_vm.yml
Labels: size/XS
