Repository openshift/openshift-ansible, pull requests merged in 2018-03, with the labels that each got.

#7255 Move common master upgrade playbooks to openshift-master component
  playbooks/common/openshift-cluster/upgrades/atomic-openshift-master.j2
  playbooks/common/openshift-cluster/upgrades/docker-cluster
  playbooks/common/openshift-cluster/upgrades/native-cluster
  playbooks/common/openshift-cluster/upgrades/openshift.docker.node.dep.service
  playbooks/common/openshift-cluster/upgrades/openshift.docker.node.service
  playbooks/common/openshift-cluster/upgrades/openvswitch-avoid-oom.conf
  playbooks/common/openshift-cluster/upgrades/openvswitch.docker.service
  playbooks/common/openshift-cluster/upgrades/openvswitch.sysconfig.j2
  playbooks/common/openshift-cluster/upgrades/upgrade_control_plane.yml
  playbooks/openshift-master/private/create_service_signer_cert.yml
  playbooks/openshift-master/private/files/shared_resource_viewer_role.yaml
  playbooks/openshift-master/private/upgrade.yml
Labels: lgtm, size/XL

#7309 [BZ 1513706] make concurrenyLimit configurable
  roles/openshift_metrics/defaults/main.yaml
  roles/openshift_metrics/templates/heapster.j2
Labels: lgtm, size/XS

#7306 [bug 1543256] Fix redeploy router from openshift_hosted refactor.
  playbooks/openshift-hosted/private/redeploy-router-certificates.yml
Labels: kind/bug, lgtm, retest-not-required, size/XS

#7332 Fixing ops health check skip and checking of ES version for not ready pods
  roles/openshift_logging/tasks/install_logging.yaml
  roles/openshift_logging_curator/tasks/determine_version.yaml
  roles/openshift_logging_curator/tasks/main.yaml
  roles/openshift_logging_curator/vars/main.yml
  roles/openshift_logging_elasticsearch/tasks/determine_version.yaml
  roles/openshift_logging_elasticsearch/tasks/get_es_version.yml
  roles/openshift_logging_elasticsearch/tasks/main.yaml
  roles/openshift_logging_elasticsearch/tasks/restart_cluster.yml
  roles/openshift_logging_elasticsearch/vars/main.yml
  roles/openshift_logging_fluentd/tasks/determine_version.yaml
  roles/openshift_logging_fluentd/tasks/main.yaml
  roles/openshift_logging_fluentd/vars/main.yml
  roles/openshift_logging_kibana/tasks/determine_version.yaml
  roles/openshift_logging_kibana/tasks/main.yaml
  roles/openshift_logging_kibana/vars/main.yml
  roles/openshift_logging_mux/tasks/determine_version.yaml
  roles/openshift_logging_mux/tasks/main.yaml
  roles/openshift_logging_mux/vars/main.yml
Labels: lgtm, size/L

#7340 etcd scaleup: use r_etcd_common_etcdctl_command instead of binary path
  playbooks/openshift-etcd/private/scaleup.yml
Labels: lgtm, size/XS

#7321 Allow for using an external openvswitch
  roles/openshift_node/defaults/main.yml
  roles/openshift_node/tasks/container_images.yml
  roles/openshift_node/tasks/systemd_units.yml
Labels: lgtm, size/XS

#7120 Remove RBAC console template
  roles/openshift_web_console/defaults/main.yml
  roles/openshift_web_console/files/console-rbac-template.yaml
  roles/openshift_web_console/tasks/install.yml
  roles/openshift_web_console/tasks/rollout_console.yml
  roles/template_service_broker/tasks/install.yml
  roles/template_service_broker/tasks/remove.yml
Labels: lgtm, size/M

#7330 Use explicit broker version for v3.9
  roles/ansible_service_broker/vars/default_images.yml
Labels: lgtm, size/XS

#7350 Release 3.9 fixes from master
  inventory/hosts.example
  playbooks/common/openshift-cluster/upgrades/atomic-openshift-master.j2
  playbooks/common/openshift-cluster/upgrades/docker-cluster
  playbooks/common/openshift-cluster/upgrades/native-cluster
  playbooks/common/openshift-cluster/upgrades/openshift.docker.node.dep.service
  playbooks/common/openshift-cluster/upgrades/openshift.docker.node.service
  playbooks/common/openshift-cluster/upgrades/openvswitch-avoid-oom.conf
  playbooks/common/openshift-cluster/upgrades/openvswitch.docker.service
  playbooks/common/openshift-cluster/upgrades/openvswitch.sysconfig.j2
  playbooks/common/openshift-cluster/upgrades/post_control_plane.yml
  playbooks/common/openshift-cluster/upgrades/upgrade_control_plane.yml
  playbooks/openshift-etcd/private/scaleup.yml
  playbooks/openshift-hosted/private/redeploy-router-certificates.yml
  playbooks/openshift-master/private/create_service_signer_cert.yml
  playbooks/openshift-master/private/files/shared_resource_viewer_role.yaml
  playbooks/openshift-master/private/upgrade.yml
  roles/openshift_aws/tasks/elb_single.yml
  roles/openshift_metrics/defaults/main.yaml
  roles/openshift_metrics/templates/heapster.j2
  roles/openshift_node/defaults/main.yml
  roles/openshift_node/tasks/container_images.yml
  roles/openshift_node/tasks/systemd_units.yml
  roles/openshift_openstack/tasks/provision.yml
  utils/etc/ansible-quiet.cfg
Labels: size/XL

#7343 [3.7] Fixing evaluating if ops deployment needs to skip health check, remov…
  roles/openshift_logging/tasks/install_logging.yaml
  roles/openshift_logging_curator/tasks/determine_version.yaml
  roles/openshift_logging_curator/tasks/main.yaml
  roles/openshift_logging_curator/vars/main.yml
  roles/openshift_logging_elasticsearch/tasks/determine_version.yaml
  roles/openshift_logging_elasticsearch/tasks/get_es_version.yml
  roles/openshift_logging_elasticsearch/tasks/main.yaml
  roles/openshift_logging_elasticsearch/tasks/restart_cluster.yml
  roles/openshift_logging_elasticsearch/vars/main.yml
  roles/openshift_logging_fluentd/tasks/determine_version.yaml
  roles/openshift_logging_fluentd/tasks/main.yaml
  roles/openshift_logging_fluentd/vars/main.yml
  roles/openshift_logging_kibana/tasks/determine_version.yaml
  roles/openshift_logging_kibana/tasks/main.yaml
  roles/openshift_logging_kibana/vars/main.yml
  roles/openshift_logging_mux/tasks/determine_version.yaml
  roles/openshift_logging_mux/tasks/main.yaml
  roles/openshift_logging_mux/vars/main.yml
Labels: lgtm, size/L

#7333 Master scheduler upgrade cleanup
  roles/lib_utils/lookup_plugins/openshift_master_facts_default_predicates.py
  roles/lib_utils/lookup_plugins/openshift_master_facts_default_priorities.py
  roles/lib_utils/test/openshift_master_facts_default_predicates_tests.py
  roles/lib_utils/test/openshift_master_facts_default_priorities_tests.py
  roles/openshift_master/tasks/upgrade/upgrade_predicates.yml
  roles/openshift_master/tasks/upgrade/upgrade_priorities.yml
  roles/openshift_master/tasks/upgrade/upgrade_scheduler.yml
  roles/openshift_master/tasks/upgrade_predicates.yml
  roles/openshift_master/vars/main.yml
Labels: lgtm, size/XL

#7357 Temporarily fix Dockerfile until we can find a replacement package
  images/installer/Dockerfile
Labels: approved, lgtm, queue/critical-fix, retest-not-required, size/XS

#7287 docker_image_availability: encode items before joining
  roles/openshift_health_checker/openshift_checks/docker_image_availability.py
Labels: lgtm, size/S

#7331 oc_obj: fail in state=list when return code != 0.
  roles/lib_openshift/library/oc_obj.py
  roles/lib_openshift/src/class/oc_obj.py
Labels: lgtm, size/XS

#7341 Correcting a typo: idle_timout -> idle_timeout
  roles/openshift_aws/defaults/main.yml
  roles/openshift_aws/tasks/elb_single.yml
Labels: lgtm, size/XS

#7358 Add s3 and block uninstall sections as well
  roles/openshift_storage_glusterfs/tasks/glusterfs_uninstall.yml
Labels: lgtm, size/S

#7352 Bug 1550717 - Add proxy env vars to ASB DC.
  roles/ansible_service_broker/tasks/install.yml
Labels: lgtm, size/XS

#7320 Fix rhgs-s3 image name
  roles/openshift_storage_glusterfs/defaults/main.yml
Labels: lgtm, size/XS

#7326 Fix for gluster-s3 pvc check count.
  roles/openshift_storage_glusterfs/tasks/gluster_s3_deploy.yml
Labels: lgtm, retest-not-required, size/XS

#7368 fix bz 1550271: restore mpath defaults config
  roles/openshift_node/templates/multipath.conf.j2
Labels: lgtm, size/XS

#7367 fix bz 1550271: restore mpath defaults config
  roles/openshift_node/templates/multipath.conf.j2
Labels: lgtm, size/XS

#7348 Bug 1550148 - Fail install if console port does not match API server port
  roles/openshift_sanitize_inventory/tasks/main.yml
Labels: lgtm, size/S

#7336 Fix the gluster-s3 pod label used in gluster-s3 service.
  roles/openshift_storage_glusterfs/files/v3.10/gluster-s3-template.yml
  roles/openshift_storage_glusterfs/files/v3.6/gluster-s3-template.yml
  roles/openshift_storage_glusterfs/files/v3.7/gluster-s3-template.yml
  roles/openshift_storage_glusterfs/files/v3.8/gluster-s3-template.yml
  roles/openshift_storage_glusterfs/files/v3.9/gluster-s3-template.yml
Labels: lgtm, size/S

#6319 Kuryr var generation in OSt dynamic inventory
  playbooks/openstack/README.md
  playbooks/openstack/inventory.py
  playbooks/openstack/openshift-cluster/provision.yml
  playbooks/openstack/sample-inventory/group_vars/all.yml
  roles/kuryr/defaults/main.yaml
  roles/kuryr/templates/cni-daemonset.yaml.j2
  roles/kuryr/templates/configmap.yaml.j2
  roles/kuryr/templates/controller-deployment.yaml.j2
  roles/lib_utils/action_plugins/sanity_checks.py
  roles/openshift_openstack/defaults/main.yml
  roles/openshift_openstack/library/os_network_extensions.py
  roles/openshift_openstack/tasks/check-prerequisites.yml
  roles/openshift_openstack/tasks/node-network.yml
  roles/openshift_openstack/tasks/provision.yml
  roles/openshift_openstack/templates/heat_stack.yaml.j2
  roles/openshift_openstack/templates/heat_stack_server.yaml.j2
Labels: lgtm, size/XL

#7319 Prometheus reader
  roles/openshift_grafana/defaults/main.yaml
Labels: lgtm, size/XS

#7334 Change default etcd port to 2379
  roles/openshift_facts/library/openshift_facts.py
Labels: lgtm, size/XS

#7377 ansible-quite: set callback_plugins path
  utils/etc/ansible-quiet.cfg
Labels: lgtm, retest-not-required, size/XS

#7310 crio: docker_gc on by default
  inventory/hosts.example
  playbooks/openshift-hosted/private/config.yml
  roles/openshift_docker_gc/defaults/main.yml
  roles/openshift_docker_gc/tasks/main.yaml
Labels: docs, kind/cleanup, lgtm, size/S

#7386 [bz 1543256] Remove redeploy after the roll has executed.
  playbooks/openshift-hosted/private/redeploy-router-certificates.yml
Labels: lgtm, size/XS

#7322 enable iscsid, rpcbind on start
  playbooks/openshift-glusterfs/private/config.yml
  roles/openshift_node/tasks/storage_plugins/iscsi.yml
  roles/openshift_storage_glusterfs/tasks/host_services.yml
Labels: lgtm, size/S

#7062 Prometheus config updates
  roles/openshift_prometheus/defaults/main.yaml
  roles/openshift_prometheus/templates/prometheus.j2
Labels: lgtm, size/S

#6907 Clarify node system container service unit
  roles/container_runtime/tasks/systemcontainer_docker.yml
  roles/openshift_node/tasks/config/install-node-docker-service-file.yml
  roles/openshift_node/tasks/node_system_container.yml
Labels: lgtm, retest-not-required, size/S

#7374 Make broker pods run correct versions on upgrade
  roles/ansible_service_broker/tasks/install.yml
  roles/template_service_broker/files/apiserver-template.yaml
Labels: lgtm, size/S

#7409 pull in recent jenkins template updates
  roles/openshift_examples/files/examples/v3.9/quickstart-templates/jenkins-ephemeral-template.json
  roles/openshift_examples/files/examples/v3.9/quickstart-templates/jenkins-persistent-template.json
Labels: size/S

#7397 Fix hosted registry upgrade bug
  playbooks/common/openshift-cluster/upgrades/post_control_plane.yml
  playbooks/openshift-glusterfs/private/registry.yml
  playbooks/openshift-master/private/additional_config.yml
  roles/openshift_examples/defaults/main.yml
  roles/openshift_hosted/tasks/upgrade_registry.yml
  roles/openshift_hosted/tasks/upgrade_routers.yml
Labels: affects_3.8, affects_3.9, lgtm, size/L

#7214 Create default storageclass for cloudprovider openstack
  playbooks/common/openshift-cluster/openshift_hosted.yml
  roles/openshift_default_storage_class/defaults/main.yml
  roles/openshift_default_storage_class/tasks/main.yml
Labels: needs-ok-to-test, size/S

#7406 Fix the DNS server name issue for OpenStack
  roles/openshift_openstack/templates/heat_stack.yaml.j2
Labels: lgtm, size/L

#7399 Refactor openshift.common.version to openshift_current_version
  playbooks/common/openshift-cluster/upgrades/init.yml
  playbooks/common/openshift-cluster/upgrades/pre/config.yml
  playbooks/common/openshift-cluster/upgrades/pre/verify_upgrade_targets.yml
  playbooks/init/cluster_facts.yml
  playbooks/init/version.yml
  playbooks/openshift-logging/private/config.yml
  playbooks/openshift-master/private/tasks/wire_aggregator.yml
  playbooks/openshift-metrics/private/config.yml
  roles/lib_utils/action_plugins/set_version_facts.py
  roles/lib_utils/library/get_current_openshift_version.py
  roles/openshift_examples/defaults/main.yml
  roles/openshift_facts/library/openshift_facts.py
  roles/openshift_hosted/tasks/storage/glusterfs_endpoints.yml
  roles/openshift_hosted_templates/defaults/main.yml
  roles/openshift_logging/tasks/delete_logging.yaml
  roles/openshift_logging/tasks/install_logging.yaml
  roles/openshift_master/tasks/push_via_dns.yml
  roles/openshift_master/templates/master.yaml.v1.j2
  roles/openshift_metrics/tasks/install_metrics.yaml
  roles/openshift_metrics/tasks/uninstall_metrics.yaml
  roles/openshift_node/templates/node.yaml.v1.j2
  roles/openshift_storage_glusterfs/tasks/gluster_s3_deploy.yml
  roles/openshift_storage_glusterfs/tasks/glusterblock_deploy.yml
  roles/openshift_storage_glusterfs/tasks/glusterfs_common.yml
  roles/openshift_storage_glusterfs/tasks/glusterfs_deploy.yml
  roles/openshift_storage_glusterfs/tasks/heketi_deploy_part1.yml
  roles/openshift_storage_glusterfs/tasks/heketi_deploy_part2.yml
  roles/openshift_version/tasks/first_master.yml
Labels: lgtm, size/L

#7413 Add wait_for_pods to upgrade for hosted components
  playbooks/common/openshift-cluster/upgrades/post_control_plane.yml
  playbooks/openshift-hosted/private/openshift_hosted_wait_for_pods.yml
  playbooks/openshift-hosted/private/upgrade.yml
  playbooks/openshift-hosted/private/upgrade_poll_and_check_certs.yml
  roles/openshift_hosted/tasks/registry.yml
  roles/openshift_hosted/tasks/set_fact_workaround.yml
Labels: affects_3.9, lgtm, size/L

#7393 [release-3.7] During master upgrade reset loopback config
  playbooks/common/openshift-cluster/upgrades/upgrade_control_plane.yml
  playbooks/common/openshift-etcd/migrate.yml
Labels: lgtm, size/XS

#7391 During master upgrade reset loopback config
  roles/openshift_master/tasks/upgrade.yml
Labels: lgtm, size/XS

#7392 [release-3.6] During master upgrade reset loopback config and etcd migration
  playbooks/common/openshift-cluster/upgrades/upgrade_control_plane.yml
  playbooks/common/openshift-etcd/migrate.yml
Labels: lgtm, size/XS

#7426 [release-3.9] Bug 1550148 - Don't use undefined openshift_version in openshift_sanitize_inventory
  roles/openshift_sanitize_inventory/tasks/main.yml
Labels: size/XS

#7424 Bug 1550148 - Don't use undefined openshift_version in openshift_sanitize_inventory
  roles/openshift_sanitize_inventory/tasks/main.yml
Labels: size/XS

#7225 Add any_errors_fatal to openstack playbooks
  playbooks/openstack/README.md
  playbooks/openstack/openshift-cluster/install.yml
  playbooks/openstack/openshift-cluster/prerequisites.yml
  playbooks/openstack/openshift-cluster/provision.yml
Labels: lgtm, size/S

#7422 Remove force cache during node upgrade install
  roles/openshift_node/tasks/upgrade.yml
  roles/openshift_node/tasks/upgrade/rpm_upgrade_install.yml
Labels: affects_3.9, lgtm, priority/P0, size/XS

#7364 Bug 1548641- upgrade now properly sets labels and selectors
  playbooks/common/openshift-cluster/upgrades/v3_9/label_nodes.yml
  playbooks/common/openshift-cluster/upgrades/v3_9/upgrade_control_plane.yml
  playbooks/init/basic_facts.yml
  roles/openshift_manage_node/tasks/config.yml
  roles/openshift_manage_node/tasks/set_default_node_role.yml
  roles/openshift_master/defaults/main.yml
  roles/openshift_master/tasks/upgrade.yml
  roles/openshift_master/templates/master.yaml.v1.j2
Labels: lgtm, priority/P0, queue/critical-fix, size/M

#7373 Switch the default network mode to ovs-networkpolicy
  inventory/dynamic/gcp/group_vars/all/00_defaults.yml
Labels: lgtm, size/XS

#7433 TSB upgrade remove and reinstall
  roles/template_service_broker/tasks/upgrade.yml
Labels: lgtm, size/XS

#7427 docker_gc: map the r_docker_gc_node_selectors to pairs
  roles/openshift_docker_gc/tasks/main.yml
Labels: lgtm, queue/critical-fix, size/XS

#7428 docker-gc: use openshift_client_binary to support Atomic
  roles/openshift_docker_gc/tasks/main.yml
Labels: lgtm, queue/critical-fix, size/XS

#7313 [3.7] etcd migrate: instead of scaleup playbook etcd server should be started back
  playbooks/common/openshift-etcd/migrate.yml
Labels: lgtm, size/M

#7380 firewall: allow access to DNS for flannel network
  roles/flannel/tasks/main.yml
Labels: lgtm, size/XS

#7347 package_version check: stop looking for docker
  roles/openshift_health_checker/openshift_checks/package_version.py
  roles/openshift_health_checker/test/package_version_test.py
Labels: lgtm, size/M

#7335 Fix grafana role node selector check
  roles/openshift_grafana/README.md
  roles/openshift_grafana/defaults/main.yaml
  roles/openshift_grafana/tasks/install_grafana.yaml
Labels: lgtm, size/S

#7443 system containers: ensure Atomic won't reset permissions for etcd_data_dir
  roles/etcd/tasks/system_container.yml
  roles/etcd/templates/etcd-dir.conf.j2
Labels: lgtm, queue/critical-fix, size/XS

#7398 Re-organized OpenStack documentation
  playbooks/openstack/README.md
  playbooks/openstack/advanced-configuration.md
  playbooks/openstack/configuration.md
  playbooks/openstack/post-install.md
Labels: lgtm, retest-not-required-docs-only, size/XXL

#7460 bump route timeout based on online testing
  roles/openshift_examples/files/examples/v3.9/quickstart-templates/jenkins-ephemeral-template.json
  roles/openshift_examples/files/examples/v3.9/quickstart-templates/jenkins-persistent-template.json
Labels: size/XS

#7453 openshift_node: Remove hardcoded cri-o node labels
  roles/openshift_node/templates/node.yaml.v1.j2
Labels: affects_3.9, kind/bug, lgtm, queue/fix, size/XS

#7400 Refactor openshift.common.deployment_type
  playbooks/common/openshift-cluster/upgrades/post_control_plane.yml
  playbooks/init/basic_facts.yml
  playbooks/init/cluster_facts.yml
  playbooks/openshift-master/private/additional_config.yml
  playbooks/openshift-master/private/config.yml
  playbooks/openshift-node/private/manage_node.yml
  roles/container_runtime/tasks/common/pre.yml
  roles/openshift_examples/defaults/main.yml
  roles/openshift_facts/library/openshift_facts.py
  roles/openshift_hosted_templates/defaults/main.yml
  roles/openshift_master/defaults/main.yml
  roles/openshift_master/tasks/main.yml
  roles/openshift_master/templates/master.yaml.v1.j2
  roles/openshift_master_facts/tasks/main.yml
  roles/openshift_version/tasks/first_master_containerized_version.yml
Labels: lgtm, size/L

#7454 Fix the gluster-s3 pod label used in gluster-s3 service.
  roles/openshift_storage_glusterfs/files/v3.6/gluster-s3-template.yml
  roles/openshift_storage_glusterfs/files/v3.7/gluster-s3-template.yml
  roles/openshift_storage_glusterfs/files/v3.8/gluster-s3-template.yml
  roles/openshift_storage_glusterfs/files/v3.9/gluster-s3-template.yml
Labels: lgtm, size/XS

#7349 Only run no_log on task that scrapes all inventory variables
  playbooks/init/basic_facts.yml
  roles/openshift_sanitize_inventory/tasks/deprecations.yml
Labels: lgtm, size/XS

#7328 Use explicit broker version for v3.7
  roles/ansible_service_broker/vars/default_images.yml
Labels: lgtm, size/XS

#7474 Revert delete tsb upgrade
  roles/template_service_broker/tasks/upgrade.yml
Labels: affects_3.9, size/XS

#7476 Correctly escape the variable value for regex searching when building patch
  roles/openshift_logging/library/logging_patch.py
Labels: affects_3.7, affects_3.9, lgtm, size/XS

#7479 Correctly escape the variable value for regex searching when building…
  roles/openshift_logging/library/logging_patch.py
Labels: lgtm, size/XS

#7317 Bug 1549220 - configmap still exist after running uninstall playbook for logging
  roles/openshift_logging/tasks/delete_logging.yaml
Labels: lgtm, size/XS

#7115 Convert calico install from systemd-based to self-hosted
  playbooks/byo/calico/legacy_upgrade.yml
  playbooks/byo/calico/roles
  playbooks/byo/calico/upgrade_versions.yml
  roles/calico/README.md
  roles/calico/defaults/main.yaml
  roles/calico/handlers/main.yml
  roles/calico/meta/main.yml
  roles/calico/tasks/main.yml
  roles/calico/templates/10-calico.conf.j2
  roles/calico/templates/calico.service.j2
  roles/calico/templates/calicoctl.cfg.j2
  roles/calico_master/README.md
  roles/calico_master/defaults/main.yaml
  roles/calico_master/meta/main.yml
  roles/calico_master/tasks/certs.yml
  roles/calico_master/tasks/main.yml
  roles/calico_master/templates/calico-policy-controller.yml.j2
  roles/calico_master/templates/calico.yml.j2
Labels: lgtm, size/XXL

#7478 Ensure that the aggregator is configured during all control plane
  playbooks/openshift-master/private/upgrade.yml
Labels: lgtm, size/XS

#7481 Adding missed line change
  roles/openshift_logging/library/logging_patch.py
Labels: affects_3.7, affects_3.9, size/XS

#7484 Changing python regex method from match to search
  roles/openshift_logging/library/logging_patch.py
Labels: lgtm, size/XS

#7402 Remove unused openshift_upgrade_config
  playbooks/common/openshift-cluster/upgrades/library/openshift_upgrade_config.py
Labels: lgtm, size/L

#7189 Require Ansible 2.4.3
  README.md
  openshift-ansible.spec
  requirements.txt
  roles/lib_utils/callback_plugins/aa_version_requirement.py
Labels: lgtm, size/XS

#7465 GlusterFS: Don't copy non-existant topology file
  roles/openshift_storage_glusterfs/tasks/glusterfs_common.yml
Labels: lgtm, size/XS

#7496 Enable epel-testing repo for ansible-2.4.3 until it goes live
  images/installer/Dockerfile
Labels: lgtm, size/XS

#7498 Release 3.9 ansible 2.4.3 libcloud 2.2.1
  images/installer/Dockerfile
Labels: size/XS

#7047 Update curator to use k8s cronjob
  roles/openshift_logging/README.md
  roles/openshift_logging/defaults/main.yml
  roles/openshift_logging/tasks/delete_logging.yaml
  roles/openshift_logging_curator/defaults/main.yml
  roles/openshift_logging_curator/files/5.x/actions.yaml
  roles/openshift_logging_curator/files/5.x/config.yaml
  roles/openshift_logging_curator/tasks/main.yaml
  roles/openshift_logging_curator/templates/5.x/curator-cj.j2
  roles/openshift_logging_curator/templates/5.x/curator.j2
Labels: lgtm, size/L

#7307 backport to 3.7 for bug 1537857
  roles/openshift_logging_elasticsearch/defaults/main.yml
  roles/openshift_logging_elasticsearch/tasks/main.yaml
  roles/openshift_logging_elasticsearch/templates/es.j2
  roles/openshift_logging_elasticsearch/templates/logging-metrics-role.j2
  roles/openshift_logging_elasticsearch/templates/logging-metrics-rolebinding.j2
Labels: lgtm, size/L

#7499 Fix references to oc client
  roles/openshift_bootstrap_autoapprover/tasks/main.yml
  roles/openshift_cloud_provider/tasks/vsphere-svc.yml
  roles/openshift_control_plane/tasks/bootstrap.yml
Labels: lgtm, queue/fix, size/XS

#7242 cockpit-ui: Make it optional
  inventory/hosts.example
  playbooks/openshift-hosted/private/cockpit-ui.yml
Labels: lgtm, needs-ok-to-test, size/XS

#7329 cri-o: configure oci-umount with CRI-O paths
  roles/container_runtime/defaults/main.yml
  roles/container_runtime/tasks/systemcontainer_crio.yml
Labels: lgtm, size/S

#7492 [release-3.7] logging patch fixes
  roles/openshift_logging/library/logging_patch.py
Labels: lgtm, size/M

#7296 change to better coding style
  roles/openshift_master/templates/docker-cluster/atomic-openshift-master-api.service.j2
  roles/openshift_master/templates/docker-cluster/atomic-openshift-master-controllers.service.j2
  roles/openshift_version/tasks/check_available_rpms.yml
Labels: lgtm, size/S

#7466 crio: Fixup docker SELinux permissions
  roles/container_runtime/tasks/package_crio.yml
Labels: lgtm, size/XS

#7274 [RHDM-354] - Add RHDM 7.0 GA templates and image streams to Openshift…
  roles/openshift_examples/examples-sync.sh
  roles/openshift_examples/files/examples/v3.10/xpaas-streams/rhdm70-image-streams.yaml
  roles/openshift_examples/files/examples/v3.10/xpaas-templates/rhdm70-full.yaml
  roles/openshift_examples/files/examples/v3.10/xpaas-templates/rhdm70-kieserver-basic-s2i.yaml
  roles/openshift_examples/files/examples/v3.10/xpaas-templates/rhdm70-kieserver-https-s2i.yaml
  roles/openshift_examples/files/examples/v3.10/xpaas-templates/rhdm70-kieserver.yaml
Labels: lgtm, size/XXL

#7500 Fix missing slash in oreg_host
  roles/openshift_sdn/defaults/main.yml
Labels: lgtm, size/XS

#7371 Allow rcpbind for CNS block in cns-secgrp (openshift_openstack).
  roles/openshift_openstack/templates/heat_stack.yaml.j2
Labels: lgtm, size/XS

#7501 Bug 1548541- Conditional for applying defaultNodeSelector now valid
  roles/openshift_master/tasks/upgrade.yml
Labels: lgtm, size/XS

#7494 GlusterFS: Add HEKETI_IGNORE_STALE_OPERATIONS to templates
  roles/openshift_storage_glusterfs/files/v3.10/deploy-heketi-template.yml
  roles/openshift_storage_glusterfs/files/v3.10/heketi-template.yml
  roles/openshift_storage_glusterfs/files/v3.6/deploy-heketi-template.yml
  roles/openshift_storage_glusterfs/files/v3.6/heketi-template.yml
  roles/openshift_storage_glusterfs/files/v3.7/deploy-heketi-template.yml
  roles/openshift_storage_glusterfs/files/v3.7/heketi-template.yml
  roles/openshift_storage_glusterfs/files/v3.8/deploy-heketi-template.yml
  roles/openshift_storage_glusterfs/files/v3.8/heketi-template.yml
  roles/openshift_storage_glusterfs/files/v3.9/deploy-heketi-template.yml
  roles/openshift_storage_glusterfs/files/v3.9/heketi-template.yml
Labels: lgtm, size/S

#7238 only annotate ops project for ops kibana when using ops
  roles/openshift_logging/tasks/annotate_ops_projects.yaml
Labels: affects_3.6, affects_3.7, affects_3.9, lgtm, size/S

#6248 Add support to pre-create subports at each trunk
  playbooks/openstack/configuration.md
  playbooks/openstack/sample-inventory/group_vars/all.yml
  roles/kuryr/README.md
  roles/openshift_openstack/tasks/generate-templates.yml
  roles/openshift_openstack/templates/heat_stack.yaml.j2
  roles/openshift_openstack/templates/heat_stack_segmentation_ids.yaml.j2
  roles/openshift_openstack/templates/heat_stack_server.yaml.j2
  roles/openshift_openstack/templates/heat_stack_subports.yaml.j2
Labels: lgtm, size/L

#7516 Pop etcd_port from local_facts file
  roles/openshift_facts/library/openshift_facts.py
Labels: lgtm, size/S

#7477 Grafana: fix references to service account, and use it for authentication
  roles/openshift_grafana/tasks/install_grafana.yaml
  roles/openshift_grafana/templates/grafana.yml.j2
Labels: lgtm, size/S

#7511 GlusterFS: Add HEKETI_IGNORE_STALE_OPERATIONS to templates
  roles/openshift_storage_glusterfs/files/v3.6/deploy-heketi-template.yml
  roles/openshift_storage_glusterfs/files/v3.6/heketi-template.yml
  roles/openshift_storage_glusterfs/files/v3.7/deploy-heketi-template.yml
  roles/openshift_storage_glusterfs/files/v3.7/heketi-template.yml
  roles/openshift_storage_glusterfs/files/v3.8/deploy-heketi-template.yml
  roles/openshift_storage_glusterfs/files/v3.8/heketi-template.yml
  roles/openshift_storage_glusterfs/files/v3.9/deploy-heketi-template.yml
  roles/openshift_storage_glusterfs/files/v3.9/heketi-template.yml
Labels: lgtm, size/S

#7512 Bug 1554828- Nodes are now labeled compute after all other labels have been applied
  playbooks/common/openshift-cluster/upgrades/v3_9/label_nodes.yml
  roles/openshift_manage_node/tasks/config.yml
  roles/openshift_manage_node/tasks/main.yml
  roles/openshift_manage_node/tasks/set_default_node_role.yml
Labels: lgtm, size/S

#7508 Bug 1548641- Correct arguments to yedit
  roles/openshift_master/tasks/upgrade.yml
Labels: lgtm, size/XS

#7468 Add Kuryr documentation
  playbooks/openstack/README.md
  playbooks/openstack/configuration.md
Labels: lgtm, retest-not-required-docs-only, size/L

#7292 [3.7] Making patching a local_action and ensuring we become:false for local…
  openshift-ansible.spec
  roles/openshift_logging/tasks/generate_jks.yaml
  roles/openshift_logging/tasks/main.yaml
  roles/openshift_logging/tasks/patch_configmap_file.yaml
Labels: lgtm, size/L

#7205 GlusterFS - Invoke oc binary with the admin.kubeconfig token rather t…
  roles/openshift_storage_glusterfs/tasks/glusterfs_common.yml
  roles/openshift_storage_glusterfs/tasks/heketi_deploy_part2.yml
  roles/openshift_storage_glusterfs/tasks/main.yml
Labels: lgtm, size/S

#7441 Enabling multi vif pool drivers
  playbooks/openstack/configuration.md
  playbooks/openstack/sample-inventory/group_vars/all.yml
  roles/kuryr/templates/configmap.yaml.j2
Labels: lgtm, size/S

#7473 cluster-operator: Break up components installs into separate playbooks
  playbooks/cluster-operator/aws/components/openshift-glusterfs.yml
  playbooks/cluster-operator/aws/components/openshift-hosted.yml
  playbooks/cluster-operator/aws/components/openshift-logging.yml
  playbooks/cluster-operator/aws/components/openshift-management.yml
  playbooks/cluster-operator/aws/components/openshift-metrics.yml
  playbooks/cluster-operator/aws/components/openshift-prometheus.yml
  playbooks/cluster-operator/aws/components/openshift-service-catalog.yml
  playbooks/cluster-operator/aws/components/openshift-web-console.yml
Labels: lgtm, retest-not-required, size/L

#7515 Allowing means to provide custom es config entries with openshift_logging_es_config
  roles/openshift_logging_elasticsearch/defaults/main.yml
  roles/openshift_logging_elasticsearch/tasks/main.yaml
Labels: lgtm, size/S

#7517 Update the examples directory
  roles/openshift_examples/files/examples/v3.10/db-templates/README.md
  roles/openshift_examples/files/examples/v3.10/db-templates/mariadb-ephemeral-template.json
  roles/openshift_examples/files/examples/v3.10/db-templates/mariadb-persistent-template.json
  roles/openshift_examples/files/examples/v3.10/db-templates/mongodb-ephemeral-template.json
  roles/openshift_examples/files/examples/v3.10/db-templates/mongodb-persistent-template.json
  roles/openshift_examples/files/examples/v3.10/db-templates/mysql-ephemeral-template.json
  roles/openshift_examples/files/examples/v3.10/db-templates/mysql-persistent-template.json
  roles/openshift_examples/files/examples/v3.10/db-templates/postgresql-ephemeral-template.json
  roles/openshift_examples/files/examples/v3.10/db-templates/postgresql-persistent-template.json
  roles/openshift_examples/files/examples/v3.10/db-templates/redis-ephemeral-template.json
  roles/openshift_examples/files/examples/v3.10/db-templates/redis-persistent-template.json
  roles/openshift_examples/files/examples/v3.10/image-streams/README.md
  roles/openshift_examples/files/examples/v3.10/image-streams/image-streams-centos7.json
  roles/openshift_examples/files/examples/v3.10/image-streams/image-streams-rhel7.json
  roles/openshift_examples/files/examples/v3.10/quickstart-templates/README.md
  roles/openshift_examples/files/examples/v3.10/quickstart-templates/cakephp-mysql-persistent.json
  roles/openshift_examples/files/examples/v3.10/quickstart-templates/cakephp-mysql.json
  roles/openshift_examples/files/examples/v3.10/quickstart-templates/dancer-mysql-persistent.json
  roles/openshift_examples/files/examples/v3.10/quickstart-templates/dancer-mysql.json
  roles/openshift_examples/files/examples/v3.10/quickstart-templates/django-postgresql-persistent.json
  roles/openshift_examples/files/examples/v3.10/quickstart-templates/django-postgresql.json
  roles/openshift_examples/files/examples/v3.10/quickstart-templates/dotnet-example.json
  roles/openshift_examples/files/examples/v3.10/quickstart-templates/dotnet-pgsql-persistent.json
  roles/openshift_examples/files/examples/v3.10/quickstart-templates/dotnet-runtime-example.json
  roles/openshift_examples/files/examples/v3.10/quickstart-templates/httpd.json
  roles/openshift_examples/files/examples/v3.10/quickstart-templates/jenkins-ephemeral-template.json
  roles/openshift_examples/files/examples/v3.10/quickstart-templates/jenkins-persistent-template.json
  roles/openshift_examples/files/examples/v3.10/quickstart-templates/nginx.json
  roles/openshift_examples/files/examples/v3.10/quickstart-templates/nodejs-mongodb-persistent.json
  roles/openshift_examples/files/examples/v3.10/quickstart-templates/nodejs-mongodb.json
  roles/openshift_examples/files/examples/v3.10/quickstart-templates/rails-postgresql-persistent.json
  roles/openshift_examples/files/examples/v3.10/quickstart-templates/rails-postgresql.json
  roles/openshift_examples/files/examples/v3.10/xpaas-streams/fis-image-streams.json
  roles/openshift_examples/files/examples/v3.10/xpaas-templates/eap64-tx-recovery-s2i.json
  roles/openshift_examples/files/examples/v3.10/xpaas-templates/eap70-tx-recovery-s2i.json
  roles/openshift_examples/files/examples/v3.10/xpaas-templates/eap71-tx-recovery-s2i.json
  roles/openshift_examples/files/examples/v3.10/xpaas-templates/karaf2-camel-amq-template.json
  roles/openshift_examples/files/examples/v3.10/xpaas-templates/karaf2-camel-log-template.json
  roles/openshift_examples/files/examples/v3.10/xpaas-templates/karaf2-camel-rest-sql-template.json
  roles/openshift_examples/files/examples/v3.10/xpaas-templates/karaf2-cxf-rest-template.json
  roles/openshift_examples/files/examples/v3.10/xpaas-templates/spring-boot-camel-amq-template.json
  roles/openshift_examples/files/examples/v3.10/xpaas-templates/spring-boot-camel-config-template.json
  roles/openshift_examples/files/examples/v3.10/xpaas-templates/spring-boot-camel-drools-template.json
  roles/openshift_examples/files/examples/v3.10/xpaas-templates/spring-boot-camel-infinispan-template.json
  roles/openshift_examples/files/examples/v3.10/xpaas-templates/spring-boot-camel-rest-sql-template.json
  roles/openshift_examples/files/examples/v3.10/xpaas-templates/spring-boot-camel-teiid-template.json
  roles/openshift_examples/files/examples/v3.10/xpaas-templates/spring-boot-camel-template.json
  roles/openshift_examples/files/examples/v3.10/xpaas-templates/spring-boot-camel-xml-template.json
  roles/openshift_examples/files/examples/v3.10/xpaas-templates/spring-boot-cxf-jaxrs-template.json
  roles/openshift_examples/files/examples/v3.10/xpaas-templates/spring-boot-cxf-jaxws-template.json
Labels: lgtm, size/XXL

#7526 Label master nodes with openshift-infra=apiserver for service catalog
  playbooks/common/openshift-cluster/upgrades/upgrade_components.yml
  playbooks/openshift-service-catalog/private/config.yml
Labels: lgtm, size/S

#7502 Use oreg_url for node and master images
  .papr.sh
  roles/openshift_control_plane/defaults/main.yml
  roles/openshift_control_plane/tasks/static.yml
  roles/openshift_node/defaults/main.yml
  roles/openshift_node/tasks/install.yml
  roles/openshift_node/tasks/node_system_container.yml
  roles/openshift_sdn/defaults/main.yml
  roles/openshift_sdn/files/sdn-images.yaml
  roles/openshift_sdn/tasks/main.yml
Labels: lgtm, retest-not-required, size/M

#7475 Bug 1553576 - Change the self_hostname to ${hostname} in openshift-ansible
  roles/openshift_logging_fluentd/files/2.x/secure-forward.conf
  roles/openshift_logging_fluentd/files/5.x/secure-forward.conf
  roles/openshift_logging_fluentd/templates/2.x/fluent.conf.j2
  roles/openshift_logging_fluentd/templates/5.x/fluent.conf.j2
  roles/openshift_logging_mux/files/2.x/secure-forward.conf
  roles/openshift_logging_mux/files/5.x/secure-forward.conf
Labels: lgtm, size/S

#7571 Bump pyOpenSSL to 17.5.0
  requirements.txt
Labels: lgtm, queue/blocks-others, size/XS

#7570 etcd migrate: ensure all master vars are set
  playbooks/common/openshift-etcd/migrate.yml
Labels: lgtm, size/XS

#7524 Change openshift_client_binary to openshift.common.client_binary
  roles/openshift_logging_elasticsearch/tasks/get_es_version.yml
Labels: lgtm, size/XS

#7579 EFS Provisioner: switch OCP tag to latest
  roles/openshift_provisioners/defaults/main.yaml
Labels: size/XS

#7557 Bug 1541946- waiting for master reboot now works behind bastion
  playbooks/common/openshift-master/restart_hosts.yml
Labels: size/S

#7497 Limit Prometheus discovery to relevant namespaces
  roles/openshift_prometheus/templates/prometheus.yml.j2
Labels: lgtm, size/S

#7582 fixing the mounts for the daemonset config to have non subpath mount
  roles/openshift_daemonset_config/templates/daemonset.yml.j2
Labels: lgtm, size/XS

#7325 use openshift_image_tag default for prometheus_node_exporter image
  roles/openshift_prometheus/vars/openshift-enterprise.yml
Labels: lgtm, size/XS

#7258 upgrade prometheus v2.0.0 -> v2.1.0
  roles/openshift_prometheus/vars/default_images.yml
Labels: lgtm, size/XS

#7546 [3.7] Adding check in case only one ES container is in the pod for upgrades to 3.7
  roles/openshift_logging_elasticsearch/tasks/get_es_version.yml
Labels: lgtm, size/S

#7591 Bumping up the default wait time for ES node to be yellow or green
  roles/openshift_logging_elasticsearch/tasks/restart_es_node.yml
  roles/openshift_logging_elasticsearch/vars/main.yml
Labels: affects_3.7, affects_3.9, lgtm, size/XS

#7493 Don't verify node exporter is running
  roles/openshift_prometheus/tasks/install_node_exporter.yaml
Labels: lgtm, size/XS

#7566 Bug 1557909 - Remove openshift_management beta acknowledgement
  roles/openshift_management/README.md
  roles/openshift_management/defaults/main.yml
  roles/openshift_management/tasks/validate.yml
Labels: kind/bug, lgtm, size/M

#7381 Use cloudprovider labels for service affinity/antiaffinity
  roles/lib_utils/lookup_plugins/openshift_master_facts_default_predicates.py
  roles/lib_utils/lookup_plugins/openshift_master_facts_default_priorities.py
  roles/lib_utils/test/conftest.py
  roles/lib_utils/test/openshift_master_facts_default_predicates_tests.py
  roles/lib_utils/test/openshift_master_facts_default_priorities_tests.py
  roles/openshift_master/tasks/upgrade/upgrade_predicates.yml
  roles/openshift_master/tasks/upgrade/upgrade_priorities.yml
  roles/openshift_master/vars/main.yml
  roles/openshift_master_facts/tasks/main.yml
  roles/openshift_master_facts/vars/main.yml
Labels: lgtm, size/L

#7407 Add metrics-server to openshift-metrics playbook
  roles/openshift_metrics/README.md
  roles/openshift_metrics/defaults/main.yaml
  roles/openshift_metrics/tasks/generate_certificates.yaml
  roles/openshift_metrics/tasks/generate_metrics_server_certificates.yaml
  roles/openshift_metrics/tasks/generate_rolebindings.yaml
  roles/openshift_metrics/tasks/generate_serviceaccounts.yaml
  roles/openshift_metrics/tasks/generate_services.yaml
  roles/openshift_metrics/tasks/install_metrics.yaml
  roles/openshift_metrics/tasks/install_support.yaml
  roles/openshift_metrics/tasks/pre_install.yaml
  roles/openshift_metrics/tasks/uninstall_metrics.yaml
  roles/openshift_metrics/templates/metrics-server-apiservice.j2
  roles/openshift_metrics/templates/metrics-server-auth-delegator.j2
  roles/openshift_metrics/templates/metrics-server-auth-reader.j2
  roles/openshift_metrics/templates/metrics-server-deployment.j2
  roles/openshift_metrics/templates/metrics-server-resource-reader.j2
  roles/openshift_metrics/templates/metrics-server-role.js2
  roles/openshift_metrics/templates/metrics-server-sa.j2
  roles/openshift_metrics/templates/metrics-server-service.j2
Labels: lgtm, size/L

#7356 roles/openshift-prometheus: fix some prometheus service discovery scraping
  roles/openshift_prometheus/templates/prometheus.j2
Labels: lgtm, size/S

#7599 add in password auth for logging proxy
  roles/openshift_logging_elasticsearch/templates/5.x/es.j2
Labels: lgtm, size/XS

#7610 fix the ELASTICSEARCH_URL for kibana
  roles/openshift_logging_kibana/templates/5.x/kibana.j2
Labels: lgtm, size/XS

#7602 Updating default run hour and minute for curator
  roles/openshift_logging_curator/defaults/main.yml
Labels: affects_3.9, lgtm, size/XS

#7612 migrate: update ETCD_NAME for migrated hosts
  playbooks/common/openshift-etcd/migrate.yml
Labels: lgtm, size/XS

#7622 Configure dnsmasq before waiting for node
  roles/openshift_node/tasks/upgrade.yml
Labels: lgtm, size/XS

#7590 Make ports pool the default when deploying with kuryr
  playbooks/openstack/configuration.md
  playbooks/openstack/sample-inventory/group_vars/all.yml
  roles/kuryr/defaults/main.yaml
  roles/kuryr/templates/configmap.yaml.j2
Labels: lgtm, size/M

#7627 [master] package_version check: stop looking for docker
  roles/openshift_health_checker/openshift_checks/package_version.py
  roles/openshift_health_checker/test/package_version_test.py
Labels: lgtm, size/M

#7628 [3.8] package_version check: stop looking for docker
  roles/openshift_health_checker/openshift_checks/package_version.py
  roles/openshift_health_checker/test/package_version_test.py
Labels: size/M

#7629 [3.9] package_version check: stop looking for docker
  roles/openshift_health_checker/openshift_checks/package_version.py
  roles/openshift_health_checker/test/package_version_test.py
Labels: size/M

#7186 Parameterize OpenStack secgrp rules
  roles/openshift_openstack/defaults/main.yml
  roles/openshift_openstack/templates/heat_stack.yaml.j2
Labels: lgtm, size/L

#7641 Remove duplicated index
  playbooks/openstack/configuration.md
Labels: needs-ok-to-test, retest-not-required-docs-only, size/XS

#7636 Replacing -v with -p for template parameters in oc_process
  roles/lib_openshift/library/oc_adm_ca_server_cert.py
  roles/lib_openshift/library/oc_adm_csr.py
  roles/lib_openshift/library/oc_adm_manage_node.py
  roles/lib_openshift/library/oc_adm_policy_group.py
  roles/lib_openshift/library/oc_adm_policy_user.py
  roles/lib_openshift/library/oc_adm_registry.py
  roles/lib_openshift/library/oc_adm_router.py
  roles/lib_openshift/library/oc_clusterrole.py
  roles/lib_openshift/library/oc_configmap.py
  roles/lib_openshift/library/oc_edit.py
  roles/lib_openshift/library/oc_env.py
  roles/lib_openshift/library/oc_group.py
  roles/lib_openshift/library/oc_image.py
  roles/lib_openshift/library/oc_label.py
  roles/lib_openshift/library/oc_obj.py
  roles/lib_openshift/library/oc_objectvalidator.py
  roles/lib_openshift/library/oc_process.py
  roles/lib_openshift/library/oc_project.py
  roles/lib_openshift/library/oc_pvc.py
  roles/lib_openshift/library/oc_route.py
  roles/lib_openshift/library/oc_scale.py
  roles/lib_openshift/library/oc_secret.py
  roles/lib_openshift/library/oc_service.py
  roles/lib_openshift/library/oc_serviceaccount.py
  roles/lib_openshift/library/oc_serviceaccount_secret.py
  roles/lib_openshift/library/oc_storageclass.py
  roles/lib_openshift/library/oc_user.py
  roles/lib_openshift/library/oc_version.py
  roles/lib_openshift/library/oc_volume.py
  roles/lib_openshift/src/lib/base.py
Labels: lgtm, size/M

#7640 Revert "Use region and zone labels added by cloudprovider for scheduling"
  roles/lib_utils/lookup_plugins/openshift_master_facts_default_predicates.py
  roles/lib_utils/lookup_plugins/openshift_master_facts_default_priorities.py
  roles/lib_utils/test/conftest.py
  roles/lib_utils/test/openshift_master_facts_default_predicates_tests.py
  roles/lib_utils/test/openshift_master_facts_default_priorities_tests.py
  roles/openshift_master/tasks/upgrade/upgrade_predicates.yml
  roles/openshift_master/tasks/upgrade/upgrade_priorities.yml
  roles/openshift_master/vars/main.yml
  roles/openshift_master_facts/tasks/main.yml
  roles/openshift_master_facts/vars/main.yml
Labels: lgtm, size/L

#7360 [3.7] wire_aggregator: skip openshift_upgrade_target version check if its undefined
  playbooks/common/openshift-master/tasks/wire_aggregator.yml
Labels: lgtm, size/XS

#7283 [3.7] service catalog: Update API healthz check to use uri module and add noproxy
  roles/openshift_service_catalog/tasks/start_api_server.yml
Labels: lgtm, size/S

#7651 Ensure master-logs works for both origin and enterprise
  roles/openshift_control_plane/files/scripts/docker/master-logs
Labels: lgtm

#7653 Install/update SDN package only when openshift SDN is used
  playbooks/common/openshift-cluster/upgrades/rpm_upgrade.yml
  roles/openshift_node/defaults/main.yml
  roles/openshift_node/tasks/bootstrap.yml
Labels: lgtm, size/S

#7656 Split the provision.yml playbook for more flexibility.
  playbooks/openstack/openshift-cluster/provision.yml
  playbooks/openstack/openshift-cluster/provision_install.yml
  playbooks/openstack/openshift-cluster/provision_resources.yml
Labels: lgtm, size/S

#7648 [3.9] Change include_tasks to import_tasks
  roles/openshift_node/tasks/config.yml
  roles/openshift_node/tasks/container_images.yml
  roles/openshift_node/tasks/dnsmasq.yml
  roles/openshift_node/tasks/dnsmasq/no-network-manager.yml
  roles/openshift_node/tasks/dnsmasq_install.yml
  roles/openshift_node/tasks/main.yml
  roles/openshift_node/tasks/systemd_units.yml
  roles/openshift_node/tasks/upgrade.yml
  roles/openshift_node/tasks/upgrade/config_changes.yml
  roles/openshift_node/tasks/upgrade/containerized_upgrade_pull.yml
  roles/openshift_node/tasks/upgrade_pre.yml
Labels: kind/bug, lgtm, priority/P0, size/M

#7644 Master components should not have configurable labels
  .papr.inventory
  playbooks/common/openshift-cluster/upgrades/upgrade_components.yml
  playbooks/openshift-service-catalog/private/config.yml
  roles/openshift_docker_gc/tasks/main.yml
  roles/openshift_service_catalog/defaults/main.yml
  roles/openshift_service_catalog/tasks/install.yml
  roles/openshift_service_catalog/tasks/start_api_server.yml
  roles/template_service_broker/defaults/main.yml
  roles/template_service_broker/tasks/deploy.yml
  roles/template_service_broker/tasks/install.yml
Labels: lgtm, size/M

#7659 Master: change openshift_node include_tasks to import_tasks
  roles/openshift_node/tasks/config.yml
  roles/openshift_node/tasks/container_images.yml
  roles/openshift_node/tasks/dnsmasq.yml
  roles/openshift_node/tasks/dnsmasq/no-network-manager.yml
  roles/openshift_node/tasks/dnsmasq_install.yml
  roles/openshift_node/tasks/main.yml
  roles/openshift_node/tasks/systemd_units.yml
  roles/openshift_node/tasks/upgrade.yml
  roles/openshift_node/tasks/upgrade/config_changes.yml
  roles/openshift_node/tasks/upgrade_pre.yml
Labels: lgtm, size/M

#7647 Remove complex version logic and fix f27 build
  .papr.inventory
  .papr.sh
  roles/openshift_version/tasks/first_master_containerized_version.yml
Labels: lgtm, size/S

#7646 CSR approval should ignore errors when retrying
  roles/lib_openshift/library/oc_adm_csr.py
  roles/lib_openshift/src/class/oc_adm_csr.py
Labels: lgtm, size/M

#7664 [3.6] Master: upgrade SDN package only when openshift SDN is used
  playbooks/common/openshift-cluster/upgrades/rpm_upgrade.yml
Labels: size/XS

#7663 [3.9] Install/update SDN package only when openshift SDN is used
  roles/openshift_master/tasks/upgrade/rpm_upgrade.yml
  roles/openshift_node/defaults/main.yml
  roles/openshift_node/tasks/install_rpms.yml
Labels: size/S

#7670 [3.7] etcd migrate: make sure masters are restarted instead of started
  playbooks/common/openshift-etcd/migrate.yml
Labels: lgtm, size/XS

#7662 Remove etcd_migrate and embedded2external
  playbooks/openshift-etcd/embedded2external.yml
  playbooks/openshift-etcd/migrate.yml
  playbooks/openshift-etcd/private/embedded2external.yml
  playbooks/openshift-etcd/private/migrate.yml
  roles/etcd/defaults/main.yaml
  roles/etcd/tasks/auxiliary/clean_data.yml
  roles/etcd/tasks/auxiliary/disable_etcd.yml
  roles/etcd/tasks/auxiliary/force_new_cluster.yml
  roles/etcd/tasks/backup.archive.yml
  roles/etcd/tasks/backup.copy.yml
  roles/etcd/tasks/backup.fetch.yml
  roles/etcd/tasks/backup.force_new_cluster.yml
  roles/etcd/tasks/backup.unarchive.yml
  roles/etcd/tasks/backup/backup.yml
  roles/etcd/tasks/backup_master_etcd_certificates.yml
  roles/etcd/tasks/certificates/backup_master_etcd_certificates.yml
  roles/etcd/tasks/check_cluster_health.yml
  roles/etcd/tasks/clean_data.yml
  roles/etcd/tasks/disable_etcd.yml
  roles/etcd/tasks/migrate.add_ttls.yml
  roles/etcd/tasks/migrate.configure_master.yml
  roles/etcd/tasks/migrate.pre_check.yml
  roles/etcd/tasks/migrate.yml
  roles/etcd/tasks/migration/add_ttls.yml
  roles/etcd/tasks/migration/check.yml
  roles/etcd/tasks/migration/check_cluster_health.yml
  roles/etcd/tasks/migration/check_cluster_status.yml
  roles/etcd/tasks/migration/configure_master.yml
  roles/etcd/tasks/migration/migrate.yml
  roles/lib_utils/library/openshift_cert_expiry.py
  roles/nuage_master/tasks/etcd_certificates.yml
  roles/openshift_control_plane/defaults/main.yml
  roles/openshift_master/defaults/main.yml
  roles/openshift_master/tasks/configure_external_etcd.yml
Labels: lgtm, size/XL

#7677 [3.9] Configure dnsmasq before waiting for node
  roles/openshift_node/tasks/upgrade.yml
Labels: lgtm, size/XS
