Repository openshift/openshift-ansible, pull requests merged in 2018-07, with the labels that each got.

#8995 Ensure SkyDNS is enabled with Kuryr SDN
  roles/kuryr/templates/cni-daemonset.yaml.j2
Labels: approved, lgtm, priority/P0, size/M

#9013 Remove the extra OpenStack network tasks
  playbooks/openstack/openshift-cluster/install.yml
  roles/openshift_openstack/defaults/main.yml
  roles/openshift_openstack/tasks/node-configuration.yml
  roles/openshift_openstack/tasks/node-network.yml
  roles/openshift_openstack/tasks/node-packages.yml
Labels: approved, lgtm, size/M

#9019 change heketi logic
  roles/openshift_storage_glusterfs/tasks/glusterfs_common.yml
Labels: approved, lgtm, size/XS

#9045 Convert rbac v1beta to v1
  roles/openshift_bootstrap_autoapprover/files/openshift-bootstrap-controller-policy.yaml
  roles/openshift_bootstrap_autoapprover/files/openshift-bootstrap-controller-role.yaml
  roles/openshift_cluster_monitoring_operator/files/cluster-monitoring-operator.yaml
  roles/openshift_logging_elasticsearch/templates/logging-metrics-role.j2
  roles/openshift_logging_elasticsearch/templates/logging-metrics-rolebinding.j2
  roles/openshift_monitor_availability/files/monitor-app-create.yaml
  roles/openshift_monitor_availability/files/prometheus-k8s-role-binding.yaml
  roles/openshift_monitor_availability/files/prometheus-k8s-role.yaml
  roles/openshift_service_catalog/files/openshift_catalog_clusterroles.yml
  roles/template_service_broker/files/rbac-template.yaml
Labels: approved, lgtm, size/M

#9053 Azure: update create_and_publish_offer to match new offer/SKUs
  playbooks/azure/openshift-cluster/create_and_publish_offer.md
  playbooks/azure/openshift-cluster/create_and_publish_offer.yml
  playbooks/azure/openshift-cluster/group_vars/all/image_publish.yml
  playbooks/azure/openshift-cluster/templates/offer.yml.j2
  roles/lib_utils/library/oo_azure_rm_publish_image.py
  roles/lib_utils/library/oo_azure_rm_publish_image_facts.py
Labels: size/L

#9057 add node get-node-logs script for azure
  playbooks/azure/openshift-cluster/build_node_image.yml
  playbooks/azure/openshift-cluster/files/get-node-logs
Labels: approved, lgtm, sig/azure, size/M

#9058 Don't upgrade nodes which only have dedicated etcd
  playbooks/common/openshift-cluster/upgrades/initialize_nodes_to_upgrade.yml
  playbooks/common/openshift-cluster/upgrades/pre/config.yml
Labels: approved, lgtm, size/XS

#9046 Change ansible variable for flexvolume location
  roles/openshift_control_plane/tasks/main.yml
  roles/openshift_control_plane/tasks/static.yml
  roles/openshift_control_plane/templates/master.yaml.v1.j2
  roles/openshift_facts/defaults/main.yml
  roles/openshift_node/tasks/config.yml
  roles/openshift_node/templates/node.yaml.v1.j2
  roles/openshift_node_group/templates/node-config.yaml.j2
Labels: approved, lgtm, size/S

#9051 Certificates signed by admins should be approved
  roles/openshift_bootstrap_autoapprover/files/openshift-bootstrap-controller.yaml
Labels: approved, lgtm, size/XS

#9081 Add simonpasquier to the OWNERS file for prometheus installer
  roles/openshift_prometheus/OWNERS
Labels: approved, lgtm, size/XS

#9062 aws scale gruops: resume gracefully on upgrades
  roles/openshift_aws/tasks/build_node_group.yml
  roles/openshift_aws/tasks/setup_master_group.yml
  roles/openshift_aws/tasks/upgrade_node_group.yml
Labels: approved, lgtm, size/M

#7759 Add SDN health check
  playbooks/openshift-checks/private/adhoc.yml
  roles/openshift_health_checker/openshift_checks/sdn.py
  roles/openshift_health_checker/test/sdn_tests.py
Labels: approved, lgtm, size/XL

#9033 change become syntax logging
  roles/openshift_logging/tasks/main.yaml
  roles/openshift_logging/tasks/patch_configmap_file.yaml
  roles/openshift_metrics/tasks/main.yaml
Labels: approved, lgtm, size/S

#8733 Migrate old master env files to new location
  roles/lib_utils/library/master_env_config_migrate.py
  roles/lib_utils/test/test_master_env_config_migrate.py
  roles/openshift_control_plane/tasks/upgrade.yml
Labels: approved, lgtm, size/L

#9089 Suppress unexpected errors caused by non-English locale during CRI-O installation
  roles/container_runtime/tasks/common/setup_docker_symlink.yml
Labels: approved, lgtm, size/XS

#8907 Add metrics-server to openshift-metrics playbook
  roles/openshift_metrics/README.md
  roles/openshift_metrics/defaults/main.yaml
  roles/openshift_metrics/tasks/generate_certificates.yaml
  roles/openshift_metrics/tasks/generate_metrics_server_certificates.yaml
  roles/openshift_metrics/tasks/generate_rolebindings.yaml
  roles/openshift_metrics/tasks/generate_serviceaccounts.yaml
  roles/openshift_metrics/tasks/generate_services.yaml
  roles/openshift_metrics/tasks/install_metrics.yaml
  roles/openshift_metrics/tasks/install_support.yaml
  roles/openshift_metrics/tasks/pre_install.yaml
  roles/openshift_metrics/tasks/uninstall_metrics.yaml
  roles/openshift_metrics/templates/metrics-server-apiservice.j2
  roles/openshift_metrics/templates/metrics-server-auth-delegator.j2
  roles/openshift_metrics/templates/metrics-server-auth-reader.j2
  roles/openshift_metrics/templates/metrics-server-deployment.j2
  roles/openshift_metrics/templates/metrics-server-resource-reader.j2
  roles/openshift_metrics/templates/metrics-server-role.js2
  roles/openshift_metrics/templates/metrics-server-sa.j2
  roles/openshift_metrics/templates/metrics-server-service.j2
Labels: approved, lgtm, size/L

#9079 Accept client certs from node, system:admin, and bootstrap SA
  roles/lib_openshift/library/oc_adm_csr.py
  roles/lib_openshift/src/ansible/oc_adm_csr.py
  roles/lib_openshift/src/class/oc_adm_csr.py
Labels: approved, lgtm, size/M

#9090 Wait for API availability before migrating storage, add retries
  playbooks/openshift-master/private/upgrade.yml
  roles/openshift_control_plane/tasks/check_master_api_is_ready.yml
  roles/openshift_control_plane/tasks/main.yml
Labels: approved, lgtm, size/M

#8949 [release-3.6] Assign openshift_version from openshift_pkg_version with correct format
  roles/openshift_ca/README.md
  roles/openshift_ca/vars/main.yml
  roles/openshift_named_certificates/vars/main.yml
  roles/openshift_version/tasks/set_version_rpm.yml
Labels: lgtm, size/S

#9069 Uninstall playbook to respect openshift_use_openshift_sdn.
  playbooks/adhoc/uninstall.yml
Labels: approved, lgtm, size/M

#9097 [Bug 1583530] [release-3.6] Skip etcd certificate redeploy on embedded etcd
  playbooks/common/openshift-cluster/upgrades/upgrade_control_plane.yml
Labels: lgtm, size/XS

#8975 [3.9] Add format check of openshift_pkg_version and openshift_release
  roles/lib_utils/action_plugins/sanity_checks.py
  roles/lib_utils/test/sanity_check_test.py
Labels: approved, lgtm, size/L

#9108 Clean cloud-init path
  playbooks/openshift-node/private/clean_image.yml
Labels: approved, lgtm, size/XS

#9059 [release-3.9] Get precise openshift version with containerized installation
  roles/openshift_facts/library/openshift_facts.py
Labels: approved, lgtm, size/S

#8989 create an imagestream import secret for importing samples
  roles/openshift_examples/tasks/main.yml
Labels: approved, lgtm, size/S

#9031 prometheus: upgrade prometheus components
  roles/openshift_prometheus/defaults/main.yaml
  roles/openshift_prometheus/files/node-exporter-template.yaml
Labels: approved, lgtm, size/S

#9038 Change multipath prio from const to alua
  roles/openshift_node/templates/multipath.conf.j2
Labels: approved, lgtm, size/XS

#9056 standalone etcds: make sure etcd facts are set before applying etcd config
  playbooks/openshift-etcd/private/config.yml
Labels: approved, lgtm, size/XS

#9065 Use OPENSHIFT_CLUSTER env in OpenStack uninstall
  playbooks/openstack/openshift-cluster/uninstall.yml
Labels: approved, lgtm, size/XS

#9086 Don't install google-cloud-sdk on non x86_64 images
  images/installer/Dockerfile
  images/installer/Dockerfile.rhel7
Labels: approved, lgtm, size/XS

#8980 [3.9] clean-up RPM generated conf from preinstalled openshift packages
  playbooks/common/private/control_plane.yml
  playbooks/openshift-master/private/clean_preinstalled_conf.yml
  playbooks/openshift-master/private/config.yml
Labels: lgtm, size/M

#8906 Grafana: convert grafana_service_targetport in annotations
  roles/openshift_grafana/tasks/install_grafana.yaml
Labels: approved, lgtm, size/XS

#9126 Do not delete IAM cert if explicitely requested
  roles/openshift_aws/defaults/main.yml
  roles/openshift_aws/tasks/uninstall_iam_cert.yml
Labels: approved, lgtm, size/XS

#9107 Ensure nodes created by a scale group have a Name tag
  roles/openshift_aws/tasks/scale_group.yml
Labels: approved, lgtm, size/XS

#9123 Sync Fuse console templates
  roles/openshift_examples/examples-sync.sh
Labels: lgtm, needs-ok-to-test, size/XS

#9096 Add Fuse Console templates
  roles/openshift_examples/files/examples/v3.10/xpaas-templates/fis-console-cluster-template.json
  roles/openshift_examples/files/examples/v3.10/xpaas-templates/fis-console-namespace-template.json
Labels: size/L

#9015 Increase lbaas_activation_timeout for kuryr-controller
  roles/kuryr/templates/configmap.yaml.j2
Labels: approved, lgtm, size/XS

#9125 [3.9] WIP Ansible 2.6 fixes
  roles/lib_utils/filter_plugins/openshift_master.py
Labels: lgtm, size/XS

#9113 Remove system container bits from etcd
  playbooks/openshift-etcd/private/upgrade_image_members.yml
  playbooks/openshift-etcd/private/upgrade_main.yml
  playbooks/openshift-etcd/private/upgrade_step.yml
  roles/etcd/defaults/main.yaml
  roles/etcd/tasks/auxiliary/drop_etcdctl.yml
  roles/etcd/tasks/drop_etcdctl.yml
  roles/etcd/tasks/restart.yml
  roles/etcd/tasks/rpm.yml
  roles/etcd/tasks/runtime.yml
  roles/etcd/tasks/upgrade/upgrade_image.yml
  roles/etcd/tasks/upgrade/upgrade_rpm.yml
  roles/etcd/tasks/upgrade_image.yml
  roles/etcd/tasks/upgrade_rpm.yml
  roles/etcd/tasks/upgrade_static.yml
  roles/etcd/tasks/validate_etcd_conf.yml
  roles/etcd/tasks/version_detect.yml
  roles/etcd/templates/etcd.conf.j2
Labels: approved, lgtm, size/L

#9128 Ensure nodes created by a scale group have a Name tag
  roles/openshift_aws/tasks/scale_group.yml
Labels: approved, lgtm, size/XS

#8328 Install OpenShift converged console
  playbooks/common/openshift-cluster/upgrades/post_control_plane.yml
  playbooks/common/private/components.yml
  playbooks/openshift-console/OWNERS
  playbooks/openshift-console/config.yml
  playbooks/openshift-console/private/config.yml
  playbooks/openshift-console/private/roles
  roles/openshift_console/OWNERS
  roles/openshift_console/defaults/main.yml
  roles/openshift_console/files/console-config.yaml
  roles/openshift_console/files/console-template.yaml
  roles/openshift_console/meta/main.yaml
  roles/openshift_console/tasks/install.yml
  roles/openshift_console/tasks/main.yml
  roles/openshift_console/tasks/remove.yml
  roles/openshift_console/tasks/start.yml
  roles/openshift_console/vars/main.yml
Labels: approved, lgtm, size/L

#9021 Make fs_inotify_max_user_watches configurable.
  roles/tuned/defaults/main.yml
  roles/tuned/templates/openshift-node/tuned.conf
Labels: approved, lgtm, size/XS

#8622 Add openstack docs about swift/ceph rados gw backed registry
  playbooks/openstack/configuration.md
Labels: approved, lgtm, size/S

#8679 Add Openshift Metering role and playbook
  playbooks/common/private/components.yml
  playbooks/openshift-metering/README.md
  playbooks/openshift-metering/config.yml
  playbooks/openshift-metering/gcp-config.yml
  playbooks/openshift-metering/private/config.yml
  playbooks/openshift-metering/private/roles
  roles/openshift_metering/README.md
  roles/openshift_metering/defaults/main.yml
  roles/openshift_metering/files/crds/metering.crd.yaml
  roles/openshift_metering/files/crds/prestotable.crd.yaml
  roles/openshift_metering/files/crds/report.crd.yaml
  roles/openshift_metering/files/crds/reportdatasource.crd.yaml
  roles/openshift_metering/files/crds/reportgenerationquery.crd.yaml
  roles/openshift_metering/files/crds/reportprometheusquery.crd.yaml
  roles/openshift_metering/files/crds/scheduledreport.crd.yaml
  roles/openshift_metering/files/crds/storagelocation.crd.yaml
  roles/openshift_metering/files/operator/metering-helm-operator-deployment.yaml
  roles/openshift_metering/files/operator/metering-helm-operator-role.yaml
  roles/openshift_metering/files/operator/metering-helm-operator-rolebinding.yaml
  roles/openshift_metering/files/operator/metering-helm-operator-service-account.yaml
  roles/openshift_metering/files/operator/metering.yaml
  roles/openshift_metering/meta/main.yaml
  roles/openshift_metering/tasks/install.yaml
  roles/openshift_metering/tasks/main.yaml
  roles/openshift_metering/tasks/uninstall.yaml
  roles/openshift_metering/vars/main.yml
Labels: approved, lgtm, size/XL

#9072 Allow the 9k-10k port range for Prometheus
  roles/openshift_node/defaults/main.yml
Labels: approved, lgtm, size/XS

#9094 Allow installs of Node Problem Detector during upgrades
  playbooks/common/openshift-cluster/upgrades/upgrade_components.yml
Labels: approved, lgtm, size/XS

#9119 Fixup various TODO sections of code
  playbooks/init/basic_facts.yml
  roles/lib_utils/action_plugins/sanity_checks.py
  roles/lib_utils/filter_plugins/oo_filters.py
  roles/lib_utils/meta/main.yml
  roles/openshift_cli/tasks/main.yml
  roles/openshift_control_plane/defaults/main.yml
  roles/openshift_control_plane/tasks/migrate_idproviders.yml
  roles/openshift_control_plane/tasks/upgrade.yml
Labels: approved, lgtm, size/L

#9138 Remove callback plugin, artifact of a quick installer
  roles/lib_utils/callback_plugins/openshift_quick_installer.py
Labels: approved, lgtm, size/L

#9142 Add check for oreg_password by default
  roles/lib_utils/action_plugins/sanity_checks.py
Labels: approved, lgtm, size/S

#9137 Exclude masters from node list for CSR approval.
  playbooks/init/evaluate_groups.yml
Labels: approved, lgtm, size/XS

#8953 Add atomic package to base and debug package lists
  playbooks/gcp/openshift-cluster/build_base_image.yml
  roles/openshift_node/defaults/main.yml
Labels: approved, lgtm, size/XS

#9063 Add EAP CD 13 imagestream and templates.
  roles/openshift_examples/files/examples/v3.11/xpaas-streams/eap-cd-image-stream.json
  roles/openshift_examples/files/examples/v3.11/xpaas-templates/eap-cd-amq-persistent-s2i.json
  roles/openshift_examples/files/examples/v3.11/xpaas-templates/eap-cd-amq-s2i.json
  roles/openshift_examples/files/examples/v3.11/xpaas-templates/eap-cd-basic-s2i.json
  roles/openshift_examples/files/examples/v3.11/xpaas-templates/eap-cd-https-s2i.json
  roles/openshift_examples/files/examples/v3.11/xpaas-templates/eap-cd-mongodb-persistent-s2i.json
  roles/openshift_examples/files/examples/v3.11/xpaas-templates/eap-cd-mongodb-s2i.json
  roles/openshift_examples/files/examples/v3.11/xpaas-templates/eap-cd-mysql-persistent-s2i.json
  roles/openshift_examples/files/examples/v3.11/xpaas-templates/eap-cd-mysql-s2i.json
  roles/openshift_examples/files/examples/v3.11/xpaas-templates/eap-cd-postgresql-persistent-s2i.json
  roles/openshift_examples/files/examples/v3.11/xpaas-templates/eap-cd-postgresql-s2i.json
  roles/openshift_examples/files/examples/v3.11/xpaas-templates/eap-cd-sso-s2i.json
  roles/openshift_examples/files/examples/v3.11/xpaas-templates/eap-cd-third-party-db-s2i.json
  roles/openshift_examples/files/examples/v3.11/xpaas-templates/eap-cd-tx-recovery-s2i.json
Labels: approved, lgtm, size/XL

#8008 Enable extended validation of routes by default
  inventory/hosts.example
  roles/lib_openshift/library/oc_adm_router.py
  roles/lib_openshift/src/ansible/oc_adm_router.py
  roles/lib_openshift/src/class/oc_adm_router.py
  roles/lib_openshift/src/doc/router
  roles/lib_openshift/src/test/unit/test_oc_adm_router.py
  roles/openshift_hosted/README.md
  roles/openshift_hosted/defaults/main.yml
  roles/openshift_hosted/tasks/router.yml
Labels: approved, lgtm, size/M

#9105 gcp: add custom repo when building image
  playbooks/gcp/openshift-cluster/build_image.yml
Labels: approved, lgtm, size/XS

#9130 Fix to shebang in bootstrap script
  roles/openshift_node/templates/bootstrap.yml.j2
Labels: approved, lgtm, size/XS

#9140 Setup logrotate on nodes once
  playbooks/openshift-etcd/private/config.yml
  playbooks/openshift-etcd/private/scaleup.yml
  playbooks/openshift-master/private/config.yml
Labels: approved, lgtm, size/XS

#9153 Add openshift_docker_gc role to upgrade path
  playbooks/openshift-hosted/private/upgrade.yml
Labels: approved, lgtm, size/XS

#9091 Add a components public playbook
  playbooks/openshift-master/components.yml
Labels: approved, lgtm, size/XS

#9145 Defining a default for logging_elasticsearch_rollout_override var in es handler
  roles/openshift_logging_elasticsearch/handlers/main.yml
Labels: affects_3.10, affects_3.9, approved, lgtm, size/XS

#9157 Force rebuild of config when upgrading to es5
  roles/openshift_logging_elasticsearch/tasks/main.yaml
Labels: approved, lgtm, size/XS

#9132 Fixing missing _es_version variable
  roles/openshift_logging_elasticsearch/tasks/main.yaml
  roles/openshift_logging_elasticsearch/vars/main.yml
Labels: approved, lgtm, size/XS

#9112 Add option to generate a static inventory for Openstack
  playbooks/openstack/configuration.md
  playbooks/openstack/inventory.py
Labels: approved, lgtm, size/M

#9106 [3.7] TSB and ASB should use openshift_hosted_infra_selector by default
  roles/template_service_broker/defaults/main.yml
Labels: lgtm, size/XS

#9104 Install metrics-server pre-upgrade
  inventory/hosts.example
  playbooks/common/openshift-cluster/upgrades/v3_11/upgrade_control_plane.yml
  playbooks/common/private/components.yml
  playbooks/metrics-server/OWNERS
  playbooks/metrics-server/config.yml
  playbooks/metrics-server/private/config.yml
  playbooks/metrics-server/private/roles
  roles/metrics_server/OWNERS
  roles/metrics_server/README.md
  roles/metrics_server/defaults/main.yaml
  roles/metrics_server/meta/main.yaml
  roles/metrics_server/tasks/generate_certs_and_apiservice.yaml
  roles/metrics_server/tasks/generate_sa_and_rbac.yaml
  roles/metrics_server/tasks/generate_svc_and_deployment.yaml
  roles/metrics_server/tasks/install_metrics_server.yaml
  roles/metrics_server/tasks/main.yaml
  roles/metrics_server/tasks/oc_apply.yaml
  roles/metrics_server/tasks/uninstall_metrics_server.yaml
  roles/metrics_server/templates/metrics-server-apiservice.j2
  roles/metrics_server/templates/metrics-server-auth-delegator.j2
  roles/metrics_server/templates/metrics-server-auth-reader.j2
  roles/metrics_server/templates/metrics-server-deployment.j2
  roles/metrics_server/templates/metrics-server-resource-reader.j2
  roles/metrics_server/templates/metrics-server-role.j2
  roles/metrics_server/templates/metrics-server-sa.j2
  roles/metrics_server/templates/metrics-server-service.j2
  roles/metrics_server/templates/serving-certs-secret.j2
  roles/openshift_metrics/README.md
  roles/openshift_metrics/defaults/main.yaml
  roles/openshift_metrics/tasks/generate_certificates.yaml
  roles/openshift_metrics/tasks/generate_metrics_server_certificates.yaml
  roles/openshift_metrics/tasks/generate_rolebindings.yaml
  roles/openshift_metrics/tasks/generate_serviceaccounts.yaml
  roles/openshift_metrics/tasks/generate_services.yaml
  roles/openshift_metrics/tasks/install_metrics.yaml
  roles/openshift_metrics/tasks/install_support.yaml
  roles/openshift_metrics/tasks/pre_install.yaml
  roles/openshift_metrics/tasks/uninstall_metrics.yaml
Labels: approved, lgtm, size/XL

#9147 Updated openshift-cluster-autoscaler role and playbooks
  playbooks/common/private/components.yml
  playbooks/openshift-cluster-autoscaler/config.yml
  playbooks/openshift-cluster-autoscaler/private/config.yml
  playbooks/openshift-cluster-autoscaler/private/roles
  playbooks/openshift-master/private/additional_config.yml
  roles/openshift_cluster_autoscaler/defaults/main.yml
  roles/openshift_cluster_autoscaler/files/clusterrole.yml
  roles/openshift_cluster_autoscaler/meta/main.yml
  roles/openshift_cluster_autoscaler/tasks/aws.yml
  roles/openshift_cluster_autoscaler/tasks/main.yml
  roles/openshift_cluster_autoscaler/templates/cluster-autoscaler.j2
Labels: approved, lgtm, size/L

#9174 Fix PVC binding of NFS pv with default storageclass set
  roles/lib_utils/action_plugins/generate_pv_pvcs_list.py
  roles/openshift_persistent_volumes/templates/persistent-volume-claim.yml.j2
  roles/openshift_persistent_volumes/templates/persistent-volume.yml.j2
Labels: approved, lgtm, size/S

#9188 [release-3.7Updating fluentd label and wait to be in a single shell
  roles/openshift_logging_fluentd/tasks/label_and_wait.yaml
  roles/openshift_logging_fluentd/tasks/main.yaml
  roles/openshift_logging_fluentd/templates/fluentd_label.sh.j2
Labels: lgtm, size/M

#9085 [RHDM-662] - Update RHDM templates on OCP and OSO
  roles/openshift_examples/files/examples/v3.11/xpaas-streams/rhdm70-image-streams.yaml
  roles/openshift_examples/files/examples/v3.11/xpaas-templates/rhdm70-full.yaml
  roles/openshift_examples/files/examples/v3.11/xpaas-templates/rhdm70-kieserver-basic-s2i.yaml
  roles/openshift_examples/files/examples/v3.11/xpaas-templates/rhdm70-kieserver-https-s2i.yaml
  roles/openshift_examples/files/examples/v3.11/xpaas-templates/rhdm70-kieserver.yaml
Labels: approved, lgtm, size/XL

#9166 Update sdn, sdn-ovs, sync, fluentd, descheduler to have system-cluster/node-critical priority classes.
  roles/openshift_daemonset_config/templates/daemonset.yml.j2
  roles/openshift_descheduler/templates/descheduler-cronjob.yaml.j2
  roles/openshift_logging_fluentd/templates/fluentd.j2
  roles/openshift_node_group/files/sync.yaml
  roles/openshift_sdn/files/sdn-ovs.yaml
  roles/openshift_sdn/files/sdn.yaml
Labels: approved, lgtm, size/XS

#9187 replace samples with ones from origin v3.10
  roles/openshift_examples/examples-sync.sh
  roles/openshift_examples/files/examples/v3.10/db-templates/mysql-ephemeral-template.json
  roles/openshift_examples/files/examples/v3.10/db-templates/mysql-persistent-template.json
  roles/openshift_examples/files/examples/v3.10/image-streams/image-streams-centos7.json
  roles/openshift_examples/files/examples/v3.10/image-streams/image-streams-rhel7.json
  roles/openshift_examples/files/examples/v3.10/quickstart-templates/dotnet-pgsql-persistent.json
  roles/openshift_examples/files/examples/v3.10/quickstart-templates/dotnet.json
  roles/openshift_examples/files/examples/v3.10/quickstart-templates/jenkins-persistent-template.json
Labels: approved, lgtm, size/XL

#9144 Controlled sysctl changes for Elasticsearch5
  playbooks/openshift-logging/private/config.yml
  roles/openshift_logging_elasticsearch/tasks/main.yaml
Labels: approved, lgtm, size/L

#9165 bug 1590920. Bump fluent default memory to 756M
  roles/openshift_logging_fluentd/defaults/main.yml
Labels: affects_3.10, approved, lgtm, size/XS

#9185 Reconfigure admin console after certificates were redeployed
  playbooks/openshift-console/private/redeploy-certificates.yml
  playbooks/redeploy-certificates.yml
Labels: approved, lgtm, size/M

#9136 Replace node.js proxy with oauth-proxy
  roles/openshift_logging_defaults/defaults/main.yml
  roles/openshift_logging_kibana/tasks/main.yaml
  roles/openshift_logging_kibana/templates/kibana.j2
Labels: approved, lgtm, size/M

#8988 Add max-size to docker log opts
  roles/container_runtime/defaults/main.yml
Labels: approved, lgtm, size/XS

#9134 Use cluster-wide settings for registry URL and credentials as defaults for ASB
  roles/ansible_service_broker/vars/openshift-enterprise.yml
Labels: approved, lgtm, size/XS

#8957 [release-3.10] Add datagrid72 templates
  roles/openshift_examples/examples-sync.sh
  roles/openshift_examples/files/examples/v3.10/xpaas-streams/datagrid72-image-stream.json
  roles/openshift_examples/files/examples/v3.10/xpaas-templates/datagrid72-basic.json
  roles/openshift_examples/files/examples/v3.10/xpaas-templates/datagrid72-https.json
  roles/openshift_examples/files/examples/v3.10/xpaas-templates/datagrid72-mysql-persistent.json
  roles/openshift_examples/files/examples/v3.10/xpaas-templates/datagrid72-mysql.json
  roles/openshift_examples/files/examples/v3.10/xpaas-templates/datagrid72-partition.json
  roles/openshift_examples/files/examples/v3.10/xpaas-templates/datagrid72-postgresql-persistent.json
  roles/openshift_examples/files/examples/v3.10/xpaas-templates/datagrid72-postgresql.json
Labels: do-not-merge/hold, needs-ok-to-test, size/XXL

#8603 Add Prometheus scrape config for openshift-logging
  roles/openshift_prometheus/templates/prometheus.yml.j2
Labels: affects_3.10, affects_3.9, approved, lgtm, size/M

#9131 [release-3.9] Don't call check_available_rpms.yml when containeriazed installation
  roles/openshift_version/tasks/masters_and_nodes.yml
Labels: lgtm, size/XS

#9084 [RHDM-662] - Update RHDM templates on OCP and OSO
  roles/openshift_examples/examples-sync.sh
  roles/openshift_examples/files/examples/v3.10/xpaas-streams/rhdm70-image-streams.yaml
  roles/openshift_examples/files/examples/v3.10/xpaas-templates/rhdm70-full.yaml
  roles/openshift_examples/files/examples/v3.10/xpaas-templates/rhdm70-kieserver-basic-s2i.yaml
  roles/openshift_examples/files/examples/v3.10/xpaas-templates/rhdm70-kieserver-https-s2i.yaml
  roles/openshift_examples/files/examples/v3.10/xpaas-templates/rhdm70-kieserver.yaml
Labels: approved, lgtm, size/XL

#9169 Add support for OpenStack internal DNS
  playbooks/openstack/configuration.md
  playbooks/openstack/openshift-cluster/provision_resources.yml
  roles/openshift_openstack/defaults/main.yml
  roles/openshift_openstack/templates/heat_stack.yaml.j2
Labels: approved, lgtm, size/L

#9198 Rename console logoImageName -> branding
  roles/openshift_console/defaults/main.yml
  roles/openshift_console/files/console-config.yaml
  roles/openshift_console/tasks/install.yml
Labels: approved, lgtm, size/S

#9204 Adds openshift_fs_inotify_max_user_instances to the node tuned profile.
  roles/tuned/defaults/main.yml
  roles/tuned/templates/openshift-node/tuned.conf
Labels: approved, lgtm, size/XS

#9199 Adding aggregate rule for new user authorization
  roles/ansible_service_broker/tasks/install.yml
  roles/ansible_service_broker/templates/broker-user-auth.clusterrole.yaml.j2
Labels: approved, lgtm, size/S

#9200 switch imagestreams to registry.redhat.io
  roles/openshift_examples/files/examples/v3.11/image-streams/dotnet_imagestreams.json
  roles/openshift_examples/files/examples/v3.11/image-streams/image-streams-rhel7.json
  roles/openshift_examples/files/examples/v3.11/xpaas-streams/amq62-image-stream.json
  roles/openshift_examples/files/examples/v3.11/xpaas-streams/amq63-image-stream.json
  roles/openshift_examples/files/examples/v3.11/xpaas-streams/datagrid65-image-stream.json
  roles/openshift_examples/files/examples/v3.11/xpaas-streams/datagrid71-image-stream.json
  roles/openshift_examples/files/examples/v3.11/xpaas-streams/datavirt63-image-stream.json
  roles/openshift_examples/files/examples/v3.11/xpaas-streams/decisionserver62-image-stream.json
  roles/openshift_examples/files/examples/v3.11/xpaas-streams/decisionserver63-image-stream.json
  roles/openshift_examples/files/examples/v3.11/xpaas-streams/decisionserver64-image-stream.json
  roles/openshift_examples/files/examples/v3.11/xpaas-streams/eap-cd-image-stream.json
  roles/openshift_examples/files/examples/v3.11/xpaas-streams/eap64-image-stream.json
  roles/openshift_examples/files/examples/v3.11/xpaas-streams/eap70-image-stream.json
  roles/openshift_examples/files/examples/v3.11/xpaas-streams/eap71-image-stream.json
  roles/openshift_examples/files/examples/v3.11/xpaas-streams/fis-image-streams.json
  roles/openshift_examples/files/examples/v3.11/xpaas-streams/jws30-tomcat7-image-stream.json
  roles/openshift_examples/files/examples/v3.11/xpaas-streams/jws30-tomcat8-image-stream.json
  roles/openshift_examples/files/examples/v3.11/xpaas-streams/jws31-tomcat7-image-stream.json
  roles/openshift_examples/files/examples/v3.11/xpaas-streams/jws31-tomcat8-image-stream.json
  roles/openshift_examples/files/examples/v3.11/xpaas-streams/openjdk18-image-stream.json
  roles/openshift_examples/files/examples/v3.11/xpaas-streams/processserver63-image-stream.json
  roles/openshift_examples/files/examples/v3.11/xpaas-streams/processserver64-image-stream.json
  roles/openshift_examples/files/examples/v3.11/xpaas-streams/rhdm70-image-streams.yaml
  roles/openshift_examples/files/examples/v3.11/xpaas-streams/sso70-image-stream.json
  roles/openshift_examples/files/examples/v3.11/xpaas-streams/sso71-image-stream.json
  roles/openshift_examples/files/examples/v3.11/xpaas-streams/sso72-image-stream.json
Labels: approved, lgtm, size/XL

#9156 Add EAP CD imagestream and templates OS 3.9
  roles/openshift_examples/files/examples/v3.9/xpaas-streams/eap-cd-image-stream.json
  roles/openshift_examples/files/examples/v3.9/xpaas-templates/eap-cd-amq-persistent-s2i.json
  roles/openshift_examples/files/examples/v3.9/xpaas-templates/eap-cd-amq-s2i.json
  roles/openshift_examples/files/examples/v3.9/xpaas-templates/eap-cd-basic-s2i.json
  roles/openshift_examples/files/examples/v3.9/xpaas-templates/eap-cd-https-s2i.json
  roles/openshift_examples/files/examples/v3.9/xpaas-templates/eap-cd-mongodb-persistent-s2i.json
  roles/openshift_examples/files/examples/v3.9/xpaas-templates/eap-cd-mongodb-s2i.json
  roles/openshift_examples/files/examples/v3.9/xpaas-templates/eap-cd-mysql-persistent-s2i.json
  roles/openshift_examples/files/examples/v3.9/xpaas-templates/eap-cd-mysql-s2i.json
  roles/openshift_examples/files/examples/v3.9/xpaas-templates/eap-cd-postgresql-persistent-s2i.json
  roles/openshift_examples/files/examples/v3.9/xpaas-templates/eap-cd-postgresql-s2i.json
  roles/openshift_examples/files/examples/v3.9/xpaas-templates/eap-cd-sso-s2i.json
  roles/openshift_examples/files/examples/v3.9/xpaas-templates/eap-cd-third-party-db-s2i.json
  roles/openshift_examples/files/examples/v3.9/xpaas-templates/eap-cd-tx-recovery-s2i.json
Labels: lgtm, size/XXL

#9122 Use service name for heketi url
  roles/openshift_storage_glusterfs/tasks/glusterfs_common.yml
  roles/openshift_storage_glusterfs/templates/gluster-block-storageclass.yml.j2
  roles/openshift_storage_glusterfs/templates/glusterfs-storageclass.yml.j2
Labels: approved, lgtm, size/M

#9073 Add EAP CD 13 imagestream and templates to OS 3.10
  roles/openshift_examples/files/examples/v3.10/xpaas-streams/eap-cd-image-stream.json
  roles/openshift_examples/files/examples/v3.10/xpaas-templates/eap-cd-amq-persistent-s2i.json
  roles/openshift_examples/files/examples/v3.10/xpaas-templates/eap-cd-amq-s2i.json
  roles/openshift_examples/files/examples/v3.10/xpaas-templates/eap-cd-basic-s2i.json
  roles/openshift_examples/files/examples/v3.10/xpaas-templates/eap-cd-https-s2i.json
  roles/openshift_examples/files/examples/v3.10/xpaas-templates/eap-cd-mongodb-persistent-s2i.json
  roles/openshift_examples/files/examples/v3.10/xpaas-templates/eap-cd-mongodb-s2i.json
  roles/openshift_examples/files/examples/v3.10/xpaas-templates/eap-cd-mysql-persistent-s2i.json
  roles/openshift_examples/files/examples/v3.10/xpaas-templates/eap-cd-mysql-s2i.json
  roles/openshift_examples/files/examples/v3.10/xpaas-templates/eap-cd-postgresql-persistent-s2i.json
  roles/openshift_examples/files/examples/v3.10/xpaas-templates/eap-cd-postgresql-s2i.json
  roles/openshift_examples/files/examples/v3.10/xpaas-templates/eap-cd-sso-s2i.json
  roles/openshift_examples/files/examples/v3.10/xpaas-templates/eap-cd-third-party-db-s2i.json
  roles/openshift_examples/files/examples/v3.10/xpaas-templates/eap-cd-tx-recovery-s2i.json
Labels: approved, lgtm, size/XL

#9210 update the default oauth-proxy image for logging
  roles/openshift_logging_defaults/defaults/main.yml
Labels: approved, lgtm, size/XS

#9179 CLOUD-2699 remove EAP 7.0 templates
  roles/openshift_examples/files/examples/v3.10/xpaas-templates/eap70-amq-persistent-s2i.json
  roles/openshift_examples/files/examples/v3.10/xpaas-templates/eap70-amq-s2i.json
  roles/openshift_examples/files/examples/v3.10/xpaas-templates/eap70-basic-s2i.json
  roles/openshift_examples/files/examples/v3.10/xpaas-templates/eap70-https-s2i.json
  roles/openshift_examples/files/examples/v3.10/xpaas-templates/eap70-mongodb-persistent-s2i.json
  roles/openshift_examples/files/examples/v3.10/xpaas-templates/eap70-mongodb-s2i.json
  roles/openshift_examples/files/examples/v3.10/xpaas-templates/eap70-mysql-persistent-s2i.json
  roles/openshift_examples/files/examples/v3.10/xpaas-templates/eap70-mysql-s2i.json
  roles/openshift_examples/files/examples/v3.10/xpaas-templates/eap70-postgresql-persistent-s2i.json
  roles/openshift_examples/files/examples/v3.10/xpaas-templates/eap70-postgresql-s2i.json
  roles/openshift_examples/files/examples/v3.10/xpaas-templates/eap70-sso-s2i.json
  roles/openshift_examples/files/examples/v3.10/xpaas-templates/eap70-third-party-db-s2i.json
  roles/openshift_examples/files/examples/v3.10/xpaas-templates/eap70-tx-recovery-s2i.json
  roles/openshift_examples/files/examples/v3.11/xpaas-templates/eap70-amq-persistent-s2i.json
  roles/openshift_examples/files/examples/v3.11/xpaas-templates/eap70-amq-s2i.json
  roles/openshift_examples/files/examples/v3.11/xpaas-templates/eap70-basic-s2i.json
  roles/openshift_examples/files/examples/v3.11/xpaas-templates/eap70-https-s2i.json
  roles/openshift_examples/files/examples/v3.11/xpaas-templates/eap70-mongodb-persistent-s2i.json
  roles/openshift_examples/files/examples/v3.11/xpaas-templates/eap70-mongodb-s2i.json
  roles/openshift_examples/files/examples/v3.11/xpaas-templates/eap70-mysql-persistent-s2i.json
  roles/openshift_examples/files/examples/v3.11/xpaas-templates/eap70-mysql-s2i.json
  roles/openshift_examples/files/examples/v3.11/xpaas-templates/eap70-postgresql-persistent-s2i.json
  roles/openshift_examples/files/examples/v3.11/xpaas-templates/eap70-postgresql-s2i.json
  roles/openshift_examples/files/examples/v3.11/xpaas-templates/eap70-sso-s2i.json
  roles/openshift_examples/files/examples/v3.11/xpaas-templates/eap70-third-party-db-s2i.json
  roles/openshift_examples/files/examples/v3.11/xpaas-templates/eap70-tx-recovery-s2i.json
Labels: approved, lgtm, size/XXL

#9008 Add scaleup playbook and docs for OpenStack
  playbooks/openstack/configuration.md
  playbooks/openstack/openshift-cluster/configure-new-nodes.yml
Labels: approved, lgtm, size/L

#9212 don't sync extraneous files(e.g. readme,owners)
  roles/openshift_examples/examples-sync.sh
  roles/openshift_examples/files/examples/v3.11/db-templates/OWNERS
  roles/openshift_examples/files/examples/v3.11/db-templates/README.md
  roles/openshift_examples/files/examples/v3.11/db-templates/mysql-ephemeral-template.json
  roles/openshift_examples/files/examples/v3.11/db-templates/mysql-persistent-template.json
  roles/openshift_examples/files/examples/v3.11/image-streams/OWNERS
  roles/openshift_examples/files/examples/v3.11/image-streams/README.md
  roles/openshift_examples/files/examples/v3.11/quickstart-templates/OWNERS
  roles/openshift_examples/files/examples/v3.11/quickstart-templates/README.md
  roles/openshift_examples/files/examples/v3.11/quickstart-templates/cakephp-mysql-persistent.json
  roles/openshift_examples/files/examples/v3.11/quickstart-templates/cakephp-mysql.json
  roles/openshift_examples/files/examples/v3.11/quickstart-templates/django-postgresql-persistent.json
  roles/openshift_examples/files/examples/v3.11/quickstart-templates/django-postgresql.json
  roles/openshift_examples/files/examples/v3.11/quickstart-templates/jenkins-persistent-template.json
  roles/openshift_examples/files/examples/v3.11/quickstart-templates/nodejs-mongodb-persistent.json
  roles/openshift_examples/files/examples/v3.11/quickstart-templates/nodejs-mongodb.json
Labels: approved, lgtm, size/L

#9233 bug 1601307. replace oc_client_binary
  roles/openshift_logging_fluentd/tasks/main.yaml
Labels: affects_3.7, lgtm, size/XS

#9160 Update docker registry auth to idempotent
  roles/container_runtime/defaults/main.yml
  roles/container_runtime/tasks/package_crio.yml
  roles/container_runtime/tasks/registry_auth.yml
  roles/lib_utils/action_plugins/sanity_checks.py
  roles/lib_utils/library/docker_creds.py
  roles/openshift_control_plane/defaults/main.yml
  roles/openshift_control_plane/tasks/registry_auth.yml
  roles/openshift_facts/defaults/main.yml
  roles/openshift_node/defaults/main.yml
  roles/openshift_node/tasks/registry_auth.yml
Labels: approved, lgtm, size/L

#9213 Remove mentions of oo_hosts_containerized_managed_true group
  playbooks/container-runtime/private/setup_storage.yml
  test/tox-inventory.txt
Labels: approved, lgtm, size/XS

#9223 bug 1601606. Quote selector to make it valid json
  roles/openshift_logging_elasticsearch/templates/pvc.j2
Labels: lgtm, size/XS

#9226 [3.10] Backport inotify changes
  roles/tuned/defaults/main.yml
  roles/tuned/templates/openshift-node/tuned.conf
Labels: approved, lgtm, size/XS

#9232 Remove extra atomic checks
  roles/etcd/tasks/backup/backup.yml
  roles/openshift_excluder/tasks/main.yml
  roles/openshift_repos/tasks/main.yaml
  roles/os_firewall/tasks/firewalld.yml
  roles/os_firewall/tasks/iptables.yml
  roles/os_firewall/tasks/main.yml
Labels: approved, lgtm, size/M

#9237 Fix sanity checks for oreg_auth_user and oreg_auth_password
  roles/lib_utils/action_plugins/sanity_checks.py
Labels: approved, lgtm, size/XS

#9109 Use ansible 2.6
  .papr.sh
  README.md
  openshift-ansible.spec
  requirements.txt
  roles/ansible_service_broker/tasks/migrate.yml
  roles/lib_utils/callback_plugins/aa_version_requirement.py
  roles/openshift_health_checker/test/action_plugin_test.py
Labels: approved, lgtm, size/S

#9189 Add playbook to update reg-auth credentials
  playbooks/container-runtime/private/registry_auth.yml
  playbooks/openshift-master/private/registry_auth.yml
  playbooks/openshift-node/private/registry_auth.yml
  playbooks/updates/README.md
  playbooks/updates/registry_auth.yml
  roles/openshift_node/tasks/node_system_container.yml
  roles/openshift_node/tasks/node_system_container_install.yml
Labels: approved, lgtm, size/L

#9246 Fix ordering of etcd stop and mask
  roles/etcd/tasks/upgrade_static.yml
Labels: approved, lgtm, size/S

#9238 Wait for existing nodes to go Ready before approval
  roles/openshift_node/tasks/distribute_bootstrap.yml
Labels: approved, lgtm, size/S

#9207 glusterfs registry: bind PV to PVC so that default storageclass would be ignored
  roles/lib_utils/action_plugins/generate_pv_pvcs_list.py
Labels: approved, lgtm, size/XS

#7825 sdn: don't blow away all existing CNI plugins
  roles/openshift_sdn/files/sdn.yaml
Labels: approved, lgtm, size/XS

#9155 Remove openshift_docker_is_node_or_master - all masters and etcd hosts are now nodes
  playbooks/container-runtime/private/config.yml
  playbooks/container-runtime/private/setup_storage.yml
  roles/container_runtime/defaults/main.yml
Labels: approved, lgtm, size/S

#9229 Fix `cpu_limit` check in event router template
  roles/openshift_logging_eventrouter/templates/eventrouter-template.j2
Labels: approved, lgtm, size/XS

#9244 Remove alternative oreg vars and update logic
  DEPLOYMENT_TYPES.md
  roles/lib_utils/action_plugins/sanity_checks.py
  roles/openshift_control_plane/README.md
  roles/openshift_control_plane/defaults/main.yml
  roles/openshift_control_plane/tasks/upgrade.yml
  roles/openshift_examples/defaults/main.yml
  roles/openshift_facts/defaults/main.yml
  roles/openshift_hosted/defaults/main.yml
  roles/openshift_hosted_templates/defaults/main.yml
  roles/openshift_master_facts/tasks/main.yml
  roles/openshift_node/README.md
  roles/openshift_node/defaults/main.yml
Labels: approved, lgtm, size/M

#9163 Add OLM install scripts
  playbooks/common/private/components.yml
  playbooks/olm/config.yml
  playbooks/olm/private/config.yml
  playbooks/olm/private/roles
  roles/olm/defaults/main.yaml
  roles/olm/files/01-alm-operator.serviceaccount.yaml
  roles/olm/files/02-alm-operator.rolebinding.yaml
  roles/olm/files/03-clusterserviceversion.crd.yaml
  roles/olm/files/05-catalogsource.crd.yaml
  roles/olm/files/06-installplan.crd.yaml
  roles/olm/files/07-subscription.crd.yaml
  roles/olm/files/08-tectonicocs.configmap.yaml
  roles/olm/files/10-tectonicocs.catalogsource.yaml
  roles/olm/files/12-alm-operator.deployment.yaml
  roles/olm/files/13-catalog-operator.deployment.yaml
  roles/olm/files/14-alm-servicebroker.clusterservicebroker.yaml
  roles/olm/files/15-alm-servicebroker.service.yaml
  roles/olm/files/16-almservicebroker-client.secret.yaml
  roles/olm/files/17-alm-servicebroker.deployment.yaml
  roles/olm/files/18-upstreamcomponents.configmap.yaml
  roles/olm/files/19-upstreamcomponents.catalogsource.yaml
  roles/olm/meta/main.yaml
  roles/olm/tasks/install.yaml
  roles/olm/tasks/main.yaml
  roles/olm/tasks/remove.yaml
  roles/olm/tasks/remove_components.yaml
Labels: approved, lgtm, size/XXL

#9256 Support specifying the rolebinding name
  roles/lib_openshift/library/oc_adm_policy_group.py
  roles/lib_openshift/library/oc_adm_policy_user.py
  roles/lib_openshift/src/ansible/oc_adm_policy_group.py
  roles/lib_openshift/src/ansible/oc_adm_policy_user.py
  roles/lib_openshift/src/class/oc_adm_policy_group.py
  roles/lib_openshift/src/class/oc_adm_policy_user.py
  roles/lib_openshift/src/doc/policy_group
  roles/lib_openshift/src/doc/policy_user
Labels: approved, lgtm, size/M

#9234 Adapt role to latest version of cluster-monitoring-operator
  roles/openshift_cluster_monitoring_operator/defaults/main.yml
  roles/openshift_cluster_monitoring_operator/files/cluster-monitoring-operator.yaml
  roles/openshift_cluster_monitoring_operator/tasks/install.yaml
  roles/openshift_cluster_monitoring_operator/templates/cluster-monitoring-operator-config.j2
  roles/openshift_cluster_monitoring_operator/templates/cluster-monitoring-operator-deployment.j2
Labels: approved, lgtm, size/L

#9247 Set log-path = ~/openshift-ansible.log
  ansible.cfg
Labels: approved, lgtm, size/XS

#9251 update imagestreams from origin
  roles/openshift_examples/files/examples/v3.11/image-streams/image-streams-centos7.json
  roles/openshift_examples/files/examples/v3.11/image-streams/image-streams-rhel7.json
Labels: approved, lgtm, size/L

#9268 catalog: add RBAC rules for namespaced brokers
  roles/openshift_service_catalog/files/kubeservicecatalog_roles_bindings.yml
Labels: approved, lgtm, size/XS

#9280 Cope with OpenShift returning no value when an environment variable is an empty string
  roles/lib_openshift/library/oc_adm_registry.py
  roles/lib_openshift/library/oc_adm_router.py
  roles/lib_openshift/library/oc_env.py
  roles/lib_openshift/library/oc_scale.py
  roles/lib_openshift/library/oc_volume.py
  roles/lib_openshift/src/lib/deploymentconfig.py
Labels: approved, lgtm, size/M

#9249 AWS: use vpc name instead of cluster id when creating security groups
  roles/openshift_aws/tasks/security_group.yml
Labels: approved, lgtm, size/XS

#9279 add firewall rules for node exporter
  playbooks/azure/openshift-cluster/build_node_image.yml
Labels: sig/azure, size/XS

#9286 Add rc code to docker_creds module
  roles/lib_utils/library/docker_creds.py
Labels: approved, lgtm, size/XS

#9271 allow NFS to be used for registry without marking cluster unsupported
  roles/lib_utils/action_plugins/sanity_checks.py
  roles/openshift_hosted/tasks/registry_storage.yml
Labels: approved, lgtm, size/S

#9259 installer_checkpoint: filter out phases without title and start time in ansible 2.6
  playbooks/metrics-server/private/config.yml
  roles/installer_checkpoint/callback_plugins/installer_checkpoint.py
Labels: approved, lgtm, size/S

#8912 Update the OpenStack Cinder PV example
  playbooks/openstack/configuration.md
Labels: approved, lgtm, size/M

#9278 [BZ 1599241] Set UID,fsGroup and Linux options to cassandra RC's
  roles/openshift_metrics/tasks/install_cassandra.yaml
  roles/openshift_metrics/tasks/pre_install.yaml
  roles/openshift_metrics/templates/hawkular_cassandra_rc.j2
Labels: lgtm, size/M

#9296 Fix order for invoking the hostpath storage task for registry
  roles/openshift_hosted/tasks/registry.yml
  roles/openshift_hosted/tasks/registry_storage.yml
Labels: approved, lgtm, size/XS

#9270 Add boolean to uninstall for docker
  playbooks/adhoc/uninstall.yml
  playbooks/adhoc/uninstall_docker.yml
  playbooks/adhoc/uninstall_openshift.yml
Labels: approved, lgtm, size/XXL

#9308 When the node process is down, don't exit
  roles/openshift_node_group/files/sync.yaml
Labels: approved, lgtm, size/S

#9254 Remove evaluations if group vars are defined or not
  playbooks/init/evaluate_groups.yml
Labels: approved, lgtm, size/M

#9285 Add RollingUpdate strategy to dockergc deployment config
  roles/openshift_docker_gc/templates/dockergc-ds.yaml.j2
Labels: approved, lgtm, size/XS

#9295 Add cert expiry check to upgrades
  playbooks/common/openshift-cluster/upgrades/init.yml
  playbooks/common/openshift-cluster/upgrades/upgrade_scale_group.yml
  playbooks/common/openshift-cluster/upgrades/v3_10/upgrade_control_plane.yml
  playbooks/common/openshift-cluster/upgrades/v3_10/upgrade_nodes.yml
  playbooks/common/openshift-cluster/upgrades/v3_11/upgrade_control_plane.yml
  playbooks/common/openshift-cluster/upgrades/v3_11/upgrade_nodes.yml
  roles/lib_utils/library/openshift_cert_expiry.py
  roles/openshift_certificate_expiry/defaults/main.yml
  roles/openshift_certificate_expiry/tasks/main.yml
  roles/openshift_certificate_expiry/templates/cert-expiry-table.html.j2
Labels: approved, lgtm, size/M

#9304 Add FeatureGates for NamespacedServiceBrokers and CatalogRestrictions
  roles/openshift_service_catalog/defaults/main.yml
  roles/openshift_service_catalog/templates/api_server.j2
  roles/openshift_service_catalog/templates/controller_manager.j2
Labels: approved, lgtm, size/S

#9309 handle symlinks in openshift-ansible container image
  images/installer/root/usr/local/bin/run
Labels: approved, lgtm, size/XS

#9305 Default openshift_is_atomic to false for openshift_repos.
  roles/openshift_repos/tasks/main.yaml
Labels: approved, lgtm, size/XS

#9289 Remove kuryr documentation that tells user to disable registry creation
  playbooks/openstack/configuration.md
  playbooks/openstack/sample-inventory/group_vars/all.yml
Labels: approved, lgtm, size/S

#9242 [release-3.10] Add scaleup playbook and docs for OpenStack
  playbooks/openstack/configuration.md
  playbooks/openstack/openshift-cluster/configure-new-nodes.yml
Labels: approved, lgtm, size/L

#9318 Allow to autoname scale group instances
  roles/openshift_aws/tasks/scale_group.yml
Labels: approved, lgtm, size/S

#9322 Fedora: Install kernel-modules
  roles/openshift_storage_glusterfs/tasks/kernel_modules.yml
Labels: approved, lgtm, size/XS

#9325 Disable papr on pull requests
  .papr.yml
Labels: approved, lgtm, size/XS

#9326 Fix glusterfs storageclass heketi url
  roles/openshift_storage_glusterfs/templates/glusterfs-storageclass.yml.j2
Labels: approved, lgtm, size/XS

#9164 [release-3.9] [Bug 1558689] Add hostname package to RHEL image
  images/installer/Dockerfile.rhel7
Labels: lgtm, size/XS

#9327 Switch to openshift-node-config in prep for removing openshift start node
  roles/openshift_node_group/files/sync.yaml
Labels: approved, lgtm, size/XS

#9298 How to deploy the cluster autoscaler
  playbooks/openshift-cluster-autoscaler/README.md
Labels: approved, lgtm, size/L

#9337 [Bug 1583530] [release-3.6] Set etcd_ca_host_group for embedded etcd
  roles/openshift_etcd_facts/defaults/main.yml
Labels: approved, lgtm, size/XS

#9243 Add OpenStack master and node scaleup
  playbooks/openstack/configuration.md
  playbooks/openstack/inventory.py
  playbooks/openstack/openshift-cluster/configure-new-nodes.yml
  playbooks/openstack/openshift-cluster/evaluate_groups.yml
  playbooks/openstack/openshift-cluster/install.yml
  playbooks/openstack/openshift-cluster/master-scaleup.yml
  playbooks/openstack/openshift-cluster/node-scaleup.yml
  playbooks/openstack/openshift-cluster/provision.yml
  playbooks/openstack/openshift-cluster/uninstall.yml
  playbooks/openstack/post-install.md
  roles/openshift_openstack/tasks/clean-dns.yml
  roles/openshift_openstack/tasks/create-registry-volume.yml
  roles/openshift_openstack/tasks/generate-dns.yml
  roles/openshift_openstack/tasks/populate-dns.yml
  roles/openshift_openstack/tasks/provision.yml
  roles/openshift_openstack/tasks/unprovision.yml
Labels: approved, lgtm, size/XL

#9236 re-enable 3.10 repos for OSA
  playbooks/azure/openshift-cluster/group_vars/all/yum_repos.yml
Labels: size/S

#9319 [3.10] Allow to autoname scale group instances
  roles/openshift_aws/tasks/scale_group.yml
Labels: approved, do-not-merge/hold, lgtm, size/S

#9294 AWS: reboot instance before sealing
  playbooks/aws/openshift-cluster/build_ami.yml
  playbooks/openshift-node/private/clean_image.yml
  roles/openshift_aws/tasks/reboot_instance.yml
Labels: approved, lgtm, size/M

#9357 Cleanup node bootstrap / scaleup code
  playbooks/azure/openshift-cluster/build_node_image.yml
  playbooks/init/evaluate_groups.yml
  playbooks/openshift-node/private/bootstrap.yml
  playbooks/openshift-node/private/certificates-backup.yml
  playbooks/openshift-node/private/certificates.yml
  playbooks/openshift-node/private/configure_bootstrap.yml
  playbooks/openshift-node/private/join.yml
  roles/openshift_node/tasks/distribute_bootstrap.yml
Labels: approved, lgtm, size/M

#9343 ignore failing dns clean errors when running openstack uninstall
  playbooks/openstack/openshift-cluster/uninstall.yml
Labels: approved, lgtm, size/XS

#9267 Updating how we get node names for logging hosts
  playbooks/openshift-logging/private/config.yml
Labels: approved, lgtm, size/S

#9355 [Bug 1609127] Add bool filter to all instances of openshift_use_crio
  playbooks/openshift-hosted/private/config.yml
  playbooks/openshift-hosted/private/install_docker_gc.yml
  playbooks/openshift-hosted/private/upgrade.yml
  roles/container_runtime/defaults/main.yml
  roles/openshift_control_plane/tasks/static_shim.yml
  roles/openshift_docker_gc/defaults/main.yml
  roles/openshift_facts/defaults/main.yml
  roles/openshift_node/defaults/main.yml
  roles/openshift_node/tasks/upgrade.yml
  roles/openshift_node/tasks/upgrade/restart.yml
  roles/openshift_node/tasks/upgrade/stop_services.yml
  roles/openshift_node/tasks/upgrade_pre.yml
  roles/openshift_node_group/defaults/main.yml
Labels: approved, lgtm, size/M

#7765 Allow disabling Network Manager managed dns
  roles/openshift_node/tasks/dnsmasq/network-manager.yml
Labels: approved, lgtm, size/S
