Repository openshift/openshift-ansible, pull requests merged in 2018-02, with the labels that each got.

#7087 persistent volume: fix template to support python3
  roles/openshift_persistent_volumes/templates/persistent-volume.yml.j2
Labels: lgtm, size/XS

#7088 Fix upgrade-control plane post_control_plane.yml
  playbooks/common/openshift-cluster/upgrades/post_control_plane.yml
Labels: lgtm, retest-not-required, size/XS

#7086 Pause for console rollout
  roles/openshift_web_console/tasks/install.yml
Labels: lgtm, size/S

#7078 Limit host scope during plays
  playbooks/container-runtime/config.yml
  playbooks/container-runtime/setup_storage.yml
  playbooks/init/main.yml
  playbooks/openshift-etcd/certificates.yml
  playbooks/openshift-etcd/config.yml
  playbooks/openshift-etcd/embedded2external.yml
  playbooks/openshift-etcd/migrate.yml
  playbooks/openshift-etcd/redeploy-ca.yml
  playbooks/openshift-etcd/redeploy-certificates.yml
  playbooks/openshift-etcd/restart.yml
  playbooks/openshift-etcd/scaleup.yml
  playbooks/openshift-etcd/upgrade.yml
  playbooks/openshift-glusterfs/config.yml
  playbooks/openshift-glusterfs/registry.yml
  playbooks/openshift-grafana/config.yml
  playbooks/openshift-hosted/config.yml
  playbooks/openshift-hosted/deploy_registry.yml
  playbooks/openshift-hosted/deploy_router.yml
  playbooks/openshift-hosted/redeploy-registry-certificates.yml
  playbooks/openshift-hosted/redeploy-router-certificates.yml
  playbooks/openshift-loadbalancer/config.yml
  playbooks/openshift-logging/config.yml
  playbooks/openshift-management/config.yml
  playbooks/openshift-metrics/config.yml
  playbooks/openshift-nfs/config.yml
  playbooks/openshift-prometheus/config.yml
  playbooks/openshift-provisioners/config.yml
  playbooks/openshift-service-catalog/config.yml
  playbooks/openshift-web-console/config.yml
  playbooks/prerequisites.yml
Labels: lgtm, size/L

#7093 Normalize the time we wait for pods to 5s * 60 retries
  roles/openshift_service_catalog/tasks/start_api_server.yml
  roles/openshift_web_console/tasks/install.yml
  roles/template_service_broker/tasks/install.yml
Labels: lgtm, size/S

#7001 Removing prefix, replacing with cidr, pool_start and pool_end vars
  playbooks/openstack/sample-inventory/group_vars/all.yml
  roles/openshift_openstack/defaults/main.yml
  roles/openshift_openstack/templates/heat_stack.yaml.j2
Labels: lgtm, size/M

#7105 additional mounts: specify 'type' in container_runtime_crio_additional_mounts
  roles/container_runtime/defaults/main.yml
Labels: size/XS

#7022 Verify that requested services have schedulable nodes matching the selectors
  roles/lib_utils/filter_plugins/oo_filters.py
  roles/openshift_facts/defaults/main.yml
  roles/openshift_logging_curator/tasks/main.yaml
  roles/openshift_logging_elasticsearch/tasks/main.yaml
  roles/openshift_logging_eventrouter/tasks/install_eventrouter.yaml
  roles/openshift_logging_kibana/tasks/main.yaml
  roles/openshift_logging_mux/tasks/main.yaml
  roles/openshift_metrics/tasks/install_cassandra.yaml
  roles/openshift_metrics/tasks/install_hawkular.yaml
  roles/openshift_metrics/tasks/install_heapster.yaml
  roles/openshift_metrics/tasks/install_hosa.yaml
  roles/openshift_prometheus/tasks/install_prometheus.yaml
  roles/openshift_provisioners/tasks/install_provisioners.yaml
  roles/openshift_service_catalog/tasks/install.yml
  roles/openshift_web_console/tasks/install.yml
  roles/template_service_broker/tasks/install.yml
Labels: lgtm, size/XL

#7099 Use r_etcd_common_etcdctl_command instead of hardcoded binary name to support containerized upgrade
  roles/etcd/defaults/main.yaml
Labels: lgtm, size/XS

#7073 Update user-data for FQDN instance hostnames
  roles/openshift_aws/templates/user_data.j2
  roles/openshift_node/files/bootstrap.yml
Labels: lgtm, retest-not-required, size/S

#6699 [openstack] custom user commands for cloud-init
  playbooks/openstack/advanced-configuration.md
  roles/openshift_openstack/defaults/main.yml
  roles/openshift_openstack/templates/user_data.j2
Labels: lgtm, size/M

#6476 Support master node high availability
  roles/kuryr/tasks/master.yaml
Labels: lgtm, size/XS

#7083 Backport changes for glusterfs and heketi template
  roles/openshift_storage_glusterfs/files/v3.6/deploy-heketi-template.yml
  roles/openshift_storage_glusterfs/files/v3.6/gluster-s3-pvcs-template.yml
  roles/openshift_storage_glusterfs/files/v3.6/gluster-s3-template.yml
  roles/openshift_storage_glusterfs/files/v3.6/glusterblock-provisioner.yml
  roles/openshift_storage_glusterfs/files/v3.6/glusterfs-template.yml
  roles/openshift_storage_glusterfs/files/v3.6/heketi-template.yml
  roles/openshift_storage_glusterfs/templates/v3.6/gluster-block-storageclass.yml.j2
  roles/openshift_storage_glusterfs/templates/v3.6/glusterfs-storageclass.yml.j2
  roles/openshift_storage_glusterfs/templates/v3.6/heketi.json.j2
Labels: lgtm, needs-ok-to-test, size/L

#7107 Add playbook to install components for cluster operator
  playbooks/cluster-operator/aws/components.yml
Labels: lgtm, retest-not-required, size/S

#7103 origin-dns: make sure cluster.local DNS server is listed first
  roles/openshift_node/files/networkmanager/99-origin-dns.sh
Labels: lgtm, size/XS

#7108 Disable console install when not 3.9 or newer
  playbooks/common/private/components.yml
Labels: lgtm, retest-not-required, size/XS

#6998 [3.7] Fix promethus for logging
  roles/openshift_logging_elasticsearch/tasks/main.yaml
  roles/openshift_logging_elasticsearch/templates/es.j2
  roles/openshift_logging_elasticsearch/templates/passwd.j2
Labels: lgtm, size/S

#7113 Fix etcd scaleup plays
  playbooks/openshift-etcd/scaleup.yml
  roles/lib_utils/action_plugins/sanity_checks.py
Labels: lgtm, size/S

#7119 etcd_scaleup: use inventory_hostname when etcd ca host is being picked
  roles/openshift_etcd_facts/tasks/set_etcd_ca_host.yml
Labels: lgtm, retest-not-required, size/XS

#7095 Add service catalog to be upgraded
  playbooks/common/openshift-cluster/upgrades/post_control_plane.yml
Labels: lgtm, size/XS

#7117 Fix gcp variable warnings
  roles/openshift_cloud_provider/tasks/gce.yml
Labels: lgtm, size/S

#7122 Add openshift_gcp_multizone bool
  roles/openshift_cloud_provider/defaults/main.yml
  roles/openshift_cloud_provider/tasks/gce.yml
  roles/openshift_gcp/defaults/main.yml
  roles/openshift_gcp/tasks/node_cloud_config.yml
Labels: lgtm, size/XS

#5251 Make node start options configurable
  roles/openshift_node/README.md
  roles/openshift_node/tasks/config/configure-node-settings.yml
Labels: lgtm, size/S

#6951 Fix OpenStack playbooks
  playbooks/openstack/openshift-cluster/install.yml
  playbooks/openstack/openshift-cluster/provision.yml
  roles/openshift_openstack/defaults/main.yml
Labels: lgtm, size/S

#7121 Invert logic to decide when to re-deploy certs
  playbooks/common/openshift-cluster/upgrades/post_control_plane.yml
Labels: lgtm, size/XS

#7116 Fix docker_upgrade variable
  playbooks/common/openshift-cluster/upgrades/docker/docker_upgrade.yml
  playbooks/common/openshift-cluster/upgrades/pre/config.yml
  roles/container_runtime/defaults/main.yml
  roles/container_runtime/tasks/docker_upgrade_check.yml
Labels: lgtm, size/S

#7106 Allow for blank StorageClass in PVC creation
  roles/lib_utils/action_plugins/generate_pv_pvcs_list.py
  roles/openshift_persistent_volumes/templates/persistent-volume-claim.yml.j2
Labels: lgtm, size/S

#6918 Uninstall playbook for Glusterfs
  playbooks/openshift-glusterfs/private/uninstall.yml
  playbooks/openshift-glusterfs/uninstall.yml
  roles/openshift_storage_glusterfs/tasks/glusterfs_config.yml
  roles/openshift_storage_glusterfs/tasks/glusterfs_config_facts.yml
  roles/openshift_storage_glusterfs/tasks/glusterfs_registry.yml
  roles/openshift_storage_glusterfs/tasks/glusterfs_registry_facts.yml
  roles/openshift_storage_glusterfs/tasks/glusterfs_uninstall.yml
  roles/openshift_storage_glusterfs/tasks/uninstall.yml
Labels: lgtm, size/L

#7130 Move installation of packages before container_runtime to ensure bind mounts are avaialable.
  roles/openshift_node/defaults/main.yml
  roles/openshift_node/tasks/bootstrap.yml
  roles/openshift_node/tasks/install_rpms.yml
Labels: lgtm, size/S

#7133 Adding missing template
  roles/openshift_logging_eventrouter/templates/2.x/eventrouter-template.j2
Labels: lgtm, size/L

#7143 Fix metadata access in OpenStack inventory
  playbooks/openstack/inventory.py
Labels: lgtm, size/XS

#7124 Fix version multi
  playbooks/common/openshift-cluster/upgrades/pre/config.yml
  playbooks/common/openshift-cluster/upgrades/pre/version_override.yml
  playbooks/common/openshift-cluster/upgrades/v3_9/upgrade_control_plane.yml
  playbooks/openshift-master/private/validate_restart.yml
  roles/openshift_version/defaults/main.yml
  roles/openshift_version/tasks/first_master.yml
  roles/openshift_version/tasks/first_master_containerized_version.yml
  roles/openshift_version/tasks/first_master_rpm_version.yml
  roles/openshift_version/tasks/masters_and_nodes.yml
Labels: lgtm, size/L

#7097 Whenever we create a new es node ignore health checks, changing prome…
  roles/openshift_logging/tasks/install_logging.yaml
  roles/openshift_logging_elasticsearch/tasks/main.yaml
  roles/openshift_logging_elasticsearch/tasks/restart_cluster.yml
  roles/openshift_logging_elasticsearch/tasks/restart_es_node.yml
Labels: affects_3.7, lgtm, size/M

#7155 Revert "Bug 1512825 - add mux pod failed for Serial number 02 has already been issued"
  roles/openshift_logging/tasks/generate_certs.yaml
  roles/openshift_logging/tasks/procure_server_certs.yaml
Labels: lgtm, size/XS

#7154 Changing conditional_set_fact from module to action_plugin
  roles/lib_openshift/action_plugins/conditional_set_fact.py
  roles/lib_openshift/library/conditional_set_fact.py
Labels: lgtm, size/L

#7125 Use curl --noproxy option for internal apiserver access
  roles/openshift_service_catalog/tasks/start_api_server.yml
Labels: lgtm, size/XS

#7137 Backports for Bug 1511870
  playbooks/common/openshift-cluster/initialize_facts.yml
  roles/openshift_facts/library/openshift_facts.py
Labels: lgtm, size/XS

#7150 Updating deprecation variable check to use a module for cleaner outpu…
  roles/openshift_sanitize_inventory/action_plugins/check_deprecated.py
  roles/openshift_sanitize_inventory/tasks/deprecations.yml
  roles/openshift_sanitize_inventory/tasks/main.yml
Labels: lgtm, size/M

#7160 [3.7] Whenever we create a new es node ignore health checks, changing prome…
  roles/openshift_logging/tasks/install_logging.yaml
  roles/openshift_logging_elasticsearch/tasks/main.yaml
  roles/openshift_logging_elasticsearch/tasks/restart_cluster.yml
  roles/openshift_logging_elasticsearch/tasks/restart_es_node.yml
Labels: backported_3.7, lgtm, size/M

#7148 Quick installer: update supported version
  utils/src/ooinstall/cli_installer.py
  utils/src/ooinstall/variants.py
Labels: lgtm, size/S

#7123 Correctly comparing against the current configmap when making es conf…
  roles/openshift_logging/tasks/patch_configmap_file.yaml
  roles/openshift_logging_elasticsearch/tasks/main.yaml
Labels: affects_3.7, lgtm, size/S

#7053 Adding ability to create files from contents
  roles/openshift_daemonset_config/README.md
  roles/openshift_daemonset_config/defaults/main.yml
  roles/openshift_daemonset_config/filter_plugins/config_filters.py
  roles/openshift_daemonset_config/tasks/main.yml
Labels: lgtm, size/L

#7084 Add vsphere section for openshift_node_kubelet_args_dict
  roles/openshift_node/defaults/main.yml
Labels: lgtm, retest-not-required, size/XS

#7013 Add cloud config variables to the sample inventory
  playbooks/openstack/sample-inventory/group_vars/all.yml
Labels: lgtm, size/XS

#7026 Run init/facts for docker upgrade
  playbooks/byo/openshift-cluster/upgrades/docker/upgrade.yml
  playbooks/common/openshift-cluster/upgrades/docker/docker_upgrade.yml
Labels: lgtm, size/M

#7190 Link to etcd v3 migration docs rather than suggesting dangerous things
  playbooks/common/openshift-cluster/upgrades/pre/verify_cluster.yml
Labels: size/XS

#7174 Fix undefined lib_utils_oo_random_word on release-3.7. #7173
  roles/openshift_logging_elasticsearch/tasks/main.yaml
Labels: lgtm, size/XS

#7180 [release-3.6] Backport #6215
  roles/openshift_facts/library/openshift_facts.py
  roles/openshift_facts/vars/default.yml
Labels: lgtm, size/XS

#7170 add steps in bootstrap playbook to handle updating aws.conf file
  playbooks/aws/provisioning-inventory.example.ini
  roles/openshift_node/tasks/bootstrap.yml
  roles/openshift_node/templates/bootstrap.yml.j2
Labels: lgtm, size/S

#7176 37 configmap patch cherrypick
  playbooks/common/openshift-cluster/config.yml
  roles/lib_openshift/action_plugins/conditional_set_fact.py
  roles/lib_openshift/library/conditional_set_fact.py
  roles/openshift_logging/filter_plugins/openshift_logging.py
  roles/openshift_logging/library/logging_patch.py
  roles/openshift_logging/library/openshift_logging_facts.py
  roles/openshift_logging/tasks/install_logging.yaml
  roles/openshift_logging/tasks/patch_configmap_file.yaml
  roles/openshift_logging/tasks/patch_configmap_files.yaml
  roles/openshift_logging/tasks/set_defaults_from_current.yml
  roles/openshift_logging_curator/tasks/main.yaml
  roles/openshift_logging_elasticsearch/tasks/main.yaml
  roles/openshift_logging_fluentd/tasks/main.yaml
  roles/openshift_logging_mux/tasks/main.yaml
  roles/openshift_metrics/tasks/install_cassandra.yaml
  roles/openshift_sanitize_inventory/action_plugins/check_deprecated.py
  roles/openshift_sanitize_inventory/library/check_deprecated.py
  roles/openshift_sanitize_inventory/library/conditional_set_fact.py
  roles/openshift_sanitize_inventory/meta/main.yml
  roles/openshift_sanitize_inventory/tasks/deprecations.yml
  roles/openshift_sanitize_inventory/tasks/main.yml
Labels: lgtm, size/XL

#7181 [1509853] Allow for overriding hosted registry_url variables
  playbooks/openshift-hosted/private/openshift_hosted_registry.yml
  playbooks/openshift-hosted/private/openshift_hosted_router.yml
  roles/openshift_facts/defaults/main.yml
  roles/openshift_hosted/defaults/main.yml
Labels: kind/bug, lgtm, size/S

#7028 kernel module loading fix
  playbooks/openshift-glusterfs/private/config.yml
  roles/openshift_storage_glusterfs/tasks/kernel_modules.yml
  roles/openshift_storage_glusterfs/templates/glusterfs.conf
  roles/openshift_storage_glusterfs/templates/glusterfs.conf.j2
Labels: lgtm, size/S

#7114 add uninstall playbooks for compute/infra scale groups
  playbooks/aws/openshift-cluster/uninstall_nodes.yml
  roles/openshift_aws/tasks/uninstall_launch_config.yml
  roles/openshift_aws/tasks/uninstall_node_group.yml
  roles/openshift_aws/tasks/uninstall_nodes.yml
  roles/openshift_aws/tasks/uninstall_scale_group.yml
Labels: lgtm, size/M

#7198 Add target mount for gluster block
  roles/openshift_storage_glusterfs/files/v3.10/glusterfs-template.yml
  roles/openshift_storage_glusterfs/files/v3.6/glusterfs-template.yml
  roles/openshift_storage_glusterfs/files/v3.7/glusterfs-template.yml
  roles/openshift_storage_glusterfs/files/v3.8/glusterfs-template.yml
  roles/openshift_storage_glusterfs/files/v3.9/glusterfs-template.yml
Labels: lgtm, size/S

#7080 Bug 1541946- waiting for master reboot now works behind bastion
  playbooks/openshift-master/private/tasks/restart_hosts.yml
Labels: lgtm, retest-not-required, size/S

#7187 Run openshift_version for image prep
  playbooks/init/version.yml
  playbooks/openshift-node/private/image_prep.yml
Labels: lgtm, size/XS

#7201 Tolerate OVS 2.6 in 3.10 as well
  roles/openshift_health_checker/openshift_checks/ovs_version.py
  roles/openshift_health_checker/openshift_checks/package_version.py
Labels: size/XS

#7152 hosts.example: openshift_dns_ip should be node-specific
  inventory/hosts.example
Labels: lgtm, size/S

#7182 Fix GlusterFS Hosted Registry - Deploy PersistentVolumeClaim definitions failure
  roles/openshift_persistent_volumes/templates/persistent-volume-claim.yml.j2
Labels: lgtm, retest-not-required, size/XS

#7179 CRI-O: use /var/run/crio/crio.sock for >=3.9
  roles/container_runtime/defaults/main.yml
  roles/container_runtime/templates/crio.conf.j2
  roles/openshift_node/defaults/main.yml
  roles/openshift_node/templates/node.yaml.v1.j2
Labels: lgtm, size/S

#7196 Adding file locking to yedit.
  roles/lib_openshift/library/oc_adm_ca_server_cert.py
  roles/lib_openshift/library/oc_adm_csr.py
  roles/lib_openshift/library/oc_adm_manage_node.py
  roles/lib_openshift/library/oc_adm_policy_group.py
  roles/lib_openshift/library/oc_adm_policy_user.py
  roles/lib_openshift/library/oc_adm_registry.py
  roles/lib_openshift/library/oc_adm_router.py
  roles/lib_openshift/library/oc_clusterrole.py
  roles/lib_openshift/library/oc_configmap.py
  roles/lib_openshift/library/oc_edit.py
  roles/lib_openshift/library/oc_env.py
  roles/lib_openshift/library/oc_group.py
  roles/lib_openshift/library/oc_image.py
  roles/lib_openshift/library/oc_label.py
  roles/lib_openshift/library/oc_obj.py
  roles/lib_openshift/library/oc_objectvalidator.py
  roles/lib_openshift/library/oc_process.py
  roles/lib_openshift/library/oc_project.py
  roles/lib_openshift/library/oc_pvc.py
  roles/lib_openshift/library/oc_route.py
  roles/lib_openshift/library/oc_scale.py
  roles/lib_openshift/library/oc_secret.py
  roles/lib_openshift/library/oc_service.py
  roles/lib_openshift/library/oc_serviceaccount.py
  roles/lib_openshift/library/oc_serviceaccount_secret.py
  roles/lib_openshift/library/oc_storageclass.py
  roles/lib_openshift/library/oc_user.py
  roles/lib_openshift/library/oc_version.py
  roles/lib_openshift/library/oc_volume.py
  roles/lib_openshift/src/lib/import.py
  roles/lib_utils/library/repoquery.py
  roles/lib_utils/library/yedit.py
  roles/lib_utils/src/class/yedit.py
  roles/lib_utils/src/lib/import.py
Labels: lgtm, size/L

#7200 Fix openshift-webconsole version check
  playbooks/common/private/components.yml
  playbooks/openshift-web-console/private/config.yml
Labels: lgtm, size/S

#7203 Change openshift.common.hostname to inventory_hostname
  playbooks/openshift-master/private/config.yml
Labels: lgtm, size/XS

#7064 Add prometheus reader role for lightweight privileges.
  roles/openshift_prometheus/defaults/main.yaml
  roles/openshift_prometheus/tasks/install_prometheus.yaml
Labels: lgtm, size/S

#7138 docker_image_availability: encode error message
  roles/openshift_health_checker/callback_plugins/zz_failure_summary.py
  roles/openshift_health_checker/openshift_checks/docker_image_availability.py
Labels: lgtm, retest-not-required, size/S

#7030 Update hosts.example to model minimum viable production cluster
  inventory/hosts.example
Labels: size/M

#7149 GlusterFS: Fix uninstall regression
  roles/openshift_storage_glusterfs/tasks/glusterfs_uninstall.yml
Labels: lgtm, size/XS

#7188 Add tox test to check for invalid playbook include
  playbooks/common/openshift-cluster/upgrades/v3_10/validator.yml
  playbooks/common/openshift-cluster/upgrades/v3_8/upgrade.yml
  playbooks/common/openshift-cluster/upgrades/v3_8/upgrade_control_plane.yml
  playbooks/common/openshift-cluster/upgrades/v3_8/validator.yml
  playbooks/common/openshift-cluster/upgrades/v3_9/validator.yml
  setup.py
Labels: lgtm, size/M

#7220 fixed an oo_filter plugin lib_utils_oo_has_no_matching_selector to do set comparison
  roles/lib_utils/filter_plugins/oo_filters.py
Labels: lgtm, size/XS

#7204 Create hawkular-metrics cluster role binding to watch namespaces
  roles/openshift_metrics/tasks/generate_rolebindings.yaml
  roles/openshift_metrics/templates/hawkular_metrics_role.j2
Labels: lgtm, size/M

#6970 Grafana roles updates.
  inventory/hosts.grafana.example
  roles/openshift_grafana/defaults/main.yml
  roles/openshift_grafana/files/grafana-ocp-oauth.yml
  roles/openshift_grafana/files/grafana-ocp.yml
  roles/openshift_grafana/files/openshift-cluster-monitoring.json
  roles/openshift_grafana/meta/main.yml
  roles/openshift_grafana/tasks/gf-permissions.yml
  roles/openshift_grafana/tasks/main.yml
Labels: lgtm, size/XXL

#7218 add deprovision playbook for cluster-operator infrastructure
  playbooks/cluster-operator/aws/uninstall_infrastructure.yml
Labels: lgtm, retest-not-required, size/S

#7222 Update API healthz check to use uri module
  roles/openshift_service_catalog/tasks/start_api_server.yml
Labels: lgtm, size/S

#7132 Log troubleshooting info when console install fails
  roles/openshift_web_console/tasks/install.yml
Labels: lgtm, size/M

#7171 Adding bootstrap during install/upgrade
  playbooks/common/openshift-cluster/upgrades/upgrade_control_plane.yml
  playbooks/openshift-master/enable_bootstrap.yml
  playbooks/openshift-master/private/config.yml
  playbooks/openshift-master/private/enable_bootstrap.yml
  playbooks/openshift-master/private/tasks/enable_bootstrap.yml
Labels: lgtm, size/M

#7169 Update CloudForms 4.6 templates for configmap mount and GA image location
  roles/openshift_examples/files/examples/v3.7/cfme-templates/cfme-backup-job.yaml
  roles/openshift_examples/files/examples/v3.7/cfme-templates/cfme-restore-job.yaml
  roles/openshift_examples/files/examples/v3.7/cfme-templates/cfme-template-ext-db.yaml
  roles/openshift_examples/files/examples/v3.7/cfme-templates/cfme-template.yaml
  roles/openshift_examples/files/examples/v3.9/cfme-templates/cfme-backup-job.yaml
  roles/openshift_examples/files/examples/v3.9/cfme-templates/cfme-restore-job.yaml
  roles/openshift_examples/files/examples/v3.9/cfme-templates/cfme-template-ext-db.yaml
  roles/openshift_examples/files/examples/v3.9/cfme-templates/cfme-template.yaml
  roles/openshift_management/files/templates/cloudforms/cfme-backup-job.yaml
  roles/openshift_management/files/templates/cloudforms/cfme-restore-job.yaml
  roles/openshift_management/files/templates/cloudforms/cfme-template-ext-db.yaml
  roles/openshift_management/files/templates/cloudforms/cfme-template.yaml
Labels: lgtm, size/L

#7067 [3.8] Revert "GlusterFS: Remove image option from heketi command"
  roles/openshift_storage_glusterfs/tasks/heketi_deploy_part2.yml
Labels: lgtm, size/XS

#7231 Revert openshift_portal_net
  roles/container_runtime/defaults/main.yml
Labels: lgtm, retest-not-required, size/XS

#7066 [3.7] Revert "GlusterFS: Remove image option from heketi command"
  roles/openshift_storage_glusterfs/tasks/heketi_deploy_part2.yml
Labels: lgtm, size/XS

#7228 skip search for an ami if openshift_aws_ami_map provides one
  roles/openshift_aws/tasks/build_node_group.yml
Labels: lgtm, size/XS

#7217 Adding ability to state absent array items with index/curr_value.
  roles/lib_openshift/library/oc_adm_ca_server_cert.py
  roles/lib_openshift/library/oc_adm_csr.py
  roles/lib_openshift/library/oc_adm_manage_node.py
  roles/lib_openshift/library/oc_adm_policy_group.py
  roles/lib_openshift/library/oc_adm_policy_user.py
  roles/lib_openshift/library/oc_adm_registry.py
  roles/lib_openshift/library/oc_adm_router.py
  roles/lib_openshift/library/oc_clusterrole.py
  roles/lib_openshift/library/oc_configmap.py
  roles/lib_openshift/library/oc_edit.py
  roles/lib_openshift/library/oc_env.py
  roles/lib_openshift/library/oc_group.py
  roles/lib_openshift/library/oc_image.py
  roles/lib_openshift/library/oc_label.py
  roles/lib_openshift/library/oc_obj.py
  roles/lib_openshift/library/oc_objectvalidator.py
  roles/lib_openshift/library/oc_process.py
  roles/lib_openshift/library/oc_project.py
  roles/lib_openshift/library/oc_pvc.py
  roles/lib_openshift/library/oc_route.py
  roles/lib_openshift/library/oc_scale.py
  roles/lib_openshift/library/oc_secret.py
  roles/lib_openshift/library/oc_service.py
  roles/lib_openshift/library/oc_serviceaccount.py
  roles/lib_openshift/library/oc_serviceaccount_secret.py
  roles/lib_openshift/library/oc_storageclass.py
  roles/lib_openshift/library/oc_user.py
  roles/lib_openshift/library/oc_version.py
  roles/lib_openshift/library/oc_volume.py
  roles/lib_utils/library/yedit.py
  roles/lib_utils/src/class/yedit.py
  roles/lib_utils/src/test/integration/yedit.yml
  roles/lib_utils/src/test/unit/test_yedit.py
Labels: lgtm, size/XXL

#7234 bug 1547348. Annotate ops projects with logging prefix
  roles/openshift_logging/tasks/annotate_ops_projects.yaml
Labels: affects_3.6, affects_3.7, lgtm, size/M

#7163 Fix for support multi-cluster heketi's topology
  roles/openshift_storage_glusterfs/templates/v1.5/topology.json.j2
  roles/openshift_storage_glusterfs/templates/v3.10/topology.json.j2
  roles/openshift_storage_glusterfs/templates/v3.6/topology.json.j2
  roles/openshift_storage_glusterfs/templates/v3.7/topology.json.j2
  roles/openshift_storage_glusterfs/templates/v3.8/topology.json.j2
  roles/openshift_storage_glusterfs/templates/v3.9/topology.json.j2
Labels: lgtm, size/S

#7244 Fix openshift_hosted_registry_storage_glusterfs_path
  roles/openshift_hosted/tasks/storage/glusterfs.yml
Labels: lgtm, retest-not-required, size/XS

#7233 Ensure wire-aggregator run on 3.7 upgrades
  playbooks/common/openshift-cluster/upgrades/v3_7/upgrade.yml
  playbooks/common/openshift-cluster/upgrades/v3_7/upgrade_control_plane.yml
Labels: lgtm, size/S

#7249 Fix upgrade verify_upgrade_targets
  playbooks/common/openshift-cluster/upgrades/pre/verify_upgrade_targets.yml
Labels: lgtm, size/XS

#6519 Don't log credentials pulled from inventory file
  playbooks/init/basic_facts.yml
  playbooks/init/version.yml
  roles/openshift_master/tasks/systemd_units.yml
Labels: lgtm, size/XS

#6640 added ci inventory and groups for containerized
  roles/openshift_health_checker/openshift_checks/docker_image_availability.py
  test/ci/install.sh
  test/ci/inventory/group_vars/OSEv3/general.yml
  test/ci/inventory/group_vars/all.yml
  test/ci/inventory/group_vars/containerized_hosts.yml
  test/ci/inventory/local_containerized.txt
Labels: lgtm, size/M

#7266 Normalize times we wait on pods to 10s * 60retries
  roles/openshift_hosted/tasks/wait_for_pod.yml
  roles/openshift_logging_elasticsearch/tasks/restart_es_node.yml
  roles/openshift_service_catalog/tasks/start_api_server.yml
  roles/openshift_web_console/tasks/install.yml
  roles/template_service_broker/tasks/install.yml
Labels: size/S

#7246 [1537872] Adding seboolean for virt_use_samba
  playbooks/openshift-master/private/config.yml
  playbooks/openshift-node/private/configure_nodes.yml
  playbooks/openshift-node/private/containerized_nodes.yml
  roles/openshift_cloud_provider/tasks/azure.yml
  roles/openshift_cloud_provider/tasks/main.yml
  roles/openshift_cloud_provider/vars/main.yml
Labels: lgtm, size/S

#7257 Fixing bz1540467 docker-registry env var migration. Adding ability to oc_edit complex array style edits.
  playbooks/common/openshift-cluster/upgrades/v3_9/upgrade_control_plane.yml
  roles/lib_openshift/library/oc_adm_ca_server_cert.py
  roles/lib_openshift/library/oc_adm_csr.py
  roles/lib_openshift/library/oc_adm_manage_node.py
  roles/lib_openshift/library/oc_adm_policy_group.py
  roles/lib_openshift/library/oc_adm_policy_user.py
  roles/lib_openshift/library/oc_adm_registry.py
  roles/lib_openshift/library/oc_adm_router.py
  roles/lib_openshift/library/oc_clusterrole.py
  roles/lib_openshift/library/oc_configmap.py
  roles/lib_openshift/library/oc_edit.py
  roles/lib_openshift/library/oc_env.py
  roles/lib_openshift/library/oc_group.py
  roles/lib_openshift/library/oc_image.py
  roles/lib_openshift/library/oc_label.py
  roles/lib_openshift/library/oc_obj.py
  roles/lib_openshift/library/oc_objectvalidator.py
  roles/lib_openshift/library/oc_process.py
  roles/lib_openshift/library/oc_project.py
  roles/lib_openshift/library/oc_pvc.py
  roles/lib_openshift/library/oc_route.py
  roles/lib_openshift/library/oc_scale.py
  roles/lib_openshift/library/oc_secret.py
  roles/lib_openshift/library/oc_service.py
  roles/lib_openshift/library/oc_serviceaccount.py
  roles/lib_openshift/library/oc_serviceaccount_secret.py
  roles/lib_openshift/library/oc_storageclass.py
  roles/lib_openshift/library/oc_user.py
  roles/lib_openshift/library/oc_version.py
  roles/lib_openshift/library/oc_volume.py
  roles/lib_openshift/src/ansible/oc_edit.py
  roles/lib_openshift/src/class/oc_edit.py
  roles/lib_openshift/src/doc/edit
  roles/lib_openshift/src/lib/base.py
  roles/openshift_hosted/tasks/migrate_default_registry_var.yml
Labels: lgtm, size/XL

#7235 Updating AMI copying tags to no longer default to parent AMI.
  roles/openshift_aws/defaults/main.yml
  roles/openshift_aws/tasks/seal_ami.yml
Labels: lgtm, size/S

#7232 Backporting storageclass changes to release-3.6 issue #5835.
  roles/lib_openshift/library/oc_storageclass.py
  roles/lib_openshift/src/ansible/oc_storageclass.py
Labels: lgtm, size/XS

#7243 Cast string to dict in lib_utils_oo_dict_to_keqv_list
  roles/lib_utils/filter_plugins/oo_filters.py
Labels: lgtm, size/S

#7240 refine condition for doing ami fetching
  roles/openshift_aws/tasks/build_node_group.yml
Labels: lgtm, size/XS

#7089 Remove NoVolumeNodeConflict from 3.9+
  roles/lib_utils/lookup_plugins/openshift_master_facts_default_predicates.py
  roles/lib_utils/test/openshift_master_facts_default_predicates_tests.py
  roles/openshift_master_facts/lookup_plugins/openshift_master_facts_default_predicates.py
  roles/openshift_master_facts/lookup_plugins/openshift_master_facts_default_priorities.py
Labels: lgtm, size/L

#7237 GlusterFS: Check for groups in template file
  roles/openshift_storage_glusterfs/templates/glusterfs.conf.j2
Labels: lgtm, size/XS

#7262 start_api_server: service catalog healthcheck doesn't require proxy
  roles/openshift_service_catalog/tasks/start_api_server.yml
Labels: size/XS

#7270 Fix aggregator relative paths
  playbooks/common/openshift-cluster/upgrades/v3_7/upgrade.yml
  playbooks/common/openshift-cluster/upgrades/v3_7/upgrade_control_plane.yml
Labels: lgtm, size/XS

#7264 Fix package tasks ordering in OpenStack playbooks
  playbooks/openstack/openshift-cluster/install.yml
  playbooks/openstack/openshift-cluster/provision.yml
Labels: lgtm, size/M

#7260 Changing default of openshift_logging_public_master_url to use opensh…
  roles/openshift_logging/defaults/main.yml
Labels: affects_3.7, lgtm, size/XS

#7239 Add field_selector parameter to oc_obj.
  roles/lib_openshift/library/oc_adm_ca_server_cert.py
  roles/lib_openshift/library/oc_adm_csr.py
  roles/lib_openshift/library/oc_adm_manage_node.py
  roles/lib_openshift/library/oc_adm_policy_group.py
  roles/lib_openshift/library/oc_adm_policy_user.py
  roles/lib_openshift/library/oc_adm_registry.py
  roles/lib_openshift/library/oc_adm_router.py
  roles/lib_openshift/library/oc_clusterrole.py
  roles/lib_openshift/library/oc_configmap.py
  roles/lib_openshift/library/oc_edit.py
  roles/lib_openshift/library/oc_env.py
  roles/lib_openshift/library/oc_group.py
  roles/lib_openshift/library/oc_image.py
  roles/lib_openshift/library/oc_label.py
  roles/lib_openshift/library/oc_obj.py
  roles/lib_openshift/library/oc_objectvalidator.py
  roles/lib_openshift/library/oc_process.py
  roles/lib_openshift/library/oc_project.py
  roles/lib_openshift/library/oc_pvc.py
  roles/lib_openshift/library/oc_route.py
  roles/lib_openshift/library/oc_scale.py
  roles/lib_openshift/library/oc_secret.py
  roles/lib_openshift/library/oc_service.py
  roles/lib_openshift/library/oc_serviceaccount.py
  roles/lib_openshift/library/oc_serviceaccount_secret.py
  roles/lib_openshift/library/oc_storageclass.py
  roles/lib_openshift/library/oc_user.py
  roles/lib_openshift/library/oc_version.py
  roles/lib_openshift/library/oc_volume.py
  roles/lib_openshift/src/ansible/oc_obj.py
  roles/lib_openshift/src/class/oc_obj.py
  roles/lib_openshift/src/doc/obj
  roles/lib_openshift/src/lib/base.py
Labels: lgtm, size/L

#7276 [BZ 1497408] delete config map, dameon set, and cluster role
  roles/openshift_metrics/tasks/uninstall_hosa.yaml
Labels: affects_3.7, lgtm, size/XS

#7272 check for empty string when installing ansible deps
  playbooks/common/openshift-cluster/initialize_facts.yml
Labels: lgtm, size/XS

#7250 Making patching a local_action and ensuring we become:false for local…
  README.md
  openshift-ansible.spec
  roles/openshift_logging/tasks/generate_jks.yaml
  roles/openshift_logging/tasks/main.yaml
  roles/openshift_logging/tasks/patch_configmap_file.yaml
Labels: affects_3.7, lgtm, size/M

#7280 Move journald setup to node tasks from master
  roles/openshift_master/defaults/main.yml
  roles/openshift_master/tasks/main.yml
  roles/openshift_master/tasks/upgrade.yml
  roles/openshift_node/defaults/main.yml
  roles/openshift_node/tasks/journald.yml
  roles/openshift_node/tasks/main.yml
  roles/openshift_node/tasks/upgrade.yml
Labels: lgtm, retest-not-required, size/M

#7267 Update glusterfs-template
  roles/openshift_storage_glusterfs/files/v1.5/glusterfs-template.yml
  roles/openshift_storage_glusterfs/files/v3.10/glusterfs-template.yml
  roles/openshift_storage_glusterfs/files/v3.6/glusterfs-template.yml
  roles/openshift_storage_glusterfs/files/v3.7/glusterfs-template.yml
  roles/openshift_storage_glusterfs/files/v3.8/glusterfs-template.yml
  roles/openshift_storage_glusterfs/files/v3.9/glusterfs-template.yml
Labels: lgtm, size/M

#7166 Block clean install of OCP 3.8 and upgrade to 3.9 only
  playbooks/byo/openshift-cluster/upgrades/README.md
  playbooks/byo/openshift-cluster/upgrades/v3_8/README.md
  playbooks/byo/openshift-cluster/upgrades/v3_8/upgrade.yml
  playbooks/byo/openshift-cluster/upgrades/v3_8/upgrade_control_plane.yml
  playbooks/byo/openshift-cluster/upgrades/v3_8/upgrade_nodes.yml
  playbooks/common/openshift-cluster/upgrades/upgrade_control_plane.yml
  playbooks/common/openshift-cluster/upgrades/v3_8/master_config_upgrade.yml
  playbooks/common/openshift-cluster/upgrades/v3_8/roles
  playbooks/common/openshift-cluster/upgrades/v3_8/upgrade.yml
  playbooks/common/openshift-cluster/upgrades/v3_8/upgrade_control_plane.yml
  playbooks/common/openshift-cluster/upgrades/v3_8/upgrade_nodes.yml
  roles/lib_utils/action_plugins/sanity_checks.py
  roles/lib_utils/library/repoquery.py
  roles/lib_utils/src/class/repoquery.py
  roles/openshift_version/tasks/check_available_rpms.yml
Labels: lgtm, retest-not-required, size/L

#7273 Dump verbose curl output and API logs when API doesn't become available.
  roles/openshift_master/tasks/check_master_api_is_ready.yml
  roles/openshift_master/tasks/main.yml
Labels: lgtm, size/M

#6963 Generic OS image/flavor check that verifies existence and compatibility
  roles/openshift_openstack/tasks/check-prerequisites.yml
  roles/openshift_openstack/tasks/custom_flavor_check.yaml
  roles/openshift_openstack/tasks/custom_image_check.yaml
  roles/openshift_openstack/tasks/image-and-flavor-check.yml
Labels: lgtm, size/M

#7226 [3.6] etcd migrate: instead of scaleup playbook etcd server should be started back
  playbooks/common/openshift-etcd/migrate.yml
Labels: lgtm, size/M

#7286 container-engine: support ADDTL_MOUNTS
  roles/container_runtime/defaults/main.yml
  roles/container_runtime/tasks/systemcontainer_docker.yml
Labels: lgtm, size/S

#7251 Add service catalog components to upgrade
  playbooks/common/openshift-cluster/upgrades/post_control_plane.yml
  playbooks/common/openshift-cluster/upgrades/upgrade_components.yml
  roles/template_service_broker/defaults/main.yml
  roles/template_service_broker/tasks/deploy.yml
  roles/template_service_broker/tasks/install.yml
  roles/template_service_broker/tasks/upgrade.yml
  roles/template_service_broker/vars/default_images.yml
  roles/template_service_broker/vars/main.yml
  roles/template_service_broker/vars/openshift-enterprise.yml
Labels: lgtm, size/L

#7256 Remove set_fact usage from web-console role
  roles/openshift_web_console/defaults/main.yml
  roles/openshift_web_console/tasks/install.yml
  roles/openshift_web_console/vars/default_images.yml
  roles/openshift_web_console/vars/main.yml
  roles/openshift_web_console/vars/openshift-enterprise.yml
Labels: lgtm, size/M

#7102 logging: allow fluentd to determine cri-o
  roles/openshift_logging/README.md
  roles/openshift_logging_fluentd/templates/2.x/fluentd.j2
Labels: lgtm, size/S

#7192 Bug 1536651 - logging-mux not working in 3.7.z when logging installed…
  roles/openshift_logging_fluentd/defaults/main.yml
Labels: lgtm, size/XS

#7259 Remove unused tasks upgrade_facts in openshift_master
  roles/openshift_master/tasks/upgrade_facts.yml
Labels: lgtm, size/M

#7271 refactor grafana role
  playbooks/openshift-grafana/private/config.yml
  playbooks/openshift-grafana/private/uninstall.yml
  playbooks/openshift-grafana/uninstall.yml
  roles/openshift_grafana/README.md
  roles/openshift_grafana/defaults/main.yaml
  roles/openshift_grafana/defaults/main.yml
  roles/openshift_grafana/files/dashboards/node-exporter-full-dashboard.json
  roles/openshift_grafana/files/dashboards/openshift-cluster-monitoring.json
  roles/openshift_grafana/meta/main.yml
  roles/openshift_grafana/tasks/facts.yaml
  roles/openshift_grafana/tasks/gf-permissions.yml
  roles/openshift_grafana/tasks/install_grafana.yaml
  roles/openshift_grafana/tasks/main.yaml
  roles/openshift_grafana/tasks/main.yml
  roles/openshift_grafana/tasks/uninstall_grafana.yaml
  roles/openshift_grafana/templates/grafana-config.yml.j2
  roles/openshift_grafana/templates/grafana.yml.j2
  roles/openshift_grafana/vars/default_images.yml
  roles/openshift_grafana/vars/openshift-enterprise.yml
Labels: lgtm, size/XXL

#7288 Remove no_log: True from openshift_version calls
  playbooks/init/version.yml
Labels: lgtm, size/XS

#7293 ntpd/chronyd will now be started before node/master services
  roles/openshift_loadbalancer/templates/haproxy.docker.service.j2
  roles/openshift_master/templates/docker-cluster/atomic-openshift-master-api.service.j2
  roles/openshift_master/templates/native-cluster/atomic-openshift-master-api.service.j2
  roles/openshift_node/templates/node.service.j2
  roles/openshift_node/templates/openshift.docker.node.service
Labels: lgtm, size/S

#7294 bug 1537857. Additional logging proxy metrics fixes
  roles/openshift_logging_elasticsearch/defaults/main.yml
  roles/openshift_logging_elasticsearch/tasks/main.yaml
  roles/openshift_logging_elasticsearch/templates/2.x/es.j2
  roles/openshift_logging_elasticsearch/templates/2.x/logging-metrics-role.j2
  roles/openshift_logging_elasticsearch/templates/2.x/logging-metrics-rolebinding.j2
  roles/openshift_logging_elasticsearch/templates/5.x/es.j2
  roles/openshift_logging_elasticsearch/templates/5.x/logging-metrics-role.j2
  roles/openshift_logging_elasticsearch/templates/5.x/logging-metrics-rolebinding.j2
Labels: affects_3.7, lgtm, size/L

#7096 vsphere svc fix upgrade and datastore fix
  playbooks/common/openshift-cluster/upgrades/upgrade_control_plane.yml
  roles/openshift_cloud_provider/files/vsphere-svc.yml
  roles/openshift_cloud_provider/tasks/vsphere-svc.yml
  roles/openshift_default_storage_class/defaults/main.yml
  roles/openshift_master/tasks/main.yml
  roles/openshift_master/tasks/update-vsphere.yml
Labels: lgtm, size/L

#7303 hosts.example: use 3.9 versions in sample inventory file
  inventory/hosts.example
Labels: lgtm, retest-not-required-docs-only, size/S

#7302 upgrade: skip restart during double upgrade
  playbooks/openshift-master/private/validate_restart.yml
Labels: lgtm, size/XS

#7236 bug 1547688. Annotate ops projects with prefix for data index
  roles/openshift_logging/tasks/annotate_ops_projects.yaml
Labels: affects_3.6, lgtm

#7223 Update controller port to match containerPort
  roles/openshift_service_catalog/tasks/install.yml
  roles/openshift_service_catalog/templates/controller_manager.j2
Labels: lgtm, size/S

#6924 Add prometheus node-exporter
  roles/openshift_prometheus/README.md
  roles/openshift_prometheus/defaults/main.yaml
  roles/openshift_prometheus/files/node-exporter-template.yaml
  roles/openshift_prometheus/tasks/install_node_exporter.yaml
  roles/openshift_prometheus/tasks/install_prometheus.yaml
  roles/openshift_prometheus/tasks/main.yaml
  roles/openshift_prometheus/vars/default_images.yml
  roles/openshift_prometheus/vars/main.yml
  roles/openshift_prometheus/vars/openshift-enterprise.yml
Labels: lgtm, size/L

#7291 Add GCS object storage to hosts.example
  inventory/hosts.example
Labels: lgtm, retest-not-required-docs-only, size/XS

#7308 Add inventory docs for gcp variables
  inventory/hosts.example
Labels: lgtm, size/XS

#7314 [bz 1508561] default to secure registry and update certificates
  playbooks/common/openshift-cluster/upgrades/post_control_plane.yml
Labels: lgtm, size/XS

#7315 Add support for instance_ids to ELB provisioner
  roles/openshift_aws/tasks/elb_single.yml
Labels: lgtm, size/XS

#7300 ansible-quiet.cfg: update callback_plugins path
  utils/etc/ansible-quiet.cfg
Labels: lgtm, size/XS
