Repository openshift/openshift-ansible, pull requests merged in 2018-12, with the labels that each got.

#10791 Added ovirt_admin variable to avoid use admin rights on RHV platform
  roles/openshift_ovirt/README.md
  roles/openshift_ovirt/tasks/build_vm_list.yml
Labels: approved, lgtm, size/S

#10789 Also set etcd_cert_config_dir for calico
  roles/calico/tasks/certs.yml
Labels: approved, size/XS

#10670 Fix Bug 1648832 - Hostname is configured as local-ipv4 in OpenStack
  roles/openshift_facts/library/openshift_facts.py
Labels: approved, lgtm, needs-ok-to-test, size/XS

#10812 Install boto3 from pip and use python-docker-py and use python-docker-py
  images/installer/Dockerfile
  playbooks/init/base_packages.yml
Labels: approved, size/XS

#10814 Run storage migration with fewer retries and longer delay
  playbooks/openshift-master/private/upgrade.yml
Labels: lgtm, size/XS

#10822 [3.9] Install boto3 from pip
  images/installer/Dockerfile
Labels: size/XS

#10821 [3.10] Install boto3 from pip and use python-docker-py and use python-docker-py
  images/installer/Dockerfile
  playbooks/init/base_packages.yml
Labels: approved, size/XS

#10806 glusterfs: bind-mount /dev/mapper into the glusterfs-server container
  roles/openshift_storage_glusterfs/files/glusterfs-template.yml
Labels: approved, lgtm, needs-ok-to-test, size/XS

#10829 Ensure OSE vars are not overwritten at the dynamic inventory
  playbooks/openstack/inventory.py
Labels: approved, lgtm, size/XS

#10833 Update Calico RBAC
  roles/calico_master/templates/calicov3.yml.j2
Labels: approved, lgtm, ok-to-test, size/S

#10763 Extend Openstack cloud provider LB parameters
  inventory/hosts.example
  roles/openshift_cloud_provider/defaults/main.yml
  roles/openshift_cloud_provider/templates/openstack.conf.j2
Labels: size/S

#10837 retries count increased on task
  roles/openshift_node_group/tasks/sync.yml
Labels: approved, lgtm, ok-to-test, size/XS

#10835 Use ansible 2.7.4
  images/installer/Dockerfile
  images/installer/origin-extra-root/etc/yum.repos.d/centos-ansible27.repo
Labels: approved, lgtm, size/XS

#10832 Update RBAC for Calico
  roles/calico/templates/calicov3.yml.j2
Labels: approved, lgtm, ok-to-test, size/S

#10742 [release-3.11] Call version.yml before repos.yml to ensure openshift_version is set
  roles/openshift_repos/meta/main.yml
  roles/openshift_repos/tasks/rhel_repos.yml
Labels: approved, lgtm, size/S

#10828 Ensure OSE vars are not overwritten at the dynamic inventory
  playbooks/openstack/resources.py
Labels: approved, lgtm, size/XS

#10843 Kuryr cleanups
  roles/kuryr/defaults/main.yaml
  roles/kuryr/templates/cni-daemonset.yaml.j2
  roles/kuryr/templates/controller-deployment.yaml.j2
Labels: approved, lgtm, size/M

#10805 openshift_ovirt: add vms into inventory groups
  roles/openshift_ovirt/README.md
  roles/openshift_ovirt/defaults/main.yml
  roles/openshift_ovirt/tasks/build_vm_list.yml
  roles/openshift_ovirt/tasks/create_all_in_one_inventory_from_vms.yaml
  roles/openshift_ovirt/tasks/create_inventory_from_vms.yaml
  roles/openshift_ovirt/tasks/create_vms.yaml
  roles/openshift_ovirt/tasks/main.yaml
  roles/openshift_ovirt/tasks/vms.j2
Labels: approved, lgtm, ok-to-test, size/L

#10809 Ensure openshift_upgrade_nodes_label works
  playbooks/common/openshift-cluster/upgrades/initialize_nodes_to_upgrade.yml
Labels: approved, lgtm, size/XS

#10831 Fix Calico liveness and readiness checks to include Calico 3.2
  roles/calico_master/tasks/main.yml
Labels: approved, lgtm, ok-to-test, size/XS

#10844 [release-3.9] Add better handling for Calico versions
  roles/calico_master/tasks/main.yml
Labels: lgtm, ok-to-test, size/XS

#10856 Handle audit log path in /var/log/origin
  roles/lib_utils/action_plugins/master_check_paths_in_config.py
  roles/lib_utils/test/test_master_check_paths_in_config.py
  roles/openshift_control_plane/tasks/main.yml
  roles/openshift_control_plane/tasks/static.yml
Labels: approved, lgtm, needs-ok-to-test, size/M

#10760 Dockerfile.rhel7: remove superfluous labels
  images/installer/Dockerfile.rhel7
Labels: size/XS

#10842 Install cifs-utils and samba required by Azure
  roles/openshift_node/defaults/main.yml
Labels: approved, lgtm, size/XS

#10858 Update Fuse templates with 7.2 release (3.10)
  roles/openshift_examples/examples-sync.sh
  roles/openshift_examples/files/examples/v3.10/xpaas-streams/fis-image-streams.json
  roles/openshift_examples/files/examples/v3.10/xpaas-templates/eap-camel-amq-template.json
  roles/openshift_examples/files/examples/v3.10/xpaas-templates/eap-camel-cdi-template.json
  roles/openshift_examples/files/examples/v3.10/xpaas-templates/eap-camel-cxf-jaxrs-template.json
  roles/openshift_examples/files/examples/v3.10/xpaas-templates/eap-camel-cxf-jaxws-template.json
  roles/openshift_examples/files/examples/v3.10/xpaas-templates/eap-camel-jpa-template.json
  roles/openshift_examples/files/examples/v3.10/xpaas-templates/fis-console-cluster-template.json
  roles/openshift_examples/files/examples/v3.10/xpaas-templates/fis-console-namespace-template.json
  roles/openshift_examples/files/examples/v3.10/xpaas-templates/fuse-apicurito.yml
  roles/openshift_examples/files/examples/v3.10/xpaas-templates/karaf-camel-amq-template.json
  roles/openshift_examples/files/examples/v3.10/xpaas-templates/karaf-camel-log-template.json
  roles/openshift_examples/files/examples/v3.10/xpaas-templates/karaf-camel-rest-sql-template.json
  roles/openshift_examples/files/examples/v3.10/xpaas-templates/karaf-cxf-rest-template.json
  roles/openshift_examples/files/examples/v3.10/xpaas-templates/spring-boot-camel-amq-template.json
  roles/openshift_examples/files/examples/v3.10/xpaas-templates/spring-boot-camel-config-template.json
  roles/openshift_examples/files/examples/v3.10/xpaas-templates/spring-boot-camel-drools-template.json
  roles/openshift_examples/files/examples/v3.10/xpaas-templates/spring-boot-camel-infinispan-template.json
  roles/openshift_examples/files/examples/v3.10/xpaas-templates/spring-boot-camel-rest-sql-template.json
  roles/openshift_examples/files/examples/v3.10/xpaas-templates/spring-boot-camel-teiid-template.json
  roles/openshift_examples/files/examples/v3.10/xpaas-templates/spring-boot-camel-template.json
  roles/openshift_examples/files/examples/v3.10/xpaas-templates/spring-boot-camel-xa-template.json
  roles/openshift_examples/files/examples/v3.10/xpaas-templates/spring-boot-camel-xml-template.json
  roles/openshift_examples/files/examples/v3.10/xpaas-templates/spring-boot-cxf-jaxrs-template.json
  roles/openshift_examples/files/examples/v3.10/xpaas-templates/spring-boot-cxf-jaxws-template.json
Labels: approved, lgtm, ok-to-test, size/XL

#10875 Install boto3 from pip
  images/installer/Dockerfile
  images/installer/origin-extra-root/etc/yum.repos.d/centos-ansible27.repo
  playbooks/init/base_packages.yml
Labels: approved, size/XS

#10884 Add openshift_node_group_name to hosts.example
  inventory/hosts.example
Labels: approved, lgtm, retest-not-required-docs-only, size/XS

#10857 Update Fuse templates with 7.2 release (3.11)
  roles/openshift_examples/examples-sync.sh
  roles/openshift_examples/files/examples/latest/xpaas-streams/fis-image-streams.json
  roles/openshift_examples/files/examples/latest/xpaas-templates/eap-camel-amq-template.json
  roles/openshift_examples/files/examples/latest/xpaas-templates/eap-camel-cdi-template.json
  roles/openshift_examples/files/examples/latest/xpaas-templates/eap-camel-cxf-jaxrs-template.json
  roles/openshift_examples/files/examples/latest/xpaas-templates/eap-camel-cxf-jaxws-template.json
  roles/openshift_examples/files/examples/latest/xpaas-templates/eap-camel-jpa-template.json
  roles/openshift_examples/files/examples/latest/xpaas-templates/fis-console-cluster-template.json
  roles/openshift_examples/files/examples/latest/xpaas-templates/fis-console-namespace-template.json
  roles/openshift_examples/files/examples/latest/xpaas-templates/fuse-apicurito.yml
  roles/openshift_examples/files/examples/latest/xpaas-templates/karaf-camel-amq-template.json
  roles/openshift_examples/files/examples/latest/xpaas-templates/karaf-camel-log-template.json
  roles/openshift_examples/files/examples/latest/xpaas-templates/karaf-camel-rest-sql-template.json
  roles/openshift_examples/files/examples/latest/xpaas-templates/karaf-cxf-rest-template.json
  roles/openshift_examples/files/examples/latest/xpaas-templates/spring-boot-camel-amq-template.json
  roles/openshift_examples/files/examples/latest/xpaas-templates/spring-boot-camel-config-template.json
  roles/openshift_examples/files/examples/latest/xpaas-templates/spring-boot-camel-drools-template.json
  roles/openshift_examples/files/examples/latest/xpaas-templates/spring-boot-camel-infinispan-template.json
  roles/openshift_examples/files/examples/latest/xpaas-templates/spring-boot-camel-rest-sql-template.json
  roles/openshift_examples/files/examples/latest/xpaas-templates/spring-boot-camel-teiid-template.json
  roles/openshift_examples/files/examples/latest/xpaas-templates/spring-boot-camel-template.json
  roles/openshift_examples/files/examples/latest/xpaas-templates/spring-boot-camel-xa-template.json
  roles/openshift_examples/files/examples/latest/xpaas-templates/spring-boot-camel-xml-template.json
  roles/openshift_examples/files/examples/latest/xpaas-templates/spring-boot-cxf-jaxrs-template.json
  roles/openshift_examples/files/examples/latest/xpaas-templates/spring-boot-cxf-jaxws-template.json
Labels: approved, lgtm, ok-to-test, size/XL

#10866 Extend logging-elasticsearch recreate param
  roles/openshift_logging_elasticsearch/templates/es.j2
Labels: approved, lgtm, size/XS

#10721 Maintain /var/lib/containers/storage mount during upgrades
  roles/openshift_node/files/clean-up-crio-pods.sh
Labels: approved, lgtm, size/XS

#10886 Check CVO status instead of particular operators
  playbooks/deploy_cluster_40.yml
Labels: approved, lgtm, size/M

#10799 Fix output of insecure registries in /etc/containers/registries.conf
  roles/container_runtime/templates/registries.conf.j2
Labels: approved, lgtm, size/XS

#10887 Recovering missing features that disappear with PR 10805
  roles/openshift_ovirt/README.md
  roles/openshift_ovirt/tasks/vms.j2
Labels: approved, lgtm, size/XS

#10896 sdn: exit when OVS crashes, tail logs
  roles/openshift_sdn/files/sdn-ovs.yaml
Labels: approved, lgtm, size/S

#10899 [release-3.10] Pass admin kubeconfig
  roles/openshift_control_plane/tasks/check_master_api_is_ready.yml
Labels: approved, lgtm, size/XS

#10895 40 scaleup
  playbooks/deploy_cluster_40.yml
  playbooks/init/basic_facts.yml
  playbooks/openshift-node/scaleup.yml
  test/libvirt/install-config.yml.template
  test/libvirt/installrc
  test/libvirt/node_scaleup.sh
  test/libvirt/terraform/config.tf
  test/libvirt/terraform/main.tf
  test/libvirt/terraform/terraform.tfvars.template
  test/libvirt/terraform/variables-libvirt.tf
Labels: approved, lgtm, size/L

#10906 Ensure multi pool driver can be disabled
  roles/kuryr/templates/configmap.yaml.j2
Labels: approved, lgtm, size/XS

#10901 40 Install node package names based on openshift_release
  roles/openshift_node40/tasks/install.yml
Labels: approved, lgtm, size/XS

#10913 [3.11] Fix CentOS repo version
  roles/openshift_repos/tasks/centos_repos.yml
Labels: approved, lgtm, size/XS

#10810 Erase docker during docker uninstall
  playbooks/adhoc/uninstall_docker.yml
Labels: approved, lgtm, size/XS

#10811 Add openshift_node_upgrade_pre_drain_hook
  HOOKS.md
  playbooks/common/openshift-cluster/upgrades/upgrade_nodes.yml
Labels: approved, lgtm, size/S

#10885 Collect bootkube logs if MCS failed to start
  inventory/dynamic/gcp/group_vars/all/00_defaults.yml
  playbooks/deploy_cluster_40.yml
Labels: approved, lgtm, size/M

#10701 Include Nuage OpenShift Monitors in Loadbalancer Config file
  playbooks/openshift-node/private/join.yml
  roles/nuage_master/meta/main.yml
  roles/nuage_master/tasks/etcd_certificates.yml
  roles/nuage_master/tasks/main.yaml
  roles/nuage_master/templates/nuage-master-config-daemonset.j2
  roles/nuage_master/templates/nuage-node-config-daemonset.j2
  roles/nuage_master/vars/main.yaml
  roles/nuage_node/meta/main.yml
  roles/nuage_node/tasks/main.yaml
  roles/openshift_loadbalancer/defaults/main.yml
Labels: approved, lgtm, ok-to-test, size/M

#10915 Added proper crio doc
  playbooks/openstack/configuration.md
Labels: approved, lgtm, size/L
