Repository openshift/openshift-ansible, pull requests merged in 2018-09, with the labels that each got.

#9048 Don't strip working set in Prometheus
  roles/openshift_prometheus/templates/prometheus.yml.j2
Labels: approved, lgtm, size/XS

#9783 [BZ 1620234] metrics clean up fails
  playbooks/common/openshift-cluster/openshift_metrics.yml
Labels: lgtm, size/XS

#9874 _idp['name'] not availabe
  roles/lib_utils/filter_plugins/openshift_master.py
Labels: approved, lgtm, size/XS

#9825 Fix loop item
  playbooks/ovirt/openshift-cluster/ovirt-vm-uninstall.yml
Labels: approved, lgtm, size/XS

#9877 Fix openshift_grafana prometheus serviceaccount default value in README
  roles/openshift_grafana/README.md
Labels: approved, lgtm, size/XS

#9873 crio: Don't use file locking
  roles/container_runtime/templates/crio.conf.j2
Labels: approved, lgtm, size/XS

#9889 Fix idp configuration when using a insecure LTPA provisioner
  roles/lib_utils/filter_plugins/openshift_master.py
Labels: approved, lgtm, size/XS

#9891 Updated packages in gold image and unsubscribe image
  playbooks/openstack/openshift-cluster/build_image.yml
Labels: approved, lgtm, size/S

#9870 Forcing full cluster restart to treat dcs as set
  roles/openshift_logging_elasticsearch/tasks/full_cluster_restart.yml
  roles/openshift_logging_elasticsearch/tasks/restart_cluster.yml
Labels: approved, lgtm, size/S

#9890 Configure repositories if RHEL
  playbooks/openstack/openshift-cluster/provision.yml
Labels: approved, lgtm, size/XS

#9880 Don't reset os_firewall_use_firewalld if iptables is inactive during upgrade
  playbooks/common/openshift-cluster/upgrades/init.yml
Labels: approved, lgtm, size/XS

#9898 Convert all remaining registry.access.redhat.com to registry.redhat.io
  README_CONTAINERIZED_INSTALLATION.md
  inventory/hosts.example
  roles/cockpit-ui/files/registry-console.yaml
  roles/lib_openshift/library/oc_adm_registry.py
  roles/lib_openshift/library/oc_adm_router.py
  roles/lib_openshift/src/ansible/oc_adm_router.py
  roles/lib_openshift/src/doc/registry
  roles/lib_openshift/src/doc/router
  roles/lib_openshift/src/test/unit/test_oc_adm_registry.py
  roles/lib_openshift/src/test/unit/test_oc_adm_router.py
  roles/openshift_examples/files/examples/latest/cfme-templates/cfme-backup-job.yaml
  roles/openshift_examples/files/examples/latest/cfme-templates/cfme-restore-job.yaml
  roles/openshift_examples/files/examples/latest/cfme-templates/cfme-template-ext-db.yaml
  roles/openshift_examples/files/examples/latest/cfme-templates/cfme-template.yaml
  roles/openshift_examples/files/examples/latest/cfme-templates/httpd-configmap-generator-template.yaml
  roles/openshift_examples/files/examples/latest/cfme-templates/jboss-middleware-manager-template.yaml
  roles/openshift_examples/files/examples/latest/xpaas-streams/rhpam70-image-streams.yaml
  roles/openshift_health_checker/openshift_checks/docker_image_availability.py
  roles/openshift_health_checker/test/docker_image_availability_test.py
  roles/openshift_hosted/README.md
  roles/openshift_management/files/templates/cloudforms/httpd-configmap-generator-template.yaml
Labels: approved, lgtm, size/M

#9900 repair container_runtime_extra_storage var values
  playbooks/ovirt/inventory.example
Labels: approved, lgtm, size/XS

#9904 Fix etcdctl aliases on etcd hosts
  roles/etcd/templates/etcdctl.sh.j2
Labels: approved, lgtm, size/S

#9901 Removing azure publishing tooling.
  playbooks/azure/openshift-cluster/create_and_publish_offer.md
  playbooks/azure/openshift-cluster/create_and_publish_offer.yml
  playbooks/azure/openshift-cluster/group_vars/all/image_publish.yml
  playbooks/azure/openshift-cluster/templates/offer.yml.j2
  roles/lib_utils/library/oo_azure_rm_publish_image.py
  roles/lib_utils/library/oo_azure_rm_publish_image_facts.py
Labels: lgtm, size/XL

#9903 Update sync DS after control plane upgrade
  playbooks/openshift-master/private/upgrade.yml
Labels: approved, lgtm, size/XS

#9907 Add namespaced servicebrokers, serviceclasses and serviceplans to adm…
  roles/openshift_service_catalog/files/openshift_catalog_clusterroles.yml
Labels: approved, lgtm, size/XS

#9879 Fix incorrect reference to idp['name']
  roles/lib_utils/filter_plugins/openshift_master.py
Labels: approved, lgtm, size/XS

#9883 Configure a list of etcd cipher suites via `etcd_cipher_suites`
  inventory/hosts.example
  roles/etcd/defaults/main.yaml
  roles/etcd/templates/etcd.conf.j2
Labels: approved, lgtm, size/XS

#9888 Add support for ak/orgid at uninstall/scale
  playbooks/openstack/openshift-cluster/master-scaleup.yml
  playbooks/openstack/openshift-cluster/node-scaleup.yml
  playbooks/openstack/openshift-cluster/uninstall.yml
  playbooks/openstack/sample-inventory/group_vars/all.yml
Labels: approved, lgtm, size/S

#8885 GlusterFS: Fix registry.yml playbook
  playbooks/openshift-glusterfs/private/registry.yml
Labels: approved, lgtm, size/S

#9919 Fixing a typo s/Cound/Could/g noticed with an error getting CSR's app…
  roles/lib_openshift/library/oc_csr_approve.py
  roles/lib_openshift/test/test_oc_csr_approve.py
Labels: approved, lgtm, size/XS

#9911 Add failed_when to 'Remove the image stream tag' tasks
  roles/openshift_bootstrap_autoapprover/tasks/main.yml
  roles/openshift_node_group/tasks/sync.yml
  roles/openshift_sdn/tasks/main.yml
Labels: approved, lgtm, size/M

#9732 Add default node groups to support running cri-o runtime
  inventory/hosts.example
  playbooks/openshift-hosted/private/install_docker_gc.yml
  playbooks/openshift-hosted/private/upgrade.yml
  roles/openshift_docker_gc/defaults/main.yml
  roles/openshift_docker_gc/templates/dockergc-ds.yaml.j2
  roles/openshift_facts/defaults/main.yml
Labels: approved, lgtm, size/M

#9744 Add playbooks to provision AWS VMs for CI
  .dockerignore
  images/installer/root/usr/local/bin/entrypoint-provider
  inventory/.gitignore
  inventory/dynamic/aws/group_vars/all/.gitkeep
  test/ci/README.md
  test/ci/deprovision.yml
  test/ci/extra_vars/default.yml
  test/ci/install.sh
  test/ci/inventory/group_vars/OSEv3/checks.yml
  test/ci/inventory/group_vars/OSEv3/general.yml
  test/ci/inventory/group_vars/OSEv3/logging.yml
  test/ci/inventory/group_vars/OSEv3/vars.yml
  test/ci/inventory/group_vars/all.yml
  test/ci/inventory/group_vars/containerized_hosts.yml
  test/ci/inventory/host_vars/localhost.yml
  test/ci/inventory/local.txt
  test/ci/inventory/local_containerized.txt
  test/ci/launch.yml
  test/ci/template-inventory.j2
  test/ci/vars.yml.sample
Labels: approved, lgtm, size/L

#9864 Update olm images to use openshift registry instead of quay
  roles/olm/defaults/main.yaml
  roles/olm/files/aggregated-edit.clusterrole.yaml
  roles/olm/files/aggregated-view.clusterrole.yaml
  roles/olm/files/catalogsource.crd.yaml
  roles/olm/files/clusterserviceversion.crd.yaml
  roles/olm/files/installplan.crd.yaml
  roles/olm/files/ocs.catalogsource.yaml
  roles/olm/files/ocs.configmap.yaml
  roles/olm/files/olm-operator.rolebinding.yaml
  roles/olm/files/olm-operator.serviceaccount.yaml
  roles/olm/files/subscription.crd.yaml
  roles/olm/tasks/install.yaml
  roles/olm/tasks/main.yaml
  roles/olm/tasks/remove_components.yaml
  roles/olm/templates/catalog-operator.deployment.j2
  roles/olm/templates/olm-operator.deployment.j2
Labels: approved, lgtm, size/M

#9910 openshift-aws: updating the subnet querying
  roles/openshift_aws/tasks/vpc_and_subnet_id.yml
Labels: approved, lgtm, size/XS

#9912 Add OLM to component upgrades
  playbooks/common/openshift-cluster/upgrades/upgrade_components.yml
Labels: approved, lgtm, size/XS

#9914 add OWNERS file for OLM
  playbooks/olm/OWNERS
  roles/olm/OWNERS
Labels: approved, lgtm, size/S

#9924 Use first_master_client_binary from hostvars[groups.oo_first_master.0]
  roles/openshift_storage_glusterfs/tasks/cluster_health.yml
Labels: approved, lgtm, size/XS

#9847 GlusterFS: Improve external cluster support
  playbooks/init/vars/cluster_hosts.yml
  playbooks/openshift-glusterfs/config.yml
  roles/openshift_hosted/tasks/registry.yml
  roles/openshift_storage_glusterfs/tasks/glusterfs_common.yml
  roles/openshift_storage_glusterfs/tasks/glusterfs_uninstall.yml
  roles/openshift_storage_glusterfs/templates/heketi-endpoints.yml.j2
Labels: approved, lgtm, size/L

#9927 openshifT_aws: removed subnet naming
  roles/openshift_aws/tasks/vpc.yml
Labels: approved, lgtm, size/XS

#9931 cluster-monitoring: Make PVCs optional
  roles/openshift_cluster_monitoring_operator/defaults/main.yml
  roles/openshift_cluster_monitoring_operator/templates/cluster-monitoring-operator-config.j2
Labels: approved, lgtm, size/XS

#9895 NSX-T fixes #8134 and fixes NSX #8015, PR #8016
  roles/lib_utils/action_plugins/sanity_checks.py
  roles/openshift_node/tasks/upgrade/stop_services.yml
Labels: approved, lgtm, size/XS

#9827 Refactor image health checks
  playbooks/openshift-hosted/private/cockpit-ui.yml
  roles/cockpit-ui/defaults/main.yml
  roles/cockpit-ui/tasks/install.yml
  roles/cockpit-ui/tasks/main.yml
  roles/openshift_health_checker/defaults/main.yml
  roles/openshift_health_checker/meta/main.yml
  roles/openshift_health_checker/openshift_checks/docker_image_availability.py
  roles/openshift_health_checker/test/docker_image_availability_test.py
Labels: approved, lgtm, size/XL

#9930 Fix issue with cockpit package list
  roles/cockpit/tasks/main.yml
Labels: approved, lgtm, size/XS

#9938 cluster-monitoring: Fix repo/docs URL
  roles/openshift_cluster_monitoring_operator/files/cluster-monitoring-operator.yaml
Labels: approved, lgtm, size/XS

#9946 Add extra debug info to csr module
  roles/lib_openshift/library/oc_csr_approve.py
  roles/lib_openshift/test/test_oc_csr_approve.py
Labels: approved, lgtm, size/L

#9862 OpenStack deployments without Floating IPs
  playbooks/openstack/configuration.md
  playbooks/openstack/sample-inventory/group_vars/all.yml
  roles/openshift_openstack/defaults/main.yml
  roles/openshift_openstack/templates/heat_stack.yaml.j2
Labels: approved, lgtm, size/L

#9951 Remove configmap check during upgrades
  playbooks/common/openshift-cluster/upgrades/init.yml
Labels: approved, lgtm, size/XS

#9876 Don't fetch provider openshift_facts if openshift_cloud_provider_kind is not set
  roles/openshift_facts/library/openshift_facts.py
Labels: approved, lgtm, size/XS

#9945 Revert ensure gquota set on slash filesystem
  playbooks/aws/openshift-cluster/build_ami.yml
  playbooks/openshift-node/private/clean_image.yml
Labels: approved, lgtm, priority/P0, queue/critical-fix, size/S

#9949 OLM fixes
  roles/olm/files/olm-operator.clusterrole.yaml
  roles/olm/files/olm-operator.rolebinding.yaml
  roles/olm/files/rh-operators.catalogsource.yaml
  roles/olm/files/rh-operators.configmap.yaml
  roles/olm/tasks/install.yaml
  roles/olm/tasks/main.yaml
Labels: approved, lgtm, size/XXL

#9958 fix ca cert deploy for 3.10 addresses bz 1585978
  playbooks/openshift-master/private/redeploy-openshift-ca.yml
Labels: approved, lgtm, size/XS

#9899 Add a playbook to remove etcd2 data
  playbooks/openshift-etcd/private/remove-etcdv2-data.yml
  playbooks/openshift-etcd/remove-etcdv2-data.yml
  roles/etcd/tasks/remove-etcd-v2-data.yml
Labels: approved, lgtm, size/M

#9957 Add oc_get_nodes to debug csr output
  roles/lib_openshift/library/oc_csr_approve.py
Labels: approved, lgtm, size/XS

#9961 olm: add openshift_facts dependency
  roles/olm/meta/main.yaml
Labels: approved, lgtm, size/XS

#9963 Install rh-operators catalog
  roles/olm/tasks/install.yaml
Labels: approved, lgtm, size/S

#9959 spec: remove roles/openshift_examples/latest symlink
  openshift-ansible.spec
Labels: approved, lgtm, size/XS

#9971 GlusterFS: Fix heketi_pod check
  roles/openshift_storage_glusterfs/tasks/heketi_deploy.yml
  roles/openshift_storage_glusterfs/tasks/heketi_init_db.yml
  roles/openshift_storage_glusterfs/tasks/heketi_init_deploy.yml
  roles/openshift_storage_glusterfs/tasks/heketi_load.yml
  roles/openshift_storage_glusterfs/tasks/heketi_pod_check.yml
  roles/openshift_storage_glusterfs/tasks/heketi_set_cli.yml
Labels: approved, lgtm, size/M

#9974 Add missing ClusterRole for OLM
  roles/olm/tasks/install.yaml
Labels: approved, lgtm, size/XS

#9970 GlusterFS: Tweak groups for external config
  playbooks/openshift-glusterfs/config.yml
  test/tox-inventory.txt
Labels: approved, lgtm, size/S

#9985 fix alertmanager example in OLM prometheus operator
  roles/olm/files/rh-operators.configmap.yaml
Labels: approved, lgtm, size/XS

#9851 SDN check: Ignore errors from `oc version`
  roles/openshift_health_checker/openshift_checks/sdn.py
Labels: approved, lgtm, size/XS

#9972 Prepare to split openshift-sdn out of the openshift binary
  roles/openshift_sdn/files/sdn.yaml
Labels: approved, lgtm, size/XS

#9979 cluster-monitoring: Fix incorrect handling of conditional PVCs
  roles/openshift_cluster_monitoring_operator/defaults/main.yml
  roles/openshift_cluster_monitoring_operator/templates/cluster-monitoring-operator-config.j2
Labels: approved, lgtm, size/XS

#9717 Allow specification of openshift_additional_registry_credentials
  roles/container_runtime/tasks/registry_auth.yml
  roles/lib_utils/library/docker_creds.py
  roles/openshift_control_plane/tasks/registry_auth.yml
  roles/openshift_examples/tasks/main.yml
  roles/openshift_facts/defaults/main.yml
  roles/openshift_node/tasks/registry_auth.yml
Labels: approved, lgtm, size/L

#9977 Fixes: BZ1618547 disable keep ns on error in ASB to prevent resource starvation
  roles/ansible_service_broker/defaults/main.yml
Labels: approved, lgtm, size/XS

#9998 cluster-monitoring: Remove version tag for passing image repos
  roles/openshift_cluster_monitoring_operator/defaults/main.yml
Labels: approved, lgtm, size/S

#9999 Revert "Don't fetch provider openshift_facts if openshift_cloud_provider_kind is not set"
  roles/openshift_facts/library/openshift_facts.py
Labels: approved, lgtm, size/XS

#10002 Set etcd facts necessary for etcd scaleup
  playbooks/openshift-etcd/private/scaleup.yml
Labels: approved, lgtm, size/S

#10004 Fix OLM installation
  roles/olm/files/catalogsource.crd.yaml
  roles/olm/files/clusterserviceversion.crd.yaml
  roles/olm/files/rh-operators.configmap.yaml
  roles/olm/templates/catalog-operator.deployment.j2
  roles/olm/templates/olm-operator.deployment.j2
Labels: approved, lgtm, size/XXL

#9975 Set gquota on slash filesystem
  playbooks/openshift-node/private/clean_image.yml
  roles/openshift_aws/defaults/main.yml
  roles/openshift_aws/tasks/set_gquota_for_slashfs.yml
Labels: approved, lgtm, size/M

#10011 cluster-monitoring: Fix regex_replace to remove image tag
  roles/openshift_cluster_monitoring_operator/defaults/main.yml
Labels: approved, lgtm, size/S

#9980 Merge back to release-3.11
  openshift-ansible.spec
  playbooks/aws/openshift-cluster/build_ami.yml
  playbooks/common/openshift-cluster/upgrades/init.yml
  playbooks/openshift-etcd/private/remove-etcdv2-data.yml
  playbooks/openshift-etcd/remove-etcdv2-data.yml
  playbooks/openshift-glusterfs/config.yml
  playbooks/openshift-master/private/redeploy-openshift-ca.yml
  playbooks/openshift-node/private/clean_image.yml
  playbooks/openstack/configuration.md
  playbooks/openstack/sample-inventory/group_vars/all.yml
  roles/ansible_service_broker/defaults/main.yml
  roles/etcd/tasks/remove-etcd-v2-data.yml
  roles/lib_openshift/library/oc_csr_approve.py
  roles/lib_openshift/test/test_oc_csr_approve.py
  roles/olm/meta/main.yaml
  roles/openshift_aws/defaults/main.yml
  roles/openshift_aws/tasks/set_gquota_for_slashfs.yml
  roles/openshift_health_checker/openshift_checks/sdn.py
  roles/openshift_openstack/defaults/main.yml
  roles/openshift_openstack/tasks/check-prerequisites.yml
  roles/openshift_openstack/templates/heat_stack.yaml.j2
  roles/openshift_sdn/files/sdn.yaml
  roles/openshift_storage_glusterfs/tasks/heketi_deploy.yml
  roles/openshift_storage_glusterfs/tasks/heketi_init_db.yml
  roles/openshift_storage_glusterfs/tasks/heketi_init_deploy.yml
  roles/openshift_storage_glusterfs/tasks/heketi_load.yml
  roles/openshift_storage_glusterfs/tasks/heketi_pod_check.yml
  roles/openshift_storage_glusterfs/tasks/heketi_set_cli.yml
  test/tox-inventory.txt
Labels: approved, lgtm, size/XL

#9784 Add playbook to migrate node imageConfig.format
  playbooks/common/openshift-cluster/upgrades/v3_11/upgrade_control_plane.yml
  playbooks/common/openshift-cluster/upgrades/v3_11/upgrade_control_plane_part1.yml
  playbooks/common/openshift-cluster/upgrades/v3_11/upgrade_control_plane_part2.yml
  playbooks/openshift-master/private/upgrade.yml
  playbooks/openshift-node/imageconfig.yml
  playbooks/openshift-node/private/imageconfig.yml
  playbooks/openshift-node/private/registry_auth.yml
  roles/openshift_control_plane/tasks/verify_api_server.yml
  roles/openshift_facts/defaults/main.yml
  roles/openshift_node/tasks/upgrade/stop_services.yml
  roles/openshift_node/tasks/upgrade_pre.yml
  roles/openshift_node_group/tasks/migrate_imageconfig.yml
Labels: approved, lgtm, size/L

#9984 Run the kube-proxy once per cluster for Calico
  roles/calico_master/meta/main.yml
  roles/calico_master/tasks/main.yml
Labels: approved, lgtm, size/XS

#9657 Update playbooks for Calico in OpenShift 3.10
  playbooks/openshift-node/private/join.yml
  roles/calico/tasks/main.yml
  roles/calico_master/templates/calicov3.yml.j2
Labels: approved, lgtm, size/S

#10023 [release-3.10]Do not stop and delete openvswitch when NSX is used #8015 and #8134
  roles/lib_utils/action_plugins/sanity_checks.py
  roles/openshift_node/tasks/upgrade/config_changes.yml
  roles/openshift_node/tasks/upgrade/stop_services.yml
Labels: approved, lgtm, size/S

#10008 Retry our etcd health check
  roles/etcd/tasks/remove-etcd-v2-data.yml
  roles/etcd/tasks/upgrade_rpm.yml
  roles/etcd/tasks/upgrade_static.yml
Labels: approved, lgtm, size/S

#10010 docker_creds: rename image_name to test_image
  roles/container_runtime/tasks/registry_auth.yml
  roles/lib_utils/library/docker_creds.py
  roles/openshift_control_plane/tasks/registry_auth.yml
  roles/openshift_facts/defaults/main.yml
  roles/openshift_node/tasks/registry_auth.yml
Labels: approved, lgtm, size/S

#9982 Add a pod template for recycler pod
  roles/openshift_control_plane/defaults/main.yml
  roles/openshift_control_plane/tasks/main.yml
  roles/openshift_control_plane/tasks/upgrade.yml
  roles/openshift_control_plane/templates/master.yaml.v1.j2
  roles/openshift_control_plane/templates/recycler_pod.yaml.j2
  roles/openshift_facts/library/openshift_facts.py
Labels: approved, lgtm, size/M

#10003 [openstack] Proper DNS for the subnet created in the build_image playbook
  playbooks/openstack/openshift-cluster/build_image.yml
Labels: approved, lgtm, size/XS

#9865 Add separate Calico etcd
  roles/calico_master/defaults/main.yaml
  roles/calico_master/tasks/certs.yml
  roles/calico_master/tasks/main.yml
  roles/calico_master/templates/calico-etcd.yml.j2
Labels: approved, lgtm, size/L

#10012 Add a wait for aggregated APIs when restarting control plane
  roles/openshift_control_plane/tasks/check_master_api_is_ready.yml
Labels: approved, size/M

#10018 Add proper liveness and readiness checks for Calico 3.2
  roles/calico_master/tasks/main.yml
  roles/calico_master/templates/calicov3.yml.j2
Labels: approved, lgtm, size/S

#10024 Collect provider facts only if cloudprovider is set
  playbooks/init/cluster_facts.yml
  roles/openshift_facts/library/openshift_facts.py
Labels: approved, lgtm, size/XS

#10025 Add preview operators to OLM Catalog
  roles/olm/files/certified-operators.catalogsource.yaml
  roles/olm/files/certified-operators.configmap.yaml
  roles/olm/files/rh-operators.configmap.yaml
  roles/olm/tasks/install.yaml
Labels: approved, lgtm, size/XXL

#10027 reducing /sys/fs/selinux/avc/cache_threshold to 8192 instead of 65535
  roles/tuned/templates/openshift/tuned.conf
Labels: approved, lgtm, size/XS

#9983 Annotate nodes with md5sum of the applied config after sync DS has updated configs
  roles/openshift_node_group/files/sync.yaml
  roles/openshift_node_group/tasks/sync.yml
Labels: approved, lgtm, size/M

#9964 Enable monitoring of openshift-metering via cluster monitoring
  roles/openshift_metering/defaults/main.yml
  roles/openshift_metering/files/monitoring/rbac/role.yaml
  roles/openshift_metering/files/monitoring/rbac/rolebinding.yaml
  roles/openshift_metering/files/monitoring/service-monitors/presto-service-monitor.yaml
  roles/openshift_metering/files/monitoring/service-monitors/reporting-operator-service-monitor.yaml
  roles/openshift_metering/tasks/monitoring-install.yml
  roles/openshift_metering/tasks/monitoring-uninstall.yml
  roles/openshift_metering/tasks/operator-install.yml
  roles/openshift_metering/tasks/operator-uninstall.yml
Labels: approved, lgtm, size/L

#10034 Update openshift ca redeploy to use correct node client-ca
  playbooks/openshift-master/private/redeploy-openshift-ca.yml
Labels: approved, lgtm, priority/P0, size/XS

#9989 Avoid S3 deployment check
  roles/openshift_storage_glusterfs/tasks/glusterfs_common.yml
Labels: approved, lgtm, size/S

#10040 Fix OpenStack parameter checks
  roles/openshift_openstack/tasks/check-prerequisites.yml
  roles/openshift_openstack/tasks/provision.yml
  roles/openshift_openstack/templates/heat_stack.yaml.j2
Labels: approved, lgtm, size/S

#9871 Run the kube-proxy once per cluster for Calico
  roles/calico_master/meta/main.yml
  roles/calico_master/tasks/main.yml
Labels: approved, lgtm, size/XS

#10048 [release-3.10] Update openshift ca redeploy to use correct node client-ca
  playbooks/openshift-master/private/redeploy-openshift-ca.yml
Labels: approved, lgtm, size/XS

#10033 Refactor csr approval for client certs ignore ready
  roles/lib_openshift/library/oc_csr_approve.py
  roles/lib_openshift/test/test_oc_csr_approve.py
Labels: approved, lgtm, size/M

#10046 Update sync daemonset annotation checks
  roles/openshift_manage_node/tasks/config.yml
  roles/openshift_node_group/tasks/sync.yml
Labels: approved, lgtm, size/S

#10038 [release-3.10] Retry our etcd health check
  roles/etcd/tasks/upgrade/upgrade_image.yml
  roles/etcd/tasks/upgrade/upgrade_rpm.yml
  roles/etcd/tasks/upgrade_static.yml
Labels: approved, lgtm, size/S

#10062 Fix volume recycler configuration on upgrade
  roles/openshift_control_plane/tasks/upgrade.yml
Labels: approved, lgtm, size/XS

#10063 certificate_expiry: gather facts so ansible_date_time is defined
  playbooks/openshift-checks/certificate_expiry/default.yaml
  playbooks/openshift-checks/certificate_expiry/easy-mode-upload.yaml
  playbooks/openshift-checks/certificate_expiry/easy-mode.yaml
  playbooks/openshift-checks/certificate_expiry/html_and_json_default_paths.yaml
  playbooks/openshift-checks/certificate_expiry/html_and_json_timestamp.yaml
  playbooks/openshift-checks/certificate_expiry/longer-warning-period-json-results.yaml
  playbooks/openshift-checks/certificate_expiry/longer_warning_period.yaml
Labels: approved, lgtm, priority/P0, size/XS

#10069 [3.10] ensure atomic and skopeo are installed
  roles/container_runtime/tasks/package_crio.yml
  roles/container_runtime/tasks/package_docker.yml
Labels: approved, lgtm, size/S

#10052 Removing launch.yml.
  playbooks/azure/openshift-cluster/launch.yml
Labels: approved, lgtm, size/L

#10056 openshift_storage_nfs_lvm: fix with_sequence
  roles/openshift_storage_nfs_lvm/tasks/nfs.yml
Labels: approved, lgtm, size/XS

#9947 [3.10] Refactor image health checks
  playbooks/openshift-hosted/private/cockpit-ui.yml
  roles/cockpit-ui/defaults/main.yml
  roles/cockpit-ui/tasks/install.yml
  roles/cockpit-ui/tasks/main.yml
  roles/openshift_health_checker/defaults/main.yml
  roles/openshift_health_checker/meta/main.yml
  roles/openshift_health_checker/openshift_checks/docker_image_availability.py
  roles/openshift_health_checker/test/docker_image_availability_test.py
Labels: approved, lgtm, size/XL

#10079 Add 3 retries around all image stream create/replace
  roles/openshift_examples/tasks/main.yml
Labels: approved, lgtm, size/S

#10077 [3.11] ensure sync DS is updated before draining masters
  playbooks/openshift-master/private/upgrade.yml
  roles/openshift_node_group/tasks/sync.yml
Labels: approved, lgtm, size/S

#10082 Ensure that recycler pod definition is deployed during upgrade
  roles/openshift_control_plane/tasks/upgrade.yml
Labels: approved, lgtm, priority/P0, size/XS

#9739 Add separate Calico etcd
  roles/calico_master/defaults/main.yaml
  roles/calico_master/tasks/certs.yml
  roles/calico_master/tasks/main.yml
  roles/calico_master/templates/calico-etcd.yml.j2
Labels: approved, lgtm, size/L

#10091 Hash the registry hostname to generate unique secret names
  roles/openshift_examples/tasks/main.yml
Labels: approved, lgtm, size/XS

#10090 Add retries around api service discovery
  roles/openshift_control_plane/tasks/check_master_api_is_ready.yml
Labels: approved, lgtm, size/S

#10068 Update uninstall_masters play to deal with standalone instances
  playbooks/aws/openshift-cluster/uninstall_masters.yml
  roles/openshift_aws/tasks/uninstall_ec2.yml
  roles/openshift_aws/tasks/uninstall_masters.yml
Labels: approved, lgtm, size/M

#9653 Add EAP 7.2.beta to v3.10
  roles/openshift_examples/files/examples/v3.10/xpaas-streams/eap72-image-stream.json
  roles/openshift_examples/files/examples/v3.10/xpaas-templates/eap72-basic-s2i.json
  roles/openshift_examples/files/examples/v3.10/xpaas-templates/eap72-https-s2i.json
  roles/openshift_examples/files/examples/v3.10/xpaas-templates/eap72-mongodb-persistent-s2i.json
  roles/openshift_examples/files/examples/v3.10/xpaas-templates/eap72-mongodb-s2i.json
  roles/openshift_examples/files/examples/v3.10/xpaas-templates/eap72-mysql-persistent-s2i.json
  roles/openshift_examples/files/examples/v3.10/xpaas-templates/eap72-mysql-s2i.json
  roles/openshift_examples/files/examples/v3.10/xpaas-templates/eap72-postgresql-persistent-s2i.json
  roles/openshift_examples/files/examples/v3.10/xpaas-templates/eap72-postgresql-s2i.json
  roles/openshift_examples/files/examples/v3.10/xpaas-templates/eap72-sso-s2i.json
  roles/openshift_examples/files/examples/v3.10/xpaas-templates/eap72-starter-s2i.json
  roles/openshift_examples/files/examples/v3.10/xpaas-templates/eap72-third-party-db-s2i.json
Labels: approved, lgtm, size/XXL

#9867 Add calico-pull-secret
  roles/calico_master/tasks/main.yml
  roles/calico_master/templates/calico-pull-secret.yml.j2
  roles/calico_master/templates/calicov3.yml.j2
Labels: approved, lgtm, size/M

#10098 make sure `openshift_use_nsx` is always defined during 3.9 -> 3.10 upgrade
  roles/openshift_node/tasks/upgrade/config_changes.yml
  roles/openshift_node/tasks/upgrade/stop_services.yml
Labels: approved, lgtm, size/XS

#10108 Don't install NM on atomic systems
  playbooks/openshift-node/private/network_manager.yml
Labels: approved, lgtm, size/XS

#10070 test/ci: setup network manager before prerequisites
  test/ci/launch.yml
  test/ci/vars.yml.sample
Labels: approved, lgtm, size/XS

#10112 Ensure dnsmasq is restarted during upgrades
  roles/openshift_node/tasks/upgrade.yml
Labels: approved, lgtm, priority/P0, size/S

#9916 Remove duplicate words
  examples/certificate-check-upload.yaml
  examples/certificate-check-volume.yaml
  inventory/hosts.example
  playbooks/openstack/configuration.md
  playbooks/openstack/openshift-cluster/master-scaleup.yml
  playbooks/openstack/openshift-cluster/node-scaleup.yml
  playbooks/openstack/openshift-cluster/provision.yml
  roles/lib_utils/action_plugins/master_check_paths_in_config.py
  roles/olm/files/clusterserviceversion.crd.yaml
  roles/openshift_management/defaults/main.yml
Labels: approved, lgtm, size/S

#10067 Fix broken package list on fedora
  playbooks/init/base_packages.yml
Labels: approved, lgtm, size/XS

#10129 [release-3.7] Ensure master facts are set during node scale-up
  playbooks/byo/openshift-node/scaleup.yml
Labels: lgtm, size/XS

#10125 Ensure atomic hosts prepull node image during pre-upgrade
  roles/openshift_node/handlers/main.yml
  roles/openshift_node/tasks/config.yml
  roles/openshift_node/tasks/copy_image_to_ostree.yml
  roles/openshift_node/tasks/main.yml
  roles/openshift_node/tasks/node_system_container.yml
  roles/openshift_node/tasks/prepull.yml
  roles/openshift_node/tasks/prepull_check.yml
  roles/openshift_node/tasks/systemd_units.yml
  roles/openshift_node/tasks/upgrade.yml
  roles/openshift_node/tasks/upgrade/config_changes.yml
  roles/openshift_node/tasks/upgrade_pre.yml
Labels: approved, lgtm, size/L

#10121 [3.11] upgrade: remove registry migration in 3.11
  playbooks/common/openshift-cluster/upgrades/v3_11/upgrade_control_plane_part2.yml
Labels: approved, lgtm, size/S

#10043 Fix wrong doc default value of logging
  roles/openshift_logging/README.md
Labels: approved, lgtm, size/XS

#10127 Make cloud-user SSH key maintenance more reliable
  roles/openshift_gcp/templates/provision_ssh.j2.sh
Labels: approved, lgtm, size/XS

#10131 Move OpenStack network fact gathering from prereqs to provision tasks
  roles/openshift_openstack/tasks/check-prerequisites.yml
  roles/openshift_openstack/tasks/provision.yml
Labels: approved, lgtm, size/M

#10107 openshift-prometheus: remove deprecated prometheus stack install
  inventory/hosts.example
  playbooks/cluster-operator/aws/components/openshift-prometheus.yml
  playbooks/common/private/components.yml
  playbooks/openshift-grafana/config.yml
  playbooks/openshift-grafana/private/config.yml
  playbooks/openshift-grafana/private/filter_plugins
  playbooks/openshift-grafana/private/lookup_plugins
  playbooks/openshift-grafana/private/roles
  playbooks/openshift-grafana/private/uninstall.yml
  playbooks/openshift-grafana/uninstall.yml
  playbooks/openshift-prometheus/OWNERS
  playbooks/openshift-prometheus/config.yml
  playbooks/openshift-prometheus/private/config.yml
  playbooks/openshift-prometheus/private/roles
  playbooks/openshift-prometheus/private/uninstall.yml
  playbooks/openshift-prometheus/uninstall.yml
  roles/openshift_grafana/README.md
  roles/openshift_grafana/defaults/main.yaml
  roles/openshift_grafana/files/dashboards/node-exporter-full-dashboard.json
  roles/openshift_grafana/files/dashboards/openshift-cluster-monitoring.json
  roles/openshift_grafana/meta/main.yml
  roles/openshift_grafana/tasks/facts.yaml
  roles/openshift_grafana/tasks/install_grafana.yaml
  roles/openshift_grafana/tasks/main.yaml
  roles/openshift_grafana/tasks/uninstall_grafana.yaml
  roles/openshift_grafana/templates/grafana-config.yml.j2
  roles/openshift_grafana/templates/grafana.yml.j2
  roles/openshift_prometheus/OWNERS
  roles/openshift_prometheus/README.md
  roles/openshift_prometheus/defaults/main.yaml
  roles/openshift_prometheus/files/node-exporter-template.yaml
  roles/openshift_prometheus/meta/main.yaml
  roles/openshift_prometheus/tasks/facts.yaml
  roles/openshift_prometheus/tasks/install_node_exporter.yaml
  roles/openshift_prometheus/tasks/install_prometheus.yaml
  roles/openshift_prometheus/tasks/main.yaml
  roles/openshift_prometheus/tasks/uninstall_prometheus.yaml
  roles/openshift_prometheus/templates/alertmanager.yml.j2
  roles/openshift_prometheus/templates/prometheus.j2
  roles/openshift_prometheus/templates/prometheus.rules.j2
  roles/openshift_prometheus/templates/prometheus.yml.j2
  roles/openshift_prometheus/tests/inventory
  roles/openshift_prometheus/tests/test.yaml
  roles/openshift_prometheus/vars/main.yml
  roles/openshift_sanitize_inventory/tasks/unsupported.yml
  test/ci/inventory/group_vars/OSEv3/vars.yml
Labels: approved, lgtm, size/XXL

#9674 Remove traces of containerized install
  playbooks/adhoc/uninstall_docker.yml
  playbooks/adhoc/uninstall_openshift.yml
  playbooks/common/openshift-cluster/upgrades/pre/verify_upgrade_targets.yml
  playbooks/init/basic_facts.yml
  roles/openshift_examples/defaults/main.yml
  roles/openshift_health_checker/openshift_checks/etcd_traffic.py
  roles/openshift_health_checker/test/etcd_traffic_test.py
  roles/openshift_loadbalancer/templates/haproxy.cfg.j2
Labels: approved, lgtm, size/M

#10138 Crio node groups bp 3.10
  inventory/hosts.example
  playbooks/openshift-hosted/private/install_docker_gc.yml
  playbooks/openshift-hosted/private/upgrade.yml
  roles/openshift_docker_gc/defaults/main.yml
  roles/openshift_docker_gc/templates/dockergc-ds.yaml.j2
  roles/openshift_facts/defaults/main.yml
Labels: approved, lgtm, size/M

#10146 [3.9] GlusterFS: Fix heketi URL in StorageClasses
  roles/openshift_storage_glusterfs/templates/v3.9/gluster-block-storageclass.yml.j2
  roles/openshift_storage_glusterfs/templates/v3.9/glusterfs-storageclass.yml.j2
Labels: lgtm, size/XS

#10141 Fix openshift_additional_registry_credentials comparison
  roles/container_runtime/tasks/registry_auth.yml
  roles/openshift_control_plane/tasks/registry_auth.yml
  roles/openshift_examples/tasks/main.yml
  roles/openshift_node/tasks/registry_auth.yml
Labels: approved, lgtm, priority/P0, size/S

#10136 [3.10] Ensure atomic hosts prepull node image during pre-upgrade
  roles/openshift_facts/defaults/main.yml
  roles/openshift_node/handlers/main.yml
  roles/openshift_node/tasks/config.yml
  roles/openshift_node/tasks/copy_image_to_ostree.yml
  roles/openshift_node/tasks/main.yml
  roles/openshift_node/tasks/node_system_container.yml
  roles/openshift_node/tasks/node_system_container_install.yml
  roles/openshift_node/tasks/prepull.yml
  roles/openshift_node/tasks/prepull_check.yml
  roles/openshift_node/tasks/systemd_units.yml
  roles/openshift_node/tasks/upgrade.yml
  roles/openshift_node/tasks/upgrade/config_changes.yml
  roles/openshift_node/tasks/upgrade_pre.yml
Labels: approved, lgtm, size/L

#10153 lib_utils_oo_oreg_image preserve path component
  roles/lib_utils/filter_plugins/oo_filters.py
Labels: approved, lgtm, size/XS

#10137 Ensure glusterfs host groups are correct for registry play
  playbooks/openshift-glusterfs/registry.yml
Labels: approved, lgtm, size/S

#10119 Fix Calico launch on multi-master cluster
  roles/calico_master/tasks/main.yml
Labels: approved, lgtm, size/XS

#10154 Add unit test for oo_oreg_image filter
  roles/lib_utils/test/test_oo_filters.py
Labels: approved, lgtm, size/M

#10168 adding container.yaml
  images/installer/container.yaml
Labels: approved, lgtm, size/S

#10149 Fix etcd scaleup playbook
  playbooks/openshift-etcd/private/remove-etcdv2-data.yml
  playbooks/openshift-etcd/private/scaleup.yml
  playbooks/openshift-etcd/private/server_certificates.yml
  playbooks/openshift-etcd/private/upgrade_rpm_members.yml
  playbooks/openshift-etcd/private/upgrade_static.yml
  roles/etcd/defaults/main.yaml
  roles/etcd/etcdctl.sh
  roles/etcd/tasks/add_new_member.yml
  roles/etcd/tasks/remove-etcd-v2-data.yml
  roles/etcd/tasks/static.yml
  roles/etcd/tasks/upgrade_rpm.yml
  roles/etcd/tasks/upgrade_static.yml
  roles/etcd/tasks/verify_cluster_health.yml
  roles/etcd/templates/etcdctl.sh.j2
  roles/installer_checkpoint/callback_plugins/installer_checkpoint.py
Labels: approved, lgtm, size/L

#10178 [3.11] remove unix prefix from crio path
  roles/openshift_facts/defaults/main.yml
Labels: approved, lgtm, size/XS

#10177 remove unix prefix from crio path
  roles/openshift_facts/defaults/main.yml
Labels: approved, lgtm, size/XS

#10124 Simplify match filter when looking for sync annotations
  roles/openshift_manage_node/tasks/config.yml
  roles/openshift_node_group/tasks/sync.yml
Labels: approved, lgtm, priority/P0, size/XS

#10180 Bump Data Grid to version 1.1.1 (release-3.10)
  roles/openshift_examples/examples-sync.sh
  roles/openshift_examples/files/examples/v3.10/xpaas-streams/datagrid72-image-stream.json
  roles/openshift_examples/files/examples/v3.10/xpaas-templates/datagrid72-basic.json
  roles/openshift_examples/files/examples/v3.10/xpaas-templates/datagrid72-https.json
  roles/openshift_examples/files/examples/v3.10/xpaas-templates/datagrid72-mysql-persistent.json
  roles/openshift_examples/files/examples/v3.10/xpaas-templates/datagrid72-mysql.json
  roles/openshift_examples/files/examples/v3.10/xpaas-templates/datagrid72-partition.json
  roles/openshift_examples/files/examples/v3.10/xpaas-templates/datagrid72-postgresql-persistent.json
  roles/openshift_examples/files/examples/v3.10/xpaas-templates/datagrid72-postgresql.json
Labels: approved, lgtm, size/L

#10179 Bump Data Grid to version 1.1.1 (master)
  roles/openshift_examples/examples-sync.sh
  roles/openshift_examples/files/examples/latest/xpaas-streams/datagrid72-image-stream.json
  roles/openshift_examples/files/examples/latest/xpaas-templates/datagrid72-basic.json
  roles/openshift_examples/files/examples/latest/xpaas-templates/datagrid72-https.json
  roles/openshift_examples/files/examples/latest/xpaas-templates/datagrid72-mysql-persistent.json
  roles/openshift_examples/files/examples/latest/xpaas-templates/datagrid72-mysql.json
  roles/openshift_examples/files/examples/latest/xpaas-templates/datagrid72-partition.json
  roles/openshift_examples/files/examples/latest/xpaas-templates/datagrid72-postgresql-persistent.json
  roles/openshift_examples/files/examples/latest/xpaas-templates/datagrid72-postgresql.json
Labels: approved, lgtm, size/XXL

#10171 Always set openstack node private ip
  playbooks/openstack/resources.py
Labels: approved, lgtm, size/S

#10191 [release-3.10] fix ca cert deploy for 3.10
  playbooks/openshift-master/private/redeploy-openshift-ca.yml
Labels: approved, lgtm, size/XS

#10185 [3.11] test/ci fixes
  playbooks/openshift-node/private/network_manager.yml
  test/ci/deprovision.yml
  test/ci/launch.yml
  test/ci/vars.yml.sample
Labels: approved, lgtm, size/M

#9863 Move cluster-cidr proxy argument to the node config
  roles/openshift_node_group/templates/node-config.yaml.j2
Labels: approved, lgtm, size/XS

#10174 Fix openstack nsupdate record
  roles/openshift_openstack/tasks/populate-dns.yml
Labels: approved, lgtm, size/XS

#10184 etcdv2 remove: avoid using failed_when
  roles/etcd/tasks/remove-etcd-v2-data.yml
Labels: approved, lgtm, size/XS

#10194 Don't re-deploy node system containers when deploying auth credentials
  playbooks/openshift-node/private/registry_auth.yml
Labels: approved, lgtm, size/XS

#10186 [3.10] - add test/ci playbooks
  .dockerignore
  images/installer/root/usr/local/bin/entrypoint-provider
  inventory/.gitignore
  inventory/dynamic/aws/group_vars/all/.gitkeep
  playbooks/openshift-node/private/network_manager.yml
  test/ci/README.md
  test/ci/deprovision.yml
  test/ci/extra_vars/default.yml
  test/ci/install.sh
  test/ci/inventory/group_vars/OSEv3/checks.yml
  test/ci/inventory/group_vars/OSEv3/general.yml
  test/ci/inventory/group_vars/OSEv3/logging.yml
  test/ci/inventory/group_vars/OSEv3/vars.yml
  test/ci/inventory/group_vars/all.yml
  test/ci/inventory/group_vars/containerized_hosts.yml
  test/ci/inventory/host_vars/localhost.yml
  test/ci/inventory/local.txt
  test/ci/inventory/local_containerized.txt
  test/ci/launch.yml
  test/ci/template-inventory.j2
  test/ci/vars.yml.sample
Labels: approved, lgtm, size/XL

#9939 [release-3.10] Add support for ak/orgid at uninstall
  playbooks/openstack/openshift-cluster/uninstall.yml
  playbooks/openstack/sample-inventory/group_vars/all.yml
Labels: approved, lgtm, size/S

#10166 GlusterFS: Fix registry playbook PV creation
  playbooks/openshift-glusterfs/private/registry.yml
  playbooks/openshift-hosted/private/openshift_hosted_registry_storage.yml
  roles/lib_utils/action_plugins/generate_pv_pvcs_list.py
  roles/openshift_facts/defaults/main.yml
  roles/openshift_persistent_volumes/tasks/main.yml
Labels: approved, lgtm, size/M

#9868 Add calico-pull-secret
  roles/calico_master/tasks/main.yml
  roles/calico_master/templates/calico-pull-secret.yml.j2
  roles/calico_master/templates/calicov3.yml.j2
Labels: approved, lgtm, size/M

#10215 Fix for recent az changes.
  playbooks/azure/openshift-cluster/tasks/create_blob_from_vm.yml
Labels: approved, lgtm, size/XS

#10130 Added capability to fix static addresses to openshift_ovirt provider vms
  playbooks/ovirt/provisioning-vars.yaml.example
  roles/openshift_ovirt/README.md
  roles/openshift_ovirt/tasks/build_vm_list.yml
Labels: approved, lgtm, size/L

#10220 cluster-monitoring: Bump cluster monitoring operator in origin
  roles/openshift_cluster_monitoring_operator/defaults/main.yml
Labels: approved, lgtm, size/XS

#10224 Enable IAM roles for EC2s in AWS
  playbooks/aws/openshift-cluster/prerequisites.yml
  playbooks/aws/openshift-cluster/provision_iam_role.yml
  roles/openshift_aws/defaults/main.yml
  roles/openshift_aws/tasks/build_node_group.yml
  roles/openshift_aws/tasks/iam_role.yml
  roles/openshift_aws/tasks/launch_config.yml
  roles/openshift_aws/tasks/provision_ec2.yml
  roles/openshift_aws/tasks/provision_ec2_facts.yml
Labels: approved, lgtm, size/M

#10165 [3.10] Backport setup_scale_group_facts changes from master
  inventory/dynamic/gcp/group_vars/all/00_defaults.yml
  playbooks/gcp/openshift-cluster/install.yml
  roles/openshift_gcp/tasks/setup_scale_group_facts.yml
Labels: approved, lgtm, size/S

#10226 Refactored Calico and updated playbooks to reflect self-hosted Calico installs only
  playbooks/openshift-master/private/config.yml
  playbooks/openshift-node/private/join.yml
  roles/calico/README.md
  roles/calico/defaults/main.yaml
  roles/calico/meta/main.yml
  roles/calico/tasks/certs.yml
  roles/calico/tasks/main.yml
  roles/calico/templates/calico-etcd.yml.j2
  roles/calico/templates/calico-pull-secret.yml.j2
  roles/calico/templates/calico.yml.j2
  roles/calico/templates/calicov3.yml.j2
  roles/calico_master/README.md
  roles/calico_master/tasks/main.yml
  roles/calico_node/README.md
  roles/calico_node/files/calico.conf
  roles/calico_node/meta/main.yml
  roles/calico_node/tasks/main.yml
Labels: approved, lgtm, size/L
