Repository openshift/openshift-ansible, pull requests merged in 2018-06, with the labels that each got.

#8512 Update Prometheus to scrape the router metrics
  roles/openshift_prometheus/tasks/install_prometheus.yaml
  roles/openshift_prometheus/tasks/uninstall_prometheus.yaml
  roles/openshift_prometheus/templates/prometheus.yml.j2
Labels: approved, lgtm, size/M

#8425 Avoid kuryr healthcheck ports collision
  roles/kuryr/defaults/main.yaml
  roles/kuryr/templates/cni-daemonset.yaml.j2
  roles/kuryr/templates/configmap.yaml.j2
  roles/kuryr/templates/controller-deployment.yaml.j2
Labels: approved, lgtm, size/S

#8604 Updating kibana proxy image to match reg url pattern of other components
  roles/openshift_logging_kibana/defaults/main.yml
Labels: approved, lgtm, size/XS

#8601 cri-o: If defaulting to openshift_release prefix it with v
  roles/container_runtime/defaults/main.yml
Labels: lgtm, size/XS

#8610 iSCSI: Start multipathd
  roles/openshift_node/tasks/storage_plugins/iscsi.yml
Labels: approved, lgtm, size/XS

#8600 Increase the delay between checking for image pull success
  roles/openshift_control_plane/tasks/main.yml
  roles/openshift_node/tasks/config.yml
  roles/openshift_node/tasks/node_system_container.yml
Labels: approved, lgtm, size/XS

#8592 Descheduler typo
  roles/openshift_descheduler/defaults/main.yaml
Labels: approved, lgtm, size/XS

#8612 Fix dockergc images
  roles/openshift_docker_gc/defaults/main.yml
  roles/openshift_docker_gc/meta/main.yml
Labels: approved, lgtm, size/XS

#8608 Check console pod readiness rather than /healthz endpoint
  roles/openshift_web_console/tasks/install.yml
Labels: lgtm, size/S

#8583 Initialise repos before installing packages
  playbooks/init/main.yml
  playbooks/prerequisites.yml
Labels: lgtm, size/XS

#8522 Updating logic when we are scaling up to skip health checks
  roles/openshift_logging_elasticsearch/tasks/full_cluster_restart.yml
  roles/openshift_logging_elasticsearch/tasks/restart_es_node.yml
  roles/openshift_logging_elasticsearch/tasks/rolling_cluster_restart.yml
Labels: approved, lgtm, size/M

#8559 Splitting output over using stdout_lines due to name formatting
  roles/openshift_logging_elasticsearch/tasks/restart_cluster.yml
Labels: approved, lgtm, size/M

#8609 container_runtime: do not depend on iptables when using firewalld
  roles/container_runtime/templates/systemcontainercustom.conf.j2
Labels: approved, lgtm, size/XS

#8615 crio-network: fix definition for systemd
  roles/container_runtime/templates/crio-network.j2
Labels: approved, lgtm, size/XS

#8625 Bug 1585648- Set timeout for ASB migration job
  roles/ansible_service_broker/tasks/migrate.yml
Labels: approved, lgtm, size/XS

#8627 Wait up to 10 minutes on image pulls
  roles/openshift_control_plane/tasks/main.yml
  roles/openshift_node/tasks/config.yml
  roles/openshift_node/tasks/node_system_container.yml
Labels: approved, size/S

#8628 Upgrade cri-o during node upgrade
  roles/openshift_node/tasks/upgrade.yml
  roles/openshift_node/tasks/upgrade_pre.yml
Labels: approved, lgtm, size/S

#8634 Don't verify java-1.8.0-openjdk
  images/installer/Dockerfile
  images/installer/Dockerfile.rhel7
Labels: approved, size/XS

#8532 Add option to pass OpenStack CA cert to Kuryr
  roles/kuryr/README.md
  roles/kuryr/tasks/master.yaml
  roles/kuryr/templates/certificates-secret.yaml.j2
  roles/kuryr/templates/configmap.yaml.j2
  roles/kuryr/templates/controller-deployment.yaml.j2
Labels: approved, lgtm, size/M

#8638 include tcpdump in azure images
  playbooks/azure/openshift-cluster/build_node_image.yml
Labels: approved, lgtm, size/XS

#8636 Only look for etcd pod on etcd hosts that are colocated w/ master
  roles/openshift_control_plane/tasks/main.yml
Labels: approved, lgtm, size/XS

#8637 Apply app label to console replica sets and pods
  roles/openshift_web_console/tasks/install.yml
Labels: approved, lgtm, size/XS

#8584 Fix OpenStack nsupdate zone handling
  playbooks/openstack/configuration.md
  playbooks/openstack/sample-inventory/group_vars/OSEv3.yml
  roles/openshift_openstack/defaults/main.yml
  roles/openshift_openstack/tasks/check-prerequisites.yml
  roles/openshift_openstack/tasks/clean-dns.yml
  roles/openshift_openstack/tasks/generate-dns.yml
  roles/openshift_openstack/tasks/populate-dns.yml
Labels: approved, lgtm, size/L

#8643 [release-3.9] Don't verify java-1.8.0-openjdk-headless
  images/installer/Dockerfile
  images/installer/Dockerfile.rhel7
Labels: size/XS

#8591 Make prometheus use persistent storage by default
  roles/openshift_cluster_monitoring_operator/defaults/main.yml
  roles/openshift_cluster_monitoring_operator/files/cluster-monitoring-operator.yaml
  roles/openshift_cluster_monitoring_operator/tasks/install.yaml
Labels: approved, lgtm, size/S

#8654 Bug 1586366 - Use include_tasks for dynamic task file includes
  roles/openshift_cloud_provider/tasks/main.yml
  roles/openshift_cloud_provider/tasks/vsphere.yml
Labels: approved, lgtm, size/XS

#8527 Make Kuryr connect to OpenShift API through LB
  playbooks/openstack/inventory.py
  roles/kuryr/README.md
  roles/kuryr/templates/configmap.yaml.j2
  roles/openshift_openstack/templates/heat_stack.yaml.j2
Labels: approved, lgtm, size/S

#8624 Fixing typo in openshift_metrics_cassandra_pvc_storage_class_name variable
  roles/openshift_metrics/tasks/generate_cassandra_pvcs.yaml
Labels: approved, lgtm, size/XS

#8645 Update ansible_service_broker_node_selector to new version
  roles/ansible_service_broker/defaults/main.yml
  roles/openshift_hosted/README.md
Labels: approved, lgtm, size/XS

#8655 Ensure repos only run during prerequisites.yml
  playbooks/init/repos.yml
  playbooks/prerequisites.yml
Labels: approved, lgtm, size/XS

#8657 azure: ensure cloud provider config is laid down in bootstrap node config
  playbooks/azure/openshift-cluster/build_node_image.yml
Labels: approved, lgtm, size/XS

#8658 azure: always build images using ssd-backed VM
  playbooks/azure/openshift-cluster/tasks/provision_instance.yml
Labels: approved, lgtm, sig/azure, size/XS

#8618 Install cri-tools and podman
  roles/container_runtime/tasks/package_crio.yml
Labels: approved, lgtm, size/XS

#8648 Remove openshift_dns_ip configuration, not valid in 3.10
  inventory/hosts.example
  roles/openshift_node/defaults/main.yml
  roles/openshift_node/files/networkmanager/99-origin-dns.sh
  roles/openshift_node/templates/node.yaml.v1.j2
Labels: approved, size/S

#8633 Do not force-terminate etcd
  roles/etcd/files/etcd.yaml
Labels: approved, lgtm, size/XS

#8653 dockergc: change image name to ose-control-plane
  roles/openshift_docker_gc/defaults/main.yml
Labels: approved, lgtm, size/XS

#8669 azure: add no_log: true to acs-engine deploy task
  playbooks/azure/openshift-cluster/launch.yml
Labels: approved, lgtm, size/XS

#8639 Force openshift_node_group_name for all nodes
  .papr-master-ha.inventory
  .papr.all-in-one.inventory
  .papr.inventory
  inventory/dynamic/gcp/group_vars/all/00_defaults.yml
  inventory/hosts.example
  inventory/hosts.glusterfs.registry-only.example
  inventory/hosts.glusterfs.storage-and-registry.example
  inventory/hosts.localhost
  inventory/hosts.openstack
  playbooks/common/openshift-cluster/upgrades/upgrade_nodes.yml
  playbooks/common/openshift-cluster/upgrades/v3_10/upgrade_control_plane.yml
  playbooks/init/sanity_checks.yml
  playbooks/openshift-master/private/config.yml
  playbooks/openshift-node/private/configure_bootstrap.yml
  roles/lib_utils/action_plugins/node_group_checks.py
  roles/openshift_facts/defaults/main.yml
  roles/openshift_gcp/defaults/main.yml
  roles/openshift_gcp/tasks/setup_scale_group_facts.yml
  roles/openshift_manage_node/tasks/config.yml
  roles/openshift_node/tasks/upgrade/bootstrap_changes.yml
  roles/openshift_node_group/defaults/main.yml
  roles/openshift_node_group/tasks/bootstrap.yml
  roles/openshift_node_group/tasks/bootstrap_config.yml
  roles/openshift_node_group/tasks/create_config.yml
  roles/openshift_node_group/tasks/main.yml
  roles/openshift_node_group/tasks/upgrade.yml
  roles/openshift_node_group/templates/node-config.yaml.j2
  roles/openshift_node_group/vars/main.yml
Labels: approved, lgtm, size/L

#8674 Check for undefined node_output.results
  playbooks/openshift-node/private/restart.yml
  roles/openshift_node/tasks/upgrade.yml
Labels: approved, size/S

#8676 Updating fluentd label and wait to be in a single shell
  roles/openshift_logging_fluentd/tasks/label_and_wait.yaml
  roles/openshift_logging_fluentd/tasks/main.yaml
  roles/openshift_logging_fluentd/templates/fluentd_label.sh.j2
Labels: affects_3.9, approved, lgtm, size/M

#8680 Add placeholder for openshift_node_group play
  playbooks/openshift-master/openshift_node_group.yml
Labels: approved, size/XS

#8673 Remove some items from vsphere cloud provider default call
  playbooks/openshift-master/private/additional_config.yml
  roles/openshift_cloud_provider/tasks/vsphere.yml
Labels: approved, lgtm, size/M

#8675 Add Luis Tomas to Kuryr and OpenStack owners
  playbooks/openstack/OWNERS
  roles/kuryr/OWNERS
Labels: approved, lgtm, size/XS

#8686 Remove podman from install it creates problems
  roles/container_runtime/tasks/package_crio.yml
Labels: approved, size/XS

#8462 [release-3.9] Updating process for doing a rolling and full cluster upgrades
  roles/openshift_logging/tasks/main.yaml
  roles/openshift_logging_elasticsearch/tasks/full_cluster_restart.yml
  roles/openshift_logging_elasticsearch/tasks/restart_cluster.yml
  roles/openshift_logging_elasticsearch/tasks/restart_es_node.yml
  roles/openshift_logging_elasticsearch/tasks/rolling_cluster_restart.yml
  roles/openshift_logging_elasticsearch/vars/main.yml
Labels: lgtm, size/XL

#8668 Fix multimaster OpenStack deployment failure
  playbooks/openstack/inventory.py
  roles/openshift_openstack/tasks/generate-dns.yml
Labels: approved, lgtm, size/S

#8656 allow node config sync controller to handle multiple node labels
  roles/openshift_node_group/files/sync.yaml
Labels: lgtm, sig/azure, size/XS

#8617 azure - do not tag node images as valid automatically
  playbooks/azure/openshift-cluster/build_base_image.yml
  playbooks/azure/openshift-cluster/build_node_image.yml
  playbooks/azure/openshift-cluster/launch.yml
  playbooks/azure/openshift-cluster/provisioning_vars.yml.example
  playbooks/azure/openshift-cluster/tag_image_as_valid.yml
  playbooks/azure/openshift-cluster/tasks/create_image_from_vm.yml
  playbooks/azure/openshift-cluster/tasks/provision_instance.yml
Labels: approved, lgtm, sig/azure, size/M

#8619 azure - do not tag node images as valid automatically 3.9
  playbooks/azure/openshift-cluster/build_base_image.yml
  playbooks/azure/openshift-cluster/build_node_image.yml
  playbooks/azure/openshift-cluster/launch.yml
  playbooks/azure/openshift-cluster/provisioning_vars.yml.example
  playbooks/azure/openshift-cluster/tag_image_as_valid.yml
  playbooks/azure/openshift-cluster/tasks/create_image_from_vm.yml
  playbooks/azure/openshift-cluster/tasks/provision_instance.yml
Labels: approved, lgtm, sig/azure, size/M

#8629 Check for mandatory node-group configmaps during upgrades
  .papr.sh
  playbooks/common/openshift-cluster/upgrades/init.yml
  playbooks/gcp/openshift-cluster/openshift_node_group.yml
  playbooks/openshift-master/openshift_node_group.yml
  roles/openshift_node_group/defaults/main.yml
  roles/openshift_node_group/tasks/check_for_config.yml
  roles/openshift_node_group/tasks/check_for_configs.yml
  roles/openshift_node_group/tasks/create_config.yml
  roles/openshift_node_group/tasks/fetch_config.yml
  roles/openshift_node_group/templates/node-config.yaml.j2
  roles/openshift_node_group/vars/main.yml
Labels: approved, lgtm, size/L

#8691 Bug 1586197 - Increase async timeout
  roles/openshift_node/tasks/upgrade/restart.yml
Labels: approved, lgtm, size/XS

#8685 Set openshift_node_group_name in OpenStack inventory
  playbooks/openstack/configuration.md
  playbooks/openstack/inventory.py
  playbooks/openstack/sample-inventory/group_vars/OSEv3.yml
  playbooks/openstack/sample-inventory/group_vars/all.yml
  roles/openshift_openstack/defaults/main.yml
  roles/openshift_openstack/templates/heat_stack.yaml.j2
  roles/openshift_openstack/templates/heat_stack_server.yaml.j2
Labels: approved, lgtm, size/L

#8689 Make the number of service catalog retries configurable
  roles/openshift_service_catalog/defaults/main.yml
  roles/openshift_service_catalog/tasks/start.yml
Labels: approved, lgtm, size/XS

#8694 Bug 1589015 - Switch to rolling deployment for web console
  roles/openshift_web_console/files/console-template.yaml
Labels: approved, lgtm, size/XS

#8693 Move openshift_master_manage_htpasswd into openshift_facts
  roles/openshift_control_plane/defaults/main.yml
  roles/openshift_facts/defaults/main.yml
Labels: approved, lgtm, size/XS

#8463 [release-3.7] Updating process for doing a rolling and full cluster upgrades
  roles/openshift_logging/tasks/main.yaml
  roles/openshift_logging_elasticsearch/tasks/full_cluster_restart.yml
  roles/openshift_logging_elasticsearch/tasks/restart_cluster.yml
  roles/openshift_logging_elasticsearch/tasks/restart_es_node.yml
  roles/openshift_logging_elasticsearch/tasks/rolling_cluster_restart.yml
  roles/openshift_logging_elasticsearch/vars/main.yml
Labels: lgtm, size/XL

#8697 Set openshift_node_group_name for AWS host groups.
  roles/openshift_aws/defaults/main.yml
  roles/openshift_aws/tasks/setup_master_group.yml
  roles/openshift_aws/tasks/setup_scale_group_facts.yml
Labels: approved, lgtm, size/S

#8574 Local Volume Storage format and setup
  inventory/hosts.example
  playbooks/container-runtime/private/setup_storage.yml
  roles/container_runtime/defaults/main.yml
  roles/container_runtime/tasks/extra_storage_setup.yml
Labels: approved, lgtm, size/S

#8706 Upgrade router and registry only when these are managed
  playbooks/openshift-hosted/private/upgrade.yml
Labels: approved, lgtm, size/XS

#8423 Added container_manage_cgroup in order for systemd to run in pods
  playbooks/openshift-management/private/config-sebool.yml
  playbooks/openshift-management/private/config.yml
Labels: approved, lgtm, size/S

#8596 Update Prometheus to scrape the router metrics
  roles/openshift_prometheus/tasks/install_prometheus.yaml
  roles/openshift_prometheus/tasks/uninstall_prometheus.yaml
  roles/openshift_prometheus/templates/prometheus.yml.j2
Labels: lgtm, size/M

#8378 [3.9] Prometheus nodeselector should default to hosted nodeselector
  roles/openshift_prometheus/defaults/main.yaml
Labels: lgtm, size/XS

#8707 Azure: calculate input image for base and node image
  playbooks/azure/openshift-cluster/build_base_image.yml
  playbooks/azure/openshift-cluster/build_node_image.yml
  playbooks/azure/openshift-cluster/tasks/create_image_from_vm.yml
  playbooks/azure/openshift-cluster/tasks/provision_instance.yml
Labels: approved, lgtm, size/S

#8709 Fix sanity_checks typos
  roles/lib_utils/action_plugins/sanity_checks.py
Labels: approved, lgtm, size/XS

#8695 Fix flaky use of `oc process`
  roles/openshift_cluster_monitoring_operator/tasks/install.yaml
  roles/openshift_monitor_availability/tasks/install_monitor_app_create.yaml
Labels: approved, lgtm, size/XS

#8621 Remove unused registry-console's imagestream
  roles/openshift_hosted_templates/files/v3.10/enterprise/registry-console.yaml
  roles/openshift_hosted_templates/files/v3.10/origin/registry-console.yaml
Labels: approved, lgtm, size/S

#8408 GlusterFS: Add GlusterFS hosts to openshift-hosted/config.yml playbook
  playbooks/openshift-hosted/config.yml
Labels: approved, kind/bug, lgtm, priority/P1, size/XS

#8715 Fix ansible_service_broker role, needs openshift_facts
  roles/ansible_service_broker/meta/main.yml
Labels: approved, lgtm, size/XS

#8708 Azure: calculate input image for base and node image 3.9
  playbooks/azure/openshift-cluster/build_base_image.yml
  playbooks/azure/openshift-cluster/build_node_image.yml
  playbooks/azure/openshift-cluster/tasks/create_image_from_vm.yml
  playbooks/azure/openshift-cluster/tasks/provision_instance.yml
Labels: approved, lgtm, size/S

#8649 Migrate hawkular metrics to a new namespace
  roles/openshift_metrics/defaults/main.yaml
  roles/openshift_metrics/tasks/clean_old_namespace.yaml
  roles/openshift_metrics/tasks/generate_cassandra_pvcs.yaml
  roles/openshift_metrics/tasks/install_metrics.yaml
  roles/openshift_metrics/tasks/main.yaml
  roles/openshift_metrics/tasks/migrate_cassandra_pvcs.yaml
  roles/openshift_metrics/tasks/oc_apply.yaml
  roles/openshift_metrics/templates/create_project.j2
  roles/openshift_metrics/templates/pvc.j2
Labels: approved, lgtm, size/L

#8713 Migrate HPA scale target refs in storage migration
  playbooks/openshift-master/private/upgrade.yml
Labels: approved, lgtm, priority/P1, size/S

#8488 azure: format data disk for docker use
  playbooks/azure/OWNERS
  playbooks/azure/openshift-cluster/build_node_image.yml
Labels: approved, lgtm, sig/azure, size/S

#8716 Don't restart dnsmasq during upgrade
  roles/openshift_node/tasks/upgrade/restart.yml
Labels: approved, lgtm, size/XS

#8661 Fix cri-o 3.9 to 3.10 upgrade
  playbooks/openshift-master/private/upgrade.yml
  roles/openshift_control_plane/files/scripts/crio/master-exec
  roles/openshift_control_plane/files/scripts/crio/master-logs
  roles/openshift_control_plane/files/scripts/crio/master-restart
  roles/openshift_control_plane/tasks/static_shim.yml
  roles/openshift_node/files/clean-up-crio-pods.sh
  roles/openshift_node/tasks/upgrade.yml
  roles/openshift_node/tasks/upgrade/restart.yml
  roles/openshift_node/tasks/upgrade/stop_services.yml
  roles/openshift_node/tasks/upgrade_pre.yml
Labels: approved, size/L

#8710 Add some openshift_node_group and openshift_node_group_name docs
  README.md
Labels: approved, lgtm, size/M

#8718 Move openshift_node_group to private play
  playbooks/openshift-master/openshift_node_config.yml
  playbooks/openshift-master/openshift_node_group.yml
  playbooks/openshift-master/private/openshift_node_group.yml
Labels: approved, lgtm, size/S

#8734 Add retries to SCC check on upgrade
  playbooks/openshift-master/private/upgrade.yml
Labels: approved, lgtm, size/XS

#8732 Adding etcd image variables to fix deployments.
  playbooks/azure/openshift-cluster/build_node_image.yml
Labels: approved, lgtm, size/XS

#8731 Add master-infra and all-in-one node-configs
  .papr.all-in-one.inventory
  .papr.inventory
  README.md
  roles/openshift_facts/defaults/main.yml
Labels: approved, lgtm, size/M

#8743 Sync daemonset should start after node configmaps are created to avoid race conditions
  playbooks/openshift-master/private/config.yml
Labels: approved, lgtm, size/S

#8744 Revert "Make SDN read config file from sysconfig"
  roles/openshift_node/tasks/bootstrap.yml
  roles/openshift_node/tasks/config/configure-node-settings.yml
  roles/openshift_sdn/files/sdn.yaml
Labels: approved, lgtm, size/S

#8751 Azure: use empty dict if input image has no tags
  playbooks/azure/openshift-cluster/tasks/create_image_from_vm.yml
Labels: approved, lgtm, sig/azure, size/XS

#8752 Azure: use empty dict if input image has no tags
  playbooks/azure/openshift-cluster/tasks/create_image_from_vm.yml
Labels: approved, lgtm, sig/azure, size/XS

#8756 azure: tag image as valid=true, not valid=True
  playbooks/azure/openshift-cluster/build_base_image.yml
Labels: approved, lgtm, size/XS

#8757 azure: tag image as valid=true, not valid=True
  playbooks/azure/openshift-cluster/build_base_image.yml
Labels: approved, lgtm, size/XS

#8755 azure: don't try to print deployment failure message when there isn't…
  playbooks/azure/openshift-cluster/launch.yml
Labels: approved, lgtm, size/XS

#8754 azure: don't try to print deployment failure message when there isn't…
  playbooks/azure/openshift-cluster/launch.yml
Labels: approved, lgtm, size/XS

#8758 azure: pass image_name into tasks/create_blob_from_vm.yml
  playbooks/azure/openshift-cluster/build_base_image.yml
  playbooks/azure/openshift-cluster/build_node_image.yml
Labels: approved, lgtm, size/XS

#8759 azure: pass image_name into tasks/create_blob_from_vm.yml
  playbooks/azure/openshift-cluster/build_base_image.yml
  playbooks/azure/openshift-cluster/build_node_image.yml
Labels: approved, lgtm, size/XS

#8739 Fix hostname check failure message
  playbooks/init/validate_hostnames.yml
Labels: approved, lgtm, size/XS

#6022 Add support for hostpath persistent volume definitions
  inventory/hosts.example
  roles/lib_utils/action_plugins/generate_pv_pvcs_list.py
  roles/openshift_facts/defaults/main.yml
  roles/openshift_hosted/tasks/registry.yml
  roles/openshift_hosted/tasks/storage/hostpath.yml
Labels: approved, lgtm, size/M

#8760 Fix minor indentation
  playbooks/azure/openshift-cluster/create_and_publish_offer.yml
Labels: approved, lgtm, size/XS

#8772 Fix to pass quoted unsafe strings (with characters like *,<,%) correctly to kubelet
  roles/openshift_node/files/openshift-node
Labels: approved, lgtm, size/XS

#8770 Bug 1564499 - Change imagePullPolicy for Broker images to Always
  roles/ansible_service_broker/defaults/main.yml
Labels: size/XS

#8721 Fix the docs, add additional .parr file description
  docs/repo_structure.md
Labels: needs-ok-to-test, retest-not-required-docs-only, size/XS

#8778 Honor openshift_hosted_manage_registry
  playbooks/common/openshift-cluster/upgrades/v3_7/upgrade_control_plane.yml
Labels: lgtm, size/XS

#8764 bug 1572493. Update default logging NS in openshift_health_checker
  roles/openshift_health_checker/openshift_checks/logging/logging.py
Labels: approved, lgtm, size/XS

#8787 Bug 1583896 - Standardize master restart
  playbooks/openshift-master/private/scaleup.yml
  roles/openshift_cloud_provider/handlers/main.yml
  roles/openshift_control_plane/handlers/main.yml
  roles/openshift_control_plane/tasks/registry_auth.yml
  roles/openshift_control_plane/tasks/restart.yml
  roles/openshift_control_plane/tasks/update_etcd_client_urls.yml
  roles/openshift_control_plane/tasks/update_master_count.yml
  roles/openshift_logging/handlers/main.yml
  roles/openshift_metrics/handlers/main.yml
Labels: approved, lgtm, size/L

#8779 upgrade: storage migrations should use 'until' to properly retry migr…
  playbooks/openshift-master/private/upgrade.yml
Labels: approved, lgtm, size/XS

#8803 PAPR: upgrade from 3.10 branch
  .papr.yml
Labels: approved, size/XS

#7613 Update glusterfs README about uninstall playbook
  playbooks/openshift-glusterfs/README.md
Labels: approved, lgtm, needs-ok-to-test, retest-not-required-docs-only, size/XS

#8576 [RHPAM-859] - Include RHPAM templates in OpenShift release
  roles/openshift_examples/examples-sync.sh
  roles/openshift_examples/files/examples/v3.10/xpaas-streams/rhpam70-image-streams.yaml
  roles/openshift_examples/files/examples/v3.10/xpaas-templates/rhpam70-authoring-ha.yaml
  roles/openshift_examples/files/examples/v3.10/xpaas-templates/rhpam70-authoring.yaml
  roles/openshift_examples/files/examples/v3.10/xpaas-templates/rhpam70-kieserver-externaldb.yaml
  roles/openshift_examples/files/examples/v3.10/xpaas-templates/rhpam70-kieserver-mysql.yaml
  roles/openshift_examples/files/examples/v3.10/xpaas-templates/rhpam70-kieserver-postgresql.yaml
  roles/openshift_examples/files/examples/v3.10/xpaas-templates/rhpam70-prod-immutable-kieserver.yaml
  roles/openshift_examples/files/examples/v3.10/xpaas-templates/rhpam70-prod-immutable-monitor.yaml
  roles/openshift_examples/files/examples/v3.10/xpaas-templates/rhpam70-prod.yaml
  roles/openshift_examples/files/examples/v3.10/xpaas-templates/rhpam70-sit.yaml
  roles/openshift_examples/files/examples/v3.10/xpaas-templates/rhpam70-trial-ephemeral.yaml
Labels: approved, lgtm, size/XXL

#8626 Redeploy registry certs only when needed.
  playbooks/openshift-hosted/private/upgrade_poll_and_check_certs.yml
Labels: approved, lgtm, size/XS

#8682 Allow for overriding of the elb names to support shorter endings for the names
  roles/openshift_aws/defaults/main.yml
Labels: approved, lgtm, size/XS

#8723 Confirm service status by ansible module
  playbooks/common/openshift-cluster/upgrades/init.yml
  roles/contiv_facts/tasks/rpm.yml
Labels: approved, lgtm, size/S

#8798 Fixed add_container_provider.yaml so it uses variable instead of set name
  roles/openshift_management/tasks/add_container_provider.yml
Labels: approved, lgtm, size/XS

#8777 Clean up docker-storage in a reliable mannger
  playbooks/adhoc/uninstall.yml
Labels: approved, lgtm, size/S

#8820 Revert update to 3.10 registry console template
  roles/openshift_hosted_templates/files/v3.10/enterprise/registry-console.yaml
Labels: approved, lgtm, size/XS

#8809 Add openshift_master_cluster_hostname to no_proxy list
  roles/openshift_facts/library/openshift_facts.py
Labels: approved, lgtm, size/XS

#8818 Fix registry gluster storage variable
  roles/openshift_hosted/README.md
Labels: needs-ok-to-test, retest-not-required-docs-only, size/XS

#8794 [release-3.9] Bug 1555214 - Increase retry for controller restart
  roles/nuage_master/handlers/main.yaml
  roles/openshift_logging/handlers/main.yml
  roles/openshift_master/handlers/main.yml
  roles/openshift_master/tasks/restart.yml
  roles/openshift_metrics/handlers/main.yml
Labels: lgtm, size/S

#8829 Add doc link to check_for_config
  roles/openshift_node_group/tasks/check_for_config.yml
Labels: approved, lgtm, size/XS

#8607 Fix OpenStack all-in-one cluster deployment
  playbooks/openstack/configuration.md
  roles/openshift_openstack/defaults/main.yml
  roles/openshift_openstack/tasks/generate-dns.yml
  roles/openshift_openstack/templates/heat_stack.yaml.j2
Labels: approved, lgtm, size/M

#8750 master config: join bootstrap settings and sync DS tasks
  playbooks/openshift-master/private/config.yml
Labels: approved, lgtm, size/XS

#8762 bug 1575546. Fix logging eventrouter cpu requests
  roles/openshift_logging_eventrouter/tasks/install_eventrouter.yaml
  roles/openshift_logging_eventrouter/templates/2.x/eventrouter-template.j2
  roles/openshift_logging_eventrouter/templates/5.x/eventrouter-template.j2
Labels: affects_3.10, affects_3.9, approved, lgtm, size/S

#8805 PAPR: set docker log driver to journald
  .papr-master-ha.inventory
  .papr.all-in-one.inventory
  .papr.inventory
Labels: approved, lgtm, size/XS

#8684 Enable container_manage_crgroup sebool
  roles/openshift_node/tasks/main.yml
Labels: approved, lgtm, size/XS

#8795 Bug 1583157 - Add openshift-node entry-point playbooks
  playbooks/openshift-node/bootstrap.yml
  playbooks/openshift-node/join.yml
  playbooks/openshift-node/private/bootstrap.yml
  playbooks/openshift-node/private/join.yml
Labels: approved, lgtm, size/M

#8782 upgrade: init facts on nodes so that NO_PROXY would include node hostnames
  playbooks/common/openshift-cluster/upgrades/v3_10/upgrade_control_plane.yml
Labels: approved, lgtm, size/XS

#8827 Record etcd static pod version only if master-exec has stdout
  roles/etcd/tasks/version_detect.yml
Labels: approved, lgtm, size/XS

#8833 Set `openshift_node_group_name` for the CNS nodes
  roles/openshift_openstack/templates/heat_stack.yaml.j2
Labels: approved, lgtm, size/XS

#8647 Fix S3 storage class path
  roles/openshift_storage_glusterfs/tasks/gluster_s3_deploy.yml
Labels: approved, lgtm, size/XS

#8641 Add extensions to included task file directives
  playbooks/common/openshift-cluster/upgrades/v3_10/upgrade_control_plane.yml
  playbooks/openshift-descheduler/private/uninstall.yml
  playbooks/openshift-grafana/private/uninstall.yml
  playbooks/openshift-management/add_many_container_providers.yml
  playbooks/openshift-management/private/add_container_provider.yml
  playbooks/openshift-management/private/uninstall.yml
  playbooks/openshift-master/private/additional_config.yml
  playbooks/openshift-master/private/config.yml
  playbooks/openshift-master/private/upgrade.yml
  playbooks/openshift-node-problem-detector/private/uninstall.yml
  playbooks/openshift-node/private/configure_bootstrap.yml
  playbooks/openshift-prometheus/private/uninstall.yml
  roles/nuage_master/tasks/etcd_certificates.yml
  roles/openshift_management/tasks/storage/nfs.yml
  roles/openshift_nfs/tasks/create_export.yml
Labels: approved, lgtm, size/M

#8767 [3.9] registry-console: limit pods to masters
  roles/openshift_hosted_templates/files/v3.6/origin/registry-console.yaml
  roles/openshift_hosted_templates/files/v3.9/enterprise/registry-console.yaml
Labels: lgtm, size/XS

#8702 Add prometheus port annotation for Grafana service
  roles/openshift_grafana/tasks/install_grafana.yaml
Labels: approved, lgtm, size/XS

#8831 Set UID,fsGroup and Linux options to cassandra RC's
  roles/openshift_metrics/defaults/main.yaml
  roles/openshift_metrics/tasks/clean_old_namespace.yaml
  roles/openshift_metrics/tasks/generate_cassandra_pvcs.yaml
  roles/openshift_metrics/tasks/install_cassandra.yaml
  roles/openshift_metrics/tasks/install_metrics.yaml
  roles/openshift_metrics/tasks/main.yaml
  roles/openshift_metrics/tasks/migrate_cassandra_pvcs.yaml
  roles/openshift_metrics/tasks/oc_apply.yaml
  roles/openshift_metrics/tasks/pre_install.yaml
  roles/openshift_metrics/templates/create_project.j2
  roles/openshift_metrics/templates/hawkular_cassandra_rc.j2
  roles/openshift_metrics/templates/pvc.j2
Labels: affects_3.10, approved, lgtm, size/L

#8848 Add node_group_checks to openshift_node_group.yml
  playbooks/openshift-master/private/openshift_node_group.yml
Labels: approved, lgtm, size/XS

#8789 Fully qualify all openshift/origin and openshift3/ose images
  README_CONTAINERIZED_INSTALLATION.md
  README_CONTAINER_IMAGE.md
  examples/certificate-check-upload.yaml
  examples/certificate-check-volume.yaml
  examples/scheduled-certcheck-upload.yaml
  examples/scheduled-certcheck-volume.yaml
  hack/build-images.sh
  hack/push-release.sh
  images/installer/README_INVENTORY_GENERATOR.md
  images/installer/root/usr/local/bin/usage
  roles/lib_openshift/library/oc_adm_registry.py
  roles/lib_openshift/library/oc_adm_router.py
  roles/lib_openshift/src/ansible/oc_adm_router.py
  roles/lib_openshift/src/doc/registry
  roles/lib_openshift/src/doc/router
  roles/lib_openshift/src/test/unit/test_oc_adm_registry.py
  roles/lib_openshift/src/test/unit/test_oc_adm_router.py
  roles/lib_utils/filter_plugins/oo_filters.py
  roles/openshift_control_plane/files/apiserver.yaml
  roles/openshift_control_plane/files/controller.yaml
  roles/openshift_health_checker/openshift_checks/docker_image_availability.py
  roles/openshift_health_checker/test/docker_image_availability_test.py
  roles/openshift_hosted/README.md
  roles/openshift_node/defaults/main.yml
  roles/openshift_web_console/files/console-template.yaml
  roles/template_service_broker/files/apiserver-template.yaml
  test/ci/inventory/group_vars/all.yml
  test/ci/inventory/group_vars/containerized_hosts.yml
Labels: approved, lgtm, size/L

#8670 Only Run Get Kuryr Services Task when cluster is running Kuryr
  roles/openshift_openstack/tasks/unprovision.yml
Labels: approved, lgtm, size/XS

#8853 Fix playbooks/openstack/openshift-cluster/roles
  playbooks/openstack/openshift-cluster/roles
Labels: approved, lgtm, size/XS

#8785 Updating node group mappings to use an openshift specific tag.
  roles/openshift_aws/defaults/main.yml
  roles/openshift_aws/tasks/scale_group.yml
  roles/openshift_aws/tasks/setup_master_group.yml
  roles/openshift_aws/tasks/setup_scale_group_facts.yml
  roles/openshift_aws/templates/user_data.j2
  roles/openshift_node/templates/bootstrap.yml.j2
Labels: approved, lgtm, size/S

#8850 openshift_aws: enabled different instance type to be used
  roles/openshift_aws/defaults/main.yml
  roles/openshift_aws/tasks/provision_instance.yml
Labels: approved, lgtm, size/XS

#8863 no_proxy: use 'append' to properly add a string to a list
  roles/openshift_facts/library/openshift_facts.py
Labels: approved, lgtm, priority/P1, size/XS

#8855 [release-3.10] Fully qualify all openshift/origin and openshift3/ose images
  README_CONTAINERIZED_INSTALLATION.md
  README_CONTAINER_IMAGE.md
  examples/certificate-check-upload.yaml
  examples/certificate-check-volume.yaml
  examples/scheduled-certcheck-upload.yaml
  examples/scheduled-certcheck-volume.yaml
  hack/build-images.sh
  hack/push-release.sh
  images/installer/README_INVENTORY_GENERATOR.md
  images/installer/root/usr/local/bin/usage
  roles/lib_openshift/library/oc_adm_registry.py
  roles/lib_openshift/library/oc_adm_router.py
  roles/lib_openshift/src/ansible/oc_adm_router.py
  roles/lib_openshift/src/doc/registry
  roles/lib_openshift/src/doc/router
  roles/lib_openshift/src/test/unit/test_oc_adm_registry.py
  roles/lib_openshift/src/test/unit/test_oc_adm_router.py
  roles/lib_utils/filter_plugins/oo_filters.py
  roles/openshift_control_plane/files/apiserver.yaml
  roles/openshift_control_plane/files/controller.yaml
  roles/openshift_health_checker/openshift_checks/docker_image_availability.py
  roles/openshift_health_checker/test/docker_image_availability_test.py
  roles/openshift_hosted/README.md
  roles/openshift_node/defaults/main.yml
  roles/openshift_web_console/files/console-template.yaml
  roles/template_service_broker/files/apiserver-template.yaml
  test/ci/inventory/group_vars/all.yml
  test/ci/inventory/group_vars/containerized_hosts.yml
Labels: approved, lgtm, size/L

#8857 Fix nsupdate var chec, checks for .
  roles/openshift_openstack/tasks/check-prerequisites.yml
Labels: approved, lgtm, size/XS

#8851 manage_node: don't add extra labels to infra/compute/master nodes
  playbooks/common/openshift-cluster/upgrades/v3_10/label_nodes.yml
  playbooks/common/openshift-cluster/upgrades/v3_11/label_nodes.yml
  roles/openshift_manage_node/tasks/main.yml
  roles/openshift_manage_node/tasks/set_default_node_role.yml
Labels: approved, lgtm, size/M

#8868 manage_node: don't add extra labels to infra/compute/master nodes
  playbooks/common/openshift-cluster/upgrades/v3_10/label_nodes.yml
  roles/openshift_manage_node/tasks/main.yml
  roles/openshift_manage_node/tasks/set_default_node_role.yml
Labels: approved, lgtm, priority/P1, size/M

#8870 Bug 1558689 - Add iproute to Dockerfile.rhel7
  images/installer/Dockerfile.rhel7
Labels: approved, lgtm, size/XS

#8874 [release-3.9] Bug 1558689 - Add iproute to Dockerfile.rhel7
  images/installer/Dockerfile.rhel7
Labels: size/XS

#8875 azure: disable waagent data disk management
  playbooks/azure/openshift-cluster/build_node_image.yml
Labels: approved, lgtm, size/XS

#8876 azure: disable waagent data disk management
  playbooks/azure/openshift-cluster/build_node_image.yml
Labels: approved, lgtm, size/XS

#8866 Deprecate openshift_node_kubelet_args and openshift_node_labels
  inventory/hosts.example
  roles/openshift_node/defaults/main.yml
  roles/openshift_sanitize_inventory/vars/main.yml
Labels: approved, lgtm, size/S

#8882 Don't verify java-1.8.0-openjdk
  images/installer/Dockerfile
  images/installer/Dockerfile.rhel7
Labels: size/XS

#8883 Don't verify java-1.8.0-openjdk
  images/installer/Dockerfile
  images/installer/Dockerfile.rhel7
Labels: size/XS

#8879 [release-3.6] Bug 1539021 - Specify all packages during upgrade
  playbooks/common/openshift-cluster/upgrades/rpm_upgrade.yml
  roles/openshift_node_upgrade/tasks/main.yml
  roles/openshift_node_upgrade/tasks/rpm_upgrade.yml
Labels: lgtm, size/M

#8880 [release-3.7] Bug 1544694 - Specify all packages during upgrade
  playbooks/common/openshift-cluster/upgrades/rpm_upgrade.yml
  roles/openshift_node_upgrade/tasks/main.yml
  roles/openshift_node_upgrade/tasks/rpm_upgrade.yml
Labels: lgtm, size/M

#8881 [release-1.5] Bug 1544783 - Specify all packages during upgrade
  playbooks/common/openshift-cluster/upgrades/rpm_upgrade.yml
  roles/openshift_node_upgrade/tasks/main.yml
  roles/openshift_node_upgrade/tasks/rpm_upgrade.yml
Labels: size/M

#8834 Sync grafana deployment to openshift-monitoring.
  roles/openshift_grafana/defaults/main.yaml
  roles/openshift_grafana/tasks/facts.yaml
  roles/openshift_grafana/tasks/install_grafana.yaml
Labels: size/XS

#8893 [release-1.5] Fix tox
  requirements.txt
  roles/lib_openshift/src/test/unit/test_oc_objectvalidator.py
  roles/openshift_certificate_expiry/library/openshift_cert_expiry.py
  roles/openshift_certificate_expiry/test/test_fakeopensslclasses.py
Labels: lgtm, size/M

#8898 Adding owners file for openshift_logging_defaults role
  roles/openshift_logging_defaults/OWNERS
Labels: affects_3.10, size/S
