Repository openshift/openshift-ansible, pull requests merged in 2018-08, with the labels that each got.

#9379 Bug 1610224 - Unable to find container log in Elasticsearch when using cri-o
  roles/openshift_logging_fluentd/templates/fluentd.j2
Labels: approved, lgtm, size/XS

#9368 Added OpenStack security group requirements section
  playbooks/openstack/README.md
Labels: approved, lgtm, size/XS

#9383 Add a license parameter to gcloud command
  inventory/hosts.example
  playbooks/gcp/openshift-cluster/build_image.yml
Labels: approved, lgtm, size/S

#7139 Allow user to specify local openstack.conf
  playbooks/openstack/configuration.md
  playbooks/openstack/sample-inventory/group_vars/OSEv3.yml
  roles/openshift_cloud_provider/tasks/openstack.yml
Labels: approved, lgtm, size/M

#9347 Clarified scaling docs, combining master/infra/app sections
  playbooks/openstack/configuration.md
Labels: approved, lgtm, size/L

#9349 Fix docker reg auth bugs
  roles/container_runtime/tasks/registry_auth.yml
  roles/lib_utils/library/docker_creds.py
  roles/openshift_control_plane/tasks/registry_auth.yml
  roles/openshift_facts/defaults/main.yml
  roles/openshift_node/tasks/registry_auth.yml
Labels: approved, lgtm, size/M

#9329 [3.9] Fix cpu_limit check in eventrouter template
  roles/openshift_logging_eventrouter/templates/2.x/eventrouter-template.j2
Labels: lgtm, size/XS

#9394 Beginning deprecation of INSTANCE_RAM var
  roles/openshift_logging_elasticsearch/templates/es.j2
Labels: approved, lgtm, size/S

#9382 Ensure the top level mount point is unmounted before other tasks
  roles/container_runtime/tasks/common/setup_docker_symlink.yml
Labels: approved, lgtm, size/XS

#9303 [release-3.10] Fix order for invoking the hostpath storage task for registry
  roles/openshift_hosted/tasks/registry.yml
  roles/openshift_hosted/tasks/registry_storage.yml
Labels: approved, do-not-merge/hold, lgtm, size/XS

#9403 Add doc note that kuryr requires openstack cloud provider
  playbooks/openstack/configuration.md
Labels: approved, lgtm, size/XS

#9407 [3.10] Add containerized glusterfs cluster health check
  playbooks/common/openshift-cluster/upgrades/pre/verify_cluster.yml
  playbooks/common/openshift-cluster/upgrades/upgrade_nodes.yml
  playbooks/common/openshift-cluster/upgrades/v3_10/upgrade_control_plane.yml
  playbooks/openshift-glusterfs/cluster_health_check.yml
  playbooks/openshift-glusterfs/private/cluster_health_check.yml
  playbooks/openshift-master/private/upgrade.yml
  roles/lib_utils/library/glusterfs_check_containerized.py
  roles/lib_utils/test/test_glusterfs_check_containerized.py
  roles/openshift_storage_glusterfs/defaults/main.yml
  roles/openshift_storage_glusterfs/tasks/check_cluster_health.yml
  roles/openshift_storage_glusterfs/tasks/uninstall.yml
Labels: approved, lgtm, size/L

#9404 Reorganized OpenStack cloud provider documentation
  playbooks/openstack/configuration.md
Labels: approved, lgtm, size/M

#9406 [3.10] Cleanup node bootstrap / scaleup code
  playbooks/azure/openshift-cluster/build_node_image.yml
  playbooks/init/evaluate_groups.yml
  playbooks/openshift-node/private/bootstrap.yml
  playbooks/openshift-node/private/certificates-backup.yml
  playbooks/openshift-node/private/certificates.yml
  playbooks/openshift-node/private/configure_bootstrap.yml
  playbooks/openshift-node/private/join.yml
  roles/openshift_node/tasks/distribute_bootstrap.yml
Labels: approved, size/M

#9312 [release-3.10] Upgrade Prometheus and AlertManager image versions
  roles/openshift_prometheus/defaults/main.yaml
Labels: approved, lgtm, size/XS

#9276 Update Calico versions to the latest (v3.1.3) in OpenShift 3.10 versions
  roles/calico_master/defaults/main.yaml
Labels: needs-ok-to-test, size/XS

#8781 Drop --confirm from migrate storage invocation
  playbooks/openshift-master/private/upgrade.yml
Labels: approved, lgtm, size/XS

#9391 Enable console picker
  roles/openshift_console/tasks/install.yml
  roles/openshift_web_console/tasks/install.yml
Labels: approved, lgtm, size/S

#9334 fix bug 1608269
  roles/olm/tasks/remove_components.yaml
Labels: approved, lgtm, size/M

#9417 BZ-1608216 Set timeoutSeconds for readinessProbe on Cassandra RCs
  roles/openshift_metrics/templates/hawkular_cassandra_rc.j2
Labels: approved, lgtm, size/XS

#9418 Bug 1611840 - Correctly set console replicas
  roles/openshift_console/files/console-template.yaml
Labels: approved, lgtm, size/XS

#9419 [3.7] bz 1600859: default openshift_use_openshift_sdn to true in playbooks and roles
  playbooks/common/openshift-cluster/upgrades/docker/tasks/restart.yml
  playbooks/common/openshift-cluster/upgrades/docker/tasks/upgrade.yml
  playbooks/common/openshift-node/restart.yml
  roles/openshift_node/defaults/main.yml
  roles/openshift_node_upgrade/handlers/main.yml
  roles/openshift_node_upgrade/tasks/main.yml
  roles/openshift_node_upgrade/tasks/restart.yml
  roles/openshift_node_upgrade/tasks/systemd_units.yml
Labels: size/S

#6611 Add blockstorage version for openstack for OpenShift 3.7
  inventory/byo/hosts.example
  roles/openshift_cloud_provider/templates/openstack.conf.j2
Labels: lgtm, size/XS

#9420 Ensure that monitoring operator has nodes to run
  roles/openshift_cluster_monitoring_operator/tasks/install.yaml
Labels: approved, lgtm, size/XS

#9277 Update Calico versions to the latest (v3.1.3)
  roles/calico_master/defaults/main.yaml
Labels: approved, lgtm, size/XS

#9275 Update Calico versions to the latest (v3.1.3) in OpenShift 3.9 versions
  roles/calico_master/defaults/main.yaml
Labels: needs-ok-to-test, size/XS

#9426 Additional cleanup of v1beta1 rbac.authorization
  roles/openshift_metering/files/operator/metering-helm-operator-role.yaml
  roles/openshift_metering/files/operator/metering-helm-operator-rolebinding.yaml
Labels: approved, lgtm, size/XS

#9392 apply the container_runtime for calico
  roles/calico/meta/main.yml
Labels: approved, lgtm, size/XS

#9335 Avoid using deprecated syntax for filters in OLM
  playbooks/common/openshift-cluster/upgrades/pre/verify_cluster.yml
  playbooks/common/openshift-cluster/upgrades/pre/verify_upgrade_targets.yml
  playbooks/init/basic_facts.yml
  playbooks/olm/private/config.yml
  playbooks/openshift-etcd/private/upgrade_rpm_members.yml
  playbooks/openshift-master/private/additional_config.yml
  roles/container_runtime/tasks/docker_sanity.yml
  roles/container_runtime/tasks/docker_upgrade_check.yml
  roles/openshift_control_plane/tasks/upgrade.yml
  roles/openshift_excluder/tasks/verify_excluder.yml
  roles/openshift_node/tasks/storage_plugins/glusterfs.yml
  roles/openshift_node/tasks/storage_plugins/nfs.yml
  roles/openshift_openstack/tasks/container-storage-setup.yml
Labels: approved, lgtm, size/M

#9423 Ensure skopeo and atomic are installed in crt role
  roles/container_runtime/tasks/package_crio.yml
  roles/container_runtime/tasks/package_docker.yml
Labels: approved, size/XS

#9438 OSA - rollback node ports
  playbooks/azure/openshift-cluster/build_node_image.yml
Labels: approved, lgtm, sig/azure, size/XS

#9390 Commit to enable AWS multi avail zone
  roles/lib_utils/filter_plugins/openshift_aws_filters.py
  roles/openshift_aws/defaults/main.yml
  roles/openshift_aws/tasks/elb_single.yml
  roles/openshift_aws/tasks/provision_instance.yml
  roles/openshift_aws/tasks/scale_group.yml
  roles/openshift_aws/tasks/vpc.yml
  roles/openshift_aws/tasks/vpc_and_subnet_id.yml
Labels: approved, lgtm, size/M

#9182 Don't set OAUTH_CLIENT_ID in console OAuth secret
  roles/openshift_console/files/console-template.yaml
Labels: approved, lgtm, size/XS

#9430 Output cert check file to more sensible location
  roles/openshift_certificate_expiry/defaults/main.yml
Labels: approved, lgtm, size/XS

#7634 Adding support for an SSL certificate signed by the OpenStack cluster
  playbooks/openstack/configuration.md
  roles/openshift_cloud_provider/defaults/main.yml
  roles/openshift_cloud_provider/tasks/openstack.yml
  roles/openshift_cloud_provider/templates/openstack.conf.j2
Labels: approved, lgtm, size/M

#9444 Sanity check htpasswd respect default
  roles/lib_utils/action_plugins/sanity_checks.py
Labels: approved, lgtm, size/XS

#9378 Adding image info to /etc/origin/image.yml on Azure
  playbooks/azure/openshift-cluster/build_node_image.yml
Labels: approved, lgtm, size/S

#9411 Remove exclude-bootstrapped logic
  playbooks/openshift-node/private/bootstrap.yml
  playbooks/openshift-node/private/clean_image.yml
  playbooks/openshift-node/private/configure_bootstrap.yml
  playbooks/openshift-node/private/configure_nodes.yml
  playbooks/openshift-node/private/disable_excluders.yml
  playbooks/openshift-node/private/enable_excluders.yml
  playbooks/openshift-node/private/image_prep.yml
Labels: approved, lgtm, size/M

#9315 oc_obj should correctly identify 'results': [{}] as 'Object not found'
  roles/lib_openshift/library/oc_obj.py
  roles/lib_openshift/src/class/oc_obj.py
Labels: approved, lgtm, size/XS

#9220 Don't collect node facts on master - these are set during bootstrap
  playbooks/openshift-master/private/config.yml
Labels: approved, lgtm, size/XS

#9211 Don't get file checksum, attributes and mime type in stat module calls
  playbooks/byo/calico/legacy_upgrade.yml
  playbooks/init/basic_facts.yml
  playbooks/openshift-master/private/certificates-backup.yml
  playbooks/openshift-master/private/config.yml
  playbooks/openshift-master/private/upgrade.yml
  playbooks/openshift-master/private/validate_restart.yml
  roles/calico/tasks/main.yml
  roles/calico_master/tasks/certs.yml
  roles/container_runtime/tasks/common/post.yml
  roles/container_runtime/tasks/package_docker.yml
  roles/contiv/tasks/old_version_cleanup.yml
  roles/contiv_facts/tasks/main.yml
  roles/etcd/tasks/backup/backup.yml
  roles/etcd/tasks/certificates/backup_ca_certificates.yml
  roles/etcd/tasks/certificates/backup_generated_certificates.yml
  roles/etcd/tasks/certificates/deploy_ca.yml
  roles/etcd/tasks/certificates/fetch_client_certificates_from_ca.yml
  roles/etcd/tasks/certificates/fetch_server_certificates_from_ca.yml
  roles/etcd/tasks/upgrade_static.yml
  roles/lib_utils/src/test/integration/yedit.yml
  roles/nuage_ca/tasks/main.yaml
  roles/nuage_master/tasks/etcd_certificates.yml
  roles/openshift_ca/tasks/main.yml
  roles/openshift_control_plane/tasks/check_existing_config.yml
  roles/openshift_control_plane/tasks/generate_session_secrets.yml
  roles/openshift_control_plane/tasks/upgrade.yml
  roles/openshift_excluder/tasks/exclude.yml
  roles/openshift_excluder/tasks/unexclude.yml
  roles/openshift_logging/tasks/generate_certs.yaml
  roles/openshift_logging/tasks/generate_jks.yaml
  roles/openshift_logging/tasks/generate_pems.yaml
  roles/openshift_logging/tasks/procure_server_certs.yaml
  roles/openshift_logging/tasks/procure_shared_key.yaml
  roles/openshift_logging_elasticsearch/tasks/main.yaml
  roles/openshift_logging_kibana/tasks/main.yaml
  roles/openshift_master_certificates/tasks/main.yml
  roles/openshift_master_facts/tasks/main.yml
  roles/openshift_node/tasks/bootstrap.yml
  roles/openshift_node/tasks/journald.yml
  roles/openshift_node/tasks/registry_auth.yml
  roles/openshift_node/templates/bootstrap.yml.j2
  roles/openshift_node_certificates/tasks/main.yml
  roles/openshift_prometheus/tasks/install_prometheus.yaml
  roles/openshift_service_catalog/tasks/install.yml
Labels: approved, lgtm, size/L

#9416 add conditional clauses for handling cnx versions
  roles/calico_master/tasks/main.yml
Labels: approved, lgtm, size/XS

#9443 Quote registry credentials for skopeo
  roles/lib_utils/library/docker_creds.py
Labels: approved, lgtm, size/XS

#9456 pylint: disable travis error
  roles/lib_openshift/library/oc_obj.py
  roles/lib_openshift/src/class/oc_obj.py
Labels: approved, lgtm, size/XS

#9466 Moving file to the image to fix error on localhost.
  playbooks/azure/openshift-cluster/build_node_image.yml
Labels: approved, lgtm, size/S

#9467 Bump OLM version to 0.6.0
  roles/olm/files/01-alm-operator.serviceaccount.yaml
  roles/olm/files/02-alm-operator.rolebinding.yaml
  roles/olm/files/03-clusterserviceversion.crd.yaml
  roles/olm/files/05-catalogsource.crd.yaml
  roles/olm/files/06-installplan.crd.yaml
  roles/olm/files/07-subscription.crd.yaml
  roles/olm/files/08-ocs.configmap.yaml
  roles/olm/files/10-ocs.catalogsource.yaml
  roles/olm/files/12-alm-operator.deployment.yaml
  roles/olm/files/13-catalog-operator.deployment.yaml
  roles/olm/files/20-aggregated-edit.clusterrole.yaml
  roles/olm/files/20-aggregated.clusterrole.yaml
  roles/olm/files/21-aggregated-view.clusterrole.yaml
  roles/olm/tasks/install.yaml
Labels: approved, lgtm, size/XXL

#9457 Renames CRI-O pause_image to openshift_crio_pause_image.
  roles/container_runtime/defaults/main.yml
  roles/container_runtime/templates/crio.conf.j2
Labels: approved, lgtm, size/S

#9301 router-redeploy: don't check that annotations are missing
  playbooks/openshift-hosted/private/redeploy-router-certificates.yml
Labels: approved, lgtm, size/XS

#9455 [3.9] faster stat
  playbooks/byo/calico/legacy_upgrade.yml
  playbooks/init/basic_facts.yml
  playbooks/openshift-logging/private/config.yml
  playbooks/openshift-master/private/certificates-backup.yml
  playbooks/openshift-master/private/clean_preinstalled_conf.yml
  playbooks/openshift-master/private/config.yml
  playbooks/openshift-master/private/set_network_facts.yml
  playbooks/openshift-master/private/tasks/wire_aggregator.yml
  playbooks/openshift-master/private/upgrade.yml
  playbooks/openshift-master/private/validate_restart.yml
  roles/calico/tasks/main.yml
  roles/calico_master/tasks/certs.yml
  roles/container_runtime/tasks/common/post.yml
  roles/container_runtime/tasks/package_docker.yml
  roles/container_runtime/tasks/registry_auth.yml
  roles/contiv/tasks/old_version_cleanup.yml
  roles/contiv_facts/tasks/main.yml
  roles/etcd/tasks/backup/backup.yml
  roles/etcd/tasks/certificates/backup_ca_certificates.yml
  roles/etcd/tasks/certificates/backup_generated_certificates.yml
  roles/etcd/tasks/certificates/deploy_ca.yml
  roles/etcd/tasks/certificates/fetch_client_certificates_from_ca.yml
  roles/etcd/tasks/certificates/fetch_server_certificates_from_ca.yml
  roles/etcd/tasks/upgrade/upgrade_image.yml
  roles/nuage_ca/tasks/main.yaml
  roles/nuage_master/tasks/etcd_certificates.yml
  roles/openshift_ca/tasks/main.yml
  roles/openshift_etcd_facts/tasks/set_etcd_ca_host.yml
  roles/openshift_excluder/tasks/exclude.yml
  roles/openshift_excluder/tasks/main.yml
  roles/openshift_excluder/tasks/unexclude.yml
  roles/openshift_logging/tasks/generate_certs.yaml
  roles/openshift_logging/tasks/generate_jks.yaml
  roles/openshift_logging/tasks/generate_pems.yaml
  roles/openshift_logging/tasks/procure_server_certs.yaml
  roles/openshift_logging/tasks/procure_shared_key.yaml
  roles/openshift_logging_elasticsearch/tasks/main.yaml
  roles/openshift_logging_kibana/tasks/main.yaml
  roles/openshift_master/tasks/registry_auth.yml
  roles/openshift_master/tasks/upgrade.yml
  roles/openshift_master_certificates/tasks/main.yml
  roles/openshift_master_facts/tasks/main.yml
  roles/openshift_node/tasks/bootstrap.yml
  roles/openshift_node/tasks/journald.yml
  roles/openshift_node/tasks/registry_auth.yml
  roles/openshift_node/templates/bootstrap.yml.j2
  roles/openshift_node_certificates/tasks/main.yml
  roles/openshift_prometheus/tasks/install_prometheus.yaml
  roles/openshift_repos/tasks/main.yaml
  roles/openshift_service_catalog/tasks/install.yml
  roles/os_firewall/tasks/main.yml
Labels: approved, lgtm, size/L

#9461 Revert "health checks: use etcd_image as it would work on Origin correctly"
  roles/openshift_health_checker/openshift_checks/docker_image_availability.py
  roles/openshift_health_checker/test/docker_image_availability_test.py
Labels: lgtm, size/XS

#9460 Fix openshift_openstack: Add public API Record
  roles/openshift_openstack/tasks/populate-dns.yml
Labels: approved, lgtm, size/XS

#9465 cluster-monitoring: pass through http(s) proxy settings
  roles/openshift_cluster_monitoring_operator/templates/cluster-monitoring-operator-config.j2
Labels: approved, lgtm, size/XS

#9181 Remove several unused vars
  playbooks/openshift-master/private/config.yml
  playbooks/openshift-master/private/upgrade.yml
  playbooks/openshift-node/private/join.yml
  playbooks/openstack/sample-inventory/group_vars/all.yml
  roles/etcd/defaults/main.yaml
  roles/openshift_control_plane/defaults/main.yml
  roles/openshift_docker_gc/defaults/main.yml
  roles/openshift_examples/defaults/main.yml
  roles/openshift_expand_partition/defaults/main.yml
  roles/openshift_facts/defaults/main.yml
  roles/openshift_hosted/defaults/main.yml
  roles/openshift_hosted/tasks/registry.yml
  roles/openshift_loadbalancer/defaults/main.yml
  roles/openshift_manage_node/defaults/main.yml
  roles/openshift_node/defaults/main.yml
Labels: approved, size/L

#9459 Nuage Specific Changes for eVDF and some minor changes
  playbooks/openshift-master/private/config.yml
  roles/nuage_ca/tasks/main.yaml
  roles/nuage_master/defaults/main.yml
  roles/nuage_master/tasks/main.yaml
  roles/nuage_master/templates/nuage-infra-pod-config-daemonset.j2
  roles/nuage_master/templates/nuage-master-config-daemonset.j2
  roles/nuage_master/templates/nuage-node-config-daemonset.j2
  roles/nuage_master/templates/nuage-strongswan-pod-config-daemonset.j2
  roles/nuage_master/vars/main.yaml
  roles/nuage_node/defaults/main.yml
  roles/nuage_node/tasks/iptables.yml
  roles/nuage_node/vars/main.yaml
Labels: approved, lgtm, size/L

#9470 Remove master env migration module
  roles/lib_utils/library/master_env_config_migrate.py
  roles/lib_utils/test/test_master_env_config_migrate.py
Labels: approved, lgtm, size/L

#9481 Fix missing input_image name error.
  playbooks/azure/openshift-cluster/build_node_image.yml
Labels: approved, lgtm, size/XS

#9454 add OSA 3.11 repos for pre-release
  playbooks/azure/openshift-cluster/group_vars/all/yum_repos.yml
Labels: approved, lgtm, sig/azure, size/S

#9464 Fix master config migration module
  roles/lib_utils/library/master_env_config_migrate.py
  roles/lib_utils/test/test_master_env_config_migrate.py
Labels: approved, lgtm, size/M

#9448 Be more accuracy for getting def_route_int and def_route_ip
  roles/openshift_node/files/networkmanager/99-origin-dns.sh
Labels: approved, lgtm, size/XS

#9214 Don't enable excluders on Atomic
  roles/openshift_excluder/tasks/exclude.yml
Labels: approved, lgtm, size/M

#9490 add equals to quoted skopeo argument
  roles/lib_utils/library/docker_creds.py
Labels: approved, lgtm, size/XS

#9482 SDN check: Fix parsing time stamp's time zone
  roles/openshift_health_checker/openshift_checks/sdn.py
Labels: approved, lgtm, size/XS

#9495 move from latest to versioned repo
  playbooks/azure/openshift-cluster/group_vars/all/yum_repos.yml
Labels: lgtm, sig/azure, size/XS

#9475 Fix prometheus annotations typo
  roles/openshift_prometheus/tasks/install_prometheus.yaml
Labels: approved, lgtm, size/XS

#9324 Set claimRef for logging PVC when NFS volume is created
  roles/openshift_logging_elasticsearch/tasks/main.yaml
  roles/openshift_sanitize_inventory/tasks/__deprecations_logging.yml
Labels: approved, lgtm, size/S

#9486 [Bug 1609027] Add quotes to docker gc node selector
  roles/openshift_docker_gc/templates/dockergc-ds.yaml.j2
Labels: approved, lgtm, size/XS

#9499 Revert "openshift_loadbalancer: remove unused vars"
  roles/openshift_loadbalancer/defaults/main.yml
Labels: approved, lgtm

#9515 Ensure kernel-modules not installed on atomic
  roles/openshift_storage_glusterfs/tasks/kernel_modules.yml
Labels: approved, lgtm, size/XS

#9487 loopback_cluster_name: use api_hostname
  roles/openshift_facts/library/openshift_facts.py
Labels: approved, lgtm, size/XS

#9520 'Wait for node to be ready' task should check that all vars are defined
  roles/openshift_node/tasks/upgrade.yml
Labels: approved, lgtm, size/XS

#9512 Fix master env migrate module comments
  roles/lib_utils/library/master_env_config_migrate.py
  roles/lib_utils/test/test_master_env_config_migrate.py
Labels: approved, size/XS

#9485 Bug 1543129 - Add configuration option for ASB local registry namespaces
  roles/ansible_service_broker/defaults/main.yml
  roles/ansible_service_broker/templates/configmap.yaml.j2
Labels: approved, lgtm, size/XS

#9488 [Bug 1609907] Remove node CSR approval from upgrade in 3.11
  roles/openshift_node/tasks/upgrade/restart.yml
Labels: approved, lgtm, size/XS

#7581 Making the app nodes an optional return.
  playbooks/openstack/inventory.py
Labels: approved, lgtm, size/XS

#9505 Adding min-port to dnsmasq configuration.
  roles/openshift_node/files/networkmanager/99-origin-dns.sh
  roles/openshift_node/templates/origin-dns.conf.j2
Labels: approved, lgtm, size/XS

#9541 [3.9] Adding min-port to dnsmasq configuration
  roles/openshift_node/files/networkmanager/99-origin-dns.sh
  roles/openshift_node/templates/origin-dns.conf.j2
Labels: lgtm, size/XS

#9539 [3.7] Adding min-port to dnsmasq configuration
  roles/openshift_node_dnsmasq/files/networkmanager/99-origin-dns.sh
  roles/openshift_node_dnsmasq/templates/origin-dns.conf.j2
Labels: lgtm, size/XS

#9530 [Bug 1614003] Conditionally skip node approval for incremental 3.10 upgrades
  roles/openshift_node/tasks/upgrade.yml
  roles/openshift_node/tasks/upgrade/restart.yml
Labels: approved, lgtm, size/S

#9500 SCC recouncilation has to run with older oc, before node upgrade
  playbooks/common/openshift-cluster/upgrades/v3_11/upgrade_control_plane.yml
  playbooks/openshift-master/private/upgrade.yml
Labels: approved, lgtm, size/M

#9507 [bz1552516] set the external url of prometheus
  roles/openshift_prometheus/templates/prometheus.j2
Labels: approved, lgtm, size/XS

#9549 [release-3.9]: Add CentoOS Origin repo for 39 release
  roles/openshift_repos/templates/CentOS-OpenShift-Origin39.repo.j2
Labels: lgtm, size/S

#9473 adding parameters to allow for load balancer creation
  roles/openshift_cloud_provider/templates/azure.conf.j2
  roles/openshift_sanitize_inventory/tasks/main.yml
Labels: approved, lgtm, size/XS

#9501 Update console branding and doc URL for OKD
  roles/openshift_console/defaults/main.yml
Labels: approved, lgtm, size/XS

#9527 Update release artifacts for OLM
  roles/olm/files/08-ocs.configmap.yaml
  roles/olm/files/08-tectonicocs.configmap.yaml
  roles/olm/files/10-tectonicocs.catalogsource.yaml
  roles/olm/files/14-alm-servicebroker.clusterservicebroker.yaml
  roles/olm/files/15-alm-servicebroker.service.yaml
  roles/olm/files/16-almservicebroker-client.secret.yaml
  roles/olm/files/17-alm-servicebroker.deployment.yaml
  roles/olm/files/18-upstreamcomponents.configmap.yaml
  roles/olm/files/19-upstreamcomponents.catalogsource.yaml
  roles/olm/files/20-aggregated.clusterrole.yaml
  roles/olm/tasks/install.yaml
  roles/olm/tasks/remove_components.yaml
Labels: approved, lgtm, size/XXL

#9209 Fixes #5174: Remove unnecessary passlib check
  roles/openshift_metrics/tasks/main.yaml
Labels: approved, lgtm, size/S

#9526 [uninstall] Remove hyperkube package
  playbooks/adhoc/uninstall_openshift.yml
Labels: approved, lgtm, size/XS

#9477 openshift_cluster_monitoring_operator: Fix enterprise images
  roles/openshift_cluster_monitoring_operator/defaults/main.yml
Labels: approved, lgtm, size/M

#9497 Switch to oc set env, since oc env is now removed
  playbooks/openshift-hosted/private/redeploy-registry-certificates.yml
  playbooks/openshift-hosted/private/redeploy-router-certificates.yml
Labels: approved, lgtm, size/XS

#9468 GlusterFS: Upgrade playbook
  playbooks/openshift-glusterfs/private/upgrade.yml
  playbooks/openshift-glusterfs/upgrade.yml
  roles/openshift_storage_glusterfs/defaults/main.yml
  roles/openshift_storage_glusterfs/files/glusterfs-template.yml
  roles/openshift_storage_glusterfs/files/heketi-template.yml
  roles/openshift_storage_glusterfs/tasks/check_cluster_health.yml
  roles/openshift_storage_glusterfs/tasks/cluster_health.yml
  roles/openshift_storage_glusterfs/tasks/glusterfs_common.yml
  roles/openshift_storage_glusterfs/tasks/glusterfs_config_facts.yml
  roles/openshift_storage_glusterfs/tasks/glusterfs_deploy.yml
  roles/openshift_storage_glusterfs/tasks/glusterfs_registry_facts.yml
  roles/openshift_storage_glusterfs/tasks/glusterfs_restart_pod.yml
  roles/openshift_storage_glusterfs/tasks/glusterfs_upgrade.yml
  roles/openshift_storage_glusterfs/tasks/heketi_deploy.yml
  roles/openshift_storage_glusterfs/tasks/heketi_deploy_part2.yml
  roles/openshift_storage_glusterfs/tasks/heketi_get_key.yml
  roles/openshift_storage_glusterfs/tasks/heketi_init_db.yml
  roles/openshift_storage_glusterfs/tasks/heketi_init_deploy.yml
  roles/openshift_storage_glusterfs/tasks/heketi_load.yml
  roles/openshift_storage_glusterfs/tasks/heketi_pod_check.yml
  roles/openshift_storage_glusterfs/tasks/heketi_setup.yml
  roles/openshift_storage_glusterfs/tasks/upgrade.yml
  roles/openshift_storage_glusterfs/tasks/wait_for_pods.yml
  roles/openshift_storage_glusterfs/templates/heketi-endpoints.yml.j2
  roles/openshift_storage_glusterfs/templates/heketi-service.yml.j2
Labels: approved, lgtm, size/XL

#9506 Don't require some RPMs to be available in the repos due to switch to static pods
  playbooks/azure/openshift-cluster/group_vars/all/yum_repos.yml
  roles/openshift_health_checker/openshift_checks/package_availability.py
  roles/openshift_health_checker/test/package_availability_test.py
  roles/openshift_repos/tasks/rhel_repos.yml
Labels: approved, lgtm, size/S

#9510 Fix the ansible-service-broker URL
  roles/ansible_service_broker/tasks/install.yml
Labels: approved, lgtm, size/XS

#9563 [3.10] node restart: check that all vars are defined
  playbooks/openshift-node/private/restart.yml
Labels: approved, lgtm, size/XS

#9513 Ensure docker package always installed
  roles/container_runtime/tasks/package_docker.yml
Labels: approved, lgtm, size/XS

#9445 Limiting additional fact collection to non-masters
  playbooks/openshift-logging/private/config.yml
Labels: approved, lgtm, size/XS

#9567 cluster-monitoring: Fix OCP image names
  roles/openshift_cluster_monitoring_operator/defaults/main.yml
Labels: approved, lgtm, size/XS

#9492 Aws dns
  playbooks/aws/openshift-cluster/provision.yml
  playbooks/aws/openshift-cluster/provision_dns.yml
  roles/lib_utils/filter_plugins/oo_filters.py
  roles/openshift_aws/defaults/main.yml
  roles/openshift_aws/tasks/build_elb_dict.yml
  roles/openshift_aws/tasks/dns.yml
  roles/openshift_aws/tasks/dns_route53.yml
  roles/openshift_aws/tasks/provision_dns.yml
Labels: approved, lgtm, size/L

#9502 Update documentation links, docs.openshift.org -> docs.okd.io
  README.md
  README_CONTAINER_IMAGE.md
  examples/README.md
  inventory/hosts.example
  playbooks/byo/README.md
  playbooks/common/openshift-cluster/upgrades/v3_11/upgrade_control_plane.yml
  playbooks/init/validate_hostnames.yml
  playbooks/openshift-master/private/upgrade.yml
  playbooks/openstack/README.md
  playbooks/openstack/configuration.md
  roles/openshift_health_checker/openshift_checks/disk_availability.py
  roles/openshift_health_checker/openshift_checks/memory_availability.py
  roles/openshift_logging/README.md
  roles/openshift_metrics/README.md
Labels: approved, lgtm, size/M

#9529 [release-3.10]: Update openshift_release version in sample inventory
  inventory/hosts.example
Labels: approved, lgtm, size/XS

#9542 [3.10] Adding min-port to dnsmasq configuration
  roles/openshift_node/files/networkmanager/99-origin-dns.sh
  roles/openshift_node/templates/origin-dns.conf.j2
Labels: approved, lgtm, size/XS

#9580 Minor Docs updates
  README.md
  README_CONTAINERIZED_INSTALLATION.md
  inventory/hosts.example
  playbooks/adhoc/uninstall_docker.yml
  playbooks/adhoc/uninstall_openshift.yml
  playbooks/common/openshift-cluster/upgrades/post_control_plane.yml
  roles/lib_openshift/library/oc_service.py
  roles/lib_openshift/src/doc/service
  roles/openshift_control_plane/templates/master.env.j2
  roles/openshift_storage_nfs_lvm/defaults/main.yml
  roles/rhel_subscribe/README.md
Labels: approved, lgtm, size/S

#9483 Fixes BZ 1596448
  playbooks/common/openshift-cluster/evaluate_groups.yml
Labels: lgtm, size/XS

#9447 Refactor registry-console template and vars
  playbooks/common/openshift-cluster/upgrades/post_control_plane.yml
  playbooks/openshift-master/private/additional_config.yml
  roles/cockpit-ui/defaults/main.yml
  roles/cockpit-ui/files/registry-console.yaml
  roles/cockpit-ui/tasks/main.yml
  roles/lib_utils/action_plugins/sanity_checks.py
  roles/openshift_facts/defaults/main.yml
  roles/openshift_hosted_templates/defaults/main.yml
  roles/openshift_hosted_templates/files/v3.10/enterprise/registry-console.yaml
  roles/openshift_hosted_templates/files/v3.11/enterprise/registry-console.yaml
  roles/openshift_hosted_templates/files/v3.11/origin/registry-console.yaml
  roles/openshift_hosted_templates/meta/main.yml
  roles/openshift_hosted_templates/sync-templates.sh
  roles/openshift_hosted_templates/tasks/main.yml
  roles/openshift_logging_defaults/defaults/main.yml
  roles/openshift_prometheus/defaults/main.yaml
Labels: approved, lgtm, size/XL

#9551 Add CentoOS Origin repo for 310 release
  roles/openshift_repos/templates/CentOS-OpenShift-Origin310.repo.j2
Labels: approved, lgtm, size/S

#9431 fixing image defaults for logging
  roles/openshift_logging_defaults/defaults/main.yml
Labels: approved, lgtm, size/XS

#9479 To avoid I/O errors, carry out vg deactivate (using vgchange -an)
  roles/openshift_storage_glusterfs/tasks/glusterfs_uninstall.yml
Labels: approved, lgtm, size/XS

#9528 Revert "loopback_cluster_name: use api_hostname"
  roles/openshift_facts/library/openshift_facts.py
Labels: approved, lgtm, size/XS

#9562 node restart: check that all vars are defined
  playbooks/openshift-node/private/restart.yml
Labels: approved, lgtm, size/XS

#9574 Update Commands in Nuage Roles to Restart Master API Server and Controller
  roles/nuage_master/handlers/main.yaml
  roles/nuage_master/tasks/main.yaml
Labels: approved, lgtm, size/M

#9553 [3.9] set the external url of prometheus
  roles/openshift_prometheus/templates/prometheus.j2
Labels: size/XS

#9521 CFME: set default value for openshift_hosted_infra_selector
  roles/openshift_management/defaults/main.yml
Labels: approved, lgtm, size/XS

#9568 Cleanup logging and metrics deprecations
  images/installer/root/etc/inventory-generator-config.yaml
  images/installer/root/usr/local/bin/generate
  roles/lib_utils/action_plugins/sanity_checks.py
  roles/openshift_health_checker/openshift_checks/logging/fluentd_config.py
  roles/openshift_health_checker/openshift_checks/logging/logging.py
  roles/openshift_health_checker/test/logging_check_test.py
  roles/openshift_logging/tasks/install_logging.yaml
  roles/openshift_logging_curator/defaults/main.yml
  roles/openshift_logging_curator/tasks/main.yaml
  roles/openshift_logging_elasticsearch/defaults/main.yml
  roles/openshift_logging_elasticsearch/tasks/main.yaml
  roles/openshift_logging_fluentd/defaults/main.yml
  roles/openshift_logging_fluentd/tasks/main.yaml
  roles/openshift_logging_kibana/defaults/main.yml
  roles/openshift_logging_kibana/tasks/main.yaml
  roles/openshift_logging_mux/defaults/main.yml
  roles/openshift_logging_mux/tasks/main.yaml
  roles/openshift_master_facts/tasks/main.yml
  roles/openshift_sanitize_inventory/tasks/__deprecations_logging.yml
  roles/openshift_sanitize_inventory/tasks/__deprecations_metrics.yml
  roles/openshift_sanitize_inventory/tasks/deprecations.yml
  roles/openshift_sanitize_inventory/vars/main.yml
Labels: approved, lgtm, size/L

#9591 Adding default value for openshift_logging_storage_kind
  roles/openshift_logging_elasticsearch/tasks/main.yaml
Labels: approved, lgtm, size/XS

#9593 fix ASB ClusterServiceBroker removal
  roles/ansible_service_broker/tasks/remove.yml
Labels: approved, lgtm, size/XS

#9582 change default sc name
  roles/openshift_default_storage_class/defaults/main.yml
Labels: approved, lgtm, size/XS

#9610 [BACKPORT] Update routers that are defined in openshift_hosted_routers
  roles/openshift_hosted/tasks/upgrade_routers.yml
Labels: lgtm, size/S

#9612 Remove pod filtering
  playbooks/common/openshift-cluster/upgrades/post_control_plane.yml
Labels: lgtm, size/XS

#9159 Specify external URL for Prometheus
  roles/openshift_prometheus/templates/prometheus.j2
Labels: approved, lgtm, size/XS

#9589 Remove unused/broken node cert plays
  playbooks/openshift-node/certificates.yml
  playbooks/openshift-node/private/certificates-backup.yml
  playbooks/openshift-node/private/certificates.yml
  playbooks/openshift-node/private/redeploy-certificates.yml
  playbooks/openshift-node/redeploy-certificates.yml
  playbooks/redeploy-certificates.yml
  roles/openshift_node_certificates/OWNERS
  roles/openshift_node_certificates/README.md
  roles/openshift_node_certificates/defaults/main.yml
  roles/openshift_node_certificates/handlers/main.yml
  roles/openshift_node_certificates/meta/main.yml
  roles/openshift_node_certificates/tasks/main.yml
  roles/openshift_node_certificates/vars/main.yml
Labels: approved, lgtm, size/L

#9620 Fix audit config interpolation
  roles/openshift_control_plane/templates/master.yaml.v1.j2
  roles/openshift_master_facts/tasks/main.yml
Labels: approved, lgtm, size/XS

#9627 Remove duplicated bootstrapped SCC check
  playbooks/common/openshift-cluster/upgrades/v3_11/upgrade_control_plane.yml
Labels: approved, lgtm, size/S

#9561 [release-3.9] [Bug 1614916] Default 3.9 to use RPM based CRI-O install
  inventory/hosts.example
  playbooks/container-runtime/private/config.yml
  playbooks/init/basic_facts.yml
  roles/container_runtime/README.md
  roles/container_runtime/defaults/main.yml
  roles/container_runtime/tasks/systemcontainer_crio.yml
  roles/openshift_cli/defaults/main.yml
  roles/openshift_cli/tasks/main.yml
  roles/openshift_sanitize_inventory/vars/main.yml
Labels: lgtm, size/L

#9614 The file name has changed to heketi_get_key.yml
  roles/openshift_storage_glusterfs/tasks/update_topology.yml
Labels: approved, lgtm, size/XS

#9615 [release-3.10] [Bug 1618425] Remove system container cri-o during 3.10 upgrade
  roles/openshift_node/tasks/upgrade.yml
  roles/openshift_node/tasks/upgrade/restart.yml
Labels: approved, lgtm, size/S

#9629 [3.10] Fix audit config interpolation
  roles/openshift_control_plane/templates/master.yaml.v1.j2
  roles/openshift_master_facts/tasks/main.yml
Labels: approved, lgtm, size/XS

#9511 SDN check: Ignore node's canonical name
  roles/openshift_health_checker/openshift_checks/sdn.py
  roles/openshift_health_checker/test/sdn_tests.py
Labels: approved, lgtm, size/M

#9579 Added support for ak when registering hosts
  roles/rhel_subscribe/README.md
  roles/rhel_subscribe/tasks/main.yml
Labels: approved, lgtm, size/S

#9606 Updating to only iterate over oo_nodes_to_config list for oo_elasticsearch_nodes
  playbooks/openshift-logging/private/config.yml
Labels: approved, lgtm, size/XS

#9613 Bug 1615275. Regenerate session_secret if it can't be used with oauth-proxy
  roles/openshift_logging_kibana/tasks/main.yaml
Labels: approved, lgtm, size/XS

#9625 Default CFME nodeselector should be a list of str, not a dict
  roles/openshift_management/defaults/main.yml
Labels: approved, lgtm, size/XS

#9635 Update for Bugzilla 1580256
  playbooks/aws/README.md
Labels: approved, lgtm, size/XS

#9618 Provide better error message for json sanity check
  roles/lib_utils/action_plugins/sanity_checks.py
Labels: approved, lgtm, size/XS

#9634 service-catalog: use K8s NamespaceLifecycle admission controller
  roles/openshift_service_catalog/templates/api_server.j2
Labels: approved, lgtm, size/XS

#9623 [OSA]remove name from tag
  playbooks/azure/openshift-cluster/build_node_image.yml
Labels: approved, lgtm, sig/azure, size/XS

#9603 Remove asb-user-access cluster-role when uninstalling ASB
  roles/ansible_service_broker/tasks/remove.yml
Labels: approved, lgtm, size/XS

#9644 Revert 9607 registry console component
  roles/cockpit-ui/defaults/main.yml
Labels: approved, lgtm, size/S

#9650 [Bug 1611818] Use openshift_image_tag for registry-console upgrade
  roles/openshift_hosted/tasks/upgrade_registry.yml
Labels: affects_3.10, affects_3.9, approved, lgtm, size/XS

#9652 Remove 3.10 upgrade playbooks
  playbooks/byo/openshift-cluster/upgrades/README.md
  playbooks/byo/openshift-cluster/upgrades/v3_10/README.md
  playbooks/byo/openshift-cluster/upgrades/v3_10/upgrade.yml
  playbooks/byo/openshift-cluster/upgrades/v3_10/upgrade_control_plane.yml
  playbooks/byo/openshift-cluster/upgrades/v3_10/upgrade_nodes.yml
  playbooks/byo/openshift-cluster/upgrades/v3_10/upgrade_scale_groups.yml
  playbooks/common/openshift-cluster/upgrades/v3_10/label_nodes.yml
  playbooks/common/openshift-cluster/upgrades/v3_10/master_config_upgrade.yml
  playbooks/common/openshift-cluster/upgrades/v3_10/roles
  playbooks/common/openshift-cluster/upgrades/v3_10/upgrade.yml
  playbooks/common/openshift-cluster/upgrades/v3_10/upgrade_control_plane.yml
  playbooks/common/openshift-cluster/upgrades/v3_10/upgrade_nodes.yml
  playbooks/gcp/openshift-cluster/upgrade.yml
Labels: approved, lgtm, size/L

#9655 Require Ansible 2.6.2
  README.md
  openshift-ansible.spec
  requirements.txt
  roles/lib_utils/callback_plugins/aa_version_requirement.py
Labels: approved, lgtm, size/XS

#9646 [release-3.9] [Bug 1553213] Upgrade cri-o during 3.9 upgrade
  roles/openshift_node/files/clean-up-crio-pods.sh
  roles/openshift_node/tasks/upgrade.yml
  roles/openshift_node/tasks/upgrade/restart.yml
  roles/openshift_node/tasks/upgrade/stop_services.yml
  roles/openshift_node/tasks/upgrade_pre.yml
Labels: lgtm, size/L

#9649 Clean up GCP disks during deprovision
  roles/openshift_gcp/templates/remove.j2.sh
Labels: approved, lgtm, size/S

#9670 Revert "Skip base package check for openshift_ca role"
  roles/openshift_ca/tasks/main.yml
Labels: approved, lgtm, size/S

#9640 Revert SCC change and fix SCC verification
  playbooks/common/openshift-cluster/upgrades/v3_11/upgrade_control_plane.yml
  playbooks/openshift-master/private/upgrade.yml
Labels: approved, lgtm, size/M

#9566 Cleanup old sanitize inventory warnings
  inventory/hosts.example
  roles/openshift_node/defaults/main.yml
  roles/openshift_node/tasks/dnsmasq/network-manager.yml
  roles/openshift_sanitize_inventory/tasks/unsupported.yml
Labels: approved, lgtm, size/S

#9658 [release-3.10] [Bug 1572857] Remove atomic-openshift-master package during upgrade
  roles/openshift_control_plane/tasks/upgrade.yml
Labels: approved, lgtm, size/XS

#9676 Update openshift-metering to 0.7.0-latest
  playbooks/openshift-metering/README.md
  roles/openshift_metering/README.md
  roles/openshift_metering/files/crds/metering.crd.yaml
  roles/openshift_metering/files/crds/prestotable.crd.yaml
  roles/openshift_metering/files/crds/report.crd.yaml
  roles/openshift_metering/files/crds/reportdatasource.crd.yaml
  roles/openshift_metering/files/crds/reportgenerationquery.crd.yaml
  roles/openshift_metering/files/crds/reportprometheusquery.crd.yaml
  roles/openshift_metering/files/crds/scheduledreport.crd.yaml
  roles/openshift_metering/files/crds/storagelocation.crd.yaml
  roles/openshift_metering/files/operator/metering-operator-deployment.yaml
  roles/openshift_metering/files/operator/metering-operator-role.yaml
  roles/openshift_metering/files/operator/metering-operator-rolebinding.yaml
  roles/openshift_metering/files/operator/metering-operator-service-account.yaml
  roles/openshift_metering/files/operator/metering.yaml
  roles/openshift_metering/tasks/operator-install.yml
Labels: approved, lgtm, size/L

#9679 [release-3.9] Fix conditional for cri-o system container removal
  roles/openshift_node/tasks/upgrade.yml
Labels: lgtm, size/XS

#9662 Removing unnecessary fail task during rhel_subscribe
  roles/rhel_subscribe/tasks/main.yml
Labels: approved, lgtm, size/XS

#9684 GlusterFS: Remove domain from heketi URL
  roles/openshift_storage_glusterfs/templates/glusterfs-storageclass.yml.j2
Labels: approved, lgtm, size/XS

#9682 Bug 1615787 - Blacklist broker-apb
  roles/ansible_service_broker/tasks/facts.yml
  roles/ansible_service_broker/templates/configmap.yaml.j2
  roles/ansible_service_broker/vars/default_images.yml
  roles/ansible_service_broker/vars/openshift-enterprise.yml
Labels: approved, lgtm, size/XS

#9218 Rework node initialization procedure to fit non-network tasks after prepull
  roles/openshift_node/tasks/config.yml
  roles/openshift_node/tasks/main.yml
  roles/openshift_node/tasks/prepull.yml
Labels: approved, lgtm, size/M
