Repository openshift/openshift-ansible, pull requests merged in 2018-11, with the labels that each got.

#10571 [release-3.11] OSP provisioning of separate 'etcd' instances (Backporting PR 10541 to release-3.11)
  playbooks/openstack/configuration.md
  playbooks/openstack/resources.py
  playbooks/openstack/sample-inventory/group_vars/all.yml
  roles/openshift_openstack/defaults/main.yml
Labels: approved, lgtm, size/M

#10567 osa - add oreg_url check
  playbooks/azure/openshift-cluster/build_node_image.yml
Labels: approved, lgtm, size/XS

#10580 glusterfs: Fix a typo in the README
  roles/openshift_storage_glusterfs/README.md
Labels: approved, lgtm, size/XS

#10593 added needed space in error message as stated in bug# 1645718
  roles/lib_utils/action_plugins/sanity_checks.py
Labels: approved, lgtm, size/XS

#10583 [release-3.11] Fix master-config.yaml path
  roles/openshift_control_plane/tasks/upgrade.yml
Labels: approved, size/XS

#10579 [3.11] Adhoc fix first atomic master after upgrade fails
  playbooks/byo/openshift-cluster/upgrades/v3_11/fix_first_master_node.yml
  playbooks/common/openshift-cluster/upgrades/v3_11/fix_first_master_node.yml
Labels: approved, size/M

#10586 [3.11] Replace undefined {{ item }} by filename
  roles/openshift_storage_glusterfs/tasks/gluster_s3_deploy.yml
Labels: approved, lgtm, size/XS

#10585 [3.10] Replace undefined {{ item }} by filename
  roles/openshift_storage_glusterfs/tasks/gluster_s3_deploy.yml
Labels: approved, lgtm, size/XS

#10528 [release-3.7] Walk the node_output for undefined
  playbooks/common/openshift-node/restart.yml
  roles/openshift_node_upgrade/tasks/main.yml
Labels: size/S

#10605 [release-3.10] Remove openshift_disable_swap for new install
  roles/openshift_node/tasks/main.yml
Labels: approved, lgtm, size/XS

#10604 [release-3.11] Remove openshift_disable_swap for new install
  roles/openshift_node/tasks/main.yml
Labels: approved, lgtm, size/XS

#10573 fix gce-logging problem
  playbooks/openshift-logging/private/config.yml
Labels: approved, lgtm, size/S

#10506 Add instructions to use cri-o in openstack
  playbooks/openstack/configuration.md
  roles/openshift_openstack/defaults/main.yml
Labels: approved, lgtm, size/L

#10507 [openstack] Run the init/main playbook properly
  playbooks/openstack/openshift-cluster/install.yml
  playbooks/openstack/openshift-cluster/provision.yml
Labels: approved, lgtm, size/S

#10610 Add Openshift 3.11 yum.repos.d file
  roles/openshift_repos/templates/CentOS-OpenShift-Origin311.repo.j2
Labels: approved, lgtm, size/S

#10613 Fix broken link in README.md
  README.md
Labels: approved, lgtm, retest-not-required-docs-only, size/XS

#10590 openshift_prometheus: cleanup unused variables
  roles/lib_utils/action_plugins/sanity_checks.py
  roles/openshift_facts/defaults/main.yml
Labels: approved, lgtm, size/S

#10611 add default(false) to openshift_autoheal_deploy
  roles/openshift_autoheal/tasks/main.yml
Labels: approved, lgtm, size/XS

#10612 Fix master paths check, while using Istio
  roles/lib_utils/action_plugins/master_check_paths_in_config.py
Labels: approved, lgtm, size/XS

#10621 Don't attemp to install packages on atomic
  roles/openshift_certificate_expiry/tasks/main.yml
Labels: approved, lgtm, size/XS

#9307 Update crio.conf.j2 template for registries
  roles/container_runtime/tasks/package_crio.yml
  roles/container_runtime/tasks/package_docker.yml
  roles/container_runtime/templates/crio.conf.j2
  roles/container_runtime/templates/registries.conf
  roles/container_runtime/templates/registries.conf.j2
Labels: approved, lgtm, size/M

#10608 Restart docker after openstack storage setup
  roles/openshift_openstack/defaults/main.yml
  roles/openshift_openstack/tasks/container-storage-setup.yml
Labels: approved, lgtm, size/S

#10629 [release-3.10] Add readiness + liveness probes for Service Catalog
  roles/openshift_service_catalog/templates/api_server.j2
  roles/openshift_service_catalog/templates/controller_manager.j2
Labels: approved, lgtm, size/M

#10634 Mount /etc/pki into controller pod
  roles/openshift_control_plane/files/controller.yaml
Labels: approved, lgtm, size/XS

#10619 Update centos_repos.yml
  roles/openshift_repos/tasks/centos_repos.yml
Labels: approved, lgtm, size/XS

#10494 Add pull request template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: approved, size/S

#10625 [release-3.11] Add readiness + liveness probes for Service Catalog
  roles/openshift_service_catalog/templates/api_server.j2
  roles/openshift_service_catalog/templates/controller_manager.j2
Labels: approved, lgtm, size/M

#10641 Start node image prepull after CRIO is restarted
  roles/openshift_cli/tasks/main.yml
  roles/openshift_node/tasks/main.yml
Labels: approved, lgtm, size/S

#10633 [release 3.11] Restart docker after openstack storage setup
  roles/openshift_openstack/defaults/main.yml
  roles/openshift_openstack/tasks/container-storage-setup.yml
Labels: approved, lgtm, size/S

#10644 Simplify PR template
  .github/PULL_REQUEST_TEMPLATE.md
  README.md
Labels: size/M

#10310 sync: tolerate all taints
  roles/openshift_node_group/files/sync.yaml
  roles/openshift_sdn/files/sdn.yaml
Labels: approved, lgtm, size/XS

#10566 adding the github_ca parameter to ensure that when we have a GitHub i…
  inventory/hosts.example
  roles/lib_utils/filter_plugins/openshift_master.py
  roles/openshift_control_plane/tasks/main.yml
  roles/openshift_master_facts/tasks/main.yml
Labels: approved, lgtm, size/M

#10627 devel-4.0: several fixes
  images/installer/Dockerfile
  roles/container_runtime/tasks/crio_firewall.yml
  roles/openshift_gcp/defaults/main.yml
  test/gcp/install.yml
Labels: approved, lgtm, size/S

#10615 openshift_prometheus: ignore router endpoint in kube service config
  roles/openshift_prometheus/templates/prometheus.yml.j2
Labels: lgtm, size/XS

#10508 handler restart master api fix
  playbooks/common/openshift-master/scaleup.yml
Labels: lgtm, size/XS

#10650 osa - move to liba mirror
  playbooks/azure/openshift-cluster/group_vars/all/yum_repos.yml
Labels: approved, lgtm, size/XS

#10649 osa remove crio
  playbooks/azure/openshift-cluster/build_node_image.yml
Labels: approved, lgtm, size/XS

#10643 Move install steps into playbooks
  playbooks/deploy_cluster_40.yml
  test/gcp/install.yml
Labels: approved, lgtm, size/L

#10642 [3.11] Start node image prepull after CRIO is restarted
  roles/openshift_node/tasks/main.yml
Labels: approved, lgtm, size/XS

#10529 [release-3.9] Walk the node_output for undefined
  playbooks/openshift-node/private/restart.yml
  roles/openshift_node/tasks/upgrade.yml
Labels: approved, lgtm, size/S

#10655 [release-3.11] Continue after failure of copying kubeconfig to user home dir.
  roles/openshift_master_certificates/tasks/main.yml
Labels: approved, lgtm, size/XS

#10675 [release 3.11] Check if docker is running before attempting to restart it
  roles/openshift_openstack/tasks/container-storage-setup.yml
Labels: approved, lgtm, size/XS

#10676 [release 3.10] Check if docker is running before attempting to restart it
  roles/openshift_openstack/tasks/container-storage-setup.yml
Labels: approved, lgtm, size/XS

#10631 Properly prefix certificate paths
  roles/calico/tasks/certs.yml
  roles/etcd/defaults/main.yaml
  roles/etcd/tasks/certificates/backup_server_certificates.yml
  roles/etcd/tasks/certificates/distribute_ca.yml
  roles/etcd/tasks/certificates/fetch_server_certificates_from_ca.yml
  roles/etcd/tasks/certificates/retrieve_ca_certificates.yml
Labels: approved, lgtm, size/M

#10678 Backport: Check both service catalog and install vars
  playbooks/common/openshift-cluster/upgrades/upgrade_components.yml
Labels: approved, lgtm, size/XS

#10658 [release 3.11] Service Catalog - wait for rollout of SC API Server & SC Controller Mgr
  roles/openshift_service_catalog/tasks/start.yml
Labels: approved, lgtm, size/M

#10706 [release-3.7] Minor update to rhel_subscribe role
  playbooks/common/openshift-node/restart.yml
  roles/rhel_subscribe/tasks/enterprise.yml
Labels: lgtm, size/S

#10645 Update node config template for crio
  roles/openshift_node_group/tasks/bootstrap.yml
  roles/openshift_node_group/templates/node-config.yaml.j2
Labels: approved, lgtm, size/S

#10713 [release-3.7] Allow openshift_install_examples to be false
  playbooks/common/openshift-cluster/upgrades/post_control_plane.yml
  playbooks/common/openshift-master/additional_config.yml
Labels: lgtm, size/XS

#10714 [release-3.9] Update openshift_facts version logic for release-3.9
  roles/openshift_facts/library/openshift_facts.py
Labels: lgtm, size/XS

#10681 Add network-project-id value for kubernetes config for GCP
  inventory/hosts.example
  roles/openshift_cloud_provider/tasks/gce.yml
  roles/openshift_gcp/defaults/main.yml
  roles/openshift_gcp/tasks/node_cloud_config.yml
Labels: approved, lgtm, size/XS

#10730 [release-3.10] Reload tuned service when node-config.yaml has changed.
  roles/openshift_node_group/files/sync.yaml
Labels: approved, lgtm, size/S

#10731 OVS: tolerate taints
  roles/openshift_sdn/files/sdn-ovs.yaml
Labels: approved, lgtm, size/XS

#10733 Add pyOpenSSL openshift-ansible dep
  openshift-ansible.spec
Labels: approved, lgtm, size/XS

#10732 Enhance parse_ignition file content decoding
  roles/lib_utils/action_plugins/parse_ignition.py
Labels: approved, lgtm, size/S

#10737 Add support for secret encryption
  inventory/hosts.example
  roles/openshift_control_plane/tasks/main.yml
  roles/openshift_control_plane/templates/master.yaml.v1.j2
  roles/openshift_control_plane/vars/main.yml
Labels: approved, lgtm, size/S

#10743 [release-3.10] Update node config template for crio
  roles/openshift_node_group/tasks/bootstrap.yml
  roles/openshift_node_group/templates/node-config.yaml.j2
Labels: approved, lgtm, size/S

#10744 [release-3.9] Check both service catalog and install vars
  playbooks/common/openshift-cluster/upgrades/upgrade_components.yml
Labels: lgtm, size/XS

#10747 [release-3.10] Use correct container CLI for docker or cri-o
  playbooks/byo/calico/legacy_upgrade.yml
  playbooks/common/openshift-cluster/upgrades/pre/verify_upgrade_targets.yml
  roles/calico/tasks/main.yml
  roles/contiv/tasks/aci.yml
  roles/etcd/tasks/static.yml
  roles/openshift_control_plane/tasks/pre_pull.yml
  roles/openshift_node/tasks/upgrade_pre.yml
Labels: approved, lgtm, size/M

#10746 Add support for secret encryption
  inventory/hosts.example
  roles/openshift_control_plane/tasks/main.yml
  roles/openshift_control_plane/templates/master.yaml.v1.j2
  roles/openshift_control_plane/vars/main.yml
Labels: approved, lgtm, size/S

#10748 Use new node labels for descheduler
  roles/openshift_descheduler/defaults/main.yaml
Labels: approved, lgtm, size/XS

#10736 Added Capability to assign an empty hostname to the created VMs
  roles/openshift_ovirt/README.md
  roles/openshift_ovirt/tasks/build_vm_list.yml
Labels: approved, lgtm, size/XS

#10754 Set no_log for registry login
  roles/container_runtime/tasks/registry_auth.yml
Labels: approved, lgtm, size/XS

#10751 Add doc to use kuryr downstream images
  playbooks/openstack/configuration.md
Labels: approved, lgtm, size/S

#10759 [osa] remove crio vars & add packages
  playbooks/azure/openshift-cluster/build_node_image.yml
Labels: approved, lgtm, size/XS

#10480 Add support for secret encryption
  inventory/hosts.example
  roles/openshift_master/tasks/main.yml
  roles/openshift_master/templates/master.yaml.v1.j2
  roles/openshift_master/vars/main.yml
Labels: lgtm, size/S

#10769 osa - make crio explicit
  playbooks/azure/openshift-cluster/build_node_image.yml
Labels: approved, lgtm, size/XS

#10734 Check for node-config.yaml file when comparing config changes in sync pod.
  roles/openshift_node_group/files/sync.yaml
Labels: approved, lgtm, size/XS

#10740 Create the namespace only in the first master
  roles/calico/tasks/main.yml
Labels: approved, lgtm, size/XS

#10767 Fixed wrong path to role in node scaleup playbook
  playbooks/openshift-node/scaleup.yml
Labels: lgtm, size/XS

#10772 Revert "Set no_log for registry login"
  roles/container_runtime/tasks/registry_auth.yml
Labels: approved, lgtm, size/XS

#10768 gluster: no need to have volumes for /dev in privileged containers
  roles/openshift_storage_glusterfs/files/glusterfs-template.yml
Labels: approved, lgtm, size/XS

#10779 Add openssh-clients dependency
  openshift-ansible.spec
Labels: approved, lgtm, size/XS

#10354 update references to outdated variable openshift_monitoring_deploy
  playbooks/openshift-metering/README.md
  test/ci/inventory/group_vars/OSEv3/vars.yml
Labels: approved, lgtm, size/XS

#10783 Install client package on first master for gluster
  playbooks/common/openshift-cluster/upgrades/pre/verify_cluster.yml
Labels: approved, lgtm, size/S

#10776 Supply namespace when generating hawkular role binding
  roles/openshift_metrics/tasks/generate_rolebindings.yaml
Labels: lgtm, size/XS

#10793 glusterfs: bind-mount /dev/disk into the glusterfs-server container
  roles/openshift_storage_glusterfs/files/glusterfs-template.yml
Labels: approved, lgtm, size/XS

#10796 Remove 80-openshift-network.conf during uninstallation
  playbooks/adhoc/uninstall_openshift.yml
Labels: approved, lgtm, size/XS

#10800 [3.9] Remove unnecessary passlib check
  roles/openshift_metrics/tasks/main.yaml
Labels: lgtm, size/S
