Repository openshift/openshift-ansible, pull requests merged in 2018-05, with the labels that each got.

#8181 [3.6] Backport etcd certificate updates from 3.7
  filter_plugins/oo_filters.py
  playbooks/common/openshift-cluster/redeploy-certificates/etcd-ca.yml
  playbooks/common/openshift-cluster/redeploy-certificates/etcd.yml
  playbooks/common/openshift-cluster/upgrades/upgrade_control_plane.yml
  playbooks/common/openshift-etcd/ca.yml
  playbooks/common/openshift-etcd/certificates.yml
  playbooks/common/openshift-etcd/config.yml
  playbooks/common/openshift-etcd/master_etcd_certificates.yml
  playbooks/common/openshift-etcd/migrate.yml
  playbooks/common/openshift-etcd/scaleup.yml
  playbooks/common/openshift-etcd/server_certificates.yml
  playbooks/common/openshift-node/etcd_client_config.yml
  roles/etcd_client_certificates/tasks/main.yml
  roles/etcd_server_certificates/tasks/main.yml
  roles/openshift_etcd_facts/defaults/main.yml
  roles/openshift_etcd_facts/tasks/main.yml
  roles/openshift_etcd_facts/tasks/set_etcd_ca_host.yml
  roles/openshift_version/tasks/main.yml
Labels: approved, lgtm, size/L

#8166 sdn: OVS pods require more memory
  roles/openshift_sdn/files/sdn-ovs.yaml
Labels: approved, lgtm, size/S

#8177 router - depricate -expose-metrics --metrics-image
  roles/lib_openshift/library/oc_adm_router.py
  roles/lib_openshift/src/ansible/oc_adm_router.py
  roles/lib_openshift/src/class/oc_adm_router.py
  roles/lib_openshift/src/doc/router
  roles/lib_openshift/src/test/unit/test_oc_adm_router.py
Labels: size/M

#8165 Remove dynamic include in logging_fluentd role
  roles/openshift_logging_fluentd/tasks/label_and_wait.yaml
  roles/openshift_logging_fluentd/tasks/main.yaml
  roles/openshift_logging_fluentd/templates/fluentd_label.sh.j2
Labels: approved, lgtm, size/M

#8071 Remove unused v39 upgrade
  playbooks/common/openshift-cluster/upgrades/v3_9/label_nodes.yml
  playbooks/common/openshift-cluster/upgrades/v3_9/master_config_upgrade.yml
  playbooks/common/openshift-cluster/upgrades/v3_9/roles
  playbooks/common/openshift-cluster/upgrades/v3_9/upgrade.yml
  playbooks/common/openshift-cluster/upgrades/v3_9/upgrade_control_plane.yml
  playbooks/common/openshift-cluster/upgrades/v3_9/upgrade_nodes.yml
Labels: lgtm, size/L

#8211 Workaround ansible/ansible #39558
  roles/openshift_node/tasks/bootstrap.yml
  roles/openshift_node/tasks/upgrade/bootstrap_changes.yml
  roles/openshift_node/tasks/upgrade/config_changes.yml
Labels: approved, lgtm, size/XS

#8212 Add templating check in failed_when conditions
  playbooks/byo/openshift-cluster/upgrades/v3_9/README.md
  playbooks/byo/openshift-cluster/upgrades/v3_9/upgrade.yml
  playbooks/byo/openshift-cluster/upgrades/v3_9/upgrade_control_plane.yml
  playbooks/byo/openshift-cluster/upgrades/v3_9/upgrade_nodes.yml
  playbooks/byo/openshift-cluster/upgrades/v3_9/upgrade_scale_groups.yml
  playbooks/common/openshift-cluster/upgrades/upgrade_scale_group.yml
  setup.py
Labels: approved, size/L

#8189 Add master config filepath checking
  playbooks/init/basic_facts.yml
  playbooks/openshift-master/private/config.yml
  roles/lib_utils/action_plugins/master_check_paths_in_config.py
  roles/lib_utils/test/test_master_check_paths_in_config.py
  roles/openshift_control_plane/tasks/check_existing_config.yml
Labels: approved, lgtm, size/L

#8137 Getting intersection of __default_ops_projects and all projects…
  roles/openshift_logging/tasks/annotate_ops_projects.yaml
  roles/openshift_logging/tasks/delete_logging.yaml
Labels: approved, lgtm, size/S

#8215 Fix redeploy cert for openshift registry
  playbooks/openshift-hosted/private/redeploy-registry-certificates.yml
Labels: approved, lgtm, size/XS

#8204 Re-add etcd rpm install path for external etcd
  playbooks/openshift-etcd/private/config.yml
  roles/etcd/defaults/main.yaml
  roles/etcd/handlers/main.yml
  roles/etcd/tasks/main.yml
  roles/etcd/tasks/rpm.yml
Labels: approved, lgtm, size/M

#8169 GlusterFS: Fix setting heketi route
  roles/openshift_storage_glusterfs/tasks/glusterfs_common.yml
Labels: approved, lgtm, size/XS

#8075 Remove system_container image from openshift_cli
  roles/openshift_cli/defaults/main.yml
Labels: approved, lgtm, size/XS

#8201 [3.9] Fix ansible playbook checks
  setup.py
Labels: approved, lgtm, size/XS

#7608 [release-3.9] Add max-time option to curl to avoid long running ansible
  playbooks/openshift-master/private/scaleup.yml
  playbooks/openshift-master/private/tasks/wire_aggregator.yml
  roles/openshift_logging/handlers/main.yml
  roles/openshift_manage_node/tasks/main.yml
  roles/openshift_master/handlers/main.yml
  roles/openshift_master/tasks/check_master_api_is_ready.yml
  roles/openshift_metrics/handlers/main.yml
  roles/openshift_node/tasks/config.yml
Labels: lgtm, size/S

#8152 [3.7] fix bz 1550271: restore mpath defaults config
  roles/openshift_node/templates/multipath.conf.j2
Labels: size/XS

#7990 [release-3.7] fix certificate auth on containerized etcd
  roles/etcd/tasks/upgrade/validate_etcd_conf.yml
  roles/etcd/templates/etcd.conf.j2
Labels: lgtm, size/M

#8224 Update the upgrade playbooks readme to point to the right 3_9 readme …
  playbooks/byo/openshift-cluster/upgrades/README.md
Labels: needs-ok-to-test, size/XS

#7991 [release-3.6] fix certificate auth on containerized etcd
  roles/etcd/templates/etcd.conf.j2
  roles/etcd_upgrade/tasks/validate_etcd_conf.yml
Labels: lgtm, size/M

#8219 azure: write blobs with vhd suffix to name
  playbooks/azure/openshift-cluster/tasks/create_blob_from_vm.yml
Labels: approved, lgtm, size/XS

#8217 Remove certificates_to_synchronize filter module
  playbooks/openshift-master/private/certificates-backup.yml
  roles/lib_utils/filter_plugins/openshift_master.py
  roles/openshift_master_certificates/tasks/main.yml
Labels: approved, lgtm, size/M

#8118 (3.10) Bug 1571385- Broker still not properly selecting master nodes
  roles/ansible_service_broker/tasks/install.yml
  roles/ansible_service_broker/templates/asb_dc.yaml.j2
Labels: approved, lgtm, size/XS

#8234 Add helfup comment for error-prone task
  roles/openshift_node/tasks/config.yml
Labels: approved, lgtm, size/XS

#8238 Resurrect scale group upgrade
  playbooks/byo/openshift-cluster/upgrades/v3_10/upgrade_scale_groups.yml
  playbooks/common/openshift-cluster/upgrades/upgrade_scale_group.yml
Labels: approved, size/M

#8069 Cleanup master related plays and variables
  playbooks/openshift-etcd/private/redeploy-ca.yml
  playbooks/openshift-master/private/certificates-backup.yml
  playbooks/openshift-master/private/certificates.yml
  playbooks/openshift-master/private/config.yml
  playbooks/openshift-master/private/redeploy-openshift-ca.yml
  playbooks/openshift-node/private/certificates.yml
  roles/openshift_ca/README.md
  roles/openshift_ca/tasks/main.yml
  roles/openshift_control_plane/tasks/main.yml
  roles/openshift_facts/defaults/main.yml
  roles/openshift_node_certificates/README.md
  roles/openshift_node_certificates/defaults/main.yml
  roles/openshift_node_certificates/meta/main.yml
Labels: approved, lgtm, size/M

#8233 PAPR: try to rebase on the latest code
  .papr.sh
Labels: approved, lgtm, size/XS

#8236 [3.9] docker rootdir is different when installing crio
  roles/openshift_docker_gc/templates/dockergc-ds.yaml.j2
Labels: lgtm, size/XS

#8216 Remove clusterNetworkCIDR/hostSubnetLength from default config
  roles/openshift_control_plane/templates/master.yaml.v1.j2
Labels: lgtm, size/XS

#8243 Fix papr.sh target branch for rebase
  .papr.sh
Labels: approved, lgtm, size/XS

#8235 docker_image_availability: bz 1570479
  roles/openshift_health_checker/openshift_checks/docker_image_availability.py
  roles/openshift_health_checker/test/docker_image_availability_test.py
Labels: approved, lgtm, size/S

#7859 Move Node Problem Detector to its own ns, make the ns hard-coded
  roles/openshift_node_problem_detector/defaults/main.yaml
  roles/openshift_node_problem_detector/tasks/install.yaml
  roles/openshift_node_problem_detector/tasks/uninstall.yaml
Labels: approved, lgtm, size/M

#8228 [3.7] Stop and start openvswitch only if openshift_use_openshift_sdn
  playbooks/common/openshift-cluster/upgrades/docker/tasks/restart.yml
  playbooks/common/openshift-cluster/upgrades/docker/tasks/upgrade.yml
  playbooks/common/openshift-node/restart.yml
  roles/openshift_node_upgrade/tasks/main.yml
  roles/openshift_node_upgrade/tasks/restart.yml
Labels: approved, lgtm, size/M

#8252 Allow for PVCs to specify storage class
  filter_plugins/oo_filters.py
  playbooks/common/openshift-glusterfs/registry.yml
  roles/openshift_persistent_volumes/templates/persistent-volume-claim.yml.j2
Labels: size/S

#8251 GlusterFS: Move uninstall playbook location
  playbooks/byo/openshift-glusterfs/uninstall.yml
  playbooks/common/openshift-glusterfs/uninstall.yml
  playbooks/openshift-glusterfs/uninstall.yml
Labels: size/S

#8256 Updating to remove annotations from namespace rather than project
  roles/openshift_logging/tasks/delete_logging.yaml
Labels: approved, lgtm, size/XS

#8232 Annotating fluentd pods for promethrus scraping
  roles/openshift_logging_fluentd/templates/2.x/fluentd.j2
  roles/openshift_logging_fluentd/templates/5.x/fluentd.j2
Labels: approved, lgtm, size/XS

#8231 Excluding the eventrouter component when looking for namespaces logging is installed in
  roles/openshift_logging/tasks/main.yaml
Labels: affects_3.9, approved, lgtm, size/XS

#8239 Fix containerized 3.9 -> 3.10 upgrade
  playbooks/openshift-etcd/private/upgrade_main.yml
  roles/etcd/defaults/main.yaml
  roles/etcd/tasks/runtime.yml
  roles/etcd/tasks/upgrade_static.yml
  roles/openshift_control_plane/tasks/static.yml
  roles/openshift_node/tasks/systemd_units.yml
Labels: approved, lgtm, size/M

#8205 service catalog: updates for upstream v0.1.16
  roles/openshift_service_catalog/files/kubeservicecatalog_roles_bindings.yml
  roles/openshift_service_catalog/tasks/start.yml
  roles/openshift_service_catalog/templates/api_server.j2
  roles/openshift_service_catalog/vars/default_images.yml
Labels: approved, lgtm, size/M

#8241 Remove non-bootstrap code
  playbooks/aws/openshift-cluster/build_ami.yml
  playbooks/aws/openshift-cluster/install.yml
  playbooks/deploy_cluster.yml
  playbooks/gcp/openshift-cluster/build_image.yml
  playbooks/gcp/openshift-cluster/install.yml
  playbooks/init/evaluate_groups.yml
  playbooks/openshift-master/private/scaleup.yml
  playbooks/openshift-node/config.yml
  playbooks/openshift-node/private/additional_config.yml
  playbooks/openshift-node/private/config.yml
  playbooks/openshift-node/private/etcd_client_config.yml
  playbooks/openshift-node/private/manage_node.yml
  playbooks/openshift-node/scaleup.yml
  roles/openshift_aws/tasks/provision_instance.yml
  roles/openshift_gcp/tasks/setup_scale_group_facts.yml
  roles/openshift_node/defaults/main.yml
  roles/openshift_node/handlers/main.yml
  roles/openshift_node/tasks/aws.yml
  roles/openshift_node/tasks/config.yml
  roles/openshift_node/tasks/config/configure-node-settings.yml
  roles/openshift_node/tasks/config/configure-proxy-settings.yml
  roles/openshift_node/tasks/dnsmasq/no-network-manager.yml
  roles/openshift_node/tasks/main.yml
  roles/openshift_node/tasks/registry_auth.yml
  roles/openshift_node/tasks/systemd_units.yml
  roles/openshift_node/tasks/upgrade.yml
  roles/openshift_node/tasks/upgrade/config_changes.yml
Labels: approved, lgtm, size/L

#8248 [3.7] PAPR: try to rebase on the latest code
  .papr.sh
Labels: approved, size/XS

#8284 [3.7] Remove dynamic include in logging_fluentd role
  roles/openshift_logging_fluentd/tasks/label_and_wait.yaml
  roles/openshift_logging_fluentd/tasks/main.yaml
  roles/openshift_logging_fluentd/templates/fluentd_label.sh.j2
Labels: approved, lgtm, size/M

#8100 Configure NetworkManager to ignore calico interfaces
  roles/calico/files/calico.conf
  roles/calico/tasks/main.yml
Labels: lgtm, needs-ok-to-test, size/S

#8286 Find a source for google-cloud-sdk-183
  images/installer/Dockerfile
Labels: approved, size/XS

#8274 Check console ready replicas instead of curling service
  roles/openshift_web_console/tasks/start.yml
Labels: approved, lgtm, size/S

#8291 Fix openshift_facts migrated_facts
  roles/openshift_facts/library/openshift_facts.py
Labels: approved, lgtm, size/S

#8275 Convert SDN master facts to openshift_facts defaults
  .papr-master-ha.inventory
  .papr.all-in-one.inventory
  .papr.inventory
  inventory/hosts.localhost
  playbooks/openshift-master/private/set_network_facts.yml
  roles/calico_master/templates/calico.yml.j2
  roles/flannel/tasks/main.yml
  roles/flannel_register/defaults/main.yaml
  roles/nuage_master/templates/nuage-node-config-daemonset.j2
  roles/nuage_node/tasks/iptables.yml
  roles/openshift_control_plane/templates/master.env.j2
  roles/openshift_control_plane/templates/master.yaml.v1.j2
  roles/openshift_facts/defaults/main.yml
  roles/openshift_facts/library/openshift_facts.py
  roles/openshift_master_facts/tasks/main.yml
  roles/openshift_node/tasks/config/configure-proxy-settings.yml
  roles/openshift_openstack/templates/heat_stack.yaml.j2
  test/ci/inventory/group_vars/all.yml
Labels: approved, kind/bug, lgtm, size/M

#8295 [3.9] Find alternate source for google-cloud-sdk-183
  images/installer/Dockerfile
Labels: approved, size/XS

#8288 Add EAP CD imagestream to 3.10
  roles/openshift_examples/files/examples/v3.10/xpaas-streams/eap-cd-image-stream.json
Labels: needs-ok-to-test, size/M

#8259 Move openshift-checks before node bootstrapping
  playbooks/aws/openshift-cluster/install.yml
  playbooks/common/private/control_plane.yml
  playbooks/deploy_cluster.yml
  playbooks/gcp/openshift-cluster/install.yml
Labels: approved, lgtm, size/XS

#8269 Remove vendored docker_container module
  roles/openshift_health_checker/library/docker_container.py
Labels: approved, lgtm, size/XXL

#6250 Add possibility to enable Persistent Local Storage using Ansible
  inventory/hosts.example
  playbooks/openshift-hosted/private/create_persistent_volumes.yml
  roles/openshift_control_plane/README.md
  roles/openshift_control_plane/defaults/main.yml
  roles/openshift_control_plane/templates/master.yaml.v1.j2
  roles/openshift_node/README.md
  roles/openshift_node/defaults/main.yml
  roles/openshift_node/templates/node.yaml.v1.j2
  roles/openshift_node_group/defaults/main.yml
  roles/openshift_node_group/templates/node-config.yaml.j2
  roles/openshift_persistent_volumes/README.md
  roles/openshift_persistentlocalstorage/README.md
  roles/openshift_persistentlocalstorage/defaults/main.yml
  roles/openshift_persistentlocalstorage/meta/main.yml
  roles/openshift_persistentlocalstorage/tasks/main.yml
  roles/openshift_persistentlocalstorage/templates/local-persistent-volume-config.j2
Labels: lgtm, size/L

#8278 add run_once for create secret task in calico_master role
  roles/calico_master/tasks/certs.yml
Labels: lgtm, size/XS

#8297 Update to CloudForms 4.6.2 templates
  roles/openshift_examples/files/examples/v3.10/cfme-templates/cfme-backup-job.yaml
  roles/openshift_examples/files/examples/v3.10/cfme-templates/cfme-restore-job.yaml
  roles/openshift_examples/files/examples/v3.10/cfme-templates/cfme-template-ext-db.yaml
  roles/openshift_examples/files/examples/v3.10/cfme-templates/cfme-template.yaml
  roles/openshift_management/files/templates/cloudforms/cfme-template-ext-db.yaml
  roles/openshift_management/files/templates/cloudforms/cfme-template.yaml
Labels: approved, lgtm, size/L

#8304 Fix etcd runtime detection
  roles/etcd/tasks/runtime.yml
Labels: approved, lgtm, size/S

#8227 [3.9] Install, update and restart openvswitch only when openshift_use_openshift_sdn is set
  playbooks/common/openshift-cluster/upgrades/docker/tasks/restart.yml
  playbooks/common/openshift-cluster/upgrades/docker/tasks/upgrade.yml
  playbooks/openshift-node/private/restart.yml
  roles/openshift_node/tasks/upgrade/restart.yml
  roles/openshift_node/tasks/upgrade/rpm_upgrade.yml
  roles/openshift_node/tasks/upgrade/rpm_upgrade_install.yml
  roles/openshift_node/tasks/upgrade/stop_services.yml
Labels: approved, lgtm, size/M

#8257 Forward porting of azure work to master
  images/installer/Dockerfile
  images/installer/origin-extra-root/etc/yum.repos.d/azure-cli.repo
  images/installer/root/usr/local/bin/entrypoint-gcp
  images/installer/root/usr/local/bin/entrypoint-provider
  inventory/dynamic/azure/ansible.cfg
  inventory/dynamic/azure/group_vars/all/.gitkeep
  inventory/dynamic/azure/none
  playbooks/aws/openshift-cluster/build_ami.yml
  playbooks/azure/OWNERS
  playbooks/azure/README.md
  playbooks/azure/openshift-cluster/build_base_image.yml
  playbooks/azure/openshift-cluster/build_node_image.yml
  playbooks/azure/openshift-cluster/deprovision.yml
  playbooks/azure/openshift-cluster/group_vars/all/yum_repos.yml
  playbooks/azure/openshift-cluster/launch.yml
  playbooks/azure/openshift-cluster/provisioning_vars.yml.example
  playbooks/azure/openshift-cluster/roles
  playbooks/azure/openshift-cluster/tasks/create_blob_from_vm.yml
  playbooks/azure/openshift-cluster/tasks/create_image_from_vm.yml
  playbooks/azure/openshift-cluster/tasks/provision_instance.yml
  playbooks/azure/openshift-cluster/tasks/remove_yum.yml
  playbooks/azure/openshift-cluster/tasks/yum_certs.yml
  roles/openshift_node/defaults/main.yml
  roles/openshift_node/tasks/bootstrap.yml
  roles/os_update_latest/defaults/main.yml
  roles/os_update_latest/tasks/main.yml
  setup.py
Labels: approved, lgtm, size/XL

#8303 Ensure existing network facts are set
  playbooks/init/basic_facts.yml
  playbooks/init/cluster_facts.yml
  playbooks/openshift-master/private/scaleup.yml
  playbooks/openshift-master/private/set_network_facts.yml
  roles/openshift_facts/defaults/main.yml
Labels: approved, size/M

#8289 Fix and simplify Installer Checkpoint
  playbooks/init/main.yml
  playbooks/openshift-autoheal/private/config.yml
  playbooks/openshift-checks/private/install.yml
  playbooks/openshift-descheduler/private/config.yml
  playbooks/openshift-etcd/private/config.yml
  playbooks/openshift-glusterfs/private/config.yml
  playbooks/openshift-grafana/private/config.yml
  playbooks/openshift-hosted/private/config.yml
  playbooks/openshift-loadbalancer/private/config.yml
  playbooks/openshift-logging/private/config.yml
  playbooks/openshift-management/private/config.yml
  playbooks/openshift-master/private/additional_config.yml
  playbooks/openshift-master/private/config.yml
  playbooks/openshift-metrics/private/config.yml
  playbooks/openshift-monitor-availability/private/config.yml
  playbooks/openshift-monitoring/private/config.yml
  playbooks/openshift-nfs/private/config.yml
  playbooks/openshift-node-problem-detector/private/config.yml
  playbooks/openshift-node/private/bootstrap.yml
  playbooks/openshift-prometheus/private/config.yml
  playbooks/openshift-service-catalog/private/config.yml
  playbooks/openshift-web-console/private/config.yml
  roles/installer_checkpoint/README.md
  roles/installer_checkpoint/callback_plugins/installer_checkpoint.py
Labels: approved, lgtm, size/L

#8290 Remove bootstrap boolean from gcp provision
  roles/openshift_gcp/templates/provision.j2.sh
Labels: approved, lgtm, size/XS

#8301 Fix upgrade containerized to bootstrap
  roles/container_runtime/defaults/main.yml
  roles/container_runtime/tasks/systemcontainer_crio.yml
  roles/openshift_node/defaults/main.yml
  roles/openshift_node/tasks/config.yml
  roles/openshift_node/tasks/systemd_units.yml
  roles/openshift_node/tasks/upgrade.yml
  roles/openshift_node/tasks/upgrade_pre.yml
Labels: approved, lgtm, size/M

#8312 Remove debugging code from #8304
  roles/etcd/tasks/runtime.yml
Labels: approved, size/XS

#8287 Update cri-o pause image and pause command
  roles/container_runtime/defaults/main.yml
  roles/container_runtime/templates/crio.conf.j2
Labels: size/S

#8262 [3.9] Update cri-o pause image and pause command
  roles/container_runtime/defaults/main.yml
  roles/container_runtime/tasks/systemcontainer_crio.yml
  roles/container_runtime/templates/crio.conf.j2
Labels: size/S

#8314 Ensure we're running with admin kubeconfig in several locations
  playbooks/openshift-node/private/join.yml
  roles/openshift_control_plane/tasks/bootstrap.yml
  roles/openshift_control_plane/tasks/main.yml
  roles/openshift_docker_gc/tasks/main.yml
  roles/openshift_grafana/tasks/install_grafana.yaml
  roles/openshift_hosted/tasks/storage/glusterfs_endpoints.yml
  roles/openshift_hosted/tasks/wait_for_pod.yml
  roles/openshift_logging_elasticsearch/tasks/get_es_version.yml
  roles/openshift_logging_elasticsearch/tasks/main.yaml
  roles/openshift_logging_elasticsearch/tasks/restart_cluster.yml
  roles/openshift_logging_elasticsearch/tasks/restart_es_node.yml
  roles/openshift_node_group/tasks/sync.yml
  roles/openshift_prometheus/tasks/install_prometheus.yaml
  roles/openshift_sdn/tasks/main.yml
Labels: approved, lgtm, size/M

#8333 Revert "[release-3.7] Adding missing deprecated var openshift_hosted_metrics_public_url"
  roles/openshift_sanitize_inventory/tasks/__deprecations_metrics.yml
  roles/openshift_sanitize_inventory/vars/main.yml
Labels: lgtm, size/XS

#8326 Fix hard-coded version in master config imageConfig.format
  roles/openshift_control_plane/defaults/main.yml
  roles/openshift_control_plane/templates/master.yaml.v1.j2
  roles/openshift_node_group/defaults/main.yml
Labels: approved, lgtm, size/XS

#8325 Fix undefined variable for existing network config
  playbooks/init/basic_facts.yml
Labels: approved, lgtm, size/S

#8330 Remove containerized lb support
  playbooks/openshift-loadbalancer/private/config.yml
  roles/openshift_loadbalancer/defaults/main.yml
  roles/openshift_loadbalancer/tasks/main.yml
  roles/openshift_loadbalancer/templates/haproxy.docker.service.j2
Labels: approved, lgtm, size/M

#8324 SDN should read bootstrapped config
  roles/openshift_node/tasks/bootstrap.yml
  roles/openshift_node_group/tasks/bootstrap.yml
  roles/openshift_sdn/files/sdn.yaml
Labels: approved, lgtm, size/S

#8329 Cleanup systemcontainer bits
  inventory/hosts.example
  playbooks/container-runtime/private/build_container_groups.yml
  playbooks/container-runtime/private/config.yml
  playbooks/container-runtime/private/setup_storage.yml
  playbooks/init/base_packages.yml
  playbooks/openshift-etcd/scaleup.yml
  roles/container_runtime/defaults/main.yml
  roles/container_runtime/tasks/common/syscontainer_packages.yml
  roles/container_runtime/tasks/package_crio.yml
  roles/container_runtime/tasks/package_docker.yml
  roles/container_runtime/tasks/systemcontainer_crio.yml
  roles/container_runtime/tasks/systemcontainer_docker.yml
  roles/contiv/defaults/main.yml
  roles/etcd/defaults/main.yaml
  roles/flannel/defaults/main.yaml
  roles/openshift_cli/defaults/main.yml
  roles/openshift_control_plane/defaults/main.yml
  roles/openshift_facts/defaults/main.yml
  roles/openshift_loadbalancer/defaults/main.yml
  roles/openshift_node/defaults/main.yml
  roles/openshift_node_certificates/defaults/main.yml
Labels: approved, lgtm, size/L

#8341 [3.9] verify that at least one master is schedulable before upgrade
  playbooks/common/openshift-cluster/upgrades/pre/verify_upgrade_targets.yml
  roles/openshift_sanitize_inventory/tasks/main.yml
Labels: approved, size/S

#8338 [3.9] Fix crio pause image syntax
  roles/container_runtime/templates/crio.conf.j2
Labels: lgtm, size/XS

#8337 Fix crio pause image syntax
  roles/container_runtime/templates/crio.conf.j2
Labels: lgtm, size/XS

#8311 upgrade_control_plan needs to invoke wire_aggregator
  playbooks/common/openshift-cluster/upgrades/v3_7/upgrade_control_plane.yml
Labels: lgtm, size/XS

#8254 Remove kuryr leftovers before removing the stack
  roles/openshift_openstack/library/os_lbaas_deletion.py
  roles/openshift_openstack/library/os_subports_deletion.py
  roles/openshift_openstack/tasks/unprovision.yml
Labels: approved, lgtm, size/L

#8348 Add in crio pause image code back
  roles/container_runtime/defaults/main.yml
Labels: approved, lgtm, size/S

#8347 azure: revoke sas url before deleting resource group
  playbooks/azure/openshift-cluster/tasks/create_blob_from_vm.yml
Labels: approved, size/XS

#8346 azure: revoke sas url before deleting resource group
  playbooks/azure/openshift-cluster/tasks/create_blob_from_vm.yml
Labels: approved, size/XS

#8317 upgrade from 3.9 w/o ASB to 3.10 with ASB fails
  roles/ansible_service_broker/tasks/upgrade.yml
Labels: approved, lgtm, size/XS

#8319 Switch from public subnet id to network id at kuryr
  playbooks/openstack/configuration.md
  playbooks/openstack/sample-inventory/group_vars/all.yml
  roles/kuryr/templates/configmap.yaml.j2
Labels: approved, lgtm, size/S

#8331 Add critical pod annotation so that descheduler does not evict itself or does not get evicted by others.
  roles/openshift_descheduler/templates/descheduler-cronjob.yaml.j2
Labels: approved, lgtm, size/XS

#8334 Remove duplicate slurp of session_secrets
  roles/openshift_control_plane/tasks/generate_session_secrets.yml
Labels: approved, lgtm, size/XS

#8335 Using existing nodeselectors for logging components as more sane defaults
  roles/openshift_logging/tasks/set_defaults_from_current.yml
Labels: approved, lgtm, size/M

#8351 Readd crio registry variables
  roles/container_runtime/defaults/main.yml
Labels: approved, kind/bug, lgtm, priority/P1, size/XS

#8336 Replace and refactor openshift_is_containerized in places
  playbooks/openshift-etcd/private/upgrade_rpm_members.yml
  playbooks/openshift-node/private/restart.yml
  roles/cockpit/tasks/main.yml
  roles/container_runtime/tasks/docker_restart.yml
  roles/lib_utils/action_plugins/sanity_checks.py
  roles/openshift_ca/tasks/main.yml
  roles/openshift_cli/tasks/main.yml
  roles/openshift_control_plane/defaults/main.yml
  roles/openshift_control_plane/tasks/registry_auth.yml
  roles/openshift_expand_partition/tasks/main.yml
  roles/openshift_facts/defaults/main.yml
  roles/openshift_manage_node/tasks/main.yml
  roles/openshift_node/tasks/install.yml
  roles/openshift_node/tasks/registry_auth.yml
  roles/openshift_node/tasks/upgrade.yml
  roles/openshift_node/tasks/upgrade/restart.yml
  roles/openshift_node/tasks/upgrade/stop_services.yml
  roles/openshift_node/tasks/upgrade_pre.yml
  roles/openshift_storage_nfs_lvm/tasks/nfs.yml
Labels: approved, lgtm, size/L

#8320 Update playbooks/adhoc/uninstall.yml
  playbooks/adhoc/uninstall.yml
Labels: approved, lgtm, size/XS

#8352 Node system container no longer depends on master services
  roles/openshift_node/tasks/node_system_container.yml
Labels: approved, lgtm, size/XS

#8354 Don't validate registry certificates when registry is disabled
  playbooks/common/openshift-cluster/upgrades/post_control_plane.yml
Labels: approved, lgtm, size/XS

#8345 Install node-dnsmasq configuration file
  roles/openshift_node/tasks/dnsmasq.yml
Labels: approved, lgtm, size/XS

#8265 PAPR improvements
  .papr-master-ha.inventory
  .papr.all-in-one.inventory
  .papr.inventory
  .papr.sh
  .papr.yml
Labels: approved, lgtm, size/S

#8313 repoquery: Omit exclude lines when ignoring excluders
  roles/lib_utils/library/repoquery.py
  roles/lib_utils/src/class/repoquery.py
Labels: approved, lgtm, size/XS

#8309 Kuryr: Copy CNI plugins as DaemonSet initContainer
  roles/kuryr/tasks/node.yaml
  roles/kuryr/templates/cni-daemonset.yaml.j2
Labels: approved, lgtm, size/M

#8364 Skip "At least one master is schedulable" when no masters are set in oo_masters_to_config
  roles/openshift_sanitize_inventory/tasks/main.yml
Labels: approved, lgtm, size/XS

#8112 [3.7] Registry remove legacy vars
  playbooks/common/openshift-cluster/upgrades/registry_upgrade.yml
  playbooks/common/openshift-cluster/upgrades/v3_7/upgrade_control_plane.yml
  roles/lib_openshift/library/oc_adm_registry.py
  roles/lib_openshift/library/oc_adm_router.py
  roles/lib_openshift/library/oc_env.py
  roles/lib_openshift/library/oc_scale.py
  roles/lib_openshift/library/oc_volume.py
  roles/lib_openshift/src/lib/deploymentconfig.py
  roles/openshift_hosted/defaults/main.yml
  roles/openshift_hosted/tasks/registry.yml
  roles/openshift_hosted/tasks/registry_service_account.yml
  roles/openshift_hosted/tasks/remove_legacy_env_variables.yml
Labels: approved, lgtm, size/M

#8367 quick installer: make all nodes schedulable
  utils/src/ooinstall/oo_config.py
  utils/test/cli_installer_tests.py
Labels: approved, lgtm, size/S

#8281 Conditionally add in a Calico v3 manifest and upgrade path to facilitate upgrades.
  roles/calico_master/defaults/main.yaml
  roles/calico_master/tasks/main.yml
  roles/calico_master/templates/calicov3.yml.j2
Labels: size/XL

#8299 Conditionally use upgraded version of Calico for different versions
  roles/calico_master/defaults/main.yaml
  roles/calico_master/tasks/main.yml
  roles/calico_master/templates/calicov3.yml.j2
Labels: approved, lgtm, size/XL

#7076 Copy files from openshift_master_generated_config_dir instead using hardlinks
  roles/openshift_master_certificates/tasks/main.yml
Labels: approved, lgtm, size/XS

#8380 source azure credentials file
  images/installer/root/usr/local/bin/entrypoint-provider
Labels: size/XS

#8375 Updating fluentd docker container mount path
  roles/openshift_logging_fluentd/templates/2.x/fluentd.j2
  roles/openshift_logging_fluentd/templates/5.x/fluentd.j2
Labels: approved, lgtm, size/XS

#8381 Remove double_upgrade bits
  playbooks/common/openshift-cluster/upgrades/pre/config.yml
  playbooks/common/openshift-cluster/upgrades/pre/version_override.yml
  playbooks/openshift-master/private/upgrade.yml
Labels: approved, lgtm, size/M

#8373 Avoid hardcoded namespace default in lib_openshift/oc_adm_router
  roles/lib_openshift/library/oc_adm_router.py
  roles/lib_openshift/src/class/oc_adm_router.py
Labels: approved, lgtm, size/XS

#8382 Add new key and remove deprecated key for master network conf
  playbooks/init/basic_facts.yml
  roles/openshift_control_plane/defaults/main.yml
  roles/openshift_control_plane/tasks/upgrade.yml
Labels: approved, lgtm, size/S

#8384 [release-3.9] Copy files from openshift_master_generated_config_dir instead using hardlinks
  roles/openshift_master_certificates/tasks/main.yml
Labels: lgtm, size/XS

#8350 Add static cluster id label to alerts
  roles/openshift_cluster_monitoring_operator/defaults/main.yml
  roles/openshift_cluster_monitoring_operator/files/cluster-monitoring-operator.yaml
  roles/openshift_cluster_monitoring_operator/tasks/install.yaml
Labels: approved, lgtm, size/S

#8270 Bug 1561485- get now returns empty instead of error when the namespace is missing
  roles/lib_openshift/library/oc_pvc.py
  roles/lib_openshift/library/oc_route.py
  roles/lib_openshift/library/oc_service.py
  roles/lib_openshift/library/oc_serviceaccount.py
  roles/lib_openshift/src/class/oc_pvc.py
  roles/lib_openshift/src/class/oc_route.py
  roles/lib_openshift/src/class/oc_service.py
  roles/lib_openshift/src/class/oc_serviceaccount.py
Labels: approved, lgtm, size/S

#8394 Fix unwanted removal of openshift.fact file
  playbooks/openshift-node/private/bootstrap.yml
Labels: approved, kind/bug, lgtm, priority/P1, size/XS

#8395 update xpaas imagestreams to explicitly import tags
  roles/openshift_examples/files/examples/v3.6/xpaas-streams/jboss-image-streams.json
Labels: approved, lgtm, size/L

#8387 openshift-node: sync script with origin
  roles/openshift_node/files/openshift-node
Labels: approved, lgtm, size/XS

#8386 Correct openshift_use_openshift_sdn
  roles/openshift_node/tasks/upgrade/rpm_upgrade.yml
  roles/openshift_node/tasks/upgrade/rpm_upgrade_install.yml
Labels: lgtm, size/XS

#8393 Implicitly create node's IST in Kuryr's namespace
  roles/kuryr/defaults/main.yaml
  roles/kuryr/tasks/master.yaml
  roles/kuryr/templates/node-images.yaml.j2
Labels: approved, lgtm, size/M

#8397 fix descheduler pod should be critical pod
  roles/openshift_descheduler/templates/descheduler-cronjob.yaml.j2
Labels: approved, lgtm, size/XS

#8409 Revert "Install node-dnsmasq configuration file"
  roles/openshift_node/tasks/dnsmasq.yml
Labels: approved, size/XS

#8402 Force creating hard- and softlinks
  roles/contiv/tasks/netmaster.yml
  roles/contiv/tasks/netplugin.yml
  roles/etcd/tasks/certificates/fetch_client_certificates_from_ca.yml
  roles/etcd/tasks/certificates/fetch_server_certificates_from_ca.yml
  roles/openshift_control_plane/tasks/upgrade.yml
  roles/openshift_master_certificates/tasks/main.yml
Labels: approved, lgtm, size/XS

#8404 [3.7] Force creating hard- and softlinks
  playbooks/common/openshift-cluster/upgrades/upgrade_control_plane.yml
  roles/contiv/tasks/netmaster.yml
  roles/contiv/tasks/netplugin.yml
  roles/etcd/tasks/certificates/fetch_client_certificates_from_ca.yml
  roles/etcd/tasks/certificates/fetch_server_certificates_from_ca.yml
  roles/openshift_master_certificates/tasks/main.yml
Labels: lgtm, size/XS

#8403 [3.9] Force creating hard- and softlinks
  roles/contiv/tasks/netmaster.yml
  roles/contiv/tasks/netplugin.yml
  roles/etcd/tasks/certificates/fetch_client_certificates_from_ca.yml
  roles/etcd/tasks/certificates/fetch_server_certificates_from_ca.yml
  roles/openshift_master/tasks/upgrade.yml
  roles/openshift_master_certificates/tasks/main.yml
Labels: lgtm, size/XS

#8099 pass cluster-cidr to proxy
  roles/openshift_node/templates/node.yaml.v1.j2
Labels: approved, lgtm, size/XS

#8418 Add patch to installer image
  images/installer/Dockerfile
Labels: affects_3.9, approved, lgtm, size/XS

#8419 Update Jinja tests used as filters
  playbooks/common/openshift-cluster/upgrades/pre/config.yml
  playbooks/openshift-node/private/join.yml
  roles/openshift_aws/tasks/elb_single.yml
  roles/openshift_aws/tasks/uninstall_iam_cert.yml
  roles/openshift_aws/tasks/uninstall_security_group.yml
  roles/openshift_control_plane/tasks/upgrade.yml
  roles/openshift_openstack/tasks/provision.yml
  roles/openshift_repos/tasks/rhel_repos.yml
Labels: approved, lgtm, size/M

#8302 Adding support for node images on 3.10 for azure.
  playbooks/azure/openshift-cluster/build_node_image.yml
  playbooks/openshift-node/private/image_prep.yml
  roles/etcd/defaults/main.yaml
  roles/etcd/tasks/static.yml
  roles/openshift_control_plane/defaults/main.yml
  roles/openshift_control_plane/tasks/static.yml
Labels: approved, lgtm, size/M

#8416 Enable monitoring upgrades
  playbooks/common/openshift-cluster/upgrades/upgrade_components.yml
Labels: approved, lgtm, size/XS

#8390 Stop upgrade when existing sccs will be changed
  playbooks/openshift-master/private/upgrade.yml
Labels: approved, lgtm, size/S

#8411 ASB nodeselector needs to be converted to json
  roles/ansible_service_broker/templates/asb_dc.yaml.j2
Labels: approved, lgtm, size/XS

#8426 fix bug 1579723
  roles/ansible_service_broker/templates/configmap.yaml.j2
Labels: approved, lgtm, size/XS

#8435 removing dnsmasq-node.conf.j2 since nothing is referencing it.
  roles/openshift_node/templates/node-dnsmasq.conf.j2
Labels: approved, lgtm, size/XS

#8383 Adding ability to publish images to the azure portal.
  playbooks/azure/openshift-cluster/create_offer.yml
  playbooks/azure/openshift-cluster/group_vars/all/image_publish.yml
  playbooks/azure/openshift-cluster/templates/offer.yml.j2
  roles/lib_utils/library/oo_azure_rm_publish_image.py
  roles/lib_utils/library/oo_azure_rm_publish_image_facts.py
Labels: approved, lgtm, size/XL

#8429 [release-3.6]: Add the ability to specify a timeout for node drain operations
  inventory/byo/hosts.origin.example
  playbooks/common/openshift-cluster/upgrades/docker/docker_upgrade.yml
  playbooks/common/openshift-cluster/upgrades/upgrade_control_plane.yml
  playbooks/common/openshift-cluster/upgrades/upgrade_nodes.yml
Labels: size/M

#8420 Bug 1579269 - Updating the CRD resource names for migration.
  roles/ansible_service_broker/tasks/migrate.yml
Labels: approved, lgtm, size/XS

#8417 Fixup SELinux permissions for docker when using a different graph path
  roles/container_runtime/tasks/package_docker.yml
Labels: lgtm, size/S

#8443 API liveness probe: set timeout to 10 sec to prevent API restart if the system is busy
  roles/openshift_control_plane/files/apiserver.yaml
Labels: approved, lgtm, size/XS

#7254 add support for vsphere-volume registry and other services
  inventory/hosts.example
  playbooks/openshift-hosted/private/config.yml
  roles/lib_utils/action_plugins/generate_pv_pvcs_list.py
  roles/openshift_hosted/tasks/registry.yml
  roles/openshift_persistent_volumes/templates/persistent-volume-claim.yml.j2
Labels: approved, lgtm, size/M

#8427 CRIO minor fixes for 3.10
  inventory/hosts.example
  playbooks/init/basic_facts.yml
  roles/openshift_cli/defaults/main.yml
  roles/openshift_cli/tasks/main.yml
  roles/openshift_health_checker/action_plugins/openshift_health_check.py
Labels: approved, lgtm, size/S

#8441 catalog: add -cluster-id-configmap-namespace=kube-service-catalog flag
  roles/openshift_service_catalog/templates/controller_manager.j2
Labels: approved, lgtm, size/XS

#8432 Specify service port for Prometheus scraping
  roles/openshift_logging_elasticsearch/tasks/main.yaml
Labels: affects_3.9, approved, lgtm, size/XS

#8415 Updating process for doing a logging ES roll outs
  roles/openshift_logging/tasks/main.yaml
  roles/openshift_logging_elasticsearch/tasks/full_cluster_restart.yml
  roles/openshift_logging_elasticsearch/tasks/restart_cluster.yml
  roles/openshift_logging_elasticsearch/tasks/restart_es_node.yml
  roles/openshift_logging_elasticsearch/tasks/rolling_cluster_restart.yml
  roles/openshift_logging_elasticsearch/vars/main.yml
Labels: affects_3.7, affects_3.9, approved, lgtm, size/L

#8428 [release-3.7]: Add the ability to specify a timeout for node drain operations
  inventory/byo/hosts.example
  playbooks/common/openshift-cluster/upgrades/docker/docker_upgrade.yml
  playbooks/common/openshift-cluster/upgrades/upgrade_control_plane.yml
  playbooks/common/openshift-cluster/upgrades/upgrade_nodes.yml
Labels: lgtm, size/M

#8145 avoid drop_column_labels in query.
  roles/openshift_grafana/files/dashboards/openshift-cluster-monitoring.json
Labels: lgtm, size/XS

#8458 Adding strace and insights-client
  playbooks/azure/openshift-cluster/build_node_image.yml
Labels: approved, lgtm, size/XS

#8448 fix The error was: KeyError: 'userNames'
  roles/lib_openshift/library/oc_adm_policy_user.py
  roles/lib_openshift/src/class/oc_adm_policy_user.py
Labels: approved, lgtm, size/XS

#8450 add volume config generation
  roles/openshift_node_group/tasks/create_config.yml
  roles/openshift_node_group/templates/volume-config.yaml.j2
Labels: approved, lgtm, size/M

#8460 Fix hosts.example openshift_master_oauth_templates
  inventory/hosts.example
Labels: approved, size/XS

#8445 Ensure sanity checks are run during upgrade
  playbooks/common/openshift-cluster/upgrades/v3_10/upgrade_control_plane.yml
  playbooks/common/openshift-cluster/upgrades/v3_10/upgrade_nodes.yml
Labels: approved, lgtm, size/XS

#8451 Changing what we check for with is_upgrade set_fact in curator main
  roles/openshift_logging_curator/tasks/main.yaml
Labels: approved, lgtm, size/XS

#8439 Update lib_openshift doc strings to reflect module name
  roles/lib_openshift/library/oc_adm_ca_server_cert.py
  roles/lib_openshift/library/oc_adm_csr.py
  roles/lib_openshift/library/oc_adm_manage_node.py
  roles/lib_openshift/library/oc_adm_policy_group.py
  roles/lib_openshift/library/oc_adm_policy_user.py
  roles/lib_openshift/library/oc_adm_registry.py
  roles/lib_openshift/library/oc_adm_router.py
  roles/lib_openshift/library/oc_clusterrole.py
  roles/lib_openshift/library/oc_configmap.py
  roles/lib_openshift/library/oc_edit.py
  roles/lib_openshift/library/oc_env.py
  roles/lib_openshift/library/oc_group.py
  roles/lib_openshift/library/oc_image.py
  roles/lib_openshift/library/oc_label.py
  roles/lib_openshift/library/oc_obj.py
  roles/lib_openshift/library/oc_objectvalidator.py
  roles/lib_openshift/library/oc_process.py
  roles/lib_openshift/library/oc_project.py
  roles/lib_openshift/library/oc_pvc.py
  roles/lib_openshift/library/oc_route.py
  roles/lib_openshift/library/oc_scale.py
  roles/lib_openshift/library/oc_secret.py
  roles/lib_openshift/library/oc_service.py
  roles/lib_openshift/library/oc_serviceaccount.py
  roles/lib_openshift/library/oc_serviceaccount_secret.py
  roles/lib_openshift/library/oc_storageclass.py
  roles/lib_openshift/library/oc_user.py
  roles/lib_openshift/library/oc_version.py
  roles/lib_openshift/library/oc_volume.py
  roles/lib_openshift/src/class/oc_adm_ca_server_cert.py
  roles/lib_openshift/src/class/oc_adm_csr.py
  roles/lib_openshift/src/class/oc_adm_manage_node.py
  roles/lib_openshift/src/class/oc_adm_policy_group.py
  roles/lib_openshift/src/class/oc_adm_policy_user.py
  roles/lib_openshift/src/class/oc_adm_registry.py
  roles/lib_openshift/src/class/oc_adm_router.py
  roles/lib_openshift/src/class/oc_clusterrole.py
  roles/lib_openshift/src/class/oc_configmap.py
  roles/lib_openshift/src/class/oc_edit.py
  roles/lib_openshift/src/class/oc_env.py
  roles/lib_openshift/src/class/oc_group.py
  roles/lib_openshift/src/class/oc_image.py
  roles/lib_openshift/src/class/oc_label.py
  roles/lib_openshift/src/class/oc_obj.py
  roles/lib_openshift/src/class/oc_objectvalidator.py
  roles/lib_openshift/src/class/oc_process.py
  roles/lib_openshift/src/class/oc_project.py
  roles/lib_openshift/src/class/oc_pvc.py
  roles/lib_openshift/src/class/oc_route.py
  roles/lib_openshift/src/class/oc_scale.py
  roles/lib_openshift/src/class/oc_secret.py
  roles/lib_openshift/src/class/oc_service.py
  roles/lib_openshift/src/class/oc_serviceaccount.py
  roles/lib_openshift/src/class/oc_serviceaccount_secret.py
  roles/lib_openshift/src/class/oc_storageclass.py
  roles/lib_openshift/src/class/oc_user.py
  roles/lib_openshift/src/class/oc_version.py
  roles/lib_openshift/src/class/oc_volume.py
Labels: approved, lgtm, size/L

#8468 bug 1581052: specify the namespace
  roles/ansible_service_broker/templates/asb_dc.yaml.j2
Labels: approved, lgtm, size/XS

#8461 Remove old openshift binaries from containerized upgragde
  roles/openshift_cli/tasks/main.yml
Labels: approved, lgtm, size/S

#8471 etcd runtime: system container can start etcd service too
  roles/etcd/tasks/runtime.yml
Labels: approved, lgtm, size/XS

#8466 Adding checks to make sure we dont fail if .failed doesnt exist
  roles/openshift_logging_elasticsearch/tasks/restart_es_node.yml
Labels: affects_3.7, affects_3.9, approved, lgtm

#8472 Docker registry: redeploy certs and update DC env vars only when registry is managed
  playbooks/common/openshift-cluster/upgrades/v3_10/upgrade_control_plane.yml
  playbooks/openshift-hosted/private/redeploy-registry-certificates.yml
Labels: approved, lgtm, size/XS
