Repository openshift/openshift-ansible, pull requests merged in 2019-10, with the labels that each got.

#11931 [GlusterFS]: fix cluster health check retry variable
  roles/openshift_storage_glusterfs/defaults/main.yml
  roles/openshift_storage_glusterfs/tasks/glusterfs_upgrade.yml
Labels: approved, lgtm, ok-to-test, size/XS

#11932 [GlusterFS]: Add check to see if daemon set was deleted successfully during upgrade
  roles/openshift_storage_glusterfs/tasks/glusterfs_upgrade.yml
Labels: approved, lgtm, ok-to-test, size/S

#11913 Mount the parent dir in daemonset configuration for openshift-sdn
  roles/openshift_sdn/files/sdn.yaml
Labels: approved, lgtm, size/S

#11914 BUG 1753890: Fixing NSX role templates to refer correct variable for clusterip
  roles/nsx/templates/ncp-configmap.yml.j2
  roles/nsx/templates/nsx-node-agent-configmap.yml.j2
Labels: approved, bugzilla/valid-bug, lgtm, ok-to-test, size/XS

#11936 [GlusterFS]: Use openshift_master_api_port var in delete daemonset task
  roles/openshift_storage_glusterfs/tasks/glusterfs_upgrade.yml
Labels: approved, lgtm, needs-ok-to-test, size/XS

#11939 [GlusterFS]: Limited sanity checks in upgrade playbook
  playbooks/openshift-glusterfs/upgrade.yml
Labels: approved, lgtm, ok-to-test, size/XS

#11938 Bug 1757081: Add check in etcd facts for certificate redeployment
  roles/openshift_etcd_facts/tasks/set_etcd_ca_host.yml
Labels: approved, bugzilla/valid-bug, lgtm, size/XS

#11944 fixed the security group tagging. also, don't re-create the _k8s sg's if they are there, openshift manages these sg's
  roles/openshift_aws/tasks/security_group.yml
Labels: approved, lgtm, size/M

#11943 [Glusterfs]: Check image tag versions earlier in the upgrade
  roles/openshift_storage_glusterfs/tasks/glusterfs_upgrade.yml
Labels: approved, lgtm, ok-to-test, size/XS

#11945 [GlusterFS]: Warn that the health check could take a long time
  roles/openshift_storage_glusterfs/tasks/cluster_health.yml
Labels: approved, lgtm, ok-to-test, size/XS

#11947 Bug 1760665: Ensure cri-o is upgraded
  roles/openshift_node/tasks/install.yml
Labels: approved, bugzilla/valid-bug, lgtm, size/XS

#11949 [GlusterFS]: revert heketi block secret type
  roles/openshift_storage_glusterfs/tasks/glusterblock_storageclass.yml
Labels: approved, lgtm, ok-to-test, size/XS

#11956 Bug 1758744: Fix upgrade not respecting openshift_pkg_version
  playbooks/openshift-master/private/upgrade.yml
  roles/openshift_ca/README.md
  roles/openshift_ca/meta/main.yml
  roles/openshift_cli/defaults/main.yml
  roles/openshift_cli/meta/main.yml
  roles/openshift_cli/tasks/main.yml
  roles/openshift_node/tasks/install.yml
Labels: approved, bugzilla/valid-bug, lgtm, size/M

#11958 Add possibility to use certs on master as source
  roles/openshift_hosted/defaults/main.yml
  roles/openshift_hosted/tasks/router.yml
  roles/openshift_named_certificates/defaults/main.yml
  roles/openshift_named_certificates/tasks/main.yml
Labels: approved, lgtm, ok-to-test, size/XS

#11964 Bug 1763046: roles/openshift_cluster_monitoring_operator: remove limits
  roles/openshift_cluster_monitoring_operator/templates/cluster-monitoring-operator-deployment.j2
Labels: approved, bugzilla/valid-bug, lgtm, size/XS

#11963 Bug 1726450: Increase timeout for control plane pod checks
  roles/openshift_control_plane/tasks/check_master_api_is_ready.yml
  roles/openshift_control_plane/tasks/main.yml
Labels: approved, bugzilla/valid-bug, lgtm, size/M

#11966 Bug 1762932: Back up certificates on all masters
  playbooks/openshift-master/private/certificates-backup.yml
Labels: approved, bugzilla/valid-bug, lgtm, size/S

#11969 Bug 1759835: Fix redploy-certificates (metrics server)
  playbooks/common/openshift-cluster/upgrades/v3_11/upgrade_control_plane_part2.yml
  playbooks/common/private/components.yml
  playbooks/metrics-server/private/redeploy-certificates.yml
  playbooks/redeploy-certificates.yml
Labels: approved, bugzilla/valid-bug, lgtm, size/S

#11962 JKS renewal bug
  roles/openshift_logging_elasticsearch/tasks/generate_secret.yaml
Labels: approved, lgtm, size/XS

#11972 Bug 1759835: Ensure openshift_metrics_server_install defaults are set
  playbooks/common/openshift-cluster/upgrades/v3_11/upgrade_control_plane_part2.yml
  playbooks/common/private/components.yml
  playbooks/redeploy-certificates.yml
  roles/openshift_facts/defaults/main.yml
  roles/openshift_master_facts/tasks/main.yml
Labels: approved, bugzilla/valid-bug, lgtm, size/M

#11971 Bug 1757501: Fixup kibana-proxy proxy variable sources
  roles/openshift_logging_kibana/templates/kibana.j2
Labels: approved, bugzilla/valid-bug, lgtm, size/S

#11978 metrics-server: Add metrics role
  roles/metrics_server/files/metrics-server-aggregated-metrics-reader.yaml
  roles/metrics_server/tasks/generate_sa_and_rbac.yaml
Labels: approved, lgtm, size/S

#11974 Bug 1729994: Allow custom mirrored registry paths
  roles/openshift_facts/defaults/main.yml
Labels: approved, bugzilla/valid-bug, lgtm, size/S

#11976 Bug 1643397: Fix satellite subscription registration
  roles/openshift_repos/tasks/rhel_repos.yml
  roles/rhel_subscribe/tasks/main.yml
Labels: approved, bugzilla/valid-bug, lgtm, size/S

#11965 Bug 1694014: add more vars to json facts list
  roles/openshift_facts/library/openshift_facts.py
Labels: approved, bugzilla/valid-bug, lgtm, size/XS

#11979 Bug 1729994: Escape literals in regex for test image
  roles/openshift_facts/defaults/main.yml
Labels: approved, bugzilla/valid-bug, lgtm, size/XS

#11973 Bug 1744248: Update docs to indicate that changing will break install
  roles/openshift_metrics/README.md
Labels: approved, bugzilla/valid-bug, lgtm, ok-to-test, size/XS

#11968 Bug 1746143: Add CA to system trust
  playbooks/openshift-node/private/join.yml
  roles/openshift_node/tasks/bootstrap.yml
  roles/openshift_node/tasks/distribute_bootstrap.yml
  roles/openshift_node/tasks/upgrade/config_changes.yml
Labels: approved, bugzilla/valid-bug, lgtm, size/S

#11925 Modify the default kuryr images
  roles/kuryr/defaults/main.yaml
Labels: approved, lgtm, size/S
