Repository openshift/openshift-ansible, pull requests merged in 2019-04, with the labels that each got.

#11412 Update kube-rbac-proxy to v0.4.1
  roles/openshift_monitor_availability/files/monitor-app-create.yaml
Labels: approved, lgtm, size/XS

#11364 [release-3.11] Satellite image URL can be worked in example template image url replecement.
  roles/openshift_examples/defaults/main.yml
  roles/openshift_examples/tasks/stream_secrets.yml
Labels: approved, lgtm, ok-to-test, size/S

#11436 test/deprovision: retry attempts to destroy instances and SG
  test/ci/deprovision.yml
Labels: approved, lgtm, size/S

#11435 Clean up test dir: delete 3.X CI & move libvirt to hack
  hack/libvirt/README.md
  hack/libvirt/cleanup.sh
  hack/libvirt/deploy.sh
  hack/libvirt/deploy_centos.sh
  hack/libvirt/dnsmasq_setup.sh
  hack/libvirt/generate_assets.sh
  hack/libvirt/generate_inventory.sh
  hack/libvirt/group_vars/nodes.yml
  hack/libvirt/install-config.yml.template
  hack/libvirt/installrc
  hack/libvirt/installrc_centos
  hack/libvirt/inv.txt.template
  hack/libvirt/node_scaleup.sh
  hack/libvirt/playbooks/files/openshift-local.repo
  hack/libvirt/playbooks/localrepo.yml
  hack/libvirt/playbooks/prep.yml
  hack/libvirt/playbooks/rhel_prep.yml
  hack/libvirt/playbooks/templates/buildah_repo.sh
  hack/libvirt/rhel_setup.sh
  hack/libvirt/run_ansible.sh
  hack/libvirt/ssh_config.sh
  hack/libvirt/terraform/bootstrap/README.md
  hack/libvirt/terraform/bootstrap/main.tf
  hack/libvirt/terraform/bootstrap/meta-data.tpl
  hack/libvirt/terraform/bootstrap/user-data.tpl
  hack/libvirt/terraform/bootstrap/variables.tf
  hack/libvirt/terraform/config.tf
  hack/libvirt/terraform/main.tf
  hack/libvirt/terraform/terraform.tfvars.template
  hack/libvirt/terraform/user-data.tpl
  hack/libvirt/terraform/variables-libvirt.tf
  hack/libvirt/terraform/volume/main.tf
  hack/libvirt/terraform/volume/outputs.tf
  hack/libvirt/terraform/volume/variables.tf
  hack/libvirt/terraform_provision.sh
  test/ci/README.md
  test/ci/deprovision.yml
  test/ci/inventory/group_vars/OSEv3/vars.yml
  test/ci/launch.yml
  test/ci/template-inventory.j2
  test/ci/vars.yml.sample
Labels: approved, lgtm, size/L

#11411 ASB: use `${version}` in default Origin image
  roles/ansible_service_broker/defaults/main.yml
Labels: approved, lgtm, size/XS

#11445 Revert "bug 1666674. Add Kibana sar and delegate url for auth-delegator"
  roles/openshift_logging_kibana/tasks/main.yaml
  roles/openshift_logging_kibana/templates/kibana.j2
Labels: approved, lgtm, size/S

#11446 [KIECLOUD-171] - Update Application templates and imagestreams on OCP…
  roles/openshift_examples/examples-sync.sh
  roles/openshift_examples/files/examples/x86_64/xpaas-streams/decisionserver62-image-stream.json
  roles/openshift_examples/files/examples/x86_64/xpaas-streams/decisionserver63-image-stream.json
  roles/openshift_examples/files/examples/x86_64/xpaas-streams/decisionserver64-image-stream.json
  roles/openshift_examples/files/examples/x86_64/xpaas-streams/processserver63-image-stream.json
  roles/openshift_examples/files/examples/x86_64/xpaas-streams/processserver64-image-stream.json
  roles/openshift_examples/files/examples/x86_64/xpaas-templates/decisionserver64-amq-s2i.json
  roles/openshift_examples/files/examples/x86_64/xpaas-templates/decisionserver64-basic-s2i.json
  roles/openshift_examples/files/examples/x86_64/xpaas-templates/decisionserver64-https-s2i.json
  roles/openshift_examples/files/examples/x86_64/xpaas-templates/processserver64-amq-mysql-persistent-s2i.json
  roles/openshift_examples/files/examples/x86_64/xpaas-templates/processserver64-amq-mysql-s2i.json
  roles/openshift_examples/files/examples/x86_64/xpaas-templates/processserver64-amq-postgresql-persistent-s2i.json
  roles/openshift_examples/files/examples/x86_64/xpaas-templates/processserver64-amq-postgresql-s2i.json
  roles/openshift_examples/files/examples/x86_64/xpaas-templates/processserver64-basic-s2i.json
  roles/openshift_examples/files/examples/x86_64/xpaas-templates/processserver64-externaldb-s2i.json
  roles/openshift_examples/files/examples/x86_64/xpaas-templates/processserver64-mysql-persistent-s2i.json
  roles/openshift_examples/files/examples/x86_64/xpaas-templates/processserver64-mysql-s2i.json
  roles/openshift_examples/files/examples/x86_64/xpaas-templates/processserver64-postgresql-persistent-s2i.json
  roles/openshift_examples/files/examples/x86_64/xpaas-templates/processserver64-postgresql-s2i.json
Labels: approved, lgtm, ok-to-test, size/XXL

#11402 [KIECLOUD-110] - Update RHDM and RHPAM 7.30 templates on OCP and OSO …
  roles/openshift_examples/examples-sync.sh
  roles/openshift_examples/files/examples/x86_64/xpaas-streams/rhdm73-image-streams.yaml
  roles/openshift_examples/files/examples/x86_64/xpaas-streams/rhpam73-image-streams.yaml
  roles/openshift_examples/files/examples/x86_64/xpaas-templates/rhdm73-authoring-ha.yaml
  roles/openshift_examples/files/examples/x86_64/xpaas-templates/rhdm73-authoring.yaml
  roles/openshift_examples/files/examples/x86_64/xpaas-templates/rhdm73-kieserver.yaml
  roles/openshift_examples/files/examples/x86_64/xpaas-templates/rhdm73-optaweb-employee-rostering.yaml
  roles/openshift_examples/files/examples/x86_64/xpaas-templates/rhdm73-prod-immutable-kieserver.yaml
  roles/openshift_examples/files/examples/x86_64/xpaas-templates/rhdm73-trial-ephemeral.yaml
  roles/openshift_examples/files/examples/x86_64/xpaas-templates/rhpam73-authoring-ha.yaml
  roles/openshift_examples/files/examples/x86_64/xpaas-templates/rhpam73-authoring.yaml
  roles/openshift_examples/files/examples/x86_64/xpaas-templates/rhpam73-kieserver-externaldb.yaml
  roles/openshift_examples/files/examples/x86_64/xpaas-templates/rhpam73-kieserver-mysql.yaml
  roles/openshift_examples/files/examples/x86_64/xpaas-templates/rhpam73-kieserver-postgresql.yaml
  roles/openshift_examples/files/examples/x86_64/xpaas-templates/rhpam73-managed.yaml
  roles/openshift_examples/files/examples/x86_64/xpaas-templates/rhpam73-prod-immutable-kieserver.yaml
  roles/openshift_examples/files/examples/x86_64/xpaas-templates/rhpam73-prod-immutable-monitor.yaml
  roles/openshift_examples/files/examples/x86_64/xpaas-templates/rhpam73-prod.yaml
  roles/openshift_examples/files/examples/x86_64/xpaas-templates/rhpam73-trial-ephemeral.yaml
Labels: approved, lgtm, ok-to-test, size/XXL

#11452 Use oc binary instead of k8s_facts
  README.md
  roles/openshift_node/tasks/config.yml
Labels: approved, lgtm, size/S

#11426 Providing default oreg_url for validation
  roles/container_runtime/tasks/common/pre.yml
Labels: approved, lgtm, ok-to-test, size/XS

#11439 Aci release 3.10
  playbooks/init/main.yml
  playbooks/init/validate_aci_params.yml
  playbooks/openshift-master/private/config.yml
  playbooks/openshift-node/private/join.yml
  roles/aci/README.md
  roles/aci/defaults/main.yml
  roles/aci/tasks/firewall.yml
  roles/aci/tasks/main.yml
  roles/openshift_control_plane/defaults/main.yml
  roles/openshift_node/defaults/main.yml
Labels: approved, lgtm, ok-to-test, size/L

#11453 Remove block storageclass when uninstalling
  roles/openshift_storage_glusterfs/tasks/glusterfs_uninstall.yml
Labels: approved, lgtm, ok-to-test, size/XS

#11456 redeploy certificates fails if use_crio_only
  playbooks/openshift-node/private/restart.yml
  playbooks/redeploy-certificates.yml
Labels: approved, lgtm, size/XS

#11455 Update crictl.yaml runtime-endpoint config to resolve warning
  roles/container_runtime/tasks/package_crio.yml
  roles/openshift_node/tasks/upgrade.yml
Labels: approved, lgtm, size/XS

#11409 Clear the cni config on boot
  roles/openshift_node/tasks/systemd_units.yml
  roles/openshift_node/templates/cleanup-cni.j2
  roles/openshift_sdn/files/sdn.yaml
Labels: approved, lgtm, size/S

#11442 openshift_ovirt: Support setting mac_address on the vm manifest
  roles/openshift_ovirt/README.md
  roles/openshift_ovirt/tasks/build_vm_list.yml
  roles/openshift_ovirt/templates/vms.j2
Labels: approved, lgtm, ok-to-test, size/M

#11449 Option to add and annotate namespaces for openshift-service-catalog
  roles/aci/defaults/main.yml
  roles/aci/tasks/main.yml
Labels: approved, lgtm, ok-to-test, size/S

#11468 [release-3.9] Backport version requirement plugin fixes
  roles/lib_utils/callback_plugins/aa_version_requirement.py
Labels: approved, lgtm, size/M

#11465 [release-3.10] ASB: use `${version}` in default image
  roles/ansible_service_broker/defaults/main.yml
Labels: approved, lgtm, size/XS

#11467 [release-3.10] Backport version requirement plugin fixes
  roles/lib_utils/callback_plugins/aa_version_requirement.py
Labels: approved, lgtm, size/M

#11469 OLM: use olm_operator_version as a tag for Origin images
  roles/olm/defaults/main.yaml
Labels: approved, lgtm, size/XS

#11460 Update docs for scaleup and upgrade
  HOOKS.md
  README.md
  docs/pull_requests.md
  inventory/hosts.example
  roles/openshift_node/README.md
Labels: approved, lgtm, size/L

#11434 Move repo setup into test.
  roles/openshift_repos/README.md
  roles/openshift_repos/defaults/main.yaml
  roles/openshift_repos/files/origin/gpg_keys/openshift-ansible-CentOS-SIG-PaaS
  roles/openshift_repos/handlers/main.yml
  roles/openshift_repos/tasks/centos_repos.yml
  roles/openshift_repos/tasks/main.yaml
  roles/openshift_repos/tasks/rhel_repos.yml
  roles/openshift_repos/templates/CentOS-OpenShift-Origin.repo.j2
  roles/openshift_repos/templates/CentOS-OpenShift-Origin14.repo.j2
  roles/openshift_repos/templates/CentOS-OpenShift-Origin15.repo.j2
  roles/openshift_repos/templates/CentOS-OpenShift-Origin310.repo.j2
  roles/openshift_repos/templates/CentOS-OpenShift-Origin36.repo.j2
  roles/openshift_repos/templates/CentOS-OpenShift-Origin37.repo.j2
  test/aws/additional_repos.yml
  test/aws/scaleup.yml
Labels: approved, lgtm, size/L

#11470 tmpfile.d file clears the cni config on boot
  roles/openshift_node/tasks/systemd_units.yml
  roles/openshift_node/templates/cleanup-cni.j2
  roles/openshift_sdn/files/sdn.yaml
Labels: approved, lgtm, size/S

#11472 Add playbooks to regenerate TLS certificates for openshift-monitoring
  playbooks/openshift-monitoring/private/redeploy-certificates.yml
  playbooks/openshift-monitoring/redeploy-certificates.yml
  playbooks/redeploy-certificates.yml
Labels: approved, lgtm, size/L

#11473 Update README.md
  README.md
Labels: approved, lgtm, needs-ok-to-test, retest-not-required-docs-only, size/XS

#11476 Ports backport of #10173
  playbooks/openstack/configuration.md
  roles/openshift_openstack/defaults/main.yml
Labels: approved, lgtm, size/L

#11459 openshift_ovirt: fix inventory items creation
  roles/openshift_ovirt/tasks/create_inventory_from_vms.yaml
Labels: approved, lgtm, ok-to-test, size/S

#11477 Prevent installing cni-cleanup file on Atomic Hosts
  roles/openshift_node/tasks/systemd_units.yml
Labels: approved, lgtm, needs-ok-to-test, size/XS

#11480 Dockerfile: install python2-psutil and lock azure-cli-core
  images/installer/Dockerfile
Labels: approved, lgtm, size/XS

#11479 Change the cni-cleanup file path to /etc
  roles/openshift_node/tasks/systemd_units.yml
Labels: approved, lgtm, ok-to-test, size/XS

#11448 Fix wrong storage_class assignment for Elastic Search when using two GlusterFS clusters
  roles/openshift_logging_elasticsearch/tasks/main.yaml
Labels: approved, lgtm, ok-to-test, size/XS

#11478 Update crictl.yaml runtime-endpoint config to resolve warning
  roles/container_runtime/tasks/package_crio.yml
  roles/openshift_node/tasks/upgrade.yml
Labels: approved, lgtm, size/S

#11491 [release-3.11] WIP Ensure master vars are passed to openshift_facts on upgrade
  playbooks/common/openshift-cluster/upgrades/pre/verify_cluster.yml
Labels: approved, lgtm, size/XS

#11474 Console cert redeploy: rerun install
  playbooks/openshift-console/private/redeploy-certificates.yml
Labels: approved, lgtm, size/S

#11471 [release-3.9] Fix condition key for all opened ports by Contrail SDN
  roles/openshift_node/defaults/main.yml
Labels: approved, lgtm, ok-to-test, size/L

#11487 [release-3.10] ensure master vars are passed to openshift_facts on upgrade
  playbooks/common/openshift-cluster/upgrades/pre/verify_cluster.yml
Labels: approved, lgtm, size/XS

#11483 Fixes NotReady nodes after ca and certificate update
  playbooks/openshift-node/private/certificates-backup.yml
  playbooks/redeploy-certificates.yml
Labels: approved, lgtm, size/S

#7467 Supports the latest image tag in a major version
  roles/openshift_version/tasks/main.yml
Labels: approved, lgtm, size/XS

#10210 [release-3.9] Configure Ansible service broker secrets
  roles/ansible_service_broker/defaults/main.yml
  roles/ansible_service_broker/tasks/install.yml
Labels: approved, lgtm, size/XS

#8089 Pull 3.7 images when using the 3.7 broker
  roles/ansible_service_broker/vars/default_images.yml
Labels: approved, lgtm, size/XS

#11353 Fix serviceaccounts' secrets for Metrics
  roles/openshift_metrics/tasks/generate_serviceaccounts.yaml
  roles/openshift_metrics/tasks/install_heapster.yaml
Labels: approved, lgtm, ok-to-test, size/S

#11501 openshift_ovirt: Fix hostname in the inventory groups
  roles/openshift_ovirt/tasks/add_host.yaml
  roles/openshift_ovirt/tasks/create_inventory_from_vms.yaml
Labels: approved, lgtm, ok-to-test, size/M

#11356 Fix serviceaccounts' secrets for Metrics
  roles/openshift_metrics/tasks/generate_serviceaccounts.yaml
  roles/openshift_metrics/tasks/install_heapster.yaml
Labels: approved, lgtm, ok-to-test, size/S

#11355 Fix serviceaccounts' secrets for Metrics
  roles/openshift_metrics/tasks/generate_serviceaccounts.yaml
  roles/openshift_metrics/tasks/install_heapster.yaml
Labels: approved, lgtm, ok-to-test, size/S

#11398 [release-3.10] Calico: Add support for environment variable IP_AUTODETECTION_METHOD
  roles/calico_master/defaults/main.yaml
  roles/calico_master/templates/calico.yml.j2
  roles/calico_master/templates/calicov3.yml.j2
Labels: approved, lgtm, ok-to-test, size/XS

#11493 Reboot after running mcd --once-from
  roles/openshift_node/tasks/config.yml
Labels: approved, lgtm, size/S

#11511 #10765 Update installation doc link for release-3.9
  README.md
Labels: approved, lgtm, ok-to-test, size/XS

#11513 #10765 Update installation doc link for release-3.11
  README.md
Labels: approved, lgtm, ok-to-test, size/XS

#11516 Update openshift_facts facts gathering
  roles/openshift_facts/library/openshift_facts.py
Labels: approved, lgtm, size/M

#11517 [release-3.11] Test using Ansible 2.7.10
  images/installer/Dockerfile
  images/installer/origin-extra-root/etc/yum.repos.d/ansible-releases.repo
  images/installer/origin-extra-root/etc/yum.repos.d/centos-ansible27.repo
  requirements.txt
Labels: approved, lgtm, size/S

#11490 Test using Ansible 2.7.10
  images/installer/origin-extra-root/etc/yum.repos.d/ansible-releases.repo
  images/installer/origin-extra-root/etc/yum.repos.d/centos-ansible27.repo
  openshift-ansible.spec
  requirements.txt
Labels: approved, lgtm, size/S

#11514 #10765 Update installation doc link
  README.md
Labels: approved, lgtm, ok-to-test, size/XS

#11521 Add nodeName to node-config template for azure
  playbooks/prerequisites.yml
  roles/openshift_node_group/tasks/create_config.yml
  roles/openshift_node_group/templates/node-config.yaml.j2
Labels: approved, lgtm, size/S

#11495 bug 1695903. fix es metrics
  roles/openshift_logging_elasticsearch/templates/es.j2
Labels: approved, lgtm, size/XS

#11525 [release-3.11] Stop gathering Ansible facts in openshift_facts
  playbooks/common/openshift-cluster/upgrades/pre/verify_cluster.yml
  playbooks/init/cluster_facts.yml
  playbooks/openshift-logging/private/config.yml
  playbooks/openshift-master/private/config.yml
  roles/openshift_builddefaults/tasks/main.yml
  roles/openshift_buildoverrides/tasks/main.yml
  roles/openshift_ca/tasks/main.yml
  roles/openshift_cloud_provider/tasks/main.yml
  roles/openshift_control_plane/tasks/main.yml
  roles/openshift_facts/library/openshift_facts.py
  roles/openshift_facts/vars/main.yml
  roles/openshift_management/tasks/add_container_provider.yml
  roles/openshift_master_facts/tasks/main.yml
  roles/openshift_named_certificates/tasks/main.yml
  roles/openshift_node/tasks/configure-proxy-settings.yml
Labels: approved, lgtm, size/M

#11515 [3.11] GlusterFS: Upgrade playbook fixes
  playbooks/openshift-glusterfs/private/setup_nodes.yml
  playbooks/openshift-glusterfs/private/upgrade.yml
  playbooks/openshift-glusterfs/upgrade.yml
  roles/openshift_node/tasks/glusterfs.yml
  roles/openshift_storage_glusterfs/tasks/heketi_pod_check.yml
Labels: approved, lgtm, size/M

#11538 Add crio defaults to openshift_facts
  roles/openshift_facts/defaults/main.yml
Labels: approved, lgtm, size/XS

#11526 [release-3.7] Fix misspelled openshift_hosted_registry_namespace var.
  roles/openshift_hosted/tasks/storage/glusterfs_endpoints.yml
  roles/openshift_storage_glusterfs/defaults/main.yml
Labels: approved, lgtm, size/XS

#11523 Remove systemd-journal-gateway from package list
  roles/openshift_node/defaults/main.yml
Labels: approved, lgtm, size/XS

#11540 [release-3.11] Move modify_yaml test to appropriate directory
  roles/lib_utils/test/modify_yaml_tests.py
Labels: approved, lgtm, size/XS

#11534 [release-3.10] Test using Ansible 2.7.10
  images/installer/Dockerfile
  images/installer/origin-extra-root/etc/yum.repos.d/ansible-releases.repo
  images/installer/origin-extra-root/etc/yum.repos.d/centos-ansible24.repo
  requirements.txt
  roles/openshift_health_checker/test/action_plugin_test.py
  setup.py
Labels: approved, lgtm, size/M

#11535 [release-3.9] Test using Ansible 2.7.10
  images/installer/Dockerfile
  images/installer/origin-extra-root/etc/yum.repos.d/ansible-releases.repo
  requirements.txt
  roles/openshift_health_checker/test/action_plugin_test.py
Labels: approved, lgtm, size/S

#11541 imageconfig playbook fails with undefined variables
  playbooks/openshift-node/imageconfig.yml
  playbooks/openshift-node/private/registry_auth.yml
Labels: approved, lgtm, size/XS

#11518 Remove early oc client install on upgrade.
  playbooks/common/openshift-cluster/upgrades/pre/verify_cluster.yml
  roles/openshift_storage_glusterfs/tasks/cluster_health.yml
  roles/openshift_storage_glusterfs/tasks/oc_client_check.yml
Labels: approved, lgtm, size/M

#11488 Add --debug flag to skopeo inspect in image health check.
  roles/openshift_health_checker/openshift_checks/docker_image_availability.py
  roles/openshift_health_checker/test/docker_image_availability_test.py
Labels: approved, lgtm, size/XS

#11539 Fix openshift_logging set_fact FAILED in python3
  roles/openshift_logging/tasks/set_defaults_from_current.yml
  roles/openshift_logging_curator/templates/curator-cj.j2
Labels: approved, lgtm, needs-ok-to-test, size/XS

#11520 Correctly evaluate openshift_metrics_heapster_standalone variable if …
  roles/openshift_metrics/templates/heapster.j2
Labels: approved, lgtm, ok-to-test, size/XS

#11507 Annotating openshift specific namespaces for ACI CNI
  roles/aci/tasks/main.yml
Labels: approved, lgtm, ok-to-test, size/XS

#11550 SDN: tolerate taints
  roles/openshift_sdn/files/sdn.yaml
Labels: approved, lgtm, size/XS

#11548 [release-3.11] Correct usage of openshift_facts
  playbooks/openshift-hosted/private/install_docker_gc.yml
  playbooks/openshift-logging/private/config.yml
Labels: approved, lgtm, size/XS

#11553 Removing quotes while executing few aci related shell commands
  roles/aci/tasks/main.yml
Labels: approved, lgtm, ok-to-test, size/S

#11556 [release-3.9] Stop gathering Ansible facts in openshift_facts
  playbooks/common/openshift-cluster/upgrades/pre/verify_cluster.yml
  playbooks/init/cluster_facts.yml
  playbooks/openshift-master/private/config.yml
  playbooks/openshift-master/private/scaleup.yml
  playbooks/openshift-master/private/set_network_facts.yml
  playbooks/openshift-master/private/validate_restart.yml
  roles/etcd/tasks/upgrade/upgrade_image.yml
  roles/openshift_builddefaults/tasks/main.yml
  roles/openshift_buildoverrides/tasks/main.yml
  roles/openshift_ca/tasks/main.yml
  roles/openshift_cli/tasks/main.yml
  roles/openshift_cloud_provider/tasks/main.yml
  roles/openshift_facts/library/openshift_facts.py
  roles/openshift_facts/vars/main.yml
  roles/openshift_management/tasks/add_container_provider.yml
  roles/openshift_master/tasks/main.yml
  roles/openshift_master_facts/tasks/main.yml
  roles/openshift_named_certificates/tasks/main.yml
Labels: approved, lgtm, size/M

#11549 [release-3.10] Correct usage of openshift_facts
  playbooks/openshift-hosted/private/install_docker_gc.yml
Labels: approved, lgtm, size/XS

#11557 [3.11] Additional GlusterFS upgrade playbook fixes
  playbooks/openshift-glusterfs/private/setup_nodes.yml
  roles/openshift_node/tasks/main.yml
  roles/openshift_node/tasks/storage_plugin_ceph.yml
  roles/openshift_node/tasks/storage_plugin_iscsi.yml
  roles/openshift_node/tasks/storage_plugin_nfs.yml
  roles/openshift_storage_glusterfs/tasks/glusterfs_upgrade.yml
Labels: approved, lgtm, size/M

#11560 Replace remote_group_id by remote_ip_prefix
  roles/openshift_openstack/templates/heat_stack.yaml.j2
Labels: approved, lgtm, size/XS
