Repository openshift/openshift-ansible, pull requests merged in 2019-07, with the labels that each got.

#11735 roles/openshift-metrics: Allow configuring heapster log level
  roles/openshift_metrics/defaults/main.yaml
  roles/openshift_metrics/templates/heapster.j2
Labels: approved, lgtm, size/XS

#11734 Fix indentation on Kuryr volumes
  roles/kuryr/templates/cni-daemonset.yaml.j2
  roles/kuryr/templates/controller-deployment.yaml.j2
Labels: approved, lgtm, size/S

#11702 openvswtich logrotate is missing due to sdn container change
  roles/openshift_sdn/files/sdn-ovs.yaml
Labels: approved, lgtm, size/S

#11631 Update tox test environment vars
  setup.py
  test/tox-inventory.txt
  test/tox-inventory.txt_extras
  tox.ini
Labels: approved, lgtm, size/S

#11736 [release-3.11] Update tox test environment vars
  setup.py
  test/tox-inventory.txt_extras
  tox.ini
Labels: approved, lgtm, size/S

#11742 Fix small typo in task name
  roles/openshift_control_plane/tasks/main.yml
Labels: approved, lgtm, ok-to-test, size/XS

#11737 [release-3.10] Update tox test environment vars
  setup.py
  test/tox-inventory.txt_extras
  tox.ini
Labels: approved, lgtm, size/S

#11595 Fix until conditionals to handle failed tasks
  roles/openshift_node/tasks/apply_machine_config.yml
  roles/openshift_node/tasks/config.yml
Labels: approved, lgtm, size/XS

#11623 Refactor openshift_node
  README.md
  images/installer/root/usr/local/bin/entrypoint-provider
  inventory/hosts.example
  roles/openshift_node/defaults/main.yml
  roles/openshift_node/tasks/apply_machine_config.yml
  roles/openshift_node/tasks/config.yml
Labels: approved, lgtm, size/L

#11661 test: ignore errors when collecting a list of containers
  roles/openshift_node/tasks/install.yml
  test/aws/scaleup.yml
Labels: approved, lgtm, size/XS

#11624 Install openshift RPMs based on cluster version
  images/installer/root/usr/local/bin/entrypoint-provider
  roles/openshift_node/defaults/main.yml
  roles/openshift_node/tasks/install.yml
  roles/openshift_node/tasks/upgrade.yml
Labels: approved, lgtm, size/M

#11627 Scaleup: Check new_workers for active nodes
  playbooks/scaleup.yml
  roles/openshift_node/defaults/main.yml
  roles/openshift_node/tasks/scaleup_checks.yml
Labels: approved, lgtm, size/M

#11691 test: wait for machineconfigpool to rollout
  test/aws/scaleup.yml
Labels: approved, lgtm, size/XS

#11732 Kube Proxy needed to be deployed for ACI to run as a part of upgrade from 3.9 to 3.10
  playbooks/common/openshift-cluster/upgrades/v3_10/upgrade_control_plane.yml
Labels: approved, lgtm, ok-to-test, size/XS

#11747 Require Ansible 2.8.1 for release-4.2
  README.md
  openshift-ansible.spec
  requirements.txt
  roles/openshift_node/callback_plugins/aa_version_requirement.py
Labels: approved, lgtm, size/S

#11751 GlusterFS: Fix version image check
  roles/openshift_storage_glusterfs/tasks/version_check.yml
Labels: approved, lgtm, size/S

#11748 GlusterFS: Remove the default values used for keys
  roles/openshift_storage_glusterfs/templates/heketi.json.j2
Labels: approved, lgtm, size/XS

#11752 Adds current registry route hostname when generating the new certs
  playbooks/openshift-hosted/private/redeploy-registry-certificates.yml
Labels: approved, lgtm, ok-to-test, size/S

#11756 translate_idps: use py3-specific infinity number if available
  roles/lib_utils/filter_plugins/openshift_master.py
Labels: approved, lgtm, size/S

#11733 Kube Proxy needed to be deployed for ACI to run as a part of upgrade from OSP 3.10 to 3.11
  playbooks/common/openshift-cluster/upgrades/v3_11/upgrade_control_plane_part2.yml
Labels: approved, lgtm, ok-to-test, size/XS

#11757 restart.yml - check gluster health before and after restart
  playbooks/openshift-node/private/restart.yml
Labels: approved, lgtm, ok-to-test, size/S

#11727 kube-proxy, namespace and firewalld corrections
  playbooks/openshift-node/private/contrail_sanitize.yml
  roles/contrail_master/tasks/main.yaml
  roles/contrail_master/tasks/os_contrail_master.yaml
Labels: approved, lgtm, ok-to-test, size/XS

#11761 Setup NetworkManager script before starting dnsmasq
  roles/openshift_node/tasks/dnsmasq.yml
Labels: approved, lgtm, ok-to-test, size/XS

#11766 [release-3.11]Wait the new scale group nodes to be ready before drain the old nodes during upgrade
  roles/openshift_aws/defaults/main.yml
  roles/openshift_aws/tasks/provision_nodes.yml
  roles/openshift_aws/tasks/wait_for_groups.yml
  roles/openshift_aws/tasks/wait_for_node.yml
Labels: approved, lgtm, size/S

#11768 Bug 1730065: Fix web console deployment conditional
  roles/openshift_web_console/tasks/start.yml
Labels: approved, bugzilla/valid-bug, lgtm, size/XS

#11764 GlusterFS upgrade playbook related additional fixes
  playbooks/openshift-glusterfs/private/setup_nodes.yml
  playbooks/openshift-glusterfs/private/upgrade.yml
  playbooks/openshift-glusterfs/upgrade.yml
  roles/openshift_node/tasks/glusterfs.yml
  roles/openshift_node/tasks/main.yml
  roles/openshift_node/tasks/storage_plugin_ceph.yml
  roles/openshift_node/tasks/storage_plugin_iscsi.yml
  roles/openshift_node/tasks/storage_plugin_nfs.yml
  roles/openshift_storage_glusterfs/tasks/glusterfs_upgrade.yml
  roles/openshift_storage_glusterfs/tasks/heketi_db_backup.yml
  roles/openshift_storage_glusterfs/tasks/heketi_pod_check.yml
Labels: approved, lgtm, size/L

#11771 Bug 1726717 : Add missing es_dc_index for ops install
  roles/openshift_logging/tasks/install_logging.yaml
  roles/openshift_logging_elasticsearch/tasks/main.yaml
Labels: approved, lgtm, size/S

#11772 Modify "Updating vm.max_map_count value" task to create 99-elasticsearch.conf file when vm.max_map_count is set to <= 262144
  playbooks/openshift-logging/private/config.yml
Labels: approved, lgtm, size/XS

#11773 [Glusterfs] Before upgrade, check for pending heketi operations.
  roles/openshift_storage_glusterfs/tasks/glusterfs_upgrade.yml
  roles/openshift_storage_glusterfs/tasks/heketi_ops_pending.yml
  roles/openshift_storage_glusterfs/tasks/heketi_set_ro.yml
Labels: approved, lgtm, size/S

#11759 Switch to the new default storage class annotation
  roles/lib_openshift/library/oc_storageclass.py
  roles/lib_openshift/src/lib/storageclass.py
  roles/lib_openshift/src/test/unit/test_oc_storageclass.py
Labels: approved, lgtm, ok-to-test, size/S

#11779 Bug 1727140: atomic-openshift-node service restarts every 3 minutes after using openshift_node_local_quota_per_fsgroup parameter during installation
  roles/openshift_node_group/files/sync.yaml
Labels: approved, bugzilla/valid-bug, lgtm, size/M

#11774 [KIECLOUD-202] - Update OpenShift catalog for RHIPS/DS 6.4.12
  roles/openshift_examples/examples-sync.sh
  roles/openshift_examples/files/examples/x86_64/xpaas-streams/decisionserver64-image-stream.json
  roles/openshift_examples/files/examples/x86_64/xpaas-streams/processserver64-image-stream.json
  roles/openshift_examples/files/examples/x86_64/xpaas-templates/decisionserver64-amq-s2i.json
  roles/openshift_examples/files/examples/x86_64/xpaas-templates/decisionserver64-basic-s2i.json
  roles/openshift_examples/files/examples/x86_64/xpaas-templates/decisionserver64-https-s2i.json
  roles/openshift_examples/files/examples/x86_64/xpaas-templates/processserver64-amq-mysql-persistent-s2i.json
  roles/openshift_examples/files/examples/x86_64/xpaas-templates/processserver64-amq-mysql-s2i.json
  roles/openshift_examples/files/examples/x86_64/xpaas-templates/processserver64-amq-postgresql-persistent-s2i.json
  roles/openshift_examples/files/examples/x86_64/xpaas-templates/processserver64-amq-postgresql-s2i.json
  roles/openshift_examples/files/examples/x86_64/xpaas-templates/processserver64-basic-s2i.json
  roles/openshift_examples/files/examples/x86_64/xpaas-templates/processserver64-externaldb-s2i.json
  roles/openshift_examples/files/examples/x86_64/xpaas-templates/processserver64-mysql-persistent-s2i.json
  roles/openshift_examples/files/examples/x86_64/xpaas-templates/processserver64-mysql-s2i.json
  roles/openshift_examples/files/examples/x86_64/xpaas-templates/processserver64-postgresql-persistent-s2i.json
  roles/openshift_examples/files/examples/x86_64/xpaas-templates/processserver64-postgresql-s2i.json
Labels: approved, lgtm, needs-ok-to-test, size/M

#11777 [Glusterfs]: Bring down the number of retries attempted for upgrade p…
  roles/openshift_storage_glusterfs/tasks/glusterfs_upgrade.yml
Labels: approved, lgtm, size/XS

#11778 [Glusterfs]: Ensure that all versions mentioned in image tag is same. [WIP]
  roles/openshift_storage_glusterfs/tasks/version_check.yml
Labels: approved, lgtm, size/XS

#11785 Ensure cni port does not collide with kernel reserved ports
  roles/kuryr/templates/configmap.yaml.j2
Labels: approved, lgtm, size/S

#11783 [GlusterFS]: Fix registry daemonset deletion as part of upgrade.
  roles/openshift_storage_glusterfs/tasks/glusterfs_upgrade.yml
Labels: approved, lgtm, size/XS

#11787 [release-3.9] Fix ASB ConfigMap
  roles/ansible_service_broker/tasks/install.yml
Labels: approved, lgtm, size/S

#11788 [release-3.10] Fix ASB ConfigMap
  roles/ansible_service_broker/templates/configmap.yaml.j2
Labels: approved, lgtm, size/S
