Repository openshift/openshift-ansible, pull requests merged in 2019-12, with the labels that each got.

#12034 Bug 1773446: Remove cloud-utils-growpart from node package list
  roles/openshift_node/defaults/main.yml
Labels: approved, bugzilla/valid-bug, lgtm, size/XS

#11935 Bz 1758552: set arp_announce=2
  roles/tuned/templates/openshift/tuned.conf
Labels: approved, lgtm, size/XS

#11918 [release 3-11] Bug 1753593: [Reg] openshift_logging_elasticsearch_kibana_index_mode…
  roles/openshift_logging/library/logging_patch.py
  roles/openshift_logging/tasks/patch_configmap_file.yaml
Labels: approved, bugzilla/valid-bug, lgtm, size/XS

#12047 Temporary workaround for crio dirs
  roles/openshift_node/tasks/install.yml
Labels: approved, lgtm, size/XS

#12039 Ensure installed crio version matches cluster API
  roles/openshift_node/defaults/main.yml
  roles/openshift_node/tasks/install.yml
Labels: approved, lgtm, size/M

#12046 [KIECLOUD-336] - Update RHPAM and RHDM templates and imagestreams on …
  roles/openshift_examples/examples-sync.sh
  roles/openshift_examples/files/examples/x86_64/xpaas-streams/rhdm75-image-streams.yaml
  roles/openshift_examples/files/examples/x86_64/xpaas-streams/rhpam75-image-streams.yaml
  roles/openshift_examples/files/examples/x86_64/xpaas-templates/rhdm75-authoring-ha.yaml
  roles/openshift_examples/files/examples/x86_64/xpaas-templates/rhdm75-authoring.yaml
  roles/openshift_examples/files/examples/x86_64/xpaas-templates/rhdm75-kieserver.yaml
  roles/openshift_examples/files/examples/x86_64/xpaas-templates/rhdm75-optaweb-employee-rostering.yaml
  roles/openshift_examples/files/examples/x86_64/xpaas-templates/rhdm75-prod-immutable-kieserver-amq.yaml
  roles/openshift_examples/files/examples/x86_64/xpaas-templates/rhdm75-prod-immutable-kieserver.yaml
  roles/openshift_examples/files/examples/x86_64/xpaas-templates/rhdm75-trial-ephemeral.yaml
  roles/openshift_examples/files/examples/x86_64/xpaas-templates/rhpam75-authoring-ha.yaml
  roles/openshift_examples/files/examples/x86_64/xpaas-templates/rhpam75-authoring.yaml
  roles/openshift_examples/files/examples/x86_64/xpaas-templates/rhpam75-kieserver-externaldb.yaml
  roles/openshift_examples/files/examples/x86_64/xpaas-templates/rhpam75-kieserver-mysql.yaml
  roles/openshift_examples/files/examples/x86_64/xpaas-templates/rhpam75-kieserver-postgresql.yaml
  roles/openshift_examples/files/examples/x86_64/xpaas-templates/rhpam75-managed.yaml
  roles/openshift_examples/files/examples/x86_64/xpaas-templates/rhpam75-prod-immutable-kieserver-amq.yaml
  roles/openshift_examples/files/examples/x86_64/xpaas-templates/rhpam75-prod-immutable-kieserver.yaml
  roles/openshift_examples/files/examples/x86_64/xpaas-templates/rhpam75-prod-immutable-monitor.yaml
  roles/openshift_examples/files/examples/x86_64/xpaas-templates/rhpam75-prod.yaml
  roles/openshift_examples/files/examples/x86_64/xpaas-templates/rhpam75-trial-ephemeral.yaml
Labels: approved, lgtm, ok-to-test, size/L

#12045 Use Ansible 2.9 for OCP 4.4
  README.md
  openshift-ansible.spec
  requirements.txt
  roles/openshift_node/callback_plugins/aa_version_requirement.py
Labels: approved, lgtm, size/S

#12044 gluster: add env variable to run Heketis LVM commands through a wrapper
  roles/openshift_storage_glusterfs/tasks/heketi_deploy.yml
  roles/openshift_storage_glusterfs/templates/heketi-template.yml.j2
Labels: approved, lgtm, size/S

#12050 Fix for bug 1755120, when key is undefined ansible sets unicode type
  playbooks/openshift-node/private/join.yml
Labels: approved, lgtm, size/XS

#12048 Remove directory creation for crio
  roles/openshift_node/tasks/install.yml
Labels: approved, lgtm, size/S

#12013 [GlusterFS]: Doc updates
  playbooks/openshift-glusterfs/README.md
  roles/openshift_storage_glusterfs/README.md
Labels: approved, lgtm, ok-to-test, size/S

#12021 Bug 1773645: Enable arch specific openshift_node packages
  roles/openshift_node/defaults/main.yml
Labels: approved, bugzilla/valid-bug, cherry-pick-approved, lgtm, size/S

#12036 Enable persistency on journal
  roles/openshift_node/tasks/install.yml
Labels: approved, lgtm, size/XS

#12053 gluster: configure pod template to enable support for nsenter
  roles/openshift_storage_glusterfs/files/glusterfs-template.yml
Labels: approved, lgtm, size/XS

#12055 Fix API version for 1.17 rebase
  roles/openshift_node/defaults/main.yml
  roles/openshift_node/tasks/install.yml
  test/aws/files/07_deployment.yml
Labels: approved, lgtm, size/S
