Repository openshift/openshift-ansible, pull requests merged in 2019-03, with the labels that each got.

#11274 Require ansible 2.6, allow ansible 2.7
  README.md
  images/installer/Dockerfile
  images/installer/origin-extra-root/etc/yum.repos.d/centos-ansible27.repo
  openshift-ansible.spec
  requirements.txt
  roles/lib_utils/callback_plugins/aa_version_requirement.py
Labels: approved, lgtm, size/S

#11273 Use correct Data Grid version
  roles/openshift_examples/examples-sync.sh
Labels: approved, lgtm, ok-to-test, size/XS

#11263 Adding docker as waagent systemd dependency
  playbooks/azure/openshift-cluster/build_node_image.yml
  playbooks/azure/openshift-cluster/files/waagent.service
Labels: approved, lgtm, size/S

#11269 [release-3.11] Prevent OpenStack heat from trying to create router when provider network is specified
  roles/openshift_openstack/templates/heat_stack.yaml.j2
Labels: approved, lgtm, size/M

#11119 [release-3.11] Correct service serving secret name in the annotation
  playbooks/openshift-hosted/private/redeploy-router-certificates.yml
Labels: approved, lgtm, ok-to-test, size/S

#11267 fixing docs to match actual defaults
  roles/openshift_logging/README.md
Labels: approved, lgtm, needs-ok-to-test, size/XS

#10698 added provisioner file path parameter to template
  roles/openshift_provisioners/templates/efs.j2
Labels: approved, lgtm, ok-to-test, size/XS

#11254 Require Ansible 2.7.7
  README.md
  images/installer/Dockerfile
  openshift-ansible.spec
  requirements.txt
  roles/lib_utils/callback_plugins/aa_version_requirement.py
Labels: approved, lgtm, size/S

#11278 Add instruction to install libvirt provider
  test/libvirt/README.md
Labels: lgtm, size/XS

#11268 sanity checks: avoid extra hostvar lookups
  roles/lib_utils/action_plugins/sanity_checks.py
  roles/lib_utils/test/sanity_check_test.py
Labels: approved, lgtm, size/L

#11261 [devel-40] Add cri-o tasks to openshift_node40 and drop container_runtime role
  playbooks/deploy_cluster_40.yml
  playbooks/openshift-node/scaleup.yml
  roles/container_runtime/README.md
  roles/container_runtime/defaults/main.yml
  roles/container_runtime/handlers/main.yml
  roles/container_runtime/meta/main.yml
  roles/container_runtime/tasks/common/post.yml
  roles/container_runtime/tasks/common/pre.yml
  roles/container_runtime/tasks/common/setup_docker_symlink.yml
  roles/container_runtime/tasks/common/udev_workaround.yml
  roles/container_runtime/tasks/crio_firewall.yml
  roles/container_runtime/tasks/docker_storage_setup_overlay.yml
  roles/container_runtime/tasks/extra_storage_setup.yml
  roles/container_runtime/tasks/main.yml
  roles/container_runtime/tasks/package_crio.yml
  roles/container_runtime/tasks/registry_auth.yml
  roles/container_runtime/templates/80-openshift-sdn.conf.j2
  roles/container_runtime/templates/crio-network.j2
  roles/container_runtime/templates/docker_storage_setup.j2
  roles/container_runtime/templates/overlay.conf.j2
  roles/container_runtime/templates/registries.conf.j2
  roles/openshift_node40/defaults/main.yml
  roles/openshift_node40/tasks/install.yml
Labels: approved, lgtm, size/XL

#11288 In atomic host, multipath file does not exists.
  roles/openshift_node/tasks/storage_plugins/iscsi.yml
Labels: approved, lgtm, size/XS

#11277 Set AWS_CA_BUNDLE via openshift_cloudprovider_aws_ca_bundle
  inventory/hosts.example
  roles/openshift_control_plane/tasks/main.yml
  roles/openshift_control_plane/templates/master.env.j2
  roles/openshift_node/tasks/aws.yml
Labels: approved, lgtm, size/S

#11289 [release-3.10] sanity checks: avoid extra hostvar lookups
  roles/lib_utils/action_plugins/sanity_checks.py
  roles/lib_utils/test/sanity_check_test.py
Labels: approved, lgtm, size/L

#11297 CloudForms 4.7 template updates for OCP 3.9
  roles/openshift_examples/files/examples/v3.9/cfme-templates/cfme-backup-job.yaml
  roles/openshift_examples/files/examples/v3.9/cfme-templates/cfme-backup-pvc.yaml
  roles/openshift_examples/files/examples/v3.9/cfme-templates/cfme-pv-backup-example.yaml
  roles/openshift_examples/files/examples/v3.9/cfme-templates/cfme-pv-db-example.yaml
  roles/openshift_examples/files/examples/v3.9/cfme-templates/cfme-pv-server-example.yaml
  roles/openshift_examples/files/examples/v3.9/cfme-templates/cfme-restore-job.yaml
  roles/openshift_examples/files/examples/v3.9/cfme-templates/cfme-scc-sysadmin.yaml
  roles/openshift_examples/files/examples/v3.9/cfme-templates/cfme-template-ext-db.yaml
  roles/openshift_examples/files/examples/v3.9/cfme-templates/cfme-template.yaml
  roles/openshift_examples/files/examples/v3.9/cfme-templates/jboss-middleware-manager-pv-example.yaml
  roles/openshift_examples/files/examples/v3.9/cfme-templates/jboss-middleware-manager-template.yaml
  roles/openshift_management/files/templates/cloudforms/cfme-backup-job.yaml
  roles/openshift_management/files/templates/cloudforms/cfme-restore-job.yaml
  roles/openshift_management/files/templates/cloudforms/cfme-template-ext-db.yaml
  roles/openshift_management/files/templates/cloudforms/cfme-template.yaml
Labels: approved, lgtm, needs-ok-to-test, size/XXL

#11249 Clean up lib_utils role (Part 2)
  roles/lib_utils/filter_plugins/oo_filters.py
  roles/lib_utils/library/docker_creds.py
  roles/lib_utils/test/test_data/bootstrap.ign.json
  roles/lib_utils/test/test_data/bs.ign.json
  roles/lib_utils/test/test_data/bs2.ign.json
  roles/lib_utils/test/test_data/example.ign.json
  roles/openshift_facts/defaults/main.yml
  roles/openshift_node40/tasks/install.yml
Labels: approved, lgtm, size/XXL

#11287 [release-3.10] Revert "Remove deprecated "openshift_logging_curator_run_timezone var…
  roles/openshift_logging/README.md
  roles/openshift_logging/defaults/main.yml
  roles/openshift_logging/tasks/install_logging.yaml
  roles/openshift_logging/tasks/set_defaults_from_current.yml
  roles/openshift_logging_curator/defaults/main.yml
Labels: approved, lgtm, size/XS

#11286 Add evars file to override vars in CI.
  test/evars/vars.yml
Labels: approved, lgtm, size/XS

#11285 [release-3.11] Add Heat template lbaas check to router subnet
  playbooks/openstack/configuration.md
  roles/openshift_openstack/templates/heat_stack_server.yaml.j2
Labels: approved, lgtm, size/XS

#11301 Include iscsi storage only on non-atomic host installs.
  roles/openshift_node/tasks/main.yml
  roles/openshift_node/tasks/storage_plugins/iscsi.yml
Labels: approved, lgtm, size/XS

#11262 Bug 1671315 - Kibana and Curator pods names are with ops
  roles/openshift_logging/tasks/delete_logging.yaml
  roles/openshift_logging/tasks/install_logging.yaml
  roles/openshift_logging_curator/tasks/main.yaml
  roles/openshift_logging_elasticsearch/tasks/main.yaml
  roles/openshift_logging_eventrouter/tasks/install_eventrouter.yaml
  roles/openshift_logging_fluentd/tasks/main.yaml
  roles/openshift_logging_kibana/tasks/main.yaml
  roles/openshift_logging_mux/tasks/main.yaml
Labels: approved, lgtm, size/M

#11290 ssh bastion: use TCP NLB and require ops-mirror.pem
  test/aws/files/01_service.yml
  test/aws/scaleup.yml
Labels: approved, lgtm, size/XS

#11299 Merge openshift_facts role into openshift_node40
  playbooks/init/basic_facts.yml
  roles/openshift_facts/README.md
  roles/openshift_facts/defaults/main.yml
  roles/openshift_facts/library/openshift_facts.py
  roles/openshift_facts/meta/main.yml
  roles/openshift_node40/defaults/main.yml
  roles/openshift_node40/meta/main.yml
Labels: approved, lgtm, size/XXL

#11303 Relax version requirements
  openshift-ansible.spec
  roles/lib_utils/callback_plugins/aa_version_requirement.py
Labels: approved, lgtm, size/XS

#11309 [release-3.10] sync and SDN pods should tolerate all taints
  roles/openshift_node_group/files/sync.yaml
  roles/openshift_sdn/files/sdn.yaml
Labels: approved, lgtm, size/S

#11308 Fix typo mistake: appliction 2 application.
  roles/openshift_examples/files/examples/x86_64/xpaas-templates/datavirt63-secure-s2i.json
  roles/openshift_examples/files/examples/x86_64/xpaas-templates/eap-cd-sso-s2i.json
  roles/openshift_examples/files/examples/x86_64/xpaas-templates/eap64-sso-s2i.json
  roles/openshift_examples/files/examples/x86_64/xpaas-templates/eap71-sso-s2i.json
  roles/openshift_examples/files/examples/x86_64/xpaas-templates/eap72-sso-s2i.json
  roles/openshift_examples/files/examples/x86_64/xpaas-templates/sso72-https.json
  roles/openshift_examples/files/examples/x86_64/xpaas-templates/sso72-mysql-persistent.json
  roles/openshift_examples/files/examples/x86_64/xpaas-templates/sso72-mysql.json
  roles/openshift_examples/files/examples/x86_64/xpaas-templates/sso72-postgresql-persistent.json
  roles/openshift_examples/files/examples/x86_64/xpaas-templates/sso72-postgresql.json
  roles/openshift_examples/files/examples/x86_64/xpaas-templates/sso72-x509-https.json
  roles/openshift_examples/files/examples/x86_64/xpaas-templates/sso72-x509-mysql-persistent.json
  roles/openshift_examples/files/examples/x86_64/xpaas-templates/sso72-x509-postgresql-persistent.json
Labels: approved, lgtm, needs-ok-to-test, size/S

#11294 Remove hidden tag for latest Fuse builders #11292
  roles/openshift_examples/files/examples/v3.10/xpaas-streams/fis-image-streams.json
Labels: approved, lgtm, ok-to-test, size/XS

#11310 fluentd: tolerate all taints
  roles/openshift_logging_fluentd/templates/fluentd.j2
Labels: approved, lgtm, size/XS

#11298 Fix version checker, Require 2.7.8
  README.md
  images/installer/origin-extra-root/etc/yum.repos.d/centos-ansible27.repo
  openshift-ansible.spec
  requirements.txt
  roles/lib_utils/callback_plugins/aa_version_requirement.py
Labels: approved, lgtm, size/M

#11300 bug 1685618. Modify default_md for logging cert generation
  roles/openshift_logging/tasks/generate_pems.yaml
  roles/openshift_logging/templates/signing.conf.j2
Labels: approved, lgtm, size/S

#11311 Logs are already being shipped to journald
  playbooks/azure/openshift-cluster/files/waagent.service
Labels: approved, lgtm, size/XS

#11313 Adding new kuryr handler to avoid races
  roles/kuryr/templates/configmap.yaml.j2
Labels: approved, lgtm, size/XS

#11295 Use tempfile module in place of command mktemp
  roles/openshift_node40/tasks/config.yml
Labels: approved, lgtm, size/S

#11312 Ensure kuryr has its own namespace
  roles/kuryr/defaults/main.yaml
  roles/kuryr/tasks/master.yaml
Labels: approved, lgtm, size/XS

#10960 [devel-40] Dockerfile: build using RPM packages
  images/installer/Dockerfile
  images/installer/Dockerfile.ci
  images/installer/origin-extra-root/etc/yum.repos.d/azure-cli.repo
  images/installer/origin-extra-root/etc/yum.repos.d/centos-openshift-origin.repo
  images/installer/origin-extra-root/etc/yum.repos.d/google-cloud-sdk.repo
  images/installer/origin-extra-root/etc/yum.repos.d/openshift-origin-4.0-ci.repo
  openshift-ansible.spec
Labels: approved, lgtm, size/L

#11169 [release-3.11] Set credentials and proper hostname when updating loopback kubeconfig
  roles/openshift_control_plane/tasks/set_loopback_context.yml
  roles/openshift_facts/library/openshift_facts.py
Labels: approved, lgtm, size/S

#11170 [release-3.10] Set credentials and proper hostname when updating loopback kubeconfig
  roles/openshift_control_plane/tasks/set_loopback_context.yml
  roles/openshift_facts/library/openshift_facts.py
Labels: approved, lgtm, size/S

#11171 [release-3.9] Set credentials and proper hostname when updating loopback kubeconfig
  roles/openshift_facts/library/openshift_facts.py
  roles/openshift_master/tasks/set_loopback_context.yml
Labels: approved, lgtm, size/S

#11319 [release-3.11] Remove runhour and runminute from curator config sample
  roles/openshift_logging_curator/files/curator.yml
Labels: approved, lgtm, ok-to-test, size/XS

#11320 Simplify DaemonSet Update
  roles/openshift_sdn/tasks/update_daemonset.yml
Labels: approved, lgtm, size/S

#11293 Remove hidden tag for latest Fuse builders #11292
  roles/openshift_examples/files/examples/x86_64/xpaas-streams/fis-image-streams.json
Labels: approved, lgtm, ok-to-test, size/XS

#11321 Revert "Merge pull request #11286 from patrickdillon/add-ci-evars"
  test/evars/vars.yml
Labels: approved, lgtm, size/XS

#11329 sdn: respect DEBUG_LOGLEVEL as written out by the "Configure Node settings" task
  roles/openshift_sdn/files/sdn.yaml
Labels: approved, lgtm, size/XS

#11283 Don't stop docker when openshift_use_crio_only
  roles/openshift_node/tasks/upgrade/restart.yml
  roles/openshift_node/tasks/upgrade/stop_services.yml
Labels: approved, lgtm, size/XS

#11326 Consolidate everything into openshift_node role
  playbooks/init/base_packages.yml
  playbooks/init/basic_facts.yml
  playbooks/init/evaluate_groups.yml
  playbooks/init/main.yml
  playbooks/init/repos.yml
  playbooks/init/roles
  playbooks/init/vars/cluster_hosts.yml
  playbooks/init/version.yml
  playbooks/openshift-node/scaleup.yml
  roles/lib_utils/library/os_firewall_manage_iptables.py
  roles/lib_utils/library/yedit.py
  roles/lib_utils/meta/main.yml
  roles/lib_utils/src/ansible/yedit.py
  roles/lib_utils/src/class/yedit.py
  roles/lib_utils/src/doc/generated
  roles/lib_utils/src/doc/license
  roles/lib_utils/src/doc/yedit
  roles/lib_utils/src/generate.py
  roles/lib_utils/src/lib/import.py
  roles/lib_utils/src/sources.yml
  roles/lib_utils/src/test/generate-and-run-tests.sh
  roles/lib_utils/src/test/integration/files/kube-manager.yaml
  roles/lib_utils/src/test/integration/yedit.yml
  roles/lib_utils/src/test/unit/test_yedit.py
  roles/openshift_node40/callback_plugins/aa_version_requirement.py
  roles/openshift_node40/defaults/main.yml
  roles/openshift_node40/library/swapoff.py
  roles/openshift_node40/meta/main.yml
  roles/openshift_node40/tasks/config.yml
  roles/openshift_node40/tasks/main.yml
  roles/rhel_subscribe/README.md
  roles/rhel_subscribe/defaults/main.yml
  roles/rhel_subscribe/meta/main.yml
  roles/rhel_subscribe/tasks/main.yml
  roles/rhel_subscribe/tasks/satellite.yml
  test/aws/scaleup.yml
  tox.ini
Labels: approved, lgtm, size/XXL

#11327 Fix validation of values in image_policy_allowed_registries_for_import
  roles/openshift_facts/library/openshift_facts.py
Labels: approved, lgtm, size/XS

#11322 Fix version_requirement callback plugin
  roles/lib_utils/callback_plugins/aa_version_requirement.py
Labels: approved, lgtm, size/M

#11334 Increase etcd quota to 8GB.
  roles/etcd/defaults/main.yaml
Labels: approved, lgtm, size/XS

#6438 Disconnected install fails at service catalog imagePullPolicy: Always
  roles/lib_openshift/src/test/integration/oc_obj.yml
  roles/openshift_examples/files/examples/v1.4/cfme-templates/jboss-middleware-manager-template.yaml
  roles/openshift_examples/files/examples/v1.5/cfme-templates/jboss-middleware-manager-template.yaml
  roles/openshift_examples/files/examples/v3.6/cfme-templates/jboss-middleware-manager-template.yaml
  roles/openshift_examples/files/examples/v3.7/cfme-templates/jboss-middleware-manager-template.yaml
  roles/openshift_hosted_templates/files/v1.2/origin/logging-deployer.yaml
  roles/openshift_hosted_templates/files/v1.4/enterprise/logging-deployer.yaml
  roles/openshift_hosted_templates/files/v1.4/origin/logging-deployer.yaml
  roles/openshift_service_catalog/templates/api_server.j2
  roles/openshift_service_catalog/templates/controller_manager.j2
Labels: approved, lgtm, size/S

#11304 bug 1676720. Check for curator cronjob
  roles/openshift_health_checker/openshift_checks/logging/curator.py
  roles/openshift_health_checker/openshift_checks/logging/logging.py
  roles/openshift_health_checker/test/curator_test.py
Labels: approved, lgtm, size/M

#11302 bug 1660956. Add container name to elasticsearch exec call
  roles/openshift_health_checker/openshift_checks/logging/elasticsearch.py
Labels: approved, lgtm, size/XS

#11337 openshift-sync: tolerate absence of KUBELET_HOSTNAME_OVERRIDE
  roles/openshift_node_group/files/sync.yaml
Labels: approved, lgtm, size/XS

#11336 Use openshift-clients package name
  images/installer/Dockerfile
  roles/openshift_node40/defaults/main.yml
  roles/openshift_node40/tasks/install.yml
Labels: approved, lgtm, size/S

#11330 Clean up tests
  .coveragerc
  .flake8
  .travis.yml
  conftest.py
  pytest.ini
  requirements.txt
  roles/openshift_node40/library/swapoff.py
  setup.py
  test-requirements.txt
  test/integration/README.md
  test/integration/build-images.sh
  test/integration/openshift_health_checker/builds/aos-package-checks/Dockerfile
  test/integration/openshift_health_checker/builds/aos-package-checks/root/etc/yum.repos.d/break-yum.repo
  test/integration/openshift_health_checker/builds/aos-package-checks/root/etc/yum.repos.d/ose-3.2.repo
  test/integration/openshift_health_checker/builds/aos-package-checks/root/etc/yum.repos.d/ose-3.3.repo
  test/integration/openshift_health_checker/builds/aos-package-checks/root/root/break-yum-update-2.spec
  test/integration/openshift_health_checker/builds/aos-package-checks/root/root/break-yum-update.spec
  test/integration/openshift_health_checker/builds/aos-package-checks/root/root/ose-3.2.spec
  test/integration/openshift_health_checker/builds/aos-package-checks/root/root/ose-3.3.spec
  test/integration/openshift_health_checker/builds/test-target-base/Dockerfile
  test/integration/openshift_health_checker/common.go
  test/integration/openshift_health_checker/preflight/playbooks/package_availability_missing_required.yml
  test/integration/openshift_health_checker/preflight/playbooks/package_availability_succeeds.yml
  test/integration/openshift_health_checker/preflight/playbooks/package_update_dep_missing.yml
  test/integration/openshift_health_checker/preflight/playbooks/package_update_repo_broken.yml
  test/integration/openshift_health_checker/preflight/playbooks/package_update_repo_disabled.yml
  test/integration/openshift_health_checker/preflight/playbooks/package_update_repo_unreachable.yml
  test/integration/openshift_health_checker/preflight/playbooks/package_version_matches.yml
  test/integration/openshift_health_checker/preflight/playbooks/package_version_mismatches.yml
  test/integration/openshift_health_checker/preflight/playbooks/package_version_multiple.yml
  test/integration/openshift_health_checker/preflight/playbooks/package_version_origin.yml
  test/integration/openshift_health_checker/preflight/playbooks/roles
  test/integration/openshift_health_checker/preflight/playbooks/tasks/enable_repo.yml
  test/integration/openshift_health_checker/preflight/preflight_test.go
  test/integration/openshift_health_checker/setup_container.yml
  test/integration/openshift_health_checker/teardown_container.yml
  test/integration/run-tests.sh
  test/tox-inventory.txt
  tox.ini
Labels: approved, lgtm, size/XXL

#11341 Redeploy admin console certificates when master certs are updated
  playbooks/openshift-console/redeploy-certificates.yml
  playbooks/openshift-master/redeploy-certificates.yml
Labels: approved, lgtm, size/XS

#11335 Include dedicated etcd in upgrade if they are nodes
  playbooks/common/openshift-cluster/upgrades/initialize_nodes_to_upgrade.yml
  playbooks/common/openshift-cluster/upgrades/pre/config.yml
Labels: approved, lgtm, size/XS

#11318 Encode the cert when loading it
  roles/lib_utils/library/openshift_cert_expiry.py
Labels: approved, lgtm, ok-to-test, size/XS

#11345 [release-3.6] Update openshift_hosted_routers example to be in ini format
  inventory/byo/hosts.origin.example
  inventory/byo/hosts.ose.example
Labels: size/M

#11296 CloudForms 4.7 template updates for OCP 3.10
  roles/openshift_examples/files/examples/v3.10/cfme-templates/cfme-backup-job.yaml
  roles/openshift_examples/files/examples/v3.10/cfme-templates/cfme-backup-pvc.yaml
  roles/openshift_examples/files/examples/v3.10/cfme-templates/cfme-pv-backup-example.yaml
  roles/openshift_examples/files/examples/v3.10/cfme-templates/cfme-pv-db-example.yaml
  roles/openshift_examples/files/examples/v3.10/cfme-templates/cfme-pv-server-example.yaml
  roles/openshift_examples/files/examples/v3.10/cfme-templates/cfme-restore-job.yaml
  roles/openshift_examples/files/examples/v3.10/cfme-templates/cfme-scc-sysadmin.yaml
  roles/openshift_examples/files/examples/v3.10/cfme-templates/cfme-template-ext-db.yaml
  roles/openshift_examples/files/examples/v3.10/cfme-templates/cfme-template.yaml
  roles/openshift_examples/files/examples/v3.10/cfme-templates/httpd-configmap-generator-template.yaml
  roles/openshift_examples/files/examples/v3.10/cfme-templates/httpd-scc-sysadmin.yaml
  roles/openshift_examples/files/examples/v3.10/cfme-templates/jboss-middleware-manager-pv-example.yaml
  roles/openshift_examples/files/examples/v3.10/cfme-templates/jboss-middleware-manager-template.yaml
  roles/openshift_management/files/templates/cloudforms/cfme-backup-job.yaml
  roles/openshift_management/files/templates/cloudforms/cfme-restore-job.yaml
  roles/openshift_management/files/templates/cloudforms/cfme-template-ext-db.yaml
  roles/openshift_management/files/templates/cloudforms/cfme-template.yaml
  roles/openshift_management/files/templates/cloudforms/httpd-configmap-generator-template.yaml
Labels: approved, lgtm, ok-to-test, size/XXL

#11342 Avoid using aliases which are prone to discovery problems
  roles/lib_openshift/library/oc_adm_policy_user.py
  roles/lib_openshift/src/class/oc_adm_policy_user.py
  roles/openshift_bootstrap_autoapprover/tasks/main.yml
  roles/openshift_node_group/tasks/sync.yml
  roles/openshift_sdn/tasks/main.yml
Labels: approved, lgtm, size/M

#11344 [release-3.10] Avoid using aliases which are prone to discovery problems
  roles/lib_openshift/library/oc_adm_policy_user.py
  roles/lib_openshift/src/class/oc_adm_policy_user.py
  roles/openshift_bootstrap_autoapprover/tasks/main.yml
  roles/openshift_node_group/tasks/sync.yml
  roles/openshift_sdn/tasks/main.yml
Labels: approved, lgtm, size/M

#11352 Sync 3.11 content
  roles/openshift_examples/examples-sync.sh
  roles/openshift_examples/files/examples/x86_64/image-streams/dotnet_imagestreams.json
  roles/openshift_examples/files/examples/x86_64/image-streams/dotnet_imagestreams_centos.json
  roles/openshift_examples/files/examples/x86_64/quickstart-templates/dotnet-example.json
  roles/openshift_examples/files/examples/x86_64/quickstart-templates/dotnet-pgsql-persistent.json
  roles/openshift_examples/files/examples/x86_64/quickstart-templates/dotnet-runtime-example.json
Labels: approved, lgtm, size/L

#11351 [release-3.11] Add race condition protection when creating projects
  roles/lib_openshift/library/oc_project.py
  roles/lib_openshift/src/class/oc_project.py
Labels: approved, lgtm, size/S

#10932 Change the example docker_version for 3.9 and higher
  inventory/hosts.example
Labels: approved, lgtm, ok-to-test, size/XS

#11361 Change the example docker_version for 3.9 and higher
  inventory/hosts.example
Labels: approved, lgtm, needs-ok-to-test, size/XS

#11357 Calico: Add support for environment variable IP_AUTODETECTION_METHOD
  roles/calico/defaults/main.yaml
  roles/calico/templates/calico.yml.j2
  roles/calico/templates/calicov3.yml.j2
Labels: approved, lgtm, ok-to-test, size/XS

#11359 Bug 1689149 - adding secret names to SA for whitelisting
  roles/openshift_logging_curator/tasks/main.yaml
  roles/openshift_logging_elasticsearch/tasks/main.yaml
  roles/openshift_logging_fluentd/tasks/main.yaml
  roles/openshift_logging_kibana/tasks/main.yaml
  roles/openshift_logging_mux/tasks/main.yaml
Labels: affects_3.10, affects_3.11, affects_3.9, approved, lgtm, size/M

#11367 Bug 1689149 - adding secret names to SA for whitelisting
  roles/openshift_logging_curator/tasks/main.yaml
  roles/openshift_logging_elasticsearch/tasks/main.yaml
  roles/openshift_logging_fluentd/tasks/main.yaml
  roles/openshift_logging_kibana/tasks/main.yaml
  roles/openshift_logging_mux/tasks/main.yaml
Labels: approved, lgtm, size/S

#11366 Bug 1689149 - adding secret names to SA for whitelisting
  roles/openshift_logging_curator/tasks/main.yaml
  roles/openshift_logging_elasticsearch/tasks/main.yaml
  roles/openshift_logging_fluentd/tasks/main.yaml
  roles/openshift_logging_kibana/tasks/main.yaml
  roles/openshift_logging_mux/tasks/main.yaml
Labels: approved, lgtm, size/L

#11368 Run ssh bastion in privileged mode
  test/aws/files/03_role.yml
  test/aws/files/07_deployment.yml
Labels: approved, do-not-merge/hold, lgtm, size/XS

#11376 [release 3.10] Allow OpenStack persistent volumes to specify storage class
  playbooks/openstack/configuration.md
  roles/lib_utils/action_plugins/generate_pv_pvcs_list.py
  roles/openshift_persistent_volumes/templates/persistent-volume.yml.j2
Labels: approved, lgtm, size/S

#11378 bug 1666674. give kibana sa auth-delegate
  roles/openshift_logging_kibana/tasks/main.yaml
  roles/openshift_logging_kibana/templates/kibana.j2
Labels: approved, lgtm, size/S

#11384 remove dash causing syntax error in kibana install role
  roles/openshift_logging_kibana/tasks/main.yaml
Labels: approved, lgtm, ok-to-test, size/XS

#11343 Ensure openshift_node variables adhere to naming standard.
  images/installer/root/usr/local/bin/entrypoint-provider
  playbooks/scaleup.yml
  roles/openshift_node/README.md
  roles/openshift_node/callback_plugins/aa_version_requirement.py
  roles/openshift_node/defaults/main.yml
  roles/openshift_node/library/swapoff.py
  roles/openshift_node/meta/main.yml
  roles/openshift_node/tasks/config.yml
  roles/openshift_node/tasks/install.yml
  roles/openshift_node/tasks/main.yml
  test/aws/scaleup.yml
  test/gcp/launch.yml
  test/libvirt/node_scaleup.sh
Labels: approved, lgtm, size/M

#11363 [release-3.11] Modify "lib_utils_oo_oreg_image" filter to work against Satellite url pattern
  roles/lib_utils/filter_plugins/oo_filters.py
Labels: approved, lgtm, needs-ok-to-test, size/XS

#11386 openshift_node: install same packages as coreos
  roles/openshift_node/defaults/main.yml
  roles/openshift_node/tasks/install.yml
Labels: approved, lgtm, size/M

#11389 Cherrypick 11343 11386
  images/installer/root/usr/local/bin/entrypoint-provider
  playbooks/scaleup.yml
  roles/openshift_node/README.md
  roles/openshift_node/callback_plugins/aa_version_requirement.py
  roles/openshift_node/defaults/main.yml
  roles/openshift_node/library/swapoff.py
  roles/openshift_node/meta/main.yml
  roles/openshift_node/tasks/config.yml
  roles/openshift_node/tasks/install.yml
  roles/openshift_node/tasks/main.yml
  roles/openshift_node40/defaults/main.yml
  test/aws/scaleup.yml
  test/libvirt/node_scaleup.sh
Labels: approved, lgtm, size/L

#11371 Dockerfile.rhel7: simplify pkg install
  images/installer/Dockerfile.rhel7
Labels: approved, lgtm, size/XS

#11403 Change namespace of testing bastion server to byoh-ssh-bastion.
  test/aws/files/01_service.yml
  test/aws/files/02_serviceaccount.yml
  test/aws/files/03_role.yml
  test/aws/files/04_rolebinding.yml
  test/aws/files/06_clusterrolebinding.yml
  test/aws/files/07_deployment.yml
  test/aws/ssh_bastion.yml
Labels: approved, lgtm, size/S

#11404 Teardown: remove security using cluster ID tag
  test/ci/deprovision.yml
Labels: approved, lgtm, size/M

#11401 Remove pull request template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: approved, lgtm, size/XS

#11396 Backup node-config and atomic-openshift services.
  roles/openshift_control_plane/tasks/upgrade.yml
  roles/openshift_node/tasks/upgrade/config_changes.yml
Labels: approved, lgtm, size/S

#11390 [release-3.11] Do not include enterprise registry unless available in oreg_url
  roles/container_runtime/tasks/common/pre.yml
Labels: approved, lgtm, size/XS

#11394 Add playbook for upgrading cri-o and kubelet on nodes
  playbooks/upgrade.yml
  roles/openshift_node/defaults/main.yml
  roles/openshift_node/tasks/install.yml
Labels: approved, lgtm, queue/blocks-others, size/M

#11400 Add ssh retries to ansible.cfg
  ansible.cfg
Labels: approved, lgtm, size/XS

#11408 Clean up and simplify openshift-ansible.spec
  openshift-ansible.spec
Labels: approved, lgtm, size/L

#11338 Update docs for 4.1
  BUILD.md
  CONTRIBUTING.md
  DEPLOYMENT_TYPES.md
  HOOKS.md
  README.md
  docs/openshift_components.md
  docs/proposals/README.md
  docs/proposals/crt_management_proposal.md
  docs/proposals/playbook_consolidation.md
  docs/proposals/proposal_template.md
  docs/proposals/role_decomposition.md
  docs/repo_structure.md
  examples/README.md
  examples/certificate-check-upload.yaml
  examples/certificate-check-volume.yaml
  examples/scheduled-certcheck-upload.yaml
  examples/scheduled-certcheck-volume.yaml
  hack/hooks/README.md
  hack/hooks/verify_generated_modules/README.md
  hack/hooks/verify_generated_modules/pre-commit
  inventory/.gitignore
  inventory/40_basic_inventory.ini
  inventory/hosts.example
  inventory/hosts.glusterfs.external.example
  inventory/hosts.glusterfs.mixed.example
  inventory/hosts.glusterfs.native.example
  inventory/hosts.glusterfs.registry-only.example
  inventory/hosts.glusterfs.storage-and-registry.example
  inventory/hosts.grafana.example
  inventory/hosts.localhost
  inventory/hosts.openstack
  inventory/install-config-example.yml
  meta/main.yml
  playbooks/README.md
Labels: approved, lgtm, size/XXL

#11415 No longer install etcd package on masters
  roles/etcd/tasks/certificates/fetch_server_certificates_from_ca.yml
Labels: approved, lgtm, size/XS

#11405 Remove conditional from Disable swap
  roles/openshift_node/tasks/config.yml
Labels: approved, lgtm, size/XS

#11395 Wait for ServiceMonitor CRD to be created should have configurable retries and delays
  inventory/hosts.example
  roles/openshift_cluster_monitoring_operator/defaults/main.yml
  roles/openshift_cluster_monitoring_operator/tasks/install.yaml
Labels: approved, lgtm, size/S

#11399 [release-3.9] Calico: Add support for environment variable IP_AUTODETECTION_METHOD
  roles/calico_master/defaults/main.yaml
  roles/calico_master/templates/calico.yml.j2
  roles/calico_master/templates/calicov3.yml.j2
Labels: approved, lgtm, ok-to-test, size/XS

#11420 lib_utils to parse *_storage_host variables with get_templated
  roles/lib_utils/action_plugins/generate_pv_pvcs_list.py
Labels: approved, lgtm, size/XS

#11360 Change the example docker_version for 3.9 and higher
  inventory/hosts.example
Labels: approved, lgtm, ok-to-test, size/XS

#11425 [release-3.7] Re-apply tuned profile during upgrade
  playbooks/common/openshift-cluster/upgrades/upgrade_control_plane.yml
  playbooks/common/openshift-cluster/upgrades/upgrade_nodes.yml
Labels: approved, lgtm, size/XS

#11424 [release-3.11] Re-apply tuned profile during upgrade
  playbooks/common/openshift-cluster/upgrades/upgrade_nodes.yml
  playbooks/openshift-master/private/upgrade.yml
Labels: approved, lgtm, size/XS

#11407 Remove papr test files
  .papr-master-ha.inventory
  .papr.all-in-one.inventory
  .papr.inventory
  .papr.sh
  .papr.yml
Labels: approved, lgtm, size/L

#11423 [release-3.10] Re-apply tuned profile during upgrade
  playbooks/common/openshift-cluster/upgrades/upgrade_nodes.yml
  playbooks/openshift-master/private/upgrade.yml
Labels: approved, lgtm, size/XS

#11430 Updating OWNERS
  OWNERS
Labels: size/XS

#11416 Increase ssh retries for CI scaleup
  inventory/dynamic/aws/ansible.cfg
Labels: approved, lgtm, size/XS

#11392 Aci release 3.11
  playbooks/init/main.yml
  playbooks/init/validate_aci_params.yml
  playbooks/openshift-master/private/config.yml
  playbooks/openshift-node/private/join.yml
  roles/aci/README.md
  roles/aci/defaults/main.yml
  roles/aci/tasks/firewall.yml
  roles/aci/tasks/main.yml
  roles/openshift_control_plane/defaults/main.yml
  roles/openshift_node/defaults/main.yml
Labels: approved, lgtm, ok-to-test, size/L
