Repository openshift/openshift-ansible, pull requests merged in 2019-08, with the labels that each got.

#11794 [release-3.11] Add ANSIBLE_CONFIG to tox.ini
  tox.ini
Labels: approved, lgtm, size/XS

#11789 [release-3.9] Update tox test environment vars
  setup.py
  test/tox-inventory.txt_extras
  tox.ini
  utils/test/cli_installer_tests.py
Labels: approved, lgtm, size/S

#11796 import_tasks no longer supports inline variables
  roles/openshift_logging/tasks/generate_certs.yaml
Labels: approved, lgtm, ok-to-test, size/S

#11795 Add ANSIBLE_CONFIG to tox.ini
  tox.ini
Labels: approved, lgtm, size/XS

#11792 [GlusterFS]: variable to skip brick size check
  roles/openshift_storage_glusterfs/defaults/main.yml
  roles/openshift_storage_glusterfs/tasks/glusterfs_config_facts.yml
  roles/openshift_storage_glusterfs/tasks/glusterfs_registry_facts.yml
  roles/openshift_storage_glusterfs/tasks/glusterfs_upgrade.yml
Labels: approved, lgtm, size/XS

#11782 Get heketi_pod name before invoking heketi-cli command.
  roles/openshift_storage_glusterfs/tasks/glusterfs_upgrade.yml
Labels: approved, lgtm, size/S

#11793 [release-3.10] Add ANSIBLE_CONFIG to tox.ini
  tox.ini
Labels: approved, lgtm, size/XS

#11802 Fixing generate_secret for redeploy-certificates and fixing up checkpoint names
  playbooks/openshift-logging/private/redeploy-certificates.yml
  roles/openshift_logging_elasticsearch/tasks/generate_secret.yaml
  roles/openshift_logging_fluentd/tasks/generate_secret.yaml
  roles/openshift_logging_mux/tasks/generate_secret.yaml
Labels: approved, lgtm, size/S

#11804 Bug 1729994: Update l_docker_creds_test_image
  roles/container_runtime/tasks/registry_auth.yml
  roles/openshift_control_plane/tasks/registry_auth.yml
  roles/openshift_facts/defaults/main.yml
  roles/openshift_node/tasks/registry_auth.yml
Labels: approved, bugzilla/valid-bug, lgtm, size/XS

#11801 Bug 1737806: Update MCO image name and entrypoint
  roles/openshift_node/tasks/apply_machine_config.yml
  roles/openshift_node/tasks/config.yml
Labels: approved, bugzilla/valid-bug, lgtm, size/XS

#11807 Update MCO entrypoint for upgrade
  roles/openshift_node/tasks/apply_machine_config.yml
Labels: approved, lgtm, size/XS

#11775 [KIECLOUD-268] - Update RHPAM and RHMD templates and imagestreams on …
  roles/openshift_examples/examples-sync.sh
  roles/openshift_examples/files/examples/x86_64/xpaas-streams/rhdm74-image-streams.yaml
  roles/openshift_examples/files/examples/x86_64/xpaas-streams/rhpam74-image-streams.yaml
  roles/openshift_examples/files/examples/x86_64/xpaas-templates/rhdm74-authoring-ha.yaml
  roles/openshift_examples/files/examples/x86_64/xpaas-templates/rhdm74-authoring.yaml
  roles/openshift_examples/files/examples/x86_64/xpaas-templates/rhdm74-kieserver.yaml
  roles/openshift_examples/files/examples/x86_64/xpaas-templates/rhdm74-optaweb-employee-rostering.yaml
  roles/openshift_examples/files/examples/x86_64/xpaas-templates/rhdm74-prod-immutable-kieserver-amq.yaml
  roles/openshift_examples/files/examples/x86_64/xpaas-templates/rhdm74-prod-immutable-kieserver.yaml
  roles/openshift_examples/files/examples/x86_64/xpaas-templates/rhdm74-trial-ephemeral.yaml
  roles/openshift_examples/files/examples/x86_64/xpaas-templates/rhpam74-authoring-ha.yaml
  roles/openshift_examples/files/examples/x86_64/xpaas-templates/rhpam74-authoring.yaml
  roles/openshift_examples/files/examples/x86_64/xpaas-templates/rhpam74-kieserver-externaldb.yaml
  roles/openshift_examples/files/examples/x86_64/xpaas-templates/rhpam74-kieserver-mysql.yaml
  roles/openshift_examples/files/examples/x86_64/xpaas-templates/rhpam74-kieserver-postgresql.yaml
  roles/openshift_examples/files/examples/x86_64/xpaas-templates/rhpam74-managed.yaml
  roles/openshift_examples/files/examples/x86_64/xpaas-templates/rhpam74-prod-immutable-kieserver-amq.yaml
  roles/openshift_examples/files/examples/x86_64/xpaas-templates/rhpam74-prod-immutable-kieserver.yaml
  roles/openshift_examples/files/examples/x86_64/xpaas-templates/rhpam74-prod-immutable-monitor.yaml
  roles/openshift_examples/files/examples/x86_64/xpaas-templates/rhpam74-prod.yaml
  roles/openshift_examples/files/examples/x86_64/xpaas-templates/rhpam74-trial-ephemeral.yaml
Labels: approved, lgtm, needs-ok-to-test, size/XXL

#11811 Configure Ansible service broker secrets
  roles/ansible_service_broker/defaults/main.yml
  roles/ansible_service_broker/templates/configmap.yaml.j2
Labels: approved, lgtm, needs-ok-to-test, size/XS

#11812 Configure Ansible service broker secrets
  roles/ansible_service_broker/defaults/main.yml
  roles/ansible_service_broker/templates/configmap.yaml.j2
Labels: approved, lgtm, needs-ok-to-test, size/XS

#11790 Require Ansible 2.8.2 for release-4.2
  README.md
  openshift-ansible.spec
  requirements.txt
  roles/openshift_node/callback_plugins/aa_version_requirement.py
Labels: approved, lgtm, size/S

#11808 Add check to ensure nodes are Ready after scaleup/upgrade
  roles/openshift_node/tasks/apply_machine_config.yml
  roles/openshift_node/tasks/config.yml
  roles/openshift_node/tasks/upgrade.yml
Labels: approved, lgtm, size/M

#11822 [release-3.11] Fix ca node sync always applying certificate
  roles/openshift_node_group/files/sync.yaml
Labels: approved, lgtm, size/S

#11821 Bug 1692735: Increase wait for aggregated API availability
  roles/openshift_control_plane/tasks/check_master_api_is_ready.yml
Labels: approved, bugzilla/valid-bug, lgtm, size/XS

#11826 Bug 1721336: Only delete and regenerate service signer cert when updating CA
  playbooks/openshift-master/private/certificates-backup.yml
Labels: approved, bugzilla/valid-bug, lgtm, size/S

#11829 Bug 1735751: avoid excessive dentries due to console liveness probe
  roles/openshift_web_console/files/console-template.yaml
Labels: approved, bugzilla/valid-bug, lgtm, size/XS

#11832 [GlusterFS]: Fix version check avoiding minor version comparison
  roles/openshift_storage_glusterfs/tasks/version_check.yml
Labels: approved, lgtm, size/XS

#11791 [GlusterFS]: Upgrade playbook is supported for converged mode only.
  roles/openshift_storage_glusterfs/tasks/glusterfs_upgrade.yml
Labels: approved, lgtm, size/XS

#11835 test: Remove task to delete CoreOS nodes
  test/aws/scaleup.yml
Labels: approved, lgtm, size/XS

#11824 Bug 1740439: Disable firewalld service during adding RHEL worker
  roles/openshift_node/tasks/config.yml
Labels: approved, bugzilla/valid-bug, lgtm, size/S

#11816 test: add timeouts to decrease amount of flakes
  test/aws/create_machineset.yml
  test/aws/files/sshd_config
Labels: approved, lgtm, size/XS

#11647 Write logs to disk when scaleup tests fail.
  test/aws/gather_logs.yml
  test/aws/scaleup.yml
Labels: approved, lgtm, size/M

#11809 Use htpasswd hawkular metrics utility to generate SHA256 FIPS complia…
  roles/openshift_metrics/defaults/main.yaml
  roles/openshift_metrics/tasks/generate_hawkular_certificates.yaml
Labels: approved, lgtm, size/S

#11839 Add retries to package command
  roles/openshift_node/tasks/install.yml
  test/aws/scaleup.yml
Labels: approved, lgtm, size/XS

#11841 Bug 1732154: Explicitly pass storage class var to logging role
  roles/openshift_logging/tasks/install_logging.yaml
Labels: approved, bugzilla/valid-bug, lgtm, size/XS

#11817 Bug 1739229: Correctly update kibana proxy related secrets and certs
  playbooks/openshift-logging/private/redeploy-certificates.yml
  roles/openshift_logging_kibana/tasks/generate_oauth_client.yaml
  roles/openshift_logging_kibana/tasks/generate_proxy_secret_files.yaml
  roles/openshift_logging_kibana/tasks/generate_route.yaml
  roles/openshift_logging_kibana/tasks/load_secret_files.yaml
  roles/openshift_logging_kibana/tasks/main.yaml
Labels: approved, bugzilla/valid-bug, lgtm, size/L

#11842 Bug 1740964: [Backport 4.1]Unless RHEL worker disable firewalld.service, "oc rsh/exec/logs" does not work
  roles/openshift_node/tasks/config.yml
Labels: approved, bugzilla/valid-bug, cherry-pick-approved, lgtm, ok-to-test, size/S

#11806 Add proxy support to scaleup.
  roles/openshift_node/tasks/config.yml
  roles/openshift_node/tasks/proxy.yml
Labels: approved, lgtm, size/M

#11843 [GlusterFS]: Fix registry daemonset deletion as part of upgrade.
  roles/openshift_storage_glusterfs/tasks/glusterfs_upgrade.yml
Labels: approved, lgtm, size/XS

#11317 pass http/s proxy env variables to kibana
  roles/openshift_logging_kibana/templates/kibana.j2
Labels: approved, lgtm, ok-to-test, size/S

#11848 Bug 1685074: workaround bugs in `oc replace`
  roles/lib_openshift/library/oc_adm_ca_server_cert.py
  roles/lib_openshift/library/oc_adm_csr.py
  roles/lib_openshift/library/oc_adm_manage_node.py
  roles/lib_openshift/library/oc_adm_policy_group.py
  roles/lib_openshift/library/oc_adm_policy_user.py
  roles/lib_openshift/library/oc_adm_registry.py
  roles/lib_openshift/library/oc_adm_router.py
  roles/lib_openshift/library/oc_clusterrole.py
  roles/lib_openshift/library/oc_configmap.py
  roles/lib_openshift/library/oc_edit.py
  roles/lib_openshift/library/oc_env.py
  roles/lib_openshift/library/oc_group.py
  roles/lib_openshift/library/oc_image.py
  roles/lib_openshift/library/oc_label.py
  roles/lib_openshift/library/oc_obj.py
  roles/lib_openshift/library/oc_objectvalidator.py
  roles/lib_openshift/library/oc_process.py
  roles/lib_openshift/library/oc_project.py
  roles/lib_openshift/library/oc_pvc.py
  roles/lib_openshift/library/oc_route.py
  roles/lib_openshift/library/oc_scale.py
  roles/lib_openshift/library/oc_secret.py
  roles/lib_openshift/library/oc_service.py
  roles/lib_openshift/library/oc_serviceaccount.py
  roles/lib_openshift/library/oc_serviceaccount_secret.py
  roles/lib_openshift/library/oc_storageclass.py
  roles/lib_openshift/library/oc_user.py
  roles/lib_openshift/library/oc_version.py
  roles/lib_openshift/library/oc_volume.py
  roles/lib_openshift/src/lib/base.py
Labels: approved, bugzilla/valid-bug, lgtm, size/M

#11847 Bug 1741432: openshift-node to approve node CSRs
  roles/openshift_node/tasks/config.yml
Labels: approved, bugzilla/valid-bug, lgtm, size/M

#11860 Bug 1745202: Correct dockergc service account namespace
  roles/openshift_docker_gc/tasks/main.yml
Labels: approved, bugzilla/valid-bug, lgtm, size/S

#11858 Bug 1744456: Extract registries.conf from bootstrap
  roles/openshift_node/tasks/config.yml
Labels: approved, bugzilla/valid-bug, lgtm, size/S

#11866 roles: switch to CMO image which is automatically build by our CI
  roles/openshift_cluster_monitoring_operator/defaults/main.yml
Labels: approved, lgtm, size/XS

#11834 [KIECLOUD-292] - Update RHPAM and RHMD templates and imagestreams on …
  roles/openshift_examples/examples-sync.sh
  roles/openshift_examples/files/examples/x86_64/xpaas-streams/rhdm74-image-streams.yaml
  roles/openshift_examples/files/examples/x86_64/xpaas-streams/rhpam74-image-streams.yaml
  roles/openshift_examples/files/examples/x86_64/xpaas-templates/rhdm74-authoring-ha.yaml
  roles/openshift_examples/files/examples/x86_64/xpaas-templates/rhdm74-authoring.yaml
  roles/openshift_examples/files/examples/x86_64/xpaas-templates/rhdm74-kieserver.yaml
  roles/openshift_examples/files/examples/x86_64/xpaas-templates/rhdm74-optaweb-employee-rostering.yaml
  roles/openshift_examples/files/examples/x86_64/xpaas-templates/rhdm74-prod-immutable-kieserver-amq.yaml
  roles/openshift_examples/files/examples/x86_64/xpaas-templates/rhdm74-prod-immutable-kieserver.yaml
  roles/openshift_examples/files/examples/x86_64/xpaas-templates/rhdm74-trial-ephemeral.yaml
  roles/openshift_examples/files/examples/x86_64/xpaas-templates/rhpam74-authoring-ha.yaml
  roles/openshift_examples/files/examples/x86_64/xpaas-templates/rhpam74-authoring.yaml
  roles/openshift_examples/files/examples/x86_64/xpaas-templates/rhpam74-kieserver-externaldb.yaml
  roles/openshift_examples/files/examples/x86_64/xpaas-templates/rhpam74-kieserver-mysql.yaml
  roles/openshift_examples/files/examples/x86_64/xpaas-templates/rhpam74-kieserver-postgresql.yaml
  roles/openshift_examples/files/examples/x86_64/xpaas-templates/rhpam74-managed.yaml
  roles/openshift_examples/files/examples/x86_64/xpaas-templates/rhpam74-prod-immutable-kieserver-amq.yaml
  roles/openshift_examples/files/examples/x86_64/xpaas-templates/rhpam74-prod-immutable-kieserver.yaml
  roles/openshift_examples/files/examples/x86_64/xpaas-templates/rhpam74-prod-immutable-monitor.yaml
  roles/openshift_examples/files/examples/x86_64/xpaas-templates/rhpam74-prod.yaml
  roles/openshift_examples/files/examples/x86_64/xpaas-templates/rhpam74-trial-ephemeral.yaml
Labels: approved, lgtm, ok-to-test, size/L

#11863 Bug 1746212: [3.11] metrics-server-certs secret does not be removed after metrics-server uninstall due to incorrect label
  roles/metrics_server/templates/serving-certs-secret.j2
Labels: approved, bugzilla/valid-bug, lgtm, ok-to-test, size/XS

#11865 Ensure port 10250 is accessible from nodes/pods
  roles/openshift_openstack/defaults/main.yml
Labels: approved, lgtm, size/XS

#11852 Fix typo in readme
  roles/kuryr/README.md
Labels: approved, lgtm, needs-ok-to-test, size/XS

#11868 Bug 1729994: Add image tag to test image for registry_auth
  roles/openshift_facts/defaults/main.yml
Labels: approved, bugzilla/valid-bug, lgtm, size/XS

#11856 Bug 1741713. Omit build api in standalone registry
  roles/openshift_control_plane/tasks/check_master_api_is_ready.yml
Labels: approved, lgtm, ok-to-test, size/XS

#11873 Update the docs about default downstream kuryr images
  playbooks/openstack/configuration.md
Labels: approved, lgtm, size/XS

#11871 Bug 1746926: Conditionally handle base64 encoded data for registries.conf
  roles/openshift_node/tasks/config.yml
Labels: approved, bugzilla/valid-bug, lgtm, size/XS
