Repository openshift/openshift-ansible, pull requests merged in 2019-09, with the labels that each got.

#11642 Option to use openshift_metrics_cassandra_pvc_name to denote exact na…
  roles/openshift_metrics/tasks/generate_cassandra_pvcs.yaml
  roles/openshift_metrics/templates/hawkular_cassandra_rc.j2
Labels: approved, lgtm, ok-to-test, size/M

#11877 Bug 1733327: Add metrics-server redeploy certificate playbook
  playbooks/metrics-server/private/redeploy-certificates.yml
  playbooks/redeploy-certificates.yml
Labels: approved, bugzilla/valid-bug, lgtm, size/M

#11881 Bug 1749024: Ensure minimum kernel version
  playbooks/init/base_packages.yml
Labels: approved, bugzilla/valid-bug, lgtm, size/S

#11878 Bug 1735502: compare solely md5 hash for config change
  roles/openshift_node_group/files/sync.yaml
Labels: approved, bugzilla/valid-bug, lgtm, size/S

#11880 Bug 1743950: Validate openshift_master_ca_certificate and ca.crt
  playbooks/init/sanity_checks.yml
Labels: approved, bugzilla/valid-bug, lgtm, size/M

#11889 Bug 1749024: Update minimum required kernel version
  playbooks/init/base_packages.yml
Labels: approved, bugzilla/valid-bug, lgtm, size/XS

#11851 Avoid gathering facts on set_fact-only play
  playbooks/openshift-etcd/private/upgrade_backup.yml
  playbooks/openshift-master/private/upgrade.yml
Labels: approved, lgtm, ok-to-test, size/XS

#11837 Update Fuse templates with 7.4 release (3.11)
  roles/openshift_examples/files/examples/x86_64/xpaas-streams/fis-image-streams.json
  roles/openshift_examples/files/examples/x86_64/xpaas-templates/eap-camel-amq-template.json
  roles/openshift_examples/files/examples/x86_64/xpaas-templates/eap-camel-cdi-template.json
  roles/openshift_examples/files/examples/x86_64/xpaas-templates/eap-camel-cxf-jaxrs-template.json
  roles/openshift_examples/files/examples/x86_64/xpaas-templates/eap-camel-cxf-jaxws-template.json
  roles/openshift_examples/files/examples/x86_64/xpaas-templates/eap-camel-jpa-template.json
  roles/openshift_examples/files/examples/x86_64/xpaas-templates/fis-console-cluster-template.json
  roles/openshift_examples/files/examples/x86_64/xpaas-templates/fis-console-namespace-template.json
  roles/openshift_examples/files/examples/x86_64/xpaas-templates/fuse-apicurito.yml
  roles/openshift_examples/files/examples/x86_64/xpaas-templates/karaf-camel-amq-template.json
  roles/openshift_examples/files/examples/x86_64/xpaas-templates/karaf-camel-log-template.json
  roles/openshift_examples/files/examples/x86_64/xpaas-templates/karaf-camel-rest-sql-template.json
  roles/openshift_examples/files/examples/x86_64/xpaas-templates/karaf-cxf-rest-template.json
  roles/openshift_examples/files/examples/x86_64/xpaas-templates/spring-boot-camel-amq-template.json
  roles/openshift_examples/files/examples/x86_64/xpaas-templates/spring-boot-camel-config-template.json
  roles/openshift_examples/files/examples/x86_64/xpaas-templates/spring-boot-camel-drools-template.json
  roles/openshift_examples/files/examples/x86_64/xpaas-templates/spring-boot-camel-infinispan-template.json
  roles/openshift_examples/files/examples/x86_64/xpaas-templates/spring-boot-camel-rest-3scale-template.json
  roles/openshift_examples/files/examples/x86_64/xpaas-templates/spring-boot-camel-rest-sql-template.json
  roles/openshift_examples/files/examples/x86_64/xpaas-templates/spring-boot-camel-teiid-template.json
  roles/openshift_examples/files/examples/x86_64/xpaas-templates/spring-boot-camel-template.json
  roles/openshift_examples/files/examples/x86_64/xpaas-templates/spring-boot-camel-xa-template.json
  roles/openshift_examples/files/examples/x86_64/xpaas-templates/spring-boot-camel-xml-template.json
  roles/openshift_examples/files/examples/x86_64/xpaas-templates/spring-boot-cxf-jaxrs-template.json
  roles/openshift_examples/files/examples/x86_64/xpaas-templates/spring-boot-cxf-jaxws-template.json
Labels: approved, lgtm, ok-to-test, size/XL

#11894 Add RHEL 7.5 to minimum kernel version
  playbooks/init/base_packages.yml
Labels: approved, lgtm, size/XS

#11888 Bug 1749341: Update registries.conf during upgrades
  playbooks/common/openshift-cluster/upgrades/docker/tasks/upgrade.yml
  roles/container_runtime/README.md
  roles/container_runtime/defaults/main.yml
  roles/container_runtime/handlers/main.yml
  roles/container_runtime/tasks/common/pre.yml
  roles/container_runtime/tasks/docker_restart.yml
  roles/container_runtime/tasks/package_crio.yml
  roles/container_runtime/tasks/package_docker.yml
  roles/container_runtime/tasks/update_registries.yml
  roles/container_runtime/templates/daemon.json
  roles/container_runtime/templates/registries.conf.j2
  roles/container_runtime/templates/systemcontainercustom.conf.j2
  roles/container_runtime/vars/main.yml
  roles/openshift_node/tasks/upgrade.yml
Labels: approved, bugzilla/valid-bug, lgtm, size/L

#11823 [release-3.10] Fix ca node sync always applying certificate
  roles/openshift_node_group/files/sync.yaml
Labels: approved, lgtm, size/S

#11905 [GlusterFS]: Add a var to make user acknowledged that upgrade playbook is in tech preview
  playbooks/openshift-glusterfs/upgrade.yml
  roles/openshift_storage_glusterfs/README.md
Labels: approved, lgtm, ok-to-test, size/S

#11908 [GlusterFS]: Update pod name so previously created heketi key can be found
  roles/openshift_storage_glusterfs/tasks/heketi_get_key.yml
Labels: approved, lgtm, ok-to-test, size/XS

#11906 [GlusterFS]: Remove upgrade playbook that was not fully backported
  playbooks/openshift-glusterfs/private/upgrade.yml
  playbooks/openshift-glusterfs/upgrade.yml
Labels: approved, lgtm, ok-to-test, size/M

#11857 [GlusterFS]: Install specific glusterfs-fuse version mentioned
  roles/openshift_node/README.md
  roles/openshift_node/defaults/main.yml
  roles/openshift_node/tasks/glusterfs.yml
Labels: approved, lgtm, size/S

#11864 [GlusterFS]: unique names for glusterblock provisioner name
  roles/openshift_storage_glusterfs/files/glusterblock-provisioner.yml
  roles/openshift_storage_glusterfs/tasks/glusterblock_storageclass.yml
  roles/openshift_storage_glusterfs/templates/gluster-block-storageclass.yml.j2
Labels: approved, lgtm, size/XS

#11216 Variables to specify failureThreshold for Hawkular probes
  roles/openshift_metrics/defaults/main.yaml
  roles/openshift_metrics/templates/hawkular_metrics_rc.j2
Labels: approved, lgtm, ok-to-test, size/XS

#11909 [release-3.11] Bug 1747305: Couldn't regenerate the cert if the /etc/origin/logging…
  roles/openshift_logging_elasticsearch/tasks/generate_secret.yaml
Labels: approved, bugzilla/valid-bug, lgtm, size/S

#11910 [release-3.11] Bug 1747307: The redeploy-certificates.yml failed when ops is enabled
  roles/openshift_logging_kibana/defaults/main.yml
Labels: approved, bugzilla/valid-bug, lgtm, size/XS

#11921 Bug 1668853: Fix rbac aggregation for OLM
  roles/olm/files/aggregated-view.clusterrole.yaml
Labels: approved, bugzilla/valid-bug, lgtm, size/XS

#11916 Bug 1751975: Modify mounts when using atomic during imageconfig if oreg username i…
  playbooks/openshift-node/imageconfig.yml
  playbooks/openshift-node/private/configure_system_container.yml
Labels: approved, bugzilla/valid-bug, lgtm, size/S

#11920 Update main.yml
  roles/openshift_storage_glusterfs/defaults/main.yml
Labels: approved, lgtm, ok-to-test, size/XS

#11924 Kuryr controller label
  roles/kuryr/templates/controller-deployment.yaml.j2
Labels: approved, lgtm, size/XS

#11917 Bug 1752532: upgrade from 3.11 failed to upgrade es settings from configmap
  roles/openshift_logging_elasticsearch/defaults/main.yml
  roles/openshift_logging_elasticsearch/tasks/main.yaml
Labels: approved, bugzilla/valid-bug, lgtm, size/M

#11922 Bug 1645725: Increase timeout for Docker images and creds
  roles/lib_utils/library/docker_creds.py
  roles/openshift_health_checker/openshift_checks/docker_image_availability.py
  roles/openshift_health_checker/test/docker_image_availability_test.py
Labels: approved, bugzilla/valid-bug, lgtm, size/S

#11930 [GlusterFS]: fix mismatched var in upgrade playbook warning
  playbooks/openshift-glusterfs/upgrade.yml
Labels: approved, lgtm, ok-to-test, size/XS
