Repository openshift/openshift-ansible, pull requests merged in 2019-11, with the labels that each got.

#11993 [KIECLOUD-316] - Update RHPAM and RHDM templates and imagestreams on …
  roles/openshift_examples/examples-sync.sh
  roles/openshift_examples/files/examples/x86_64/xpaas-streams/rhdm75-image-streams.yaml
  roles/openshift_examples/files/examples/x86_64/xpaas-streams/rhpam75-image-streams.yaml
  roles/openshift_examples/files/examples/x86_64/xpaas-templates/rhdm75-authoring-ha.yaml
  roles/openshift_examples/files/examples/x86_64/xpaas-templates/rhdm75-authoring.yaml
  roles/openshift_examples/files/examples/x86_64/xpaas-templates/rhdm75-kieserver.yaml
  roles/openshift_examples/files/examples/x86_64/xpaas-templates/rhdm75-optaweb-employee-rostering.yaml
  roles/openshift_examples/files/examples/x86_64/xpaas-templates/rhdm75-prod-immutable-kieserver-amq.yaml
  roles/openshift_examples/files/examples/x86_64/xpaas-templates/rhdm75-prod-immutable-kieserver.yaml
  roles/openshift_examples/files/examples/x86_64/xpaas-templates/rhdm75-trial-ephemeral.yaml
  roles/openshift_examples/files/examples/x86_64/xpaas-templates/rhpam75-authoring-ha.yaml
  roles/openshift_examples/files/examples/x86_64/xpaas-templates/rhpam75-authoring.yaml
  roles/openshift_examples/files/examples/x86_64/xpaas-templates/rhpam75-kieserver-externaldb.yaml
  roles/openshift_examples/files/examples/x86_64/xpaas-templates/rhpam75-kieserver-mysql.yaml
  roles/openshift_examples/files/examples/x86_64/xpaas-templates/rhpam75-kieserver-postgresql.yaml
  roles/openshift_examples/files/examples/x86_64/xpaas-templates/rhpam75-managed.yaml
  roles/openshift_examples/files/examples/x86_64/xpaas-templates/rhpam75-prod-immutable-kieserver-amq.yaml
  roles/openshift_examples/files/examples/x86_64/xpaas-templates/rhpam75-prod-immutable-kieserver.yaml
  roles/openshift_examples/files/examples/x86_64/xpaas-templates/rhpam75-prod-immutable-monitor.yaml
  roles/openshift_examples/files/examples/x86_64/xpaas-templates/rhpam75-prod.yaml
  roles/openshift_examples/files/examples/x86_64/xpaas-templates/rhpam75-trial-ephemeral.yaml
Labels: approved, lgtm, ok-to-test, size/XXL

#11975 ignore failure on master
  playbooks/adhoc/uninstall_openshift.yml
Labels: approved, lgtm, needs-ok-to-test, size/XS

#12004 Bug 1769222: Fix test_image for additional registries
  roles/cockpit-ui/defaults/main.yml
  roles/container_runtime/defaults/main.yml
  roles/container_runtime/tasks/registry_auth.yml
  roles/kuryr/defaults/main.yaml
  roles/metrics_server/defaults/main.yaml
  roles/olm/defaults/main.yaml
  roles/openshift_autoheal/defaults/main.yml
  roles/openshift_cluster_autoscaler/defaults/main.yml
  roles/openshift_cluster_monitoring_operator/defaults/main.yml
  roles/openshift_console/defaults/main.yml
  roles/openshift_control_plane/defaults/main.yml
  roles/openshift_control_plane/tasks/pre_pull.yml
  roles/openshift_control_plane/tasks/registry_auth.yml
  roles/openshift_control_plane/tasks/static.yml
  roles/openshift_control_plane/tasks/upgrade.yml
  roles/openshift_control_plane/templates/master.yaml.v1.j2
  roles/openshift_descheduler/defaults/main.yaml
  roles/openshift_docker_gc/defaults/main.yml
  roles/openshift_examples/defaults/main.yml
  roles/openshift_examples/tasks/stream_secrets.yml
  roles/openshift_facts/defaults/main.yml
  roles/openshift_health_checker/defaults/main.yml
  roles/openshift_hosted/defaults/main.yml
  roles/openshift_logging/defaults/main.yml
  roles/openshift_logging_defaults/defaults/main.yml
  roles/openshift_metrics/defaults/main.yaml
  roles/openshift_node/defaults/main.yml
  roles/openshift_node/tasks/prepull.yml
  roles/openshift_node/tasks/registry_auth.yml
  roles/openshift_node_group/defaults/main.yml
  roles/openshift_node_group/tasks/migrate_imageconfig.yml
  roles/openshift_node_group/templates/node-config.yaml.j2
  roles/openshift_node_problem_detector/defaults/main.yaml
  roles/openshift_service_catalog/defaults/main.yml
  roles/openshift_web_console/defaults/main.yml
  roles/template_service_broker/defaults/main.yml
Labels: approved, bugzilla/valid-bug, lgtm, size/L

#11991 Bug 1767111 - logging - expose undefined field, multiline parameters
  roles/openshift_logging/README.md
  roles/openshift_logging_fluentd/defaults/main.yml
  roles/openshift_logging_fluentd/templates/fluentd.j2
Labels: approved, lgtm, size/M

#12009 Bug 1766792: Restrict new scaleup machinesets to 1 replica
  test/aws/create_machineset.yml
Labels: approved, bugzilla/valid-bug, lgtm, size/XS

#12003 Bug 1767579: Remove import playbook restart
  playbooks/openshift-node/private/join.yml
Labels: approved, bugzilla/valid-bug, lgtm, size/XS

#11987 Fix gluster after restart change
  playbooks/openshift-node/private/restart.yml
Labels: approved, lgtm, size/XS

#12007 Enable arch specific openshift_node packages
  roles/openshift_node/defaults/main.yml
Labels: approved, lgtm, size/S

#12014 Fix web console URL
  roles/openshift_web_console/tasks/install.yml
Labels: approved, lgtm, size/XS

#12020 Bug 1772543: Add logging certificate redeploy to main redeploy playbook
  playbooks/redeploy-certificates.yml
Labels: approved, bugzilla/valid-bug, lgtm, size/XS

#12016 Use Ansible 2.9.1 for testing
  images/installer/Dockerfile
  requirements.txt
Labels: approved, lgtm, size/XS

#12022 Fail waiting for machine creation if phase is failed
  test/aws/create_machineset.yml
Labels: approved, lgtm, size/M

#12011 Increase the timeout for restart
  playbooks/openshift-node/private/restart.yml
Labels: approved, lgtm, size/XS

#12017 [release-3.11] Bug 1747307: The redeploy-certificates.yml failed when ops is enabled
  roles/openshift_logging_kibana/defaults/main.yml
Labels: approved, bugzilla/valid-bug, lgtm, size/XS

#12025 Bug 1756255: Fix openshift_health_checker sdn.py key error
  playbooks/common/openshift-cluster/upgrades/v3_11/fix_first_master_node.yml
  playbooks/common/openshift-cluster/upgrades/v3_11/upgrade_control_plane_part2.yml
  playbooks/openshift-checks/private/adhoc.yml
  playbooks/openshift-checks/private/health.yml
  playbooks/openshift-checks/private/install.yml
  playbooks/openshift-checks/private/pre-install.yml
  roles/openshift_health_checker/openshift_checks/sdn.py
  roles/openshift_health_checker/test/sdn_tests.py
Labels: approved, bugzilla/valid-bug, lgtm, size/S

#12027 Bug 1774412: Remove obsolete roles from local openshift.fact
  roles/openshift_facts/library/openshift_facts.py
Labels: approved, bugzilla/valid-bug, lgtm, size/XS

#11999 Bug 1765646: Fluentd single pod logging performance regression 3.x
  roles/openshift_logging/README.md
  roles/openshift_logging_fluentd/defaults/main.yml
  roles/openshift_logging_fluentd/templates/fluentd.j2
Labels: approved, bugzilla/valid-bug, lgtm, size/S

#12028 Bug 1756457: Ensure openshift_master_cluster_hostname is set when deploying multiple masters
  roles/openshift_sanitize_inventory/tasks/main.yml
Labels: approved, bugzilla/valid-bug, lgtm, size/XS

#11984 Bug 1725834: Create configmaps only for used openshift_node_group_names
  playbooks/openshift-master/private/scaleup.yml
  playbooks/openshift-node/scaleup.yml
  roles/openshift_node_group/tasks/check_for_configs.yml
  roles/openshift_node_group/tasks/main.yml
  roles/openshift_node_group/tasks/upgrade.yml
Labels: approved, bugzilla/valid-bug, lgtm, size/M

#11838 Update EAP CD to CD17
  roles/openshift_examples/files/examples/x86_64/xpaas-streams/eap-cd-image-stream.json
  roles/openshift_examples/files/examples/x86_64/xpaas-templates/eap-cd-amq-persistent-s2i.json
  roles/openshift_examples/files/examples/x86_64/xpaas-templates/eap-cd-amq-s2i.json
  roles/openshift_examples/files/examples/x86_64/xpaas-templates/eap-cd-basic-s2i.json
  roles/openshift_examples/files/examples/x86_64/xpaas-templates/eap-cd-https-s2i.json
  roles/openshift_examples/files/examples/x86_64/xpaas-templates/eap-cd-mongodb-persistent-s2i.json
  roles/openshift_examples/files/examples/x86_64/xpaas-templates/eap-cd-mongodb-s2i.json
  roles/openshift_examples/files/examples/x86_64/xpaas-templates/eap-cd-mysql-persistent-s2i.json
  roles/openshift_examples/files/examples/x86_64/xpaas-templates/eap-cd-mysql-s2i.json
  roles/openshift_examples/files/examples/x86_64/xpaas-templates/eap-cd-postgresql-persistent-s2i.json
  roles/openshift_examples/files/examples/x86_64/xpaas-templates/eap-cd-postgresql-s2i.json
  roles/openshift_examples/files/examples/x86_64/xpaas-templates/eap-cd-sso-s2i.json
  roles/openshift_examples/files/examples/x86_64/xpaas-templates/eap-cd-starter-s2i.json
  roles/openshift_examples/files/examples/x86_64/xpaas-templates/eap-cd-third-party-db-s2i.json
  roles/openshift_examples/files/examples/x86_64/xpaas-templates/eap-cd-tx-recovery-postgresql-s2i.json
  roles/openshift_examples/files/examples/x86_64/xpaas-templates/eap-cd-tx-recovery-s2i.json
Labels: approved, lgtm, ok-to-test, size/XXL

#12024 Update Fuse templates with 7.5 release
  roles/openshift_examples/files/examples/x86_64/xpaas-streams/fis-image-streams.json
  roles/openshift_examples/files/examples/x86_64/xpaas-templates/eap-camel-amq-template.json
  roles/openshift_examples/files/examples/x86_64/xpaas-templates/eap-camel-cdi-template.json
  roles/openshift_examples/files/examples/x86_64/xpaas-templates/eap-camel-cxf-jaxrs-template.json
  roles/openshift_examples/files/examples/x86_64/xpaas-templates/eap-camel-cxf-jaxws-template.json
  roles/openshift_examples/files/examples/x86_64/xpaas-templates/eap-camel-jpa-template.json
  roles/openshift_examples/files/examples/x86_64/xpaas-templates/fis-console-cluster-template.json
  roles/openshift_examples/files/examples/x86_64/xpaas-templates/fis-console-namespace-template.json
  roles/openshift_examples/files/examples/x86_64/xpaas-templates/fuse-apicurito.yml
  roles/openshift_examples/files/examples/x86_64/xpaas-templates/karaf-camel-amq-template.json
  roles/openshift_examples/files/examples/x86_64/xpaas-templates/karaf-camel-log-template.json
  roles/openshift_examples/files/examples/x86_64/xpaas-templates/karaf-camel-rest-sql-template.json
  roles/openshift_examples/files/examples/x86_64/xpaas-templates/karaf-cxf-rest-template.json
  roles/openshift_examples/files/examples/x86_64/xpaas-templates/spring-boot-camel-amq-template.json
  roles/openshift_examples/files/examples/x86_64/xpaas-templates/spring-boot-camel-config-template.json
  roles/openshift_examples/files/examples/x86_64/xpaas-templates/spring-boot-camel-drools-template.json
  roles/openshift_examples/files/examples/x86_64/xpaas-templates/spring-boot-camel-infinispan-template.json
  roles/openshift_examples/files/examples/x86_64/xpaas-templates/spring-boot-camel-rest-3scale-template.json
  roles/openshift_examples/files/examples/x86_64/xpaas-templates/spring-boot-camel-rest-sql-template.json
  roles/openshift_examples/files/examples/x86_64/xpaas-templates/spring-boot-camel-template.json
  roles/openshift_examples/files/examples/x86_64/xpaas-templates/spring-boot-camel-xa-template.json
  roles/openshift_examples/files/examples/x86_64/xpaas-templates/spring-boot-camel-xml-template.json
  roles/openshift_examples/files/examples/x86_64/xpaas-templates/spring-boot-cxf-jaxrs-template.json
  roles/openshift_examples/files/examples/x86_64/xpaas-templates/spring-boot-cxf-jaxws-template.json
Labels: approved, lgtm, ok-to-test, size/XXL

#12029 Inserted a missing "endif"
  roles/openshift_logging_fluentd/templates/fluentd.j2
Labels: approved, lgtm, ok-to-test, size/XS
