Repository openshift/openshift-ansible, pull requests merged in 2019-06, with the labels that each got.

#11633 Enable ports population for new namespaces
  roles/kuryr/templates/configmap.yaml.j2
Labels: approved, lgtm, size/XS

#11639 Added mandatory missing argument "system_facts"
  playbooks/byo/openshift_facts.yml
Labels: approved, lgtm, ok-to-test, size/XS

#11563 Option to use hostpath mount for Elastic Search storage
  roles/openshift_logging/tasks/install_logging.yaml
  roles/openshift_logging_elasticsearch/defaults/main.yml
  roles/openshift_logging_elasticsearch/tasks/main.yaml
Labels: approved, lgtm, ok-to-test, size/M

#11660 [release-3.11] Control plane pods didn't come up by incorrect data type of "openshift_master_audit_config"
  inventory/hosts.example
Labels: approved, lgtm, ok-to-test, size/XS

#11669 Bug 1585070: remove cpu_manager_state file
  roles/openshift_node/tasks/upgrade/config_changes.yml
Labels: approved, bugzilla/valid-bug, lgtm, size/XS

#11672 Add EAP CD 16 imagestreams & templates
  roles/openshift_examples/files/examples/x86_64/xpaas-streams/eap-cd-image-stream.json
  roles/openshift_examples/files/examples/x86_64/xpaas-templates/eap-cd-amq-persistent-s2i.json
  roles/openshift_examples/files/examples/x86_64/xpaas-templates/eap-cd-amq-s2i.json
  roles/openshift_examples/files/examples/x86_64/xpaas-templates/eap-cd-basic-s2i.json
  roles/openshift_examples/files/examples/x86_64/xpaas-templates/eap-cd-https-s2i.json
  roles/openshift_examples/files/examples/x86_64/xpaas-templates/eap-cd-mongodb-persistent-s2i.json
  roles/openshift_examples/files/examples/x86_64/xpaas-templates/eap-cd-mongodb-s2i.json
  roles/openshift_examples/files/examples/x86_64/xpaas-templates/eap-cd-mysql-persistent-s2i.json
  roles/openshift_examples/files/examples/x86_64/xpaas-templates/eap-cd-mysql-s2i.json
  roles/openshift_examples/files/examples/x86_64/xpaas-templates/eap-cd-postgresql-persistent-s2i.json
  roles/openshift_examples/files/examples/x86_64/xpaas-templates/eap-cd-postgresql-s2i.json
  roles/openshift_examples/files/examples/x86_64/xpaas-templates/eap-cd-sso-s2i.json
  roles/openshift_examples/files/examples/x86_64/xpaas-templates/eap-cd-starter-s2i.json
  roles/openshift_examples/files/examples/x86_64/xpaas-templates/eap-cd-third-party-db-s2i.json
  roles/openshift_examples/files/examples/x86_64/xpaas-templates/eap-cd-tx-recovery-postgresql-s2i.json
  roles/openshift_examples/files/examples/x86_64/xpaas-templates/eap-cd-tx-recovery-s2i.json
Labels: approved, lgtm, ok-to-test, size/L

#11673 [3.11]: allow cluster autoscaler to evict pods
  roles/openshift_cluster_autoscaler/files/clusterrole.yml
Labels: approved, lgtm, size/XS

#11675 [release-3.9] Fail on Ansible 2.8
  README.md
  roles/lib_utils/callback_plugins/aa_version_requirement.py
Labels: approved, lgtm

#11674 [release-3.10] Fail on Ansible 2.8
  README.md
  roles/lib_utils/callback_plugins/aa_version_requirement.py
Labels: approved, lgtm, size/XS

#11670 Clean up Ansible Service Broker Configmap
  roles/ansible_service_broker/templates/configmap.yaml.j2
Labels: approved, lgtm, size/S

#11679 Remove kuryrnet handler from default kuryr configuration
  playbooks/openstack/configuration.md
  roles/kuryr/templates/configmap.yaml.j2
Labels: approved, lgtm, size/S

#11663 Fix timeoutSeconds in hawkular-cassandra
  roles/openshift_metrics/templates/hawkular_cassandra_rc.j2
Labels: approved, lgtm, ok-to-test, size/XS

#11603 [release-3.10] While upgrading to 3.10 add node-config file check
  roles/openshift_node/handlers/main.yml
  roles/openshift_node/tasks/upgrade/restart.yml
Labels: approved, lgtm, size/M

#11681 Add redeploy cert for service catalog, asb and tsb
  playbooks/openshift-service-catalog/private/redeploy-certificates.yml
  playbooks/redeploy-certificates.yml
  roles/ansible_service_broker/tasks/delete_secrets.yml
  roles/ansible_service_broker/tasks/restart_pods.yml
  roles/ansible_service_broker/tasks/update_secrets.yml
  roles/openshift_service_catalog/tasks/delete_secrets.yml
  roles/openshift_service_catalog/tasks/restart_pods.yml
  roles/template_service_broker/tasks/delete_secrets.yml
  roles/template_service_broker/tasks/restart_pods.yml
  roles/template_service_broker/tasks/update_secrets.yml
Labels: approved, lgtm, size/L

#11653 If managed registry is false modify example ImageStream referencePolicy
  roles/openshift_examples/tasks/modify_imagestreams.yml
  roles/openshift_examples/tasks/x86_64_examples.yml
Labels: approved, lgtm, size/M

#11688 [release-3.11] Fix module_results for recent commits
  roles/openshift_logging_elasticsearch/tasks/main.yaml
Labels: approved, lgtm, size/XS

#11683 Fixed delete and restore tasks.
  roles/openshift_storage_glusterfs/tasks/glusterfs_uninstall.yml
Labels: approved, lgtm, ok-to-test, size/XS

#11684 Updates changes service catalog certificate for Ansible 2.8
  roles/ansible_service_broker/tasks/restart_pods.yml
  roles/ansible_service_broker/tasks/update_secrets.yml
  roles/openshift_service_catalog/tasks/restart_pods.yml
  roles/template_service_broker/tasks/restart_pods.yml
  roles/template_service_broker/tasks/update_secrets.yml
Labels: approved, lgtm, size/S

#11699 Fix issue with metrics undefined l_kubelet_node_name
  playbooks/openshift-metrics/config.yml
Labels: approved, lgtm, size/XS

#10920 Supply namespace when generating hawkular role binding
  roles/openshift_metrics/tasks/generate_rolebindings.yaml
Labels: approved, lgtm, ok-to-test, size/XS

#11630 [release-3.9] Don't use hostvars fact for openshift_master_etcd_urls
  playbooks/openshift-node/private/additional_config.yml
  roles/calico_master/tasks/certs.yml
Labels: approved, lgtm, ok-to-test, size/XS

#11695 [release-3.11] Run networkmanager and selinux checks in prereqs
  playbooks/deploy_cluster.yml
  playbooks/init/sanity_checks.yml
  playbooks/openshift-master/scaleup.yml
  playbooks/prerequisites.yml
  roles/openshift_node/tasks/main.yml
Labels: approved, lgtm, size/M

#11651 Juniper Contrail SDN patch
  playbooks/openshift-master/private/config.yml
  playbooks/openshift-node/private/contrail_sanitize.yml
  playbooks/openshift-node/private/join.yml
  roles/contrail_common/README.md
  roles/contrail_common/defaults/main.yml
  roles/contrail_common/tasks/determine_contrail_masters.yaml
  roles/contrail_common/tasks/hosts_to_ip.yaml
  roles/contrail_common/tasks/main.yml
  roles/contrail_master/README.md
  roles/contrail_master/defaults/main.yml
  roles/contrail_master/meta/main.yml
  roles/contrail_master/tasks/main.yaml
  roles/contrail_master/tasks/os_contrail_master.yaml
  roles/contrail_master/tasks/os_contrail_nested.yaml
  roles/contrail_master/templates/contrail-agent-5.j2
  roles/contrail_master/templates/contrail-analytics-5.j2
  roles/contrail_master/templates/contrail-analytics-alarm-5.j2
  roles/contrail_master/templates/contrail-analytics-db-5.j2
  roles/contrail_master/templates/contrail-analytics-snmp-5.j2
  roles/contrail_master/templates/contrail-config-db-5.j2
  roles/contrail_master/templates/contrail-control-config-5.j2
  roles/contrail_master/templates/contrail-ext-redis-5.j2
  roles/contrail_master/templates/contrail-image-downloader-5.j2
  roles/contrail_master/templates/contrail-infra-vars-5.j2
  roles/contrail_master/templates/contrail-installer-4.j2
  roles/contrail_master/templates/contrail-kube-manager-5.j2
  roles/contrail_master/templates/contrail-namespace.j2
  roles/contrail_master/templates/contrail-nested.j2
  roles/contrail_master/templates/contrail-webui-5.j2
  roles/contrail_master/templates/getIp.j2
  roles/contrail_master/templates/wait_for_pod.j2
  roles/contrail_st/README.md
  roles/contrail_st/tasks/main.yaml
  roles/contrail_st/tasks/schema_transformer_sanity.yaml
Labels: approved, lgtm, ok-to-test, size/XXL

#11586 Fix: generate hawkular-cassandra pvc (dynamic)
  roles/openshift_metrics/tasks/generate_cassandra_pvcs.yaml
Labels: approved, lgtm, ok-to-test, size/XS

#11704 Redeploy catalog/broker certs by default
  playbooks/openshift-service-catalog/private/redeploy-certificates.yml
  playbooks/redeploy-certificates.yml
  roles/ansible_service_broker/tasks/generate_certs.yml
  roles/ansible_service_broker/tasks/install.yml
Labels: approved, lgtm, size/M

#11707 openshift_facts: fix MTU detection
  roles/openshift_facts/library/openshift_facts.py
Labels: approved, lgtm, size/XS

#11701 Remove subPaths when mounting Kuryr pods volumes
  roles/kuryr/templates/cni-daemonset.yaml.j2
  roles/kuryr/templates/controller-deployment.yaml.j2
Labels: approved, lgtm, size/S

#11710 Contrail namespace edited
  roles/contrail_master/tasks/os_contrail_master.yaml
Labels: approved, lgtm, ok-to-test, size/XS

#11713 Add ClusterRole to perform read/write with endpoint
  roles/openshift_storage_glusterfs/files/glusterblock-provisioner.yml
Labels: approved, lgtm, size/XS

#11717 [release-3.11] Fix openshift_logging_elasticsearch handler (Ansible 2.8)
  roles/openshift_logging_elasticsearch/handlers/main.yml
Labels: approved, lgtm, size/XS

#11721 Add openshift ca to trust via node sync
  roles/openshift_node_group/files/sync.yaml
Labels: approved, lgtm, size/S

#11723 [release-3.10] Add openshift ca to trust via node sync
  roles/openshift_node_group/files/sync.yaml
Labels: approved, lgtm, size/S

#11724 [release-3.11] Ensure default vars are loaded for sanity checks
  playbooks/init/sanity_checks.yml
Labels: approved, lgtm, size/XS

#11698 Add required dirs for crio 1.14.4
  roles/openshift_node/tasks/install.yml
Labels: approved, lgtm, size/S

#11728 Ensure master facts are set executing node config
  playbooks/openshift-node/config.yml
Labels: approved, lgtm, ok-to-test, size/XS
