Repository openshift/openshift-ansible, pull requests merged in 2019-01, with the labels that each got.

#10909 Add proper 4.0 README steps
  README.md
  inventory/40_basic_inventory.ini
  inventory/install-config-example.yml
Labels: approved, size/L

#10934 gluster: allow dynamic creation of devices
  roles/openshift_storage_glusterfs/files/glusterfs-template.yml
Labels: approved, lgtm, needs-ok-to-test, size/M

#10942 [libvirt] Set worker replicas to 1 for now
  test/libvirt/install-config.yml.template
Labels: approved, lgtm, size/XS

#10684 Release 3.11 vsphere network public network
  inventory/hosts.example
  roles/openshift_cloud_provider/templates/vsphere.conf.j2
Labels: approved, lgtm, size/XS

#10940 [release-3.11] Switch subjectAltName type to bytes when checking certs using pyOpenSSL.
  roles/lib_utils/filter_plugins/oo_filters.py
Labels: approved, lgtm, size/XS

#10910 sdn: upgrade SDN after all nodes are upgraded.
  playbooks/common/openshift-cluster/upgrades/upgrade_nodes.yml
  playbooks/common/openshift-cluster/upgrades/v3_11/upgrade_control_plane_part2.yml
  roles/openshift_sdn/tasks/main.yml
Labels: approved, lgtm, size/M

#10945 Use Calico v3.4.0
  roles/calico/tasks/main.yml
  roles/calico_master/defaults/main.yaml
Labels: approved, lgtm, ok-to-test, size/XS

#10961 test/aws: create necessary security groups
  test/ci/deprovision.yml
  test/ci/launch.yml
Labels: approved, lgtm, size/M

#10952 Use Calico v3.4.0
  roles/calico/defaults/main.yaml
Labels: approved, lgtm, needs-ok-to-test, size/XS

#10953 Use namespace variable instead of default namespace value, glusterfs
  roles/openshift_storage_glusterfs/tasks/glusterfs_upgrade.yml
Labels: approved, lgtm, size/XS

#10950 [release-3.11]FIX:Bug 1614176:Add openshift_sdn_vxlan_port to change the vxlanPort
  roles/openshift_control_plane/templates/master.yaml.v1.j2
  roles/openshift_facts/defaults/main.yml
  roles/openshift_node/defaults/main.yml
Labels: approved, lgtm, ok-to-test, size/XS

#10946 Override of logging ES image pull secret
  roles/openshift_logging_elasticsearch/defaults/main.yml
  roles/openshift_logging_elasticsearch/tasks/main.yaml
Labels: approved, lgtm, ok-to-test, size/XS

#10816 GlusterFS advanced deployment options
  roles/openshift_storage_glusterfs/README.md
  roles/openshift_storage_glusterfs/templates/glusterfs-storageclass.yml.j2
  roles/openshift_storage_glusterfs/templates/topology.json.j2
Labels: approved, lgtm, ok-to-test, size/S

#10970 Fix BZ1663306 when gluster nodes are SchedulingDisabled
  roles/lib_utils/library/glusterfs_check_containerized.py
  roles/lib_utils/test/test_glusterfs_check_containerized.py
Labels: approved, lgtm, ok-to-test, size/S

#10981 Fix install of kube_proxy_and_dns, with Calico
  roles/calico/tasks/main.yml
Labels: approved, lgtm, ok-to-test, size/XS

#10982 Added enviroment values for easier heketi-cli usage
  roles/openshift_storage_glusterfs/files/heketi-template.yml
Labels: approved, lgtm, needs-ok-to-test, size/XS

#10963 [Release 3.11] Add NSX-T as a network option
  playbooks/openshift-master/private/config.yml
  playbooks/openshift-node/private/join.yml
  roles/nsx/README.md
  roles/nsx/defaults/main.yml
  roles/nsx/files/ncp-os-scc.yml
  roles/nsx/files/nsx-ncp-rbac-oc.yml
  roles/nsx/meta/main.yml
  roles/nsx/tasks/main.yml
  roles/nsx/templates/ncp-configmap.yml.j2
  roles/nsx/templates/ncp-rc.yml.j2
  roles/nsx/templates/nsx-node-agent-configmap.yml.j2
  roles/nsx/templates/nsx-node-agent-ds.yml.j2
  roles/nsx_node/README.md
  roles/nsx_node/defaults/main.yml
  roles/nsx_node/meta/main.yml
  roles/nsx_node/tasks/main.yml
Labels: approved, lgtm, ok-to-test, size/XXL

#10871 Remove vendored ansible-profile callback
  ansible-profile/README.md
  ansible-profile/callback_plugins/profile_tasks.py
Labels: approved, size/M

#10997 Add OWNERS file.
  OWNERS
Labels: size/S

#10996 Add OWNERS file.
  OWNERS
Labels: size/S

#11000 glusterfs: Force delete heketi pod and avoid waiting for unmount,
  roles/openshift_storage_glusterfs/tasks/glusterfs_uninstall.yml
Labels: approved, lgtm, size/XS

#10988 Fix cluster logging restart message
  roles/openshift_logging_elasticsearch/tasks/restart_cluster.yml
Labels: approved, lgtm, size/XS

#10979 [release 3.11] fix OpenStack heat template conditional
  roles/openshift_openstack/templates/heat_stack.yaml.j2
Labels: approved, lgtm, size/M

#10974 [release 3.11] fix openstack facts when ec2 var is empty
  roles/openshift_facts/library/openshift_facts.py
Labels: approved, lgtm, size/S

#11012 Port #10740 and #10981 to release-3.10
  roles/calico_master/tasks/main.yml
Labels: approved, lgtm, ok-to-test, size/XS

#11014 [release 3.9] fix openstack facts when ec2 var is empty
  roles/openshift_facts/library/openshift_facts.py
Labels: approved, lgtm, size/S

#10665 Juniper Contrail SDN patch
  playbooks/openshift-master/private/config.yml
  playbooks/openshift-node/private/additional_config.yml
  playbooks/openshift-node/private/manage_node.yml
  roles/contrail_common/README.md
  roles/contrail_common/tasks/determine_contrail_masters.yaml
  roles/contrail_common/tasks/hosts_to_ip.yaml
  roles/contrail_common/tasks/main.yml
  roles/contrail_controller/README.md
  roles/contrail_controller/defaults/main.yml
  roles/contrail_controller/tasks/main.yaml
  roles/contrail_controller/tasks/os_contrail_master.yaml
  roles/contrail_controller/templates/contrail-agent-installer-5.j2
  roles/contrail_controller/templates/contrail-controller-installer-5.j2
  roles/contrail_controller/templates/contrail-image-downloader-5.j2
  roles/contrail_controller/templates/contrail-infra-installer-5.j2
  roles/contrail_controller/templates/contrail-installer-4.j2
  roles/contrail_controller/templates/contrail-installer-5.1.j2
  roles/contrail_controller/templates/contrail-nested.j2
  roles/contrail_controller/templates/getIp.j2
  roles/contrail_controller/templates/wait_for_pod.j2
  roles/contrail_master/README.md
  roles/contrail_master/defaults/main.yml
  roles/contrail_master/meta/main.yml
  roles/contrail_master/tasks/main.yaml
  roles/contrail_master/tasks/ntp.yml
  roles/contrail_master/templates/ntp.conf.j2
  roles/contrail_node/README.md
  roles/contrail_node/defaults/main.yml
  roles/contrail_node/meta/main.yml
  roles/contrail_node/tasks/bind_mounts.yaml
  roles/contrail_node/tasks/main.yaml
  roles/contrail_node/tasks/node_config.yaml
  roles/contrail_node/tasks/ntp.yml
  roles/contrail_node/templates/ntp.conf.j2
  roles/contrail_node/vars/main.yaml
  roles/contrail_st/README.md
  roles/contrail_st/tasks/main.yaml
  roles/contrail_st/tasks/schema_transformer_sanity.yaml
  roles/contrail_web_console/README.md
  roles/contrail_web_console/defaults/main.yml
  roles/contrail_web_console/files/console-config.yaml
  roles/contrail_web_console/files/console-template.yaml
  roles/contrail_web_console/tasks/main.yaml
  roles/contrail_web_console/tasks/web_console_install.yaml
  roles/openshift_node/defaults/main.yml
  roles/openshift_node/templates/openshift.docker.node.service
Labels: approved, lgtm, ok-to-test, size/XXL

#10948 [release 3.11] Allow OpenStack persistent volumes to specify storage class
  playbooks/openstack/configuration.md
  roles/lib_utils/action_plugins/generate_pv_pvcs_list.py
  roles/openshift_persistent_volumes/templates/persistent-volume.yml.j2
Labels: approved, lgtm, size/S

#11034 Hardcode CentOS repository template for 3.10
  roles/openshift_repos/tasks/centos_repos.yml
Labels: approved, lgtm, size/S

#11040 Hardcode CentOS repository template for 3.9
  roles/openshift_repos/tasks/centos_repos.yml
Labels: approved, lgtm, size/S

#10977 [3.11] split readiness from liveness probe
  roles/openshift_service_catalog/files/kubeservicecatalog_roles_bindings.yml
  roles/openshift_service_catalog/templates/api_server.j2
  roles/openshift_service_catalog/templates/controller_manager.j2
Labels: approved, lgtm, size/M

#11041 Hardcode CentOS repository template for 3.11
  roles/openshift_repos/tasks/centos_repos.yml
Labels: approved, lgtm, size/XS

#11046 Fix 404 url ( bz1668210 )
  roles/openshift_master/templates/atomic-openshift-master.j2
  roles/openshift_master/templates/native-cluster/atomic-openshift-master-api.j2
  roles/openshift_master/templates/native-cluster/atomic-openshift-master-controllers.j2
Labels: approved, lgtm, size/XS

#10921 Supply namespace when generating hawkular role binding
  roles/openshift_metrics/tasks/generate_rolebindings.yaml
Labels: approved, lgtm, ok-to-test, size/XS, ¯\_(ツ)_/¯

#11039 Run nsx_node role on openshift nodes only, Closes #11038
  playbooks/openshift-node/private/join.yml
Labels: approved, lgtm, ok-to-test, size/XS

#11047 Fix 404 url ( bz1668221 )
  roles/openshift_control_plane/templates/master.env.j2
Labels: approved, lgtm, size/XS

#10976 [3.10] split readiness from liveness probe
  roles/openshift_service_catalog/files/kubeservicecatalog_roles_bindings.yml
  roles/openshift_service_catalog/templates/api_server.j2
  roles/openshift_service_catalog/templates/controller_manager.j2
Labels: approved, lgtm, size/M

#11033 [release-3.11]Add tasks to run init playbooks for collecting "openshift_is_atomic" fact
  playbooks/openshift-checks/certificate_expiry/default.yaml
  playbooks/openshift-checks/certificate_expiry/easy-mode.yaml
  playbooks/openshift-checks/certificate_expiry/html_and_json_default_paths.yaml
  playbooks/openshift-checks/certificate_expiry/longer-warning-period-json-results.yaml
  playbooks/openshift-checks/certificate_expiry/longer_warning_period.yaml
Labels: approved, lgtm, ok-to-test, size/M

#10817 [release-3.11]FIX:1644741:Add new variables to specify storageclass to prometheus and alertmanager
  inventory/hosts.example
Labels: needs-ok-to-test, size/XS

#11044 Enable cinder predicate by default
  roles/lib_utils/lookup_plugins/openshift_master_facts_default_predicates.py
  roles/lib_utils/test/openshift_master_facts_default_predicates_tests.py
Labels: approved, lgtm, size/XS

#11015 Fix auditConfig.policyConfiguration in master_check_paths_in_config
  roles/lib_utils/action_plugins/master_check_paths_in_config.py
Labels: approved, lgtm, ok-to-test, size/S

#10978 libvirt - Add ingress reconfig steps
  test/libvirt/README.md
Labels: approved, size/S

#10710 Retrieve heketi secret before setting CLI command
  roles/openshift_storage_glusterfs/tasks/update_topology.yml
Labels: approved, lgtm, size/XS

#11030 Fix documentation for oc - modules
  roles/lib_openshift/library/oc_adm_csr.py
  roles/lib_openshift/library/oc_adm_policy_group.py
  roles/lib_openshift/library/oc_adm_policy_user.py
  roles/lib_openshift/library/oc_adm_registry.py
  roles/lib_openshift/library/oc_adm_router.py
  roles/lib_openshift/library/oc_clusterrole.py
  roles/lib_openshift/library/oc_configmap.py
  roles/lib_openshift/library/oc_env.py
  roles/lib_openshift/library/oc_group.py
  roles/lib_openshift/library/oc_image.py
  roles/lib_openshift/library/oc_label.py
  roles/lib_openshift/library/oc_obj.py
  roles/lib_openshift/library/oc_process.py
  roles/lib_openshift/library/oc_project.py
  roles/lib_openshift/library/oc_pvc.py
  roles/lib_openshift/library/oc_route.py
  roles/lib_openshift/library/oc_secret.py
  roles/lib_openshift/library/oc_service.py
  roles/lib_openshift/library/oc_serviceaccount.py
  roles/lib_openshift/library/oc_serviceaccount_secret.py
  roles/lib_openshift/library/oc_storageclass.py
  roles/lib_openshift/library/oc_user.py
  roles/lib_openshift/library/oc_version.py
  roles/lib_openshift/library/oc_volume.py
  roles/lib_openshift/src/doc/clusterrole
  roles/lib_openshift/src/doc/configmap
  roles/lib_openshift/src/doc/csr
  roles/lib_openshift/src/doc/env
  roles/lib_openshift/src/doc/group
  roles/lib_openshift/src/doc/image
  roles/lib_openshift/src/doc/label
  roles/lib_openshift/src/doc/obj
  roles/lib_openshift/src/doc/policy_group
  roles/lib_openshift/src/doc/policy_user
  roles/lib_openshift/src/doc/process
  roles/lib_openshift/src/doc/project
  roles/lib_openshift/src/doc/pvc
  roles/lib_openshift/src/doc/registry
  roles/lib_openshift/src/doc/route
  roles/lib_openshift/src/doc/router
  roles/lib_openshift/src/doc/secret
  roles/lib_openshift/src/doc/service
  roles/lib_openshift/src/doc/serviceaccount
  roles/lib_openshift/src/doc/serviceaccount_secret
  roles/lib_openshift/src/doc/storageclass
  roles/lib_openshift/src/doc/user
  roles/lib_openshift/src/doc/version
  roles/lib_openshift/src/doc/volume
Labels: approved, lgtm, ok-to-test, size/L

#11059 Fix 404 url ( bz1668210 ) for v3.2
  roles/openshift_master/templates/atomic-openshift-master.j2
  roles/openshift_master/templates/native-cluster/atomic-openshift-master-api.j2
  roles/openshift_master/templates/native-cluster/atomic-openshift-master-controllers.j2
Labels: size/XS

#11058 Fix 404 url ( bz1668210 ) for v3.3
  roles/openshift_master/templates/atomic-openshift-master.j2
  roles/openshift_master/templates/native-cluster/atomic-openshift-master-api.j2
  roles/openshift_master/templates/native-cluster/atomic-openshift-master-controllers.j2
Labels: size/XS

#11057 Fix 404 url ( bz1668210 ) for v3.4
  roles/openshift_master/templates/atomic-openshift-master.j2
  roles/openshift_master/templates/native-cluster/atomic-openshift-master-api.j2
  roles/openshift_master/templates/native-cluster/atomic-openshift-master-controllers.j2
Labels: size/XS

#11056 Fix 404 url ( bz1668210 ) for v3.5
  roles/openshift_master/templates/atomic-openshift-master.j2
  roles/openshift_master/templates/native-cluster/atomic-openshift-master-api.j2
  roles/openshift_master/templates/native-cluster/atomic-openshift-master-controllers.j2
Labels: size/XS

#11055 Fix 404 url ( bz1668210 ) for v3.6
  roles/openshift_master/templates/atomic-openshift-master.j2
  roles/openshift_master/templates/native-cluster/atomic-openshift-master-api.j2
  roles/openshift_master/templates/native-cluster/atomic-openshift-master-controllers.j2
Labels: size/XS

#11054 Fix 404 url ( bz1668210 ) for v3.7
  roles/openshift_master/templates/atomic-openshift-master.j2
  roles/openshift_master/templates/native-cluster/atomic-openshift-master-api.j2
  roles/openshift_master/templates/native-cluster/atomic-openshift-master-controllers.j2
Labels: size/XS

#11061 Fix sanity-check removed vars
  roles/lib_utils/action_plugins/sanity_checks.py
  roles/lib_utils/test/sanity_check_test.py
Labels: approved, lgtm, size/S

#11065 Revert "Enable cinder predicate by default"
  roles/lib_utils/lookup_plugins/openshift_master_facts_default_predicates.py
  roles/lib_utils/test/openshift_master_facts_default_predicates_tests.py
Labels: size/XS

#11026 Include namedcertificates in the list of expiration checks
  roles/lib_utils/library/openshift_cert_expiry.py
Labels: approved, lgtm, ok-to-test, size/XS

#11067 [release-3.10] update test/ci playbooks
  test/ci/launch.yml
Labels: approved, size/S

#11068 gluster: detect intent to deploy legacy OpenShift Container Storage
  roles/openshift_storage_glusterfs/tasks/glusterfs_deploy.yml
Labels: approved, lgtm, ok-to-test, size/XS

#11050 [release-3.10] Fix OpenShift SDN/OVS pod restart during upgrades
  playbooks/common/openshift-cluster/upgrades/v3_10/upgrade_control_plane.yml
  roles/openshift_node/tasks/upgrade.yml
  roles/openshift_sdn/files/sdn-ovs.yaml
  roles/openshift_sdn/files/sdn.yaml
  roles/openshift_sdn/meta/main.yaml
  roles/openshift_sdn/tasks/update_daemonset.yml
  roles/openshift_sdn/tasks/update_daemonsets.yml
Labels: approved, do-not-merge/hold, lgtm, size/M

#11052 openshift_node: open the router stats port by default
  roles/openshift_node/defaults/main.yml
Labels: approved, lgtm, size/XS

#11071 Fixed "AnsibleUndefinedVariable" error for missing annotations
  roles/openshift_persistent_volumes/templates/persistent-volume-claim.yml.j2
  roles/openshift_persistent_volumes/templates/persistent-volume.yml.j2
Labels: approved, lgtm, ok-to-test, size/XS

#11072 Pull heketi admin key from deploymentconfig object
  roles/openshift_storage_glusterfs/tasks/heketi_get_key.yml
Labels: approved, lgtm, ok-to-test, size/S

#11062 Fix sanity-check removed vars
  roles/lib_utils/action_plugins/sanity_checks.py
  roles/lib_utils/test/sanity_check_test.py
Labels: approved, lgtm, size/S

#11073 Add newlines when concatenating router certificate
  roles/lib_openshift/library/oc_adm_router.py
  roles/lib_openshift/src/class/oc_adm_router.py
Labels: approved, lgtm, size/S

#11010 Add new team members to OWNERS file.
  OWNERS
Labels: approved, size/XS

#11064 Add openshift_cloud_provider config for subnetwork-name
  roles/openshift_cloud_provider/defaults/main.yml
  roles/openshift_cloud_provider/tasks/gce.yml
Labels: approved, lgtm, ok-to-test, size/S

#11079 Maintain etcd as owner of certs.
  roles/etcd/tasks/certificates/fetch_server_certificates_from_ca.yml
Labels: approved, lgtm, size/S

#11076 Add EAP 7.2.0.GA imagestreams and templates
  roles/openshift_examples/files/examples/x86_64/xpaas-streams/eap72-image-stream.json
  roles/openshift_examples/files/examples/x86_64/xpaas-templates/eap72-amq-persistent-s2i.json
  roles/openshift_examples/files/examples/x86_64/xpaas-templates/eap72-amq-s2i.json
  roles/openshift_examples/files/examples/x86_64/xpaas-templates/eap72-basic-s2i.json
  roles/openshift_examples/files/examples/x86_64/xpaas-templates/eap72-https-s2i.json
  roles/openshift_examples/files/examples/x86_64/xpaas-templates/eap72-mongodb-persistent-s2i.json
  roles/openshift_examples/files/examples/x86_64/xpaas-templates/eap72-mongodb-s2i.json
  roles/openshift_examples/files/examples/x86_64/xpaas-templates/eap72-mysql-persistent-s2i.json
  roles/openshift_examples/files/examples/x86_64/xpaas-templates/eap72-mysql-s2i.json
  roles/openshift_examples/files/examples/x86_64/xpaas-templates/eap72-postgresql-persistent-s2i.json
  roles/openshift_examples/files/examples/x86_64/xpaas-templates/eap72-postgresql-s2i.json
  roles/openshift_examples/files/examples/x86_64/xpaas-templates/eap72-sso-s2i.json
  roles/openshift_examples/files/examples/x86_64/xpaas-templates/eap72-starter-s2i.json
  roles/openshift_examples/files/examples/x86_64/xpaas-templates/eap72-third-party-db-s2i.json
  roles/openshift_examples/files/examples/x86_64/xpaas-templates/eap72-tx-recovery-s2i.json
Labels: approved, lgtm, ok-to-test, size/XXL

#11087 Add additional gluster SMEs to approvers, update ansible reviewers
  playbooks/openshift-glusterfs/OWNERS
  roles/openshift_storage_glusterfs/OWNERS
Labels: approved, size/S

#11089 Bug 1651632 - Force console rollout every time the playbook runs
  roles/openshift_console/files/console-template.yaml
Labels: approved, lgtm, size/XS

#11088 [KIECLOUD-71] - Update PAM and DM templates on OpenShift for 7.2.0
  roles/openshift_examples/examples-sync.sh
  roles/openshift_examples/files/examples/x86_64/xpaas-streams/rhdm72-image-streams.yaml
  roles/openshift_examples/files/examples/x86_64/xpaas-streams/rhpam72-image-streams.yaml
  roles/openshift_examples/files/examples/x86_64/xpaas-templates/rhdm72-authoring-ha.yaml
  roles/openshift_examples/files/examples/x86_64/xpaas-templates/rhdm72-authoring.yaml
  roles/openshift_examples/files/examples/x86_64/xpaas-templates/rhdm72-kieserver.yaml
  roles/openshift_examples/files/examples/x86_64/xpaas-templates/rhdm72-optaweb-employee-rostering-trial-ephemeral.yaml
  roles/openshift_examples/files/examples/x86_64/xpaas-templates/rhdm72-prod-immutable-kieserver.yaml
  roles/openshift_examples/files/examples/x86_64/xpaas-templates/rhdm72-trial-ephemeral.yaml
  roles/openshift_examples/files/examples/x86_64/xpaas-templates/rhpam72-authoring-ha.yaml
  roles/openshift_examples/files/examples/x86_64/xpaas-templates/rhpam72-authoring.yaml
  roles/openshift_examples/files/examples/x86_64/xpaas-templates/rhpam72-kieserver-externaldb.yaml
  roles/openshift_examples/files/examples/x86_64/xpaas-templates/rhpam72-kieserver-mysql.yaml
  roles/openshift_examples/files/examples/x86_64/xpaas-templates/rhpam72-kieserver-postgresql.yaml
  roles/openshift_examples/files/examples/x86_64/xpaas-templates/rhpam72-prod-immutable-kieserver.yaml
  roles/openshift_examples/files/examples/x86_64/xpaas-templates/rhpam72-prod-immutable-monitor.yaml
  roles/openshift_examples/files/examples/x86_64/xpaas-templates/rhpam72-prod.yaml
  roles/openshift_examples/files/examples/x86_64/xpaas-templates/rhpam72-trial-ephemeral.yaml
Labels: approved, lgtm, needs-ok-to-test, size/XXL

#11085 gluster: add HEKETI_DEBUG_UMOUNT_FAILURES environment variable for extra debugging
  roles/openshift_storage_glusterfs/files/heketi-template.yml
Labels: approved, lgtm, size/XS

#11075 [release-3.11] Fix OpenShift SDN/OVS pod restart during upgrades
  playbooks/common/openshift-cluster/upgrades/upgrade_nodes.yml
  playbooks/common/openshift-cluster/upgrades/v3_11/upgrade_control_plane_part2.yml
  roles/openshift_node/tasks/upgrade.yml
  roles/openshift_sdn/files/sdn-ovs.yaml
  roles/openshift_sdn/files/sdn.yaml
  roles/openshift_sdn/meta/main.yaml
  roles/openshift_sdn/tasks/main.yml
  roles/openshift_sdn/tasks/update_daemonset.yml
  roles/openshift_sdn/tasks/update_daemonsets.yml
Labels: approved, lgtm, size/L

#11078 Allow disable of MERGE_JSON_LOG
  roles/openshift_logging_fluentd/defaults/main.yml
  roles/openshift_logging_fluentd/templates/5.x/fluentd.j2
Labels: approved, lgtm, size/XS

#10985 Scale up workers in CI runs
  inventory/dynamic/aws/ansible.cfg
  inventory/dynamic/aws/group_vars/all/00_defaults.yml
  inventory/dynamic/aws/inventory
  playbooks/openshift-node/scaleup.yml
  roles/openshift_facts/defaults/main.yml
  roles/openshift_gcp/tasks/setup_scale_group_facts.yml
  test/aws/README.md
  test/aws/create_machineset.yml
  test/aws/deprovision.yml
  test/aws/get_machinesets.yml
  test/aws/inventory/group_vars/OSEv3/vars.yml
  test/aws/launch.yml
  test/aws/scaleup.yml
  test/aws/template-inventory.j2
  test/aws/vars.yml.sample
  test/gcp/launch.yml
Labels: approved, lgtm, size/XL

#10336 [3.10] Node problem detector always pull images from registry.redhat.io for openshift-enterprise
  roles/openshift_node_problem_detector/defaults/main.yaml
  roles/openshift_node_problem_detector/templates/node-problem-detector-daemonset.yaml.j2
Labels: approved, lgtm, size/S

#11095 openshift_node: open the router stats port by default
  roles/openshift_node/defaults/main.yml
Labels: approved, lgtm, size/XS

#8890 [3.9] oc_storageclass: support mountOptions and reclaimPolicy
  inventory/hosts.example
  roles/lib_openshift/library/oc_storageclass.py
  roles/lib_openshift/src/ansible/oc_storageclass.py
  roles/lib_openshift/src/class/oc_storageclass.py
  roles/lib_openshift/src/doc/storageclass
  roles/lib_openshift/src/lib/storageclass.py
  roles/lib_openshift/src/test/integration/oc_storageclass.yml
  roles/lib_openshift/src/test/unit/test_oc_storageclass.py
  roles/openshift_default_storage_class/defaults/main.yml
  roles/openshift_default_storage_class/tasks/azure.yml
  roles/openshift_default_storage_class/tasks/main.yml
Labels: approved, lgtm, size/L

#11100 Update router service when its annotation changes
  roles/lib_openshift/library/oc_adm_router.py
  roles/lib_openshift/src/class/oc_adm_router.py
  roles/lib_openshift/src/test/unit/test_oc_adm_router.py
Labels: approved, lgtm, size/L

#11081 multipath: add hardware_handler for LIO-ORG (gluster-block) config
  roles/openshift_node/templates/multipath.conf.j2
Labels: approved, lgtm, size/XS

#11092 [3.10] Start node image prepull after CRIO is restarted
  roles/openshift_node/tasks/main.yml
Labels: approved, lgtm, size/S

#11045 [devel-40] Add openshift_bootstrap_endpoint for scaleup.
  playbooks/deploy_cluster_40.yml
  playbooks/init/basic_facts.yml
  playbooks/openshift-node/scaleup.yml
Labels: approved, lgtm, size/M

#11104 [release-3.11] Remove docker-common in uninstall
  playbooks/adhoc/uninstall_docker.yml
Labels: approved, lgtm, size/XS
