Repository openshift/openshift-ansible, pull requests merged in 2019-02, with the labels that each got.

#11105 [release-3.11] Remove hard coded gather_timeout in openshift_facts
  roles/openshift_facts/library/openshift_facts.py
Labels: approved, lgtm, size/XS

#11101 [3.11] Added liveness probes to apiserver template
  roles/template_service_broker/files/apiserver-template.yaml
Labels: approved, lgtm, ok-to-test, size/S

#11112 Fixes idempotency on update of service in oc_service
  roles/lib_openshift/library/oc_service.py
  roles/lib_openshift/src/class/oc_service.py
Labels: approved, lgtm, size/XS

#11110 Fixing incorrect indentation for cns-secgrp in heat template
  roles/openshift_openstack/templates/heat_stack.yaml.j2
Labels: approved, lgtm, size/XS

#11099 Create contrail-system namespace and nodeselector changes
  roles/contrail_controller/tasks/os_contrail_master.yaml
  roles/contrail_controller/templates/contrail-agent-installer-5.j2
  roles/contrail_controller/templates/contrail-controller-installer-5.j2
  roles/contrail_controller/templates/contrail-image-downloader-5.j2
  roles/contrail_controller/templates/contrail-infra-installer-5.j2
  roles/contrail_controller/templates/contrail-installer-4.j2
  roles/contrail_controller/templates/contrail-installer-5.1.j2
  roles/contrail_controller/templates/contrail-namespace.j2
  roles/contrail_controller/templates/contrail-nested.j2
  roles/contrail_controller/templates/wait_for_pod.j2
  roles/contrail_node/tasks/etcd_certs.yaml
  roles/contrail_node/tasks/main.yaml
Labels: approved, lgtm, ok-to-test, size/XXL

#11106 [releaes-3.9] Pass possible string through bool filter
  playbooks/openshift-master/private/templates/openshift-ansible-catalog-console.js
Labels: approved, lgtm, size/XS

#11107 [release-3.7] Pass possible strings through bool filter
  playbooks/common/openshift-master/tasks/wire_aggregator.yml
  playbooks/common/openshift-master/templates/openshift-ansible-catalog-console.js
Labels: approved, lgtm, size/XS

#11094 cert expiry: cert subject can contain unicode
  roles/lib_utils/library/openshift_cert_expiry.py
Labels: approved, lgtm, size/XS

#11108 Remove condition for pre-pulling container images.
  roles/contiv/tasks/aci.yml
  roles/etcd/tasks/static.yml
  roles/openshift_control_plane/tasks/pre_pull.yml
  roles/openshift_control_plane/tasks/pre_pull_poll.yml
  roles/openshift_node/tasks/prepull.yml
  roles/openshift_node/tasks/prepull_check.yml
Labels: approved, lgtm, size/M

#11136 GlusterFS: Implement container image version check
  roles/openshift_storage_glusterfs/tasks/glusterfs_common.yml
  roles/openshift_storage_glusterfs/tasks/version_check.yml
Labels: approved, lgtm, size/S

#11116 ovs process gets killed when oom-killer is invoked
  roles/openshift_sdn/files/sdn-ovs.yaml
Labels: approved, lgtm, size/S

#11133 [release-3.11] Run nsx role on the first master only
  playbooks/openshift-master/private/config.yml
  roles/nsx/defaults/main.yml
  roles/nsx/templates/ncp-rc.yml.j2
  roles/nsx/templates/nsx-node-agent-ds.yml.j2
Labels: approved, lgtm, ok-to-test, size/S

#11138 GlusterFS: Keep logs on uninstall
  roles/openshift_storage_glusterfs/tasks/glusterfs_uninstall.yml
Labels: approved, lgtm, size/XS

#11131 Check for changes to volume-config in sync pod.
  roles/openshift_node_group/files/sync.yaml
Labels: approved, lgtm, size/S

#11114 [BZ1665835] - jboss image streams do not have referencePolicy.type se…
  roles/openshift_examples/files/examples/x86_64/xpaas-streams/rhpam70-image-streams.yaml
Labels: approved, lgtm, ok-to-test, size/L

#11151 Ensure async etcd-image-pull job exists before checking status.
  roles/openshift_control_plane/tasks/pre_pull_poll.yml
Labels: approved, lgtm, size/XS

#11150 ovs process gets killed when oom-killer is invoked
  roles/openshift_sdn/files/sdn-ovs.yaml
Labels: approved, lgtm, size/S

#11156 Open up tcp/udp DNS port 53
  roles/openshift_node/defaults/main.yml
Labels: approved, lgtm, ok-to-test, size/XS

#11162 Add init facts step for html_and_json_timestamp.yaml
  playbooks/openshift-checks/certificate_expiry/html_and_json_timestamp.yaml
Labels: approved, lgtm, size/XS

#11140 test/aws: wait for machinesets to be registered
  test/aws/create_machineset.yml
  test/aws/get_machinesets.yml
  test/aws/scaleup.yml
Labels: approved, lgtm, size/S

#10724 GlusterFS: Recreate config directories for external uninstall
  roles/openshift_storage_glusterfs/tasks/glusterfs_uninstall.yml
Labels: approved, lgtm, size/M

#11144 Templates for CloudForms 4.7
  roles/openshift_management/files/templates/cloudforms/cfme-backup-job.yaml
  roles/openshift_management/files/templates/cloudforms/cfme-restore-job.yaml
  roles/openshift_management/files/templates/cloudforms/cfme-template-ext-db.yaml
  roles/openshift_management/files/templates/cloudforms/cfme-template.yaml
  roles/openshift_management/files/templates/cloudforms/httpd-configmap-generator-template.yaml
Labels: approved, lgtm, ok-to-test, size/XL

#11161 Fix gluster deploy checks
  roles/openshift_storage_glusterfs/tasks/glusterfs_deploy.yml
Labels: approved, lgtm, ok-to-test, size/XS

#11166 Remove cfme templates from openshift_examples directory
  roles/openshift_examples/files/examples/x86_64/cfme-templates/cfme-backup-job.yaml
  roles/openshift_examples/files/examples/x86_64/cfme-templates/cfme-backup-pvc.yaml
  roles/openshift_examples/files/examples/x86_64/cfme-templates/cfme-pv-backup-example.yaml
  roles/openshift_examples/files/examples/x86_64/cfme-templates/cfme-pv-db-example.yaml
  roles/openshift_examples/files/examples/x86_64/cfme-templates/cfme-pv-server-example.yaml
  roles/openshift_examples/files/examples/x86_64/cfme-templates/cfme-restore-job.yaml
  roles/openshift_examples/files/examples/x86_64/cfme-templates/cfme-scc-sysadmin.yaml
  roles/openshift_examples/files/examples/x86_64/cfme-templates/cfme-template-ext-db.yaml
  roles/openshift_examples/files/examples/x86_64/cfme-templates/cfme-template.yaml
  roles/openshift_examples/files/examples/x86_64/cfme-templates/httpd-configmap-generator-template.yaml
  roles/openshift_examples/files/examples/x86_64/cfme-templates/httpd-scc-sysadmin.yaml
  roles/openshift_examples/files/examples/x86_64/cfme-templates/jboss-middleware-manager-pv-example.yaml
  roles/openshift_examples/files/examples/x86_64/cfme-templates/jboss-middleware-manager-template.yaml
Labels: approved, lgtm, needs-ok-to-test, size/XXL

#11165 bug 1668338. Fix the correct ds template
  roles/openshift_logging_fluentd/templates/2.x/fluentd.j2
Labels: affects_3.10, affects_3.9, approved, lgtm, size/XS

#11155 set permissions on vsphere.conf file
  roles/openshift_cloud_provider/tasks/vsphere.yml
Labels: approved, lgtm, needs-ok-to-test, size/XS

#10993 Back port override of logging ES image pull secret to release v3.9
  roles/openshift_logging_elasticsearch/defaults/main.yml
  roles/openshift_logging_elasticsearch/tasks/main.yaml
Labels: lgtm, ok-to-test, size/S

#11009 Fix ansible groups to prevent unlabeling non-openshift nodes from inventory
  roles/openshift_storage_glusterfs/tasks/glusterfs_deploy.yml
Labels: lgtm, ok-to-test, size/XS

#11163 Ignore paths in `etcd-servers-overrides`
  roles/lib_utils/action_plugins/master_check_paths_in_config.py
  roles/lib_utils/test/test_master_check_paths_in_config.py
Labels: approved, lgtm, size/S

#11154 scaleup: new namespace for machinesets
  test/aws/create_machineset.yml
  test/aws/get_machinesets.yml
  test/aws/scaleup.yml
Labels: approved, lgtm, size/XS

#11178 [release-3.9] Allow to configure BlockStorage.ignore-volume-az for Openstack Cloud Provider
  roles/openshift_cloud_provider/defaults/main.yml
  roles/openshift_cloud_provider/templates/openstack.conf.j2
Labels: approved, lgtm, size/XS

#11179 azure: pull RPMs from CDN
  playbooks/azure/openshift-cluster/group_vars/all/yum_repos.yml
Labels: approved, lgtm, size/S

#11176 [release-3.11] openshift_node: use init_file to replace journald.conf settings
  roles/openshift_node/tasks/journald.yml
Labels: approved, lgtm, size/S

#11187 Removing SystemKeepFree to use default value
  roles/openshift_node/defaults/main.yml
Labels: approved, lgtm, size/XS

#11186 [release-3.11] Run firewall task on upgrades
  roles/openshift_node/tasks/upgrade.yml
Labels: approved, lgtm, size/XS

#11192 [KIECLOUD-112] - Update RHPAM/DM templates on OpenShift Service Catal…
  roles/openshift_examples/examples-sync.sh
  roles/openshift_examples/files/examples/x86_64/xpaas-streams/rhdm72-image-streams.yaml
  roles/openshift_examples/files/examples/x86_64/xpaas-streams/rhpam72-image-streams.yaml
  roles/openshift_examples/files/examples/x86_64/xpaas-templates/rhdm72-authoring-ha.yaml
  roles/openshift_examples/files/examples/x86_64/xpaas-templates/rhdm72-authoring.yaml
  roles/openshift_examples/files/examples/x86_64/xpaas-templates/rhdm72-kieserver.yaml
  roles/openshift_examples/files/examples/x86_64/xpaas-templates/rhdm72-optaweb-employee-rostering-trial-ephemeral.yaml
  roles/openshift_examples/files/examples/x86_64/xpaas-templates/rhdm72-prod-immutable-kieserver.yaml
  roles/openshift_examples/files/examples/x86_64/xpaas-templates/rhdm72-trial-ephemeral.yaml
  roles/openshift_examples/files/examples/x86_64/xpaas-templates/rhpam72-authoring-ha.yaml
  roles/openshift_examples/files/examples/x86_64/xpaas-templates/rhpam72-authoring.yaml
  roles/openshift_examples/files/examples/x86_64/xpaas-templates/rhpam72-kieserver-externaldb.yaml
  roles/openshift_examples/files/examples/x86_64/xpaas-templates/rhpam72-kieserver-mysql.yaml
  roles/openshift_examples/files/examples/x86_64/xpaas-templates/rhpam72-kieserver-postgresql.yaml
  roles/openshift_examples/files/examples/x86_64/xpaas-templates/rhpam72-prod-immutable-kieserver.yaml
  roles/openshift_examples/files/examples/x86_64/xpaas-templates/rhpam72-prod-immutable-monitor.yaml
  roles/openshift_examples/files/examples/x86_64/xpaas-templates/rhpam72-prod.yaml
  roles/openshift_examples/files/examples/x86_64/xpaas-templates/rhpam72-trial-ephemeral.yaml
Labels: approved, lgtm, ok-to-test, size/L

#11198 azure: fix typo in repo
  playbooks/azure/openshift-cluster/group_vars/all/yum_repos.yml
Labels: approved, lgtm, size/XS

#11205 [Release-3.7] Configure API aggregation in serial
  playbooks/common/openshift-cluster/upgrades/v3_7/upgrade_control_plane.yml
Labels: approved, lgtm, size/XS

#11199 [release-3.11] Correct regressions of Curator5 template file
  roles/openshift_logging_curator/templates/curator-cj.j2
Labels: approved, lgtm, ok-to-test, size/XS

#11143 Protect from dangerous etcd_image changes
  roles/etcd/defaults/main.yaml
  roles/etcd/tasks/static.yml
Labels: approved, lgtm, size/S

#11160 [release-3.11] Make same timezone with running hosts
  roles/etcd/files/etcd.yaml
  roles/openshift_control_plane/files/apiserver.yaml
  roles/openshift_control_plane/files/controller.yaml
Labels: approved, lgtm, needs-ok-to-test, size/S

#11207 Bug 1672847. Corrected KUBERNETES_TRUST_CERTIFICATES reference.
  roles/openshift_logging_elasticsearch/templates/es.j2
Labels: affects_3.10, affects_3.9, approved, lgtm, size/XS

#11212 Fix https://bugzilla.redhat.com/show_bug.cgi?id=1678442
  roles/openshift_logging_elasticsearch/templates/2.x/es.j2
Labels: approved, lgtm, size/XS

#11203 crio 1.12 and ssh-bastion in a pod
  inventory/dynamic/aws/ansible.cfg
  inventory/dynamic/gcp/group_vars/all/00_defaults.yml
  playbooks/init/basic_facts.yml
  roles/container_runtime/tasks/package_crio.yml
  roles/container_runtime/templates/crio.conf.j2
  roles/lib_openshift/library/oc_adm_ca_server_cert.py
  roles/lib_openshift/library/oc_adm_csr.py
  roles/lib_openshift/library/oc_adm_manage_node.py
  roles/lib_openshift/library/oc_adm_policy_group.py
  roles/lib_openshift/library/oc_adm_policy_user.py
  roles/lib_openshift/library/oc_adm_registry.py
  roles/lib_openshift/library/oc_adm_router.py
  roles/lib_openshift/library/oc_clusterrole.py
  roles/lib_openshift/library/oc_configmap.py
  roles/lib_openshift/library/oc_edit.py
  roles/lib_openshift/library/oc_env.py
  roles/lib_openshift/library/oc_group.py
  roles/lib_openshift/library/oc_image.py
  roles/lib_openshift/library/oc_label.py
  roles/lib_openshift/library/oc_obj.py
  roles/lib_openshift/library/oc_objectvalidator.py
  roles/lib_openshift/library/oc_process.py
  roles/lib_openshift/library/oc_project.py
  roles/lib_openshift/library/oc_pvc.py
  roles/lib_openshift/library/oc_route.py
  roles/lib_openshift/library/oc_scale.py
  roles/lib_openshift/library/oc_secret.py
  roles/lib_openshift/library/oc_service.py
  roles/lib_openshift/library/oc_serviceaccount.py
  roles/lib_openshift/library/oc_serviceaccount_secret.py
  roles/lib_openshift/library/oc_storageclass.py
  roles/lib_openshift/library/oc_user.py
  roles/lib_openshift/library/oc_version.py
  roles/lib_openshift/library/oc_volume.py
  roles/lib_openshift/src/lib/base.py
  test/aws/create_machineset.yml
  test/aws/files/01_service.yml
  test/aws/files/02_serviceaccount.yml
  test/aws/files/03_role.yml
  test/aws/files/04_rolebinding.yml
  test/aws/files/05_clusterrole.yml
  test/aws/files/06_clusterrolebinding.yml
  test/aws/files/07_deployment.yml
  test/aws/files/sshd_config
  test/aws/get_machinesets.yml
  test/aws/scaleup.yml
  test/aws/ssh_bastion.yml
  test/gcp/launch.yml
Labels: approved, lgtm, size/XL

#11208 Uninstall no longer unmounts openshift.local.volumes
  playbooks/adhoc/uninstall_openshift.yml
Labels: approved, lgtm, size/XS

#11218 Switch manage-node to cordon
  test/aws/scaleup.yml
Labels: approved, lgtm, size/XS

#11220 [release-3.11] kibana, curator ops false; wait for es deploy
  roles/openshift_logging/tasks/install_logging.yaml
  roles/openshift_logging_elasticsearch/tasks/restart_es_node.yml
Labels: approved, lgtm, size/S

#11222 Ensure dns records are available when deleting the stack
  playbooks/openstack/openshift-cluster/uninstall.yml
Labels: approved, lgtm, size/S

#11153 Copy multipath.conf file only if target does not exists.
  roles/openshift_node/tasks/storage_plugins/iscsi.yml
  roles/openshift_node/templates/multipath.conf.j2
Labels: approved, lgtm, size/M

#11230 Fix OpenShiftSDN case
  inventory/install-config-example.yml
  test/libvirt/install-config.yml.template
Labels: approved, lgtm, size/XS

#11211 Revert "[release-3.11] Correct regressions of Curator5 template file"
  roles/openshift_logging_curator/templates/curator-cj.j2
Labels: approved, lgtm, size/XS

#11225 Complete requirements for persistent storage azure backend
  playbooks/azure/openshift-cluster/build_node_image.yml
  roles/openshift_node/defaults/main.yml
Labels: approved, lgtm, size/XS

#11233 test/ci: remove SG using `ec2_group`
  test/ci/deprovision.yml
  test/ci/launch.yml
Labels: approved, lgtm, size/S

#11226 Uninstall: delete all cri-o containers.
  playbooks/adhoc/uninstall_openshift.yml
Labels: approved, lgtm, size/XS

#11238 Update OWNERS file.
  OWNERS
Labels: approved, size/XS

#10958 Use MCO --once-from instead of custom ansible module
  playbooks/deploy_cluster_40.yml
  playbooks/init/base_packages.yml
  playbooks/openshift-node/scaleup.yml
  roles/lib_utils/action_plugins/parse_ignition.py
  roles/lib_utils/test/test_parse_ignition.py
  roles/openshift_node40/defaults/main.yml
  roles/openshift_node40/tasks/config.yml
  roles/openshift_node40/tasks/create_files_from_ignition.yml
  roles/openshift_node40/tasks/systemd.yml
Labels: approved, lgtm, size/L

#11196 Deprecate installer_checkpoint
  playbooks/init/main.yml
  roles/installer_checkpoint/README.md
  roles/installer_checkpoint/callback_plugins/installer_checkpoint.py
Labels: approved, lgtm, size/L

#11231 [release-3.11] Remove deprecated "openshift_logging_curator_run_timezone variable"
  roles/openshift_logging/README.md
  roles/openshift_logging/defaults/main.yml
  roles/openshift_logging/tasks/install_logging.yaml
  roles/openshift_logging/tasks/set_defaults_from_current.yml
  roles/openshift_logging_curator/defaults/main.yml
Labels: approved, lgtm, ok-to-test, size/XS

#11236 ssh_bastion: retry until ingress details appear in ssh bastion svc
  test/aws/ssh_bastion.yml
Labels: approved, lgtm, size/XS

#11195 Deprecate openshift_sanitize_inventory
  playbooks/init/basic_facts.yml
  roles/openshift_sanitize_inventory/README.md
  roles/openshift_sanitize_inventory/action_plugins/check_deprecated.py
  roles/openshift_sanitize_inventory/filter_plugins/openshift_sanitize_inventory.py
  roles/openshift_sanitize_inventory/meta/main.yml
  roles/openshift_sanitize_inventory/tasks/__deprecations_logging.yml
  roles/openshift_sanitize_inventory/tasks/deprecations.yml
  roles/openshift_sanitize_inventory/tasks/main.yml
  roles/openshift_sanitize_inventory/tasks/unsupported.yml
  roles/openshift_sanitize_inventory/vars/main.yml
Labels: approved, lgtm, size/L

#11197 Clean up lib_utils
  roles/lib_utils/action_plugins/generate_pv_pvcs_list.py
  roles/lib_utils/action_plugins/master_check_paths_in_config.py
  roles/lib_utils/action_plugins/node_group_checks.py
  roles/lib_utils/action_plugins/sanity_checks.py
  roles/lib_utils/filter_plugins/oo_cert_expiry.py
  roles/lib_utils/filter_plugins/oo_filters.py
  roles/lib_utils/filter_plugins/openshift_aws_filters.py
  roles/lib_utils/filter_plugins/openshift_hosted_filters.py
  roles/lib_utils/filter_plugins/openshift_master.py
  roles/lib_utils/library/delegated_serial_command.py
  roles/lib_utils/library/get_current_openshift_version.py
  roles/lib_utils/library/glusterfs_check_containerized.py
  roles/lib_utils/library/kubeclient_ca.py
  roles/lib_utils/library/modify_yaml.py
  roles/lib_utils/library/oo_iam_kms.py
  roles/lib_utils/library/openshift_cert_expiry.py
  roles/lib_utils/library/repoquery.py
  roles/lib_utils/lookup_plugins/openshift_master_facts_default_predicates.py
  roles/lib_utils/lookup_plugins/openshift_master_facts_default_priorities.py
  roles/lib_utils/src/ansible/repoquery.py
  roles/lib_utils/src/class/repoquery.py
  roles/lib_utils/src/doc/repoquery
  roles/lib_utils/src/lib/repoquery.py
  roles/lib_utils/src/sources.yml
  roles/lib_utils/src/test/integration/repoquery.yml
  roles/lib_utils/src/test/unit/test_repoquery.py
  roles/lib_utils/test/conftest.py
  roles/lib_utils/test/openshift_master_facts_bad_input_tests.py
  roles/lib_utils/test/openshift_master_facts_conftest.py
  roles/lib_utils/test/openshift_master_facts_default_predicates_tests.py
  roles/lib_utils/test/openshift_master_facts_default_priorities_tests.py
  roles/lib_utils/test/sanity_check_test.py
  roles/lib_utils/test/test_fakeopensslclasses.py
  roles/lib_utils/test/test_glusterfs_check_containerized.py
  roles/lib_utils/test/test_load_and_handle_cert.py
  roles/lib_utils/test/test_master_check_paths_in_config.py
  roles/lib_utils/test/test_oo_filters.py
  roles/lib_utils/test/test_sanity_checks.py
  test/unit/modify_yaml_tests.py
Labels: approved, lgtm, size/XXL

#11245 [devel-40] Get current release image from cluster version object
  playbooks/openshift-node/scaleup.yml
Labels: approved, lgtm, size/M

#11243 Run MCD task asynchronously
  roles/openshift_node40/tasks/config.yml
Labels: approved, lgtm, size/S

#11253 Handle null values and multiple certs when checking namedCertificate expirys.
  roles/lib_utils/library/openshift_cert_expiry.py
Labels: approved, lgtm, size/XS

#11246 Fix console certs after master cert redeploy
  playbooks/openshift-master/redeploy-certificates.yml
  playbooks/openshift-web-console/redeploy-certificates.yml
Labels: approved, lgtm, size/XS
