Repository openshift/openshift-ansible, pull requests merged in 2019-05, with the labels that each got.

#11568 Fix typo in Cisco ACI roles
  roles/aci/tasks/firewall.yml
Labels: approved, lgtm, ok-to-test, size/XS

#11565 Fix container registry block all not blocking all registries
  roles/container_runtime/defaults/main.yml
  roles/container_runtime/tasks/common/pre.yml
  roles/container_runtime/tasks/package_docker.yml
Labels: approved, lgtm, size/S

#11578 Remove myself from OWNERS due to pending absence
  OWNERS
Labels: approved, lgtm, size/XS

#11579 Remove myself from OWNERS due to pending absence
  OWNERS
Labels: approved, lgtm, size/XS

#11588 GlusterFS: Various upgrade playbook fixes
  roles/lib_utils/library/glusterfs_check_containerized.py
  roles/lib_utils/test/test_glusterfs_check_containerized.py
  roles/openshift_storage_glusterfs/tasks/cluster_health.yml
  roles/openshift_storage_glusterfs/tasks/glusterfs_restart_pod.yml
  roles/openshift_storage_glusterfs/tasks/glusterfs_upgrade.yml
  roles/openshift_storage_glusterfs/tasks/heketi_db_backup.yml
Labels: approved, lgtm, size/L

#11592 [release-3.11] Remove bash debug flag from 99-origin-dns.sh script
  roles/openshift_node/files/networkmanager/99-origin-dns.sh
Labels: approved, lgtm, size/XS

#11584 [release-3.11] BZ1702544 - Elasticsearch failed to start due to invalid cert date if…
  roles/openshift_logging/files/generate-jks.sh
Labels: approved, lgtm, size/XS

#11596 Update specfile requirements
  images/installer/Dockerfile
  openshift-ansible.spec
Labels: approved, lgtm, size/S

#11582 [release-3.10] Fix container registry block all not blocking all registries
  roles/container_runtime/defaults/main.yml
  roles/container_runtime/tasks/common/pre.yml
Labels: approved, lgtm, size/XS

#11599 metrics-server: Add node selector variable
  roles/metrics_server/defaults/main.yaml
  roles/metrics_server/templates/metrics-server-deployment.j2
Labels: approved, lgtm, size/XS

#11598 Fix openshift_kube_config_path defaults
  playbooks/upgrade.yml
  roles/openshift_node/defaults/main.yml
  roles/openshift_node/tasks/config.yml
  roles/openshift_node/tasks/upgrade.yml
Labels: approved, lgtm, size/L

#11157 Volume quota refactor bz 1669555
  roles/openshift_node_group/files/sync.yaml
Labels: approved, lgtm, size/M

#11604 Update patch_configmap_file.yaml
  roles/openshift_logging/tasks/patch_configmap_file.yaml
Labels: approved, lgtm, needs-ok-to-test, size/XS

#11606 GlusterFS: Fix brick capacity detection in health check
  roles/lib_utils/library/glusterfs_check_containerized.py
Labels: approved, lgtm, size/S

#11602 [release-3.9] Add a condition not to add "compute" label badly when master scaleup.yml
  roles/openshift_manage_node/tasks/set_default_node_role.yml
Labels: approved, lgtm, needs-ok-to-test, size/XS

#11609 openshift_node: always check for missing TCMU iSCSI device entry
  roles/openshift_node/tasks/storage_plugin_iscsi.yml
Labels: approved, lgtm, size/XS

#11611 [KIECLOUD-214] - Update RHDM and RHPAM 7.3.1 templates on OCP and OSO…
  roles/openshift_examples/examples-sync.sh
  roles/openshift_examples/files/examples/x86_64/xpaas-streams/rhdm73-image-streams.yaml
  roles/openshift_examples/files/examples/x86_64/xpaas-streams/rhpam73-image-streams.yaml
  roles/openshift_examples/files/examples/x86_64/xpaas-templates/rhdm73-authoring-ha.yaml
  roles/openshift_examples/files/examples/x86_64/xpaas-templates/rhdm73-authoring.yaml
  roles/openshift_examples/files/examples/x86_64/xpaas-templates/rhdm73-kieserver.yaml
  roles/openshift_examples/files/examples/x86_64/xpaas-templates/rhdm73-optaweb-employee-rostering.yaml
  roles/openshift_examples/files/examples/x86_64/xpaas-templates/rhdm73-prod-immutable-kieserver.yaml
  roles/openshift_examples/files/examples/x86_64/xpaas-templates/rhdm73-trial-ephemeral.yaml
  roles/openshift_examples/files/examples/x86_64/xpaas-templates/rhpam73-authoring-ha.yaml
  roles/openshift_examples/files/examples/x86_64/xpaas-templates/rhpam73-authoring.yaml
  roles/openshift_examples/files/examples/x86_64/xpaas-templates/rhpam73-kieserver-externaldb.yaml
  roles/openshift_examples/files/examples/x86_64/xpaas-templates/rhpam73-kieserver-mysql.yaml
  roles/openshift_examples/files/examples/x86_64/xpaas-templates/rhpam73-kieserver-postgresql.yaml
  roles/openshift_examples/files/examples/x86_64/xpaas-templates/rhpam73-managed.yaml
  roles/openshift_examples/files/examples/x86_64/xpaas-templates/rhpam73-prod-immutable-kieserver.yaml
  roles/openshift_examples/files/examples/x86_64/xpaas-templates/rhpam73-prod-immutable-monitor.yaml
  roles/openshift_examples/files/examples/x86_64/xpaas-templates/rhpam73-prod.yaml
  roles/openshift_examples/files/examples/x86_64/xpaas-templates/rhpam73-trial-ephemeral.yaml
Labels: approved, lgtm

#11615 Bug 1710226: [release-4.1] RHEL upgrade: use API to get ignition from machine config
  roles/openshift_node/tasks/apply_machine_config.yml
  roles/openshift_node/tasks/upgrade.yml
Labels: approved, lgtm, size/M

#11614 RHEL upgrade: use API to get ignition from machine config
  roles/openshift_node/tasks/apply_machine_config.yml
  roles/openshift_node/tasks/upgrade.yml
Labels: approved, lgtm, size/M

#11613 Bug 1710424 - Creating logging playbook to do cert rotation
  playbooks/openshift-logging/private/check_es_health.yaml
  playbooks/openshift-logging/private/redeploy-certificates.yml
  playbooks/openshift-logging/redeploy-certificates.yml
  roles/openshift_logging/tasks/discover_namespace.yaml
  roles/openshift_logging/tasks/main.yaml
  roles/openshift_logging_curator/tasks/generate_secret.yaml
  roles/openshift_logging_curator/tasks/main.yaml
  roles/openshift_logging_elasticsearch/tasks/generate_secret.yaml
  roles/openshift_logging_elasticsearch/tasks/main.yaml
  roles/openshift_logging_elasticsearch/tasks/restart_pods.yaml
  roles/openshift_logging_fluentd/tasks/generate_secret.yaml
  roles/openshift_logging_fluentd/tasks/main.yaml
  roles/openshift_logging_kibana/tasks/generate_secret.yaml
  roles/openshift_logging_kibana/tasks/main.yaml
  roles/openshift_logging_kibana/tasks/restart_pods.yaml
  roles/openshift_logging_mux/tasks/generate_secret.yaml
  roles/openshift_logging_mux/tasks/main.yaml
Labels: approved, lgtm, size/XL

#11620 [release-3.11] To provide a way to specify audit policyFile add "openshift_master_audit_policyfile"
  roles/openshift_control_plane/tasks/main.yml
  roles/openshift_master_facts/tasks/main.yml
Labels: approved, lgtm, ok-to-test, size/S

#11616 [release-3.10] Fix openshift sdn taint toleration
  roles/openshift_sdn/files/sdn.yaml
Labels: approved, lgtm, size/XS

#11618 Test using Ansible 2.8.0
  openshift-ansible.spec
  requirements.txt
Labels: approved, lgtm, size/XS

#11625 [release-3.10] Remove deprecated variables openshift_ip and openshift_set_node_ip.
  images/installer/root/usr/local/bin/generate
  inventory/hosts.example
  playbooks/init/validate_hostnames.yml
  playbooks/openstack/inventory.py
  roles/lib_utils/action_plugins/sanity_checks.py
  roles/openshift_node/defaults/main.yml
  roles/openshift_node/templates/node.yaml.v1.j2
Labels: approved, lgtm, size/S

#11621 [BZ 1710311] Make readinessProbe timeout configurable and add initialDelaySeconds
  roles/openshift_metrics/defaults/main.yaml
  roles/openshift_metrics/templates/hawkular_cassandra_rc.j2
Labels: approved, lgtm, size/XS

#11622 [release-3.11] Remove deprecated openshift_set_node_ip & openshift_ip vars
  inventory/hosts.example
  playbooks/init/cluster_facts.yml
  playbooks/init/validate_hostnames.yml
  playbooks/openshift-logging/private/config.yml
  playbooks/openstack/resources.py
  roles/lib_utils/action_plugins/sanity_checks.py
  roles/openshift_node/defaults/main.yml
Labels: approved, lgtm, size/S

#11632 Test using Ansible 2.7.11
  images/installer/Dockerfile
  requirements.txt
Labels: approved, lgtm, size/XS

#11566 Bug 1656487: Avoid duplicate env vars in router deploymentconfig
  roles/lib_openshift/library/oc_adm_router.py
  roles/lib_openshift/src/class/oc_adm_router.py
  roles/lib_openshift/src/test/unit/test_oc_adm_router.py
Labels: approved, lgtm, size/L

#11581 Adding retries for Elastic Search with HA
  roles/openshift_logging_elasticsearch/tasks/restart_cluster.yml
  roles/openshift_logging_elasticsearch/tasks/rolling_cluster_restart.yml
Labels: approved, lgtm, ok-to-test, size/M

#11610 [release-3.9] Workaround missing network metrics when using cri-o
  playbooks/openshift-metrics/private/config.yml
  playbooks/openshift-node/private/restart.yml
Labels: approved, lgtm, size/M

#11607 Workaround missing network metrics when using cri-o
  playbooks/openshift-metrics/private/config.yml
  playbooks/openshift-node/private/restart.yml
Labels: approved, lgtm, size/M

#11650 Fail on Ansible 2.8
  README.md
  roles/lib_utils/callback_plugins/aa_version_requirement.py
Labels: approved, lgtm, size/XS
