Repository openshift/openshift-ansible, pull requests merged in 2020-05, with the labels that each got.

#12151 Bug 1827982: Install cifs-utils, required for azure-file mounts
  roles/openshift_node/defaults/main.yml
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#12145 Bug 1826213: Update version check to support semver change
  roles/openshift_node/defaults/main.yml
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#12156 Enable EPEL repo for openshift origin install on CentOS
  roles/openshift_repos/tasks/centos_repos.yml
  roles/openshift_repos/tasks/main.yaml
  roles/openshift_repos/templates/CentOS-OpenShift-Origin.repo.j2
  roles/openshift_repos/templates/CentOS-OpenShift-Origin14.repo.j2
  roles/openshift_repos/templates/CentOS-OpenShift-Origin15.repo.j2
  roles/openshift_repos/templates/CentOS-OpenShift-Origin310.repo.j2
  roles/openshift_repos/templates/CentOS-OpenShift-Origin36.repo.j2
  roles/openshift_repos/templates/CentOS-OpenShift-Origin37.repo.j2
Labels: approved, lgtm

#12119 Bug 1808068: Add /usr/share/pki to sync pod
  roles/openshift_node_group/files/sync.yaml
Labels: approved, bugzilla/severity-low, bugzilla/valid-bug, lgtm, size/XS

#12152 Bug 1828484: Add conditional to fix openshift_master_cluster_hostname check
  playbooks/gcp/openshift-cluster/install.yml
  roles/openshift_sanitize_inventory/tasks/main.yml
Labels: approved, bugzilla/severity-urgent, bugzilla/valid-bug, lgtm

#12149 Bug 1824056: fix task name for removal of openshift-monitoring project
  roles/openshift_cluster_monitoring_operator/tasks/remove.yaml
Labels: approved, bugzilla/severity-low, bugzilla/valid-bug, lgtm

#12154 Bug 1829492: Remove hard coded openshift_certificate_expiry_warning_days
  playbooks/common/openshift-cluster/upgrades/init.yml
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#12136 Bug 1818961: [release-4.4] Use oc_csr_approve Ansible module for CSR approval
  .travis.yml
  openshift-ansible.spec
  pytest.ini
  roles/openshift_node/library/oc_csr_approve.py
  roles/openshift_node/tasks/apply_machine_config.yml
  roles/openshift_node/tasks/config.yml
  roles/openshift_node/tasks/gather_debug.yml
  roles/openshift_node/test/test_data/oc_csr_approve_pending.json
  roles/openshift_node/test/test_data/oc_csr_server_multiple_pends_one_host.json
  roles/openshift_node/test/test_data/oc_get_nodes.json
  roles/openshift_node/test/test_data/openssl1.txt
  roles/openshift_node/test/test_oc_csr_approve.py
  test-requirements.txt
  tox.ini
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, cherry-pick-approved, lgtm

#10526 Bug 1633506: Possibility to define nodeSelector for hawkular-metrics-schema job
  roles/openshift_metrics/defaults/main.yaml
  roles/openshift_metrics/tasks/install_hawkular_schema_job.yaml
  roles/openshift_metrics/templates/hawkular_metrics_schema_job.j2
Labels: approved, bugzilla/severity-low, bugzilla/valid-bug, lgtm, size/S

#12121 Fix namespace for rh-operators.configmap.yaml
  roles/olm/files/rh-operators.configmap.yaml
Labels: approved, lgtm, ok-to-test, size/XS

#11981 Don't abort if ElasticSearch is slow
  roles/openshift_logging_elasticsearch/tasks/restart_es_node.yml
Labels: approved, lgtm, ok-to-test, size/XS

#12153 Bug 1803616: Copy the htpasswd using local action
  roles/openshift_metrics/tasks/generate_hawkular_certificates.yaml
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#12122 use openshift3/registry-console instead of cockpit/kubernetes with or…
  inventory/hosts.example
  roles/cockpit-ui/defaults/main.yml
Labels: approved, lgtm, ok-to-test, size/S

#12078 Update EAP CD 18 imagestreams and templates
  roles/openshift_examples/files/examples/x86_64/xpaas-streams/eap-cd-image-stream.json
  roles/openshift_examples/files/examples/x86_64/xpaas-templates/eap-cd-amq-persistent-s2i.json
  roles/openshift_examples/files/examples/x86_64/xpaas-templates/eap-cd-amq-s2i.json
  roles/openshift_examples/files/examples/x86_64/xpaas-templates/eap-cd-basic-s2i.json
  roles/openshift_examples/files/examples/x86_64/xpaas-templates/eap-cd-https-s2i.json
  roles/openshift_examples/files/examples/x86_64/xpaas-templates/eap-cd-sso-s2i.json
  roles/openshift_examples/files/examples/x86_64/xpaas-templates/eap-cd-starter-s2i.json
  roles/openshift_examples/files/examples/x86_64/xpaas-templates/eap-cd-third-party-db-s2i.json
  roles/openshift_examples/files/examples/x86_64/xpaas-templates/eap-cd-tx-recovery-s2i.json
Labels: approved, lgtm, ok-to-test, size/XL

#11726 fix failed to get stats
  roles/openshift_node_group/templates/node-config.yaml.j2
Labels: approved, lgtm, ok-to-test, size/XS

#11605 Added output to master-restart. Avoid searchs and serves as doc
  roles/openshift_control_plane/files/scripts/crio/master-restart
  roles/openshift_control_plane/files/scripts/docker/master-restart
Labels: approved, lgtm, ok-to-test, size/XS

#12100 Remove OVS pod force grace-period 0 on upgrade
  roles/openshift_node/tasks/upgrade.yml
Labels: approved, lgtm, ok-to-test, size/S

#12158 Bug 1829492: Add six month expiry check back to upgrades
  playbooks/common/openshift-cluster/upgrades/init.yml
  roles/openshift_certificate_expiry/defaults/main.yml
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#12159 Bug 1832379: Remove cert expiry check during cert redeploy
  playbooks/openshift-etcd/private/redeploy-ca.yml
  playbooks/openshift-etcd/private/redeploy-certificates.yml
  playbooks/openshift-master/private/redeploy-openshift-ca.yml
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#12157 API server use the local etcd instance first
  playbooks/init/cluster_facts.yml
  playbooks/openshift-etcd/private/scaleup.yml
Labels: approved, lgtm, ok-to-test

#12143 Bug 1691678: Generate htpaswd inside hawkular metrics container
  roles/openshift_metrics/tasks/generate_hawkular_certificates.yaml
  roles/openshift_metrics/templates/hawkular_metrics_rc.j2
Labels: approved, bugzilla/severity-urgent, bugzilla/valid-bug, lgtm

#12160 Use variable for EPEL RPM URL for CentOS
  roles/openshift_repos/defaults/main.yaml
  roles/openshift_repos/tasks/centos_repos.yml
Labels: approved, lgtm

#12161 Add support to configure subnetpool prefixlen at Kuryr
  roles/openshift_openstack/defaults/main.yml
  roles/openshift_openstack/templates/heat_stack.yaml.j2
Labels: approved, lgtm

#12163 Bug 1830158: Add support for global namespaces and removal of remote_group_id
  playbooks/openstack/configuration.md
  roles/kuryr/defaults/main.yaml
  roles/kuryr/templates/configmap.yaml.j2
  roles/openshift_openstack/templates/heat_stack.yaml.j2
Labels: approved, bugzilla/severity-low, bugzilla/valid-bug, lgtm

#12168 Update OpenStack and Kuryr reviewers/approvers
  roles/kuryr/OWNERS
  roles/openshift_openstack/OWNERS
Labels: approved, lgtm

#12165 Bug 1816966: Updating ES restart policy
  roles/openshift_logging_elasticsearch/tasks/full_cluster_restart.yml
  roles/openshift_logging_elasticsearch/tasks/restart_cluster.yml
  roles/openshift_logging_elasticsearch/tasks/restart_es_node.yml
  roles/openshift_logging_elasticsearch/tasks/rolling_cluster_restart.yml
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#12173 Bug 1839965: Enable seboolean for Azure mount support
  roles/openshift_node/tasks/config.yml
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#12172 Bug 1814451: Added expiration checks for aggregator-proxy related certs
  roles/lib_utils/library/openshift_cert_expiry.py
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#12171 [KIECLOUD-390] - Update RHPAM and RHDM templates adocs files and temp…
  roles/openshift_examples/files/examples/x86_64/xpaas-streams/rhdm77-image-streams.yaml
  roles/openshift_examples/files/examples/x86_64/xpaas-streams/rhpam77-image-streams.yaml
  roles/openshift_examples/files/examples/x86_64/xpaas-templates/rhdm77-authoring-ha.yaml
  roles/openshift_examples/files/examples/x86_64/xpaas-templates/rhdm77-authoring.yaml
  roles/openshift_examples/files/examples/x86_64/xpaas-templates/rhdm77-kieserver.yaml
  roles/openshift_examples/files/examples/x86_64/xpaas-templates/rhdm77-prod-immutable-kieserver-amq.yaml
  roles/openshift_examples/files/examples/x86_64/xpaas-templates/rhdm77-prod-immutable-kieserver.yaml
  roles/openshift_examples/files/examples/x86_64/xpaas-templates/rhdm77-trial-ephemeral.yaml
  roles/openshift_examples/files/examples/x86_64/xpaas-templates/rhpam77-authoring-ha.yaml
  roles/openshift_examples/files/examples/x86_64/xpaas-templates/rhpam77-authoring.yaml
  roles/openshift_examples/files/examples/x86_64/xpaas-templates/rhpam77-kieserver-externaldb.yaml
  roles/openshift_examples/files/examples/x86_64/xpaas-templates/rhpam77-kieserver-mysql.yaml
  roles/openshift_examples/files/examples/x86_64/xpaas-templates/rhpam77-kieserver-postgresql.yaml
  roles/openshift_examples/files/examples/x86_64/xpaas-templates/rhpam77-managed.yaml
  roles/openshift_examples/files/examples/x86_64/xpaas-templates/rhpam77-prod-immutable-kieserver-amq.yaml
  roles/openshift_examples/files/examples/x86_64/xpaas-templates/rhpam77-prod-immutable-kieserver.yaml
  roles/openshift_examples/files/examples/x86_64/xpaas-templates/rhpam77-prod-immutable-monitor.yaml
  roles/openshift_examples/files/examples/x86_64/xpaas-templates/rhpam77-prod.yaml
  roles/openshift_examples/files/examples/x86_64/xpaas-templates/rhpam77-trial-ephemeral.yaml
Labels: approved, lgtm, ok-to-test

#12167 Bug 1828433: Bump etcd to version 3.2.28
  roles/etcd/defaults/main.yaml
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm, ok-to-test

#12162 Bug 1800467: gluster: use memory (tmpfs) emptydir for glusterfs-run volume
  roles/openshift_storage_glusterfs/files/glusterfs-template.yml
Labels: approved, bugzilla/severity-high, lgtm, ok-to-test
