Repository openshift/openshift-ansible, pull requests merged in 2020-12, with the labels that each got.

#12278 roles/openshift_facts: Set quay.io as default registry
  roles/cockpit-ui/defaults/main.yml
  roles/cockpit-ui/tasks/install.yml
  roles/openshift_facts/defaults/main.yml
Labels: approved, lgtm

#12280 Bug 1902067: playbooks/openshift-node: Remove restart from join.yml
  playbooks/openshift-node/private/join.yml
  playbooks/redeploy-certificates.yml
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#12251 ignore failed msg when running task Verify if the ca-bundle contains …
  roles/openshift_named_certificates/tasks/main.yml
Labels: approved, lgtm

#12281 Bug 1904767: network: default openshift_master_external_ip_network_cidrs to empty
  roles/openshift_control_plane/templates/master.yaml.v1.j2
Labels: approved, bugzilla/severity-low, bugzilla/valid-bug, lgtm

#12282 Reorder the when checks to take into account the case that the named …
  roles/openshift_named_certificates/tasks/main.yml
Labels: approved, lgtm, ok-to-test
