Repository openshift/openshift-ansible, pull requests merged in 2020-08, with the labels that each got.

#12214 Bug 1802394: Limit corsAllowedOrigins to HTTPS
  roles/openshift_control_plane/templates/master.yaml.v1.j2
Labels: approved, bugzilla/severity-low, bugzilla/valid-bug, lgtm

#12217 Adjust amphora VM default ranges
  roles/openshift_openstack/defaults/main.yml
Labels: approved, lgtm

#12218 Bug 1856078: Ensure port/subport created by heat has tags if Kuryr is used
  roles/openshift_openstack/templates/heat_stack_server.yaml.j2
  roles/openshift_openstack/templates/heat_stack_subports.yaml.j2
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#12220 Update CloudForms 4.7 templates for HTTPD headers
  roles/openshift_management/files/templates/cloudforms/cfme-template-ext-db.yaml
  roles/openshift_management/files/templates/cloudforms/cfme-template.yaml
Labels: approved, lgtm, ok-to-test

#12221 Bump requirements.txt
  requirements.txt
Labels: approved, lgtm

#12219 Bug 1867134: Remove log-openvswitch mount from ovs daemonset
  roles/openshift_sdn/files/sdn-ovs.yaml
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#12222 Bug 1807201: logging_elasticsearch: disable system_call_filter check on non-amd64 architectures
  roles/openshift_logging_elasticsearch/tasks/main.yaml
  roles/openshift_logging_elasticsearch/templates/elasticsearch.yml.j2
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm
