Repository openshift/openshift-ansible, pull requests merged in 2020-03, with the labels that each got.

#12114 Increase podman pull timeout
  roles/openshift_node/tasks/apply_machine_config.yml
  roles/openshift_node/tasks/config.yml
Labels: approved, lgtm, size/XS

#12092 Adding Prometheus 0.23.2
  roles/olm/files/rh-operators.configmap.yaml
Labels: approved, lgtm, size/XL

#12116 Refine Python version for tox in travis
  tox.ini
Labels: approved, lgtm, size/XS

#12117 Use Ansible 2.9.5 for OCP 4.5
  README.md
  openshift-ansible.spec
  requirements.txt
  roles/openshift_node/callback_plugins/aa_version_requirement.py
Labels: approved, lgtm, size/S

#12110 Remove k8s modules from test playbooks
  openshift-ansible.spec
  setup.py
  test/aws/create_machines.yml
  test/aws/files/01_service.yml
  test/aws/files/02_serviceaccount.yml
  test/aws/files/03_role.yml
  test/aws/files/04_rolebinding.yml
  test/aws/files/05_clusterrole.yml
  test/aws/files/06_clusterrolebinding.yml
  test/aws/files/07_deployment.yml
  test/aws/files/sshd_config
  test/aws/get_machinesets.yml
  test/aws/scaleup.yml
  test/aws/ssh_bastion.yml
  test/aws/tasks/additional_repos.yml
  test/aws/tasks/create_machineset.yml
  test/aws/tasks/gather_logs.yml
  test/aws/tasks/get_machinesets.yml
Labels: approved, lgtm, size/XL

#12129 Bug 1815010: Use oc_csr_approve Ansible module for CSR approval
  openshift-ansible.spec
  pytest.ini
  roles/openshift_node/library/oc_csr_approve.py
  roles/openshift_node/tasks/apply_machine_config.yml
  roles/openshift_node/tasks/config.yml
  roles/openshift_node/tasks/gather_debug.yml
  roles/openshift_node/test/test_data/oc_csr_approve_pending.json
  roles/openshift_node/test/test_data/oc_csr_server_multiple_pends_one_host.json
  roles/openshift_node/test/test_data/oc_get_nodes.json
  roles/openshift_node/test/test_data/openssl1.txt
  roles/openshift_node/test/test_oc_csr_approve.py
  test-requirements.txt
  tox.ini
Labels: approved, bugzilla/valid-bug, lgtm
