Repository openshift/openshift-ansible, pull requests merged in 2020-02, with the labels that each got.

#12082 Bug 1798168: Update RHPAM and RHDM templates and imagestreams on …
  roles/openshift_examples/examples-sync.sh
  roles/openshift_examples/files/examples/x86_64/xpaas-streams/rhdm76-image-streams.yaml
  roles/openshift_examples/files/examples/x86_64/xpaas-streams/rhpam76-image-streams.yaml
  roles/openshift_examples/files/examples/x86_64/xpaas-templates/rhdm76-authoring-ha.yaml
  roles/openshift_examples/files/examples/x86_64/xpaas-templates/rhdm76-authoring.yaml
  roles/openshift_examples/files/examples/x86_64/xpaas-templates/rhdm76-kieserver.yaml
  roles/openshift_examples/files/examples/x86_64/xpaas-templates/rhdm76-prod-immutable-kieserver-amq.yaml
  roles/openshift_examples/files/examples/x86_64/xpaas-templates/rhdm76-prod-immutable-kieserver.yaml
  roles/openshift_examples/files/examples/x86_64/xpaas-templates/rhdm76-trial-ephemeral.yaml
  roles/openshift_examples/files/examples/x86_64/xpaas-templates/rhpam76-authoring-ha.yaml
  roles/openshift_examples/files/examples/x86_64/xpaas-templates/rhpam76-authoring.yaml
  roles/openshift_examples/files/examples/x86_64/xpaas-templates/rhpam76-kieserver-externaldb.yaml
  roles/openshift_examples/files/examples/x86_64/xpaas-templates/rhpam76-kieserver-mysql.yaml
  roles/openshift_examples/files/examples/x86_64/xpaas-templates/rhpam76-kieserver-postgresql.yaml
  roles/openshift_examples/files/examples/x86_64/xpaas-templates/rhpam76-managed.yaml
  roles/openshift_examples/files/examples/x86_64/xpaas-templates/rhpam76-prod-immutable-kieserver-amq.yaml
  roles/openshift_examples/files/examples/x86_64/xpaas-templates/rhpam76-prod-immutable-kieserver.yaml
  roles/openshift_examples/files/examples/x86_64/xpaas-templates/rhpam76-prod-immutable-monitor.yaml
  roles/openshift_examples/files/examples/x86_64/xpaas-templates/rhpam76-prod.yaml
  roles/openshift_examples/files/examples/x86_64/xpaas-templates/rhpam76-trial-ephemeral.yaml
Labels: approved, bugzilla/valid-bug, lgtm, ok-to-test, size/XXL

#12096 Bug 1798365: gluster: fix how lvm wrapper is passed to heketi templates
  roles/openshift_storage_glusterfs/defaults/main.yml
  roles/openshift_storage_glusterfs/files/deploy-heketi-template.yml
  roles/openshift_storage_glusterfs/files/heketi-template.yml
  roles/openshift_storage_glusterfs/tasks/glusterfs_config_facts.yml
  roles/openshift_storage_glusterfs/tasks/glusterfs_registry_facts.yml
  roles/openshift_storage_glusterfs/tasks/heketi_deploy.yml
  roles/openshift_storage_glusterfs/tasks/heketi_init_deploy.yml
Labels: approved, bugzilla/valid-bug, lgtm, ok-to-test, size/M

#12095 Use Ansible 2.9.4 for testing
  images/installer/Dockerfile
  requirements.txt
Labels: approved, bugzilla/valid-bug, lgtm, size/XS

#12070 Bug 1793093: [release-4.3] Fix machine config apply on upgrade
  roles/openshift_node/tasks/apply_machine_config.yml
  roles/openshift_node/tasks/upgrade.yml
Labels: approved, bugzilla/valid-bug, cherry-pick-approved, lgtm, size/L

#12094 Remove variable from logging task name
  roles/openshift_logging_elasticsearch/tasks/restart_cluster.yml
Labels: approved, bugzilla/valid-bug, lgtm, size/XS

#12101 Fix cluster monitoring operator config map with etcd
  roles/openshift_cluster_monitoring_operator/templates/cluster-monitoring-operator-config.j2
Labels: approved, lgtm, size/S

#12105 Bug 1804655: roles/openshift_cluster_monitoring_operator: configure retention
  roles/openshift_cluster_monitoring_operator/defaults/main.yml
  roles/openshift_cluster_monitoring_operator/templates/cluster-monitoring-operator-config.j2
Labels: approved, bugzilla/valid-bug, lgtm, size/XS

#12099 Bug 1779811: Gather debug data on task failure
  images/installer/root/usr/local/bin/generate
  roles/openshift_node/defaults/main.yml
  roles/openshift_node/tasks/apply_machine_config.yml
  roles/openshift_node/tasks/config.yml
  roles/openshift_node/tasks/gather_debug.yml
  roles/openshift_node/tasks/install.yml
  roles/openshift_node/tasks/proxy.yml
  roles/openshift_node/tasks/scaleup_checks.yml
  roles/openshift_node/tasks/upgrade.yml
  test/aws/create_machineset.yml
  test/aws/scaleup.yml
Labels: approved, bugzilla/valid-bug, lgtm, size/L

#12091 Bug 1796709: Delete container.yaml
  images/installer/container.yaml
Labels: approved, bugzilla/valid-bug, lgtm, size/S

#11967 Bug 1754081: Certificate expiration misses node certificates
  playbooks/common/openshift-cluster/upgrades/init.yml
  roles/lib_utils/library/openshift_cert_expiry.py
Labels: approved, bugzilla/valid-bug, lgtm, size/S

#12109 Retry podman pull
  roles/openshift_node/tasks/apply_machine_config.yml
  roles/openshift_node/tasks/config.yml
  roles/openshift_node/tasks/install.yml
Labels: approved, lgtm, size/S

#12102 Use Python3 for tests
  .travis.yml
  test-requirements.txt
  tox.ini
Labels: approved, lgtm, needs-rebase, size/S

#12112 Increase worker config rollout timeout
  test/aws/scaleup.yml
Labels: approved, lgtm, size/XS

#12111 Delete container.yaml
  images/installer/container.yaml
Labels: approved, lgtm, size/S
