Repository openshift/openshift-ansible, pull requests merged in 2020-10, with the labels that each got.

#12242 Bug 1884095: Update playbook to install NetworkManager-ovs
  roles/openshift_node/defaults/main.yml
Labels: approved, bugzilla/severity-urgent, bugzilla/valid-bug, lgtm

#12234 Bug 1882203: separate playbook to redeploy named certs only
  playbooks/openshift-master/private/named-certificates.yml
  playbooks/openshift-master/redeploy-named-certificates.yml
  roles/openshift_named_certificates/tasks/main.yml
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#12248 Bug 1757081: playbooks/openshift-etcd: Ensure etcd CA is present on first etcd host
  playbooks/openshift-etcd/private/redeploy-certificates.yml
  roles/etcd/tasks/verify_ca_certificates.yml
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#12239 playbooks/openshift-node: Check for GlusterFS project during restart
  playbooks/openshift-node/private/restart.yml
Labels: approved, lgtm

#12244 Bug 1882572: playbooks/container-runtime: Combine role import into one task
  playbooks/container-runtime/private/config.yml
  roles/container_runtime/tasks/install.yml
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#12249 Bug 1870490: roles/openshift-node: Verify host matches cluster FIPS
  roles/openshift_node/tasks/install.yml
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#12250 Bug 1836157: roles/openshift_peristent_volumes: Correct persistent-volume.yml template
  roles/openshift_persistent_volumes/templates/persistent-volume.yml.j2
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#12252 Revert "Bug 1848454: OpenShift logging upgrade from 3.11.161 to 3.11.219 fails"
  roles/openshift_logging/tasks/install_logging.yaml
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#12243 Update README.md
  README.md
Labels: approved, lgtm, ok-to-test

#12253 Bug 1879356: Add node_bootstrap_autoapprover as part of upgrade component
  playbooks/common/openshift-cluster/upgrades/upgrade_components.yml
Labels: approved, bugzilla/severity-low, bugzilla/valid-bug, lgtm, ok-to-test

#12255 Bug 1812431: roles/openshift_control_plane: Verify local API health
  roles/openshift_control_plane/handlers/main.yml
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#12256 test/aws: Remove temporary kernel update
  test/aws/create_machines.yml
Labels: approved, lgtm

#12257 Bug 1892159: Wait for node to be ready task should check that all vars are defined
  playbooks/openshift-node/private/registry_auth.yml
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm, ok-to-test
