Repository openshift/openshift-ansible, pull requests merged in 2020-09, with the labels that each got.

#12224 Bug 1874530: release-3.11: Gather initialization facts for all masters
  playbooks/init/basic_facts.yml
  playbooks/openshift-master/openshift_node_group.yml
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#12225 Bug 1779811: Install pre-release kernel (for scaleup-rhel7 CI)
  test/aws/create_machines.yml
Labels: approved, bugzilla/severity-urgent, bugzilla/valid-bug, lgtm

#12223 Bug 1874324: Update playbook to install and activate openvswitch2.13
  roles/openshift_node/defaults/main.yml
Labels: approved, bugzilla/severity-unspecified, bugzilla/valid-bug, lgtm

#12227 Bug 1852753: Add --force and --grace-period options to SDN pod delete
  roles/openshift_node/tasks/upgrade.yml
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#12230 [KIECLOUD-418] - Update RHPAM and RHDM templates and imagestreams on …
  roles/openshift_examples/examples-sync.sh
  roles/openshift_examples/files/examples/x86_64/xpaas-streams/rhdm78-image-streams.yaml
  roles/openshift_examples/files/examples/x86_64/xpaas-streams/rhpam78-image-streams.yaml
  roles/openshift_examples/files/examples/x86_64/xpaas-templates/rhdm78-authoring-ha.yaml
  roles/openshift_examples/files/examples/x86_64/xpaas-templates/rhdm78-authoring.yaml
  roles/openshift_examples/files/examples/x86_64/xpaas-templates/rhdm78-kieserver.yaml
  roles/openshift_examples/files/examples/x86_64/xpaas-templates/rhdm78-prod-immutable-kieserver-amq.yaml
  roles/openshift_examples/files/examples/x86_64/xpaas-templates/rhdm78-prod-immutable-kieserver.yaml
  roles/openshift_examples/files/examples/x86_64/xpaas-templates/rhdm78-trial-ephemeral.yaml
  roles/openshift_examples/files/examples/x86_64/xpaas-templates/rhpam78-authoring-ha.yaml
  roles/openshift_examples/files/examples/x86_64/xpaas-templates/rhpam78-authoring.yaml
  roles/openshift_examples/files/examples/x86_64/xpaas-templates/rhpam78-kieserver-externaldb.yaml
  roles/openshift_examples/files/examples/x86_64/xpaas-templates/rhpam78-kieserver-mysql.yaml
  roles/openshift_examples/files/examples/x86_64/xpaas-templates/rhpam78-kieserver-postgresql.yaml
  roles/openshift_examples/files/examples/x86_64/xpaas-templates/rhpam78-managed.yaml
  roles/openshift_examples/files/examples/x86_64/xpaas-templates/rhpam78-prod-immutable-kieserver-amq.yaml
  roles/openshift_examples/files/examples/x86_64/xpaas-templates/rhpam78-prod-immutable-kieserver.yaml
  roles/openshift_examples/files/examples/x86_64/xpaas-templates/rhpam78-prod-immutable-monitor.yaml
  roles/openshift_examples/files/examples/x86_64/xpaas-templates/rhpam78-prod.yaml
  roles/openshift_examples/files/examples/x86_64/xpaas-templates/rhpam78-trial-ephemeral.yaml
Labels: approved, lgtm, ok-to-test

#12226 Bug 1870123: Fix docker_storage health check
  images/installer/Dockerfile
  requirements.txt
  roles/openshift_health_checker/openshift_checks/docker_storage.py
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#12231 Pin pyrsistent to 0.16.1 for tox tests to work under Travis CI
  requirements.txt
Labels: approved, lgtm

#12235 Bug 1772580: roles/openshift_master_certificates: Update bootstrap.kubeconfig
  roles/openshift_master_certificates/tasks/main.yml
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#12238 Bug 1837123: Detect an incomplete OpenShift CA redeployment
  playbooks/openshift-master/private/check-client-ca.yml
  playbooks/redeploy-certificates.yml
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#12233 Bug 1848454: OpenShift logging upgrade from 3.11.161 to 3.11.219 fails
  roles/openshift_logging/tasks/install_logging.yaml
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#12236 Bug 1791160: roles/openshift_master_certificates: Update node.kubeconfig
  roles/openshift_master_certificates/tasks/main.yml
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#12237 Bug 1883036: adding option to not redeploy service signer
  playbooks/openshift-master/private/certificates-backup.yml
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm
