Repository openshift/openshift-ansible, pull requests merged in 2020-11, with the labels that each got.

#12258 add php 7.2 into 3.11 cause cuppet says 7.1 will no longer work with sclorg/cakephp-ex
  roles/openshift_examples/files/examples/x86_64/image-streams/image-streams-rhel7.json
  roles/openshift_examples/files/examples/x86_64/quickstart-templates/cakephp-mysql-persistent.json
  roles/openshift_examples/files/examples/x86_64/quickstart-templates/cakephp-mysql.json
Labels: approved, lgtm

#12262 add php 7.2 into 3.11 cause cuppet says 7.1 will no longer work with sclorg/cakephp-ex (centos as with for CI/e2e testing)
  roles/openshift_examples/files/examples/x86_64/image-streams/image-streams-centos7.json
Labels: approved, lgtm

#12263 Bug 1888962: roles/openshift_node: Update NetworkManager conf.d default
  roles/openshift_node/tasks/dnsmasq/network-manager.yml
Labels: approved, bugzilla/severity-urgent, bugzilla/valid-bug, lgtm

#12266 [KIECLOUD-419] - Update RHPAM and RHDM templates and imagestreams on …
  roles/openshift_examples/examples-sync.sh
  roles/openshift_examples/files/examples/x86_64/xpaas-streams/rhdm79-image-streams.yaml
  roles/openshift_examples/files/examples/x86_64/xpaas-streams/rhpam79-image-streams.yaml
  roles/openshift_examples/files/examples/x86_64/xpaas-templates/rhdm79-authoring-ha.yaml
  roles/openshift_examples/files/examples/x86_64/xpaas-templates/rhdm79-authoring.yaml
  roles/openshift_examples/files/examples/x86_64/xpaas-templates/rhdm79-kieserver.yaml
  roles/openshift_examples/files/examples/x86_64/xpaas-templates/rhdm79-prod-immutable-kieserver-amq.yaml
  roles/openshift_examples/files/examples/x86_64/xpaas-templates/rhdm79-prod-immutable-kieserver.yaml
  roles/openshift_examples/files/examples/x86_64/xpaas-templates/rhdm79-trial-ephemeral.yaml
  roles/openshift_examples/files/examples/x86_64/xpaas-templates/rhpam79-authoring-ha.yaml
  roles/openshift_examples/files/examples/x86_64/xpaas-templates/rhpam79-authoring.yaml
  roles/openshift_examples/files/examples/x86_64/xpaas-templates/rhpam79-kieserver-externaldb.yaml
  roles/openshift_examples/files/examples/x86_64/xpaas-templates/rhpam79-kieserver-mysql.yaml
  roles/openshift_examples/files/examples/x86_64/xpaas-templates/rhpam79-kieserver-postgresql.yaml
  roles/openshift_examples/files/examples/x86_64/xpaas-templates/rhpam79-managed.yaml
  roles/openshift_examples/files/examples/x86_64/xpaas-templates/rhpam79-prod-immutable-kieserver-amq.yaml
  roles/openshift_examples/files/examples/x86_64/xpaas-templates/rhpam79-prod-immutable-kieserver.yaml
  roles/openshift_examples/files/examples/x86_64/xpaas-templates/rhpam79-prod-immutable-monitor.yaml
  roles/openshift_examples/files/examples/x86_64/xpaas-templates/rhpam79-prod.yaml
  roles/openshift_examples/files/examples/x86_64/xpaas-templates/rhpam79-trial-ephemeral.yaml
Labels: approved, lgtm, ok-to-test

#12267 Bug 1895309: roles/openshift_node: Allow newer cri-o version
  images/installer/root/usr/local/bin/entrypoint-provider
  roles/openshift_node/defaults/main.yml
  roles/openshift_node/tasks/install.yml
  roles/openshift_node/tasks/scaleup_checks.yml
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#12260 roles/openshift_version: Use only x.y version from first master
  playbooks/common/openshift-cluster/upgrades/init.yml
  roles/openshift_ca/tasks/main.yml
  roles/openshift_node/tasks/install.yml
  roles/openshift_version/tasks/first_master.yml
Labels: approved, lgtm

#12261 Bug 1888372: openshift_node: Drain nodes and restart during join.yml
  playbooks/openshift-node/private/join.yml
  playbooks/openshift-node/private/restart.yml
  roles/openshift_node/tasks/sdn_delete.yml
  roles/openshift_node/tasks/upgrade.yml
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#12269 Bug 1860906: openshift-cluster/upgrades: Allow short nodes names when filtering
  playbooks/common/openshift-cluster/upgrades/initialize_nodes_to_upgrade.yml
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#12265 playbooks/openshift-hosted: Use 'command' and tidy conditionals
  playbooks/openshift-hosted/private/redeploy-registry-certificates.yml
  playbooks/openshift-hosted/private/redeploy-router-certificates.yml
Labels: approved, lgtm

#12268 Bug 1777061: playbooks/init: Refresh master facts during init
  playbooks/init/cluster_facts.yml
  playbooks/init/main.yml
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#12164 Update openshift_node_packages to match OSE repo
  roles/openshift_node/defaults/main.yml
Labels: approved, lgtm

#12270 playbooks/init: Fix GCP job when oo_masters is not defined
  playbooks/init/cluster_facts.yml
Labels: approved, lgtm

#12271 Revert "Bug 1860906: openshift-cluster/upgrades: Allow short nodes names when filtering"
  playbooks/common/openshift-cluster/upgrades/initialize_nodes_to_upgrade.yml
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#12272 Bug 1860906: openshift-cluster/upgrades: Allow openshift_kubelet_name_override when filtering
  playbooks/common/openshift-cluster/upgrades/initialize_nodes_to_upgrade.yml
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#12273 Bug 1880784: playbooks/init: Validate openshift_master_named_certificates
  playbooks/init/main.yml
  playbooks/init/validate_cert_params.yml
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm
