Repository openshift/openshift-ansible, pull requests merged in 2020-07, with the labels that each got.

#12196 Ensure kuryr resources are tagged
  roles/kuryr/templates/configmap.yaml.j2
Labels: approved, lgtm

#12202 Fix bootstrap ignition user-agent
  roles/openshift_node/tasks/config.yml
Labels: approved, lgtm

#12203 Bug 1848723: Correct GCP group mapping for infra and compute
  inventory/dynamic/gcp/group_vars/all/00_defaults.yml
Labels: approved, bugzilla/severity-urgent, bugzilla/valid-bug, lgtm

#12200 [CI] test/aws/tasks: Properly retry task on command failure
  test/aws/tasks/get_machinesets.yml
Labels: approved, lgtm

#12204 Bug 1848606: Fix repeating logging restarts
  roles/openshift_logging_elasticsearch/handlers/main.yml
  roles/openshift_logging_elasticsearch/tasks/restart_cluster.yml
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#12206 Bug 1856435: allow bypassing of replacing fluentd configmap
  roles/openshift_logging_fluentd/defaults/main.yml
  roles/openshift_logging_fluentd/tasks/main.yaml
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#12210 Fix #12209 - regenerate logging certs
  roles/openshift_logging_elasticsearch/tasks/generate_secret.yaml
Labels: approved, lgtm, ok-to-test

#12211 Bug 1859531: Fix new configmap for logging fresh install
  roles/openshift_logging_curator/tasks/main.yaml
  roles/openshift_logging_fluentd/tasks/main.yaml
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#12205 Add boto to Ansible image for CI
  openshift-ansible.spec
Labels: approved, lgtm

#12212 Add boto3 to Ansible test image in CI
  openshift-ansible.spec
Labels: approved, lgtm

#12213 [KIECLOUD-397] - 7.8.0 - Update RHPAM and RHDM templates/adocs files …
  roles/openshift_examples/examples-sync.sh
  roles/openshift_examples/files/examples/x86_64/xpaas-streams/rhdm78-image-streams.yaml
  roles/openshift_examples/files/examples/x86_64/xpaas-streams/rhpam78-image-streams.yaml
  roles/openshift_examples/files/examples/x86_64/xpaas-templates/rhdm78-authoring-ha.yaml
  roles/openshift_examples/files/examples/x86_64/xpaas-templates/rhdm78-authoring.yaml
  roles/openshift_examples/files/examples/x86_64/xpaas-templates/rhdm78-kieserver.yaml
  roles/openshift_examples/files/examples/x86_64/xpaas-templates/rhdm78-prod-immutable-kieserver-amq.yaml
  roles/openshift_examples/files/examples/x86_64/xpaas-templates/rhdm78-prod-immutable-kieserver.yaml
  roles/openshift_examples/files/examples/x86_64/xpaas-templates/rhdm78-trial-ephemeral.yaml
  roles/openshift_examples/files/examples/x86_64/xpaas-templates/rhpam78-authoring-ha.yaml
  roles/openshift_examples/files/examples/x86_64/xpaas-templates/rhpam78-authoring.yaml
  roles/openshift_examples/files/examples/x86_64/xpaas-templates/rhpam78-kieserver-externaldb.yaml
  roles/openshift_examples/files/examples/x86_64/xpaas-templates/rhpam78-kieserver-mysql.yaml
  roles/openshift_examples/files/examples/x86_64/xpaas-templates/rhpam78-kieserver-postgresql.yaml
  roles/openshift_examples/files/examples/x86_64/xpaas-templates/rhpam78-managed.yaml
  roles/openshift_examples/files/examples/x86_64/xpaas-templates/rhpam78-prod-immutable-kieserver-amq.yaml
  roles/openshift_examples/files/examples/x86_64/xpaas-templates/rhpam78-prod-immutable-kieserver.yaml
  roles/openshift_examples/files/examples/x86_64/xpaas-templates/rhpam78-prod-immutable-monitor.yaml
  roles/openshift_examples/files/examples/x86_64/xpaas-templates/rhpam78-prod.yaml
  roles/openshift_examples/files/examples/x86_64/xpaas-templates/rhpam78-trial-ephemeral.yaml
Labels: approved, lgtm, ok-to-test
