Repository openshift/openshift-ansible, pull requests merged in 2020-01, with the labels that each got.

#12052 Unexpected iptables rules are saved to "/etc/sysconfig/iptables" on first master host
  playbooks/openshift-master/private/additional_config.yml
Labels: approved, lgtm, ok-to-test, size/S

#12058 Bug 1786297: Remove machine config apply from upgrade
  roles/openshift_node/tasks/apply_machine_config.yml
  roles/openshift_node/tasks/upgrade.yml
Labels: approved, bugzilla/valid-bug, lgtm, size/L

#12057 Bug 1787012: gluster - do not enable hostPID for glusterfs-server pods
  roles/openshift_storage_glusterfs/files/glusterfs-template.yml
Labels: approved, bugzilla/valid-bug, lgtm, size/XS

#12061 Bug 1744900: Bump up etcd release to 3.2.26
  roles/etcd/defaults/main.yaml
Labels: approved, bugzilla/valid-bug, lgtm, size/XS

#12069 Bug 1793078: Fix machine config apply on upgrade
  roles/openshift_node/tasks/apply_machine_config.yml
  roles/openshift_node/tasks/upgrade.yml
Labels: approved, bugzilla/valid-bug, lgtm, size/L

#12076 roles/openshift_storage_glusterfs/OWNERS add nixpanic
  roles/openshift_storage_glusterfs/OWNERS
Labels: approved, lgtm, size/XS

#12072 Bug 1791667: gluster: Heketi template does not contain LVM-wrapper on containerized deployment
  roles/openshift_storage_glusterfs/defaults/main.yml
  roles/openshift_storage_glusterfs/tasks/glusterfs_config_facts.yml
  roles/openshift_storage_glusterfs/tasks/glusterfs_registry_facts.yml
  roles/openshift_storage_glusterfs/tasks/heketi_init_deploy.yml
  roles/openshift_storage_glusterfs/templates/deploy-heketi-template.yml.j2
  roles/openshift_storage_glusterfs/templates/heketi-template.yml.j2
Labels: approved, bugzilla/valid-bug, lgtm, size/M

#12084 Support monitoring of etcd with cluster monitoring operator
  roles/openshift_cluster_monitoring_operator/defaults/main.yml
  roles/openshift_cluster_monitoring_operator/templates/cluster-monitoring-operator-config.j2
Labels: approved, lgtm, size/S

#12081 metrics_server: add nodes resource to aggregated-metrics-reader
  roles/metrics_server/files/metrics-server-aggregated-metrics-reader.yaml
Labels: approved, lgtm, size/XS

#12085 Update owners for monitoring components
  playbooks/openshift-monitoring/OWNERS
  roles/openshift_cluster_monitoring_operator/OWNERS
Labels: approved, lgtm, size/M

#12090 Fix to rename ovirt_vms to ovirt_vm
  playbooks/ovirt/openshift-cluster/ovirt-vm-uninstall.yml
Labels: approved, lgtm, size/XS
