Repository openshift/openshift-ansible, pull requests merged in 2020-04, with the labels that each got.

#12135 fix for docker build issue
  images/installer/Dockerfile
Labels: approved, lgtm, ok-to-test

#12133 Bug 1816422: Fix CRDs names on Kuryr tasks
  roles/kuryr/tasks/master.yaml
Labels: approved, bugzilla/valid-bug, lgtm

#12126 [KIECLOUD-369] - Update RHPAM and RHDM templates and imagestreams on …
  roles/openshift_examples/examples-sync.sh
  roles/openshift_examples/files/examples/x86_64/xpaas-streams/rhdm77-image-streams.yaml
  roles/openshift_examples/files/examples/x86_64/xpaas-streams/rhpam77-image-streams.yaml
  roles/openshift_examples/files/examples/x86_64/xpaas-templates/rhdm77-authoring-ha.yaml
  roles/openshift_examples/files/examples/x86_64/xpaas-templates/rhdm77-authoring.yaml
  roles/openshift_examples/files/examples/x86_64/xpaas-templates/rhdm77-kieserver.yaml
  roles/openshift_examples/files/examples/x86_64/xpaas-templates/rhdm77-prod-immutable-kieserver-amq.yaml
  roles/openshift_examples/files/examples/x86_64/xpaas-templates/rhdm77-prod-immutable-kieserver.yaml
  roles/openshift_examples/files/examples/x86_64/xpaas-templates/rhdm77-trial-ephemeral.yaml
  roles/openshift_examples/files/examples/x86_64/xpaas-templates/rhpam77-authoring-ha.yaml
  roles/openshift_examples/files/examples/x86_64/xpaas-templates/rhpam77-authoring.yaml
  roles/openshift_examples/files/examples/x86_64/xpaas-templates/rhpam77-kieserver-externaldb.yaml
  roles/openshift_examples/files/examples/x86_64/xpaas-templates/rhpam77-kieserver-mysql.yaml
  roles/openshift_examples/files/examples/x86_64/xpaas-templates/rhpam77-kieserver-postgresql.yaml
  roles/openshift_examples/files/examples/x86_64/xpaas-templates/rhpam77-managed.yaml
  roles/openshift_examples/files/examples/x86_64/xpaas-templates/rhpam77-prod-immutable-kieserver-amq.yaml
  roles/openshift_examples/files/examples/x86_64/xpaas-templates/rhpam77-prod-immutable-kieserver.yaml
  roles/openshift_examples/files/examples/x86_64/xpaas-templates/rhpam77-prod-immutable-monitor.yaml
  roles/openshift_examples/files/examples/x86_64/xpaas-templates/rhpam77-prod.yaml
  roles/openshift_examples/files/examples/x86_64/xpaas-templates/rhpam77-trial-ephemeral.yaml
Labels: approved, lgtm, ok-to-test

#12137 BUG 1819597: Install rh-operators in the correct namespace
  roles/olm/files/rh-operators.configmap.yaml
Labels: approved, bugzilla/low, bugzilla/valid-bug, lgtm

#12144 Bug 1824828: [release-3.11] Update GCE image disk size
  playbooks/gcp/openshift-cluster/build_base_image.yml
Labels: approved, bugzilla/high, bugzilla/valid-bug, lgtm

#12146 Bug 1824828: [release-3.11] Update GCE image disk size (build_image)
  playbooks/gcp/openshift-cluster/build_image.yml
Labels: approved, bugzilla/high, bugzilla/valid-bug, lgtm

#12140 Bug 1816959: [release-4.3] Use oc_csr_approve Ansible module for CSR approval
  .travis.yml
  openshift-ansible.spec
  pytest.ini
  roles/openshift_node/library/oc_csr_approve.py
  roles/openshift_node/tasks/apply_machine_config.yml
  roles/openshift_node/tasks/config.yml
  roles/openshift_node/tasks/gather_debug.yml
  roles/openshift_node/test/test_data/oc_csr_approve_pending.json
  roles/openshift_node/test/test_data/oc_csr_server_multiple_pends_one_host.json
  roles/openshift_node/test/test_data/oc_get_nodes.json
  roles/openshift_node/test/test_data/openssl1.txt
  roles/openshift_node/test/test_oc_csr_approve.py
  test-requirements.txt
  tox.ini
Labels: approved, bugzilla/valid-bug, cherry-pick-approved, lgtm

#12141 Bug 1824101: Upgrading the RHEL7 worker nodes from OCP4.2 to OCP4.3 can be failed due to conflict of the podman package dependency
  roles/openshift_node/defaults/main.yml
Labels: approved, bugzilla/medium, bugzilla/valid-bug, lgtm
