Repository openshift/openshift-ansible, pull requests merged in 2021-05, with the labels that each got.

#12327 release-3.11: Update OWNERS
  OWNERS
Labels: approved, lgtm

#12328 Bug 1955012: roles/openshift_facts: Force repoquery option
  roles/openshift_facts/defaults/main.yml
  test/ci/template-inventory.j2
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#12316 Bug 1939605: cri-o+kuryr: Switch to proper netns management …
  roles/container_runtime/templates/crio.conf.j2
  roles/kuryr/templates/cni-daemonset.yaml.j2
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#12317 [KIECLOUD-494] - Update RHPAM and RHDM templates and imagestreams on …
  roles/openshift_examples/examples-sync.sh
  roles/openshift_examples/files/examples/x86_64/xpaas-streams/rhdm710-image-streams.yaml
  roles/openshift_examples/files/examples/x86_64/xpaas-streams/rhpam710-image-streams.yaml
  roles/openshift_examples/files/examples/x86_64/xpaas-templates/rhdm710-authoring-ha.yaml
  roles/openshift_examples/files/examples/x86_64/xpaas-templates/rhdm710-authoring.yaml
  roles/openshift_examples/files/examples/x86_64/xpaas-templates/rhdm710-kieserver.yaml
  roles/openshift_examples/files/examples/x86_64/xpaas-templates/rhdm710-prod-immutable-kieserver-amq.yaml
  roles/openshift_examples/files/examples/x86_64/xpaas-templates/rhdm710-prod-immutable-kieserver.yaml
  roles/openshift_examples/files/examples/x86_64/xpaas-templates/rhdm710-trial-ephemeral.yaml
  roles/openshift_examples/files/examples/x86_64/xpaas-templates/rhpam710-authoring-ha.yaml
  roles/openshift_examples/files/examples/x86_64/xpaas-templates/rhpam710-authoring.yaml
  roles/openshift_examples/files/examples/x86_64/xpaas-templates/rhpam710-kieserver-externaldb.yaml
  roles/openshift_examples/files/examples/x86_64/xpaas-templates/rhpam710-kieserver-mysql.yaml
  roles/openshift_examples/files/examples/x86_64/xpaas-templates/rhpam710-kieserver-postgresql.yaml
  roles/openshift_examples/files/examples/x86_64/xpaas-templates/rhpam710-managed.yaml
  roles/openshift_examples/files/examples/x86_64/xpaas-templates/rhpam710-prod-immutable-kieserver-amq.yaml
  roles/openshift_examples/files/examples/x86_64/xpaas-templates/rhpam710-prod-immutable-kieserver.yaml
  roles/openshift_examples/files/examples/x86_64/xpaas-templates/rhpam710-prod-immutable-monitor.yaml
  roles/openshift_examples/files/examples/x86_64/xpaas-templates/rhpam710-prod.yaml
  roles/openshift_examples/files/examples/x86_64/xpaas-templates/rhpam710-trial-ephemeral.yaml
Labels: approved, lgtm, ok-to-test
