Repository openshift/openshift-ansible, pull requests merged in 2021-07, with the labels that each got.

#12336 Bug 1968411: do not specify `force` and `grace-period 0` for SDN deleted
  roles/openshift_node/tasks/sdn_delete.yml
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#12339 openshift_examples: restore openjdk18 examples
  roles/openshift_examples/examples-sync.sh
  roles/openshift_examples/files/examples/x86_64/xpaas-streams/openjdk18-image-stream.json
  roles/openshift_examples/files/examples/x86_64/xpaas-templates/openjdk18-web-basic-s2i.json
Labels: approved, lgtm

#12340 [KIECLOUD-568] - Update RHPAM and RHDM templates and imagestreams on …
  roles/openshift_examples/examples-sync.sh
  roles/openshift_examples/files/examples/x86_64/xpaas-streams/rhdm711-image-streams.yaml
  roles/openshift_examples/files/examples/x86_64/xpaas-streams/rhpam711-image-streams.yaml
  roles/openshift_examples/files/examples/x86_64/xpaas-templates/rhdm711-authoring-ha.yaml
  roles/openshift_examples/files/examples/x86_64/xpaas-templates/rhdm711-authoring.yaml
  roles/openshift_examples/files/examples/x86_64/xpaas-templates/rhdm711-kieserver.yaml
  roles/openshift_examples/files/examples/x86_64/xpaas-templates/rhdm711-prod-immutable-kieserver-amq.yaml
  roles/openshift_examples/files/examples/x86_64/xpaas-templates/rhdm711-prod-immutable-kieserver.yaml
  roles/openshift_examples/files/examples/x86_64/xpaas-templates/rhdm711-trial-ephemeral.yaml
  roles/openshift_examples/files/examples/x86_64/xpaas-templates/rhpam711-authoring-ha.yaml
  roles/openshift_examples/files/examples/x86_64/xpaas-templates/rhpam711-authoring.yaml
  roles/openshift_examples/files/examples/x86_64/xpaas-templates/rhpam711-kieserver-externaldb.yaml
  roles/openshift_examples/files/examples/x86_64/xpaas-templates/rhpam711-kieserver-mysql.yaml
  roles/openshift_examples/files/examples/x86_64/xpaas-templates/rhpam711-kieserver-postgresql.yaml
  roles/openshift_examples/files/examples/x86_64/xpaas-templates/rhpam711-managed.yaml
  roles/openshift_examples/files/examples/x86_64/xpaas-templates/rhpam711-prod-immutable-kieserver-amq.yaml
  roles/openshift_examples/files/examples/x86_64/xpaas-templates/rhpam711-prod-immutable-kieserver.yaml
  roles/openshift_examples/files/examples/x86_64/xpaas-templates/rhpam711-prod-immutable-monitor.yaml
  roles/openshift_examples/files/examples/x86_64/xpaas-templates/rhpam711-prod.yaml
  roles/openshift_examples/files/examples/x86_64/xpaas-templates/rhpam711-trial-ephemeral.yaml
Labels: approved, lgtm, ok-to-test
