Repository openshift/openshift-ansible, pull requests merged in 2021-06, with the labels that each got.

#12330 Bug 1965827: Add catalog entrypoint playbook
  playbooks/openshift-service-catalog/redeploy-certificates.yml
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#12329 Bug 1962884: Bump up etcd to version 3.2.32
  roles/etcd/defaults/main.yaml
Labels: approved, bugzilla/severity-unspecified, bugzilla/valid-bug, lgtm

#12334 Upgrade virtualenv in Travis CI
  .travis.yml
Labels: approved, bugzilla/valid-bug, lgtm

#12332 OWNERS Update
  OWNERS
Labels: approved, bugzilla/valid-bug, lgtm

#12333 Remove deprecated test playbooks
  .gitignore
  setup.py
  test/aws/create_machines.yml
  test/aws/scaleup.yml
  test/aws/tasks/additional_repos.yml
  test/aws/tasks/create_machineset.yml
  test/aws/tasks/gather_logs.yml
  test/aws/tasks/get_machinesets.yml
Labels: approved, lgtm

#12337 [KIECLOUD-493] - Update RHPAM and RHDM templates and imagestreams on OpenShift Service Catalog for 7.11.0 release
  roles/openshift_examples/examples-sync.sh
  roles/openshift_examples/files/examples/x86_64/xpaas-streams/rhdm711-image-streams.yaml
  roles/openshift_examples/files/examples/x86_64/xpaas-streams/rhpam711-image-streams.yaml
  roles/openshift_examples/files/examples/x86_64/xpaas-templates/rhdm711-authoring-ha.yaml
  roles/openshift_examples/files/examples/x86_64/xpaas-templates/rhdm711-authoring.yaml
  roles/openshift_examples/files/examples/x86_64/xpaas-templates/rhdm711-kieserver.yaml
  roles/openshift_examples/files/examples/x86_64/xpaas-templates/rhdm711-prod-immutable-kieserver-amq.yaml
  roles/openshift_examples/files/examples/x86_64/xpaas-templates/rhdm711-prod-immutable-kieserver.yaml
  roles/openshift_examples/files/examples/x86_64/xpaas-templates/rhdm711-trial-ephemeral.yaml
  roles/openshift_examples/files/examples/x86_64/xpaas-templates/rhpam711-authoring-ha.yaml
  roles/openshift_examples/files/examples/x86_64/xpaas-templates/rhpam711-authoring.yaml
  roles/openshift_examples/files/examples/x86_64/xpaas-templates/rhpam711-kieserver-externaldb.yaml
  roles/openshift_examples/files/examples/x86_64/xpaas-templates/rhpam711-kieserver-mysql.yaml
  roles/openshift_examples/files/examples/x86_64/xpaas-templates/rhpam711-kieserver-postgresql.yaml
  roles/openshift_examples/files/examples/x86_64/xpaas-templates/rhpam711-managed.yaml
  roles/openshift_examples/files/examples/x86_64/xpaas-templates/rhpam711-prod-immutable-kieserver-amq.yaml
  roles/openshift_examples/files/examples/x86_64/xpaas-templates/rhpam711-prod-immutable-kieserver.yaml
  roles/openshift_examples/files/examples/x86_64/xpaas-templates/rhpam711-prod-immutable-monitor.yaml
  roles/openshift_examples/files/examples/x86_64/xpaas-templates/rhpam711-prod.yaml
  roles/openshift_examples/files/examples/x86_64/xpaas-templates/rhpam711-trial-ephemeral.yaml
Labels: approved, lgtm, ok-to-test

#12335 Bump ansible in requirements.txt
  requirements.txt
Labels: approved, lgtm

#12331 CORS-1710: Initial support for RHEL8 worker nodes
  roles/openshift_node/defaults/main.yml
  roles/openshift_node/tasks/apply_machine_config.yml
  roles/openshift_node/tasks/config.yml
  roles/openshift_node/tasks/install.yml
Labels: approved, lgtm

#12338 Bug 1964084: OpenShift-ansible playbook tries to pull image from 'r…
  roles/openshift_examples/files/examples/x86_64/image-streams/dotnet_imagestreams.json
  roles/openshift_examples/files/examples/x86_64/image-streams/dotnet_imagestreams_centos.json
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm, ok-to-test
