Repository openshift/openshift-ansible, pull requests merged in 2021-02, with the labels that each got.

#12294 Bug 1920567: patch to check if the ca-bundle.crt exists
  roles/openshift_named_certificates/tasks/main.yml
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#12293 release-4.5: Add boto packages for Ansible test image in CI
  openshift-ansible.spec
Labels: approved, bugzilla/valid-bug, cherry-pick-approved, lgtm

#12295 Updating CI repo URL
  images/installer/origin-extra-root/etc/yum.repos.d/openshift-origin-4.0-ci.repo
Labels: approved, bugzilla/valid-bug, lgtm

#12291 Bug 1915760: Increase node ready wait to 10 minutes
  roles/openshift_node/tasks/apply_machine_config.yml
  roles/openshift_node/tasks/config.yml
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#12306 Bug 1849003: [release-3.11] Fix string handling when setting facts
  roles/openshift_logging/tasks/set_defaults_from_current.yml
Labels: approved, bugzilla/severity-low, bugzilla/valid-bug, lgtm

#12307 Bug 1921353: [release-3.11] Gather cluster_facts after version.yml during upgrade
  playbooks/common/openshift-cluster/upgrades/init.yml
  playbooks/common/openshift-cluster/upgrades/pre/config.yml
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#12309 Bug 1879407: Adding int typecasting for _component_cluster_size
  roles/openshift_logging_elasticsearch/tasks/restart_cluster.yml
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm
