Repository openshift/openshift-ansible, pull requests merged in 2021-01, with the labels that each got.

#12289 Pin PyJWT==1.7.1, Fixes image build issue
  images/installer/Dockerfile
Labels: approved, lgtm

#12286 Bug 1873346: Support upgrades of Kuryr compoments
  playbooks/common/openshift-cluster/upgrades/v3_11/upgrade_control_plane_part2.yml
  roles/kuryr/tasks/upgrade.yaml
  roles/openshift_node/tasks/upgrade.yml
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#12284 Bug 1879407: Correctly use ops cluster size if evaluating es-ops component for restart
  roles/openshift_logging_elasticsearch/tasks/restart_cluster.yml
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#12285 [KIECLOUD-460] - Update RHPAM and RHDM templates and imagestreams on …
  roles/openshift_examples/examples-sync.sh
  roles/openshift_examples/files/examples/x86_64/xpaas-streams/rhdm79-image-streams.yaml
  roles/openshift_examples/files/examples/x86_64/xpaas-streams/rhpam79-image-streams.yaml
  roles/openshift_examples/files/examples/x86_64/xpaas-templates/rhdm79-authoring-ha.yaml
  roles/openshift_examples/files/examples/x86_64/xpaas-templates/rhdm79-authoring.yaml
  roles/openshift_examples/files/examples/x86_64/xpaas-templates/rhdm79-kieserver.yaml
  roles/openshift_examples/files/examples/x86_64/xpaas-templates/rhdm79-prod-immutable-kieserver-amq.yaml
  roles/openshift_examples/files/examples/x86_64/xpaas-templates/rhdm79-prod-immutable-kieserver.yaml
  roles/openshift_examples/files/examples/x86_64/xpaas-templates/rhdm79-trial-ephemeral.yaml
  roles/openshift_examples/files/examples/x86_64/xpaas-templates/rhpam79-authoring-ha.yaml
  roles/openshift_examples/files/examples/x86_64/xpaas-templates/rhpam79-authoring.yaml
  roles/openshift_examples/files/examples/x86_64/xpaas-templates/rhpam79-kieserver-externaldb.yaml
  roles/openshift_examples/files/examples/x86_64/xpaas-templates/rhpam79-kieserver-mysql.yaml
  roles/openshift_examples/files/examples/x86_64/xpaas-templates/rhpam79-kieserver-postgresql.yaml
  roles/openshift_examples/files/examples/x86_64/xpaas-templates/rhpam79-managed.yaml
  roles/openshift_examples/files/examples/x86_64/xpaas-templates/rhpam79-prod-immutable-kieserver-amq.yaml
  roles/openshift_examples/files/examples/x86_64/xpaas-templates/rhpam79-prod-immutable-kieserver.yaml
  roles/openshift_examples/files/examples/x86_64/xpaas-templates/rhpam79-prod-immutable-monitor.yaml
  roles/openshift_examples/files/examples/x86_64/xpaas-templates/rhpam79-prod.yaml
  roles/openshift_examples/files/examples/x86_64/xpaas-templates/rhpam79-trial-ephemeral.yaml
Labels: approved, lgtm, ok-to-test
