Repository openshift/openshift-ansible, pull requests merged in 2022-01, with the labels that each got.

#12362 Bug 2035494: Set keyfile to be the primary NetworkManager plugin
  roles/openshift_node/tasks/config.yml
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-high

#12364 Bug 2041983: Pin python-lazy-object version
  test-requirements.txt
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-medium

#12363 Bug 1636993: Fix EFS provisioner image name
  roles/openshift_provisioners/defaults/main.yaml
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-medium

#12365 KIECLOUD-584-Update RHPAM and RHDM templates and imagestreams on Open…
  roles/openshift_examples/examples-sync.sh
  roles/openshift_examples/files/examples/x86_64/xpaas-streams/rhdm712-image-streams.yaml
  roles/openshift_examples/files/examples/x86_64/xpaas-streams/rhpam712-image-streams.yaml
  roles/openshift_examples/files/examples/x86_64/xpaas-templates/rhdm712-authoring-ha.yaml
  roles/openshift_examples/files/examples/x86_64/xpaas-templates/rhdm712-authoring.yaml
  roles/openshift_examples/files/examples/x86_64/xpaas-templates/rhdm712-kieserver.yaml
  roles/openshift_examples/files/examples/x86_64/xpaas-templates/rhdm712-prod-immutable-kieserver-amq.yaml
  roles/openshift_examples/files/examples/x86_64/xpaas-templates/rhdm712-prod-immutable-kieserver.yaml
  roles/openshift_examples/files/examples/x86_64/xpaas-templates/rhdm712-trial-ephemeral.yaml
  roles/openshift_examples/files/examples/x86_64/xpaas-templates/rhpam712-authoring-ha.yaml
  roles/openshift_examples/files/examples/x86_64/xpaas-templates/rhpam712-authoring.yaml
  roles/openshift_examples/files/examples/x86_64/xpaas-templates/rhpam712-kieserver-externaldb.yaml
  roles/openshift_examples/files/examples/x86_64/xpaas-templates/rhpam712-kieserver-mysql.yaml
  roles/openshift_examples/files/examples/x86_64/xpaas-templates/rhpam712-kieserver-postgresql.yaml
  roles/openshift_examples/files/examples/x86_64/xpaas-templates/rhpam712-managed.yaml
  roles/openshift_examples/files/examples/x86_64/xpaas-templates/rhpam712-prod-immutable-kieserver-amq.yaml
  roles/openshift_examples/files/examples/x86_64/xpaas-templates/rhpam712-prod-immutable-kieserver.yaml
  roles/openshift_examples/files/examples/x86_64/xpaas-templates/rhpam712-prod-immutable-monitor.yaml
  roles/openshift_examples/files/examples/x86_64/xpaas-templates/rhpam712-prod.yaml
  roles/openshift_examples/files/examples/x86_64/xpaas-templates/rhpam712-trial-ephemeral.yaml
Labels: lgtm, approved, ok-to-test
