Repository openshift/openshift-ansible, pull requests merged in 2022-02, with the labels that each got.

#12366 Use user/pass auth when the user_pass_auth var is present
  roles/openshift_gcp/templates/yum_repo.j2
Labels: lgtm, approved

#12370 Bug 2052393: Install jq package required by configure-ovs
  roles/openshift_node/defaults/main.yml
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-urgent

#12372 Bug 2040488: Unit tests to use python 3.7
  .travis.yml
  tox.ini
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-medium

#12369 Bug 2037620: Require RHEL v8.4 or newer beginning with OpenShift v4.10
  playbooks/scaleup.yml
  playbooks/upgrade.yml
  roles/openshift_node/tasks/version_checks.yml
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-high
