Repository openshift/openshift-ansible, pull requests merged in 2022-03, with the labels that each got.

#12374 Bug 2060147: Include libseccomp in the list of packages that we ensure are up to date
  roles/openshift_node/defaults/main.yml
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-medium

#12368 Update best_practices_guide.adoc
  docs/best_practices_guide.adoc
Labels: lgtm, approved, ok-to-test

#12380 [release-4.8] Bug 2060476: Install jq package required by configure-ovs
  roles/openshift_node/defaults/main.yml
Labels: lgtm, approved, bugzilla/valid-bug, cherry-pick-approved, bugzilla/severity-urgent, backport-risk-assessed

#12382 Adds aarch64 dict to enable the openshift-node role for RHEL ARM Workers
  roles/openshift_node/defaults/main.yml
Labels: lgtm, approved
