Repository openshift/openshift-ansible, pull requests merged in 2023-04, with the labels that each got.

#12444 Dockerfile: install dnf-command(config-manager)
  images/installer/Dockerfile
Labels: lgtm, approved

#12441 Bug 1980127: [release-3.11] remove old SDN binaries when the sdn is deployed
  roles/openshift_sdn/files/sdn.yaml
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-high

#12445 OCPBUGS-5255: exclude kubelet from fixfiles
  roles/openshift_node/tasks/config.yml
Labels: lgtm, approved, bugzilla/valid-bug, jira/severity-important, jira/valid-bug, jira/valid-reference

#12446 Set default remote_tmp
  ansible.cfg
Labels: lgtm, approved
