Repository openshift/openshift-ansible, pull requests merged in 2024-03, with the labels that each got.

#12492 OCPCLOUD-2484,OCPCLOUD-2481: Adds azure and gcp image credential providers
  roles/openshift_node/defaults/main.yml
Labels: lgtm, approved, jira/valid-reference

#12476 OCPBUGS-22366: Restart the openvswitch service on [re]install
  roles/openshift_node/tasks/install.yml
Labels: lgtm, approved, jira/severity-moderate, jira/valid-bug, jira/valid-reference, acknowledge-critical-fixes-only

#12495 Switch to openshift-kubelet package
  roles/openshift_node/defaults/main.yml
Labels: lgtm, approved
