Repository openshift/openshift-ansible, pull requests merged in 2024-08, with the labels that each got.

#12503 OCPBUGS-35209: Update Dockerfile to centos9 stream.
  images/installer/Dockerfile
  images/installer/README_CONTAINER_IMAGE.md
  requirements.txt
Labels: lgtm, approved, jira/valid-bug, jira/valid-reference

#12505 OCPBUGS-34844: Disable repo container-tools before installs
  roles/openshift_node/tasks/install.yml
Labels: lgtm, approved, jira/severity-important, jira/valid-bug, jira/valid-reference

#12506 Add rhel-9 attribute in openshift_node_support_packages
  roles/openshift_node/defaults/main.yml
Labels: lgtm, approved

#12512 OCPBUGS-39160: Manully cherry-pick the changes for updating Dockerfile to centos9 stream
  images/installer/Dockerfile
  images/installer/README_CONTAINER_IMAGE.md
  requirements.txt
Labels: lgtm, approved, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference
